### ISSUE TITLE
N.H. Sea Grant favicon

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#100]
The favicon used in NHSG's instance of eSeaGrant isn't the one we provided to Deepak via Dropbox.

**Comment by ecsion** [comment]
Please attache the favicon file here and we will update it for you.

**Comment by schalifoux** [comment]
It's a .ico file, and when I tried to upload it here, I get a message that the filetype isn't supported. That's also why I couldn't e-mail it directly to Deepak.

**Comment by ecsion** [comment]
Simply change the .ico extension to ._ico and upload. We will then correct the extension back to .ico
