### ISSUE TITLE
RISG: Budget Justification showing INCORRECT values, but calculating correctly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1000]
At this URL:

https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTAzNjM0&id=380
 and see screen shot

<img width="1286" alt="Screen Shot 2019-09-16 at 12 56 04 PM" src="https://user-images.githubusercontent.com/18398763/64977822-2505dc80-d882-11e9-85d9-5ecc95f921b0.png">

the values calculated by eSeaGrant for each Person listed are INCORRECT. For instance, Andrew Davies [PI] is calculated at $3210.2834 when the actual value (14651 * 0.3026) is $4433.3926. 

Despite showing the incorrect calculations in the Budget Justifications, the Budget Worksheet is calculating and summing the actual values correctly.

The calculations shown in the Budget Justification box MUST be fixed to show the actual/correct value. This is a CRITICAL ERROR that must be corrected so we can submit budgets to the national office. Thank you.

**Comment by pankaj-ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
The error has been fixed. If possible, could the values reported be rounded to the nearest full dollar amount? There is no need to carry out a dollar value to 4 decimal places, and for our purposes, no decimal places are used. If that minor issue could be corrected it would make the information clearer/less confusion. Thank you for fixing the reported error.

**Comment by pankaj-ecsion** [comment]
Changes are done. Please check.

**Comment by alandesbonnet** [comment]
Perfect. Thank you.

Alan Desbonnet
Assistant Director
