### ISSUE TITLE
NCSG - Adding email address for confirmation emails

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#1001]
I am still receiving confirmation emails when a proposal is submitted but, can we add someone else to get them as well?  If so, where is that option?  I would like to add John Fear (jmfear@ncsu.edu) to the system to receive submission emails.

**Comment by ecsion** [comment]
Mary Beth, I believe this was done. We are closing this issue, please reopen if not fixed.
