### ISSUE TITLE
Investigator Could Not Save Publication

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1002]
PI on project (2018SP-R-Mostafavi-CNH3) could not save a publication on report call (RQP-2019-Q2). Said "For some reason, I was not able to save the publication info. The system did not save the info I entered." No other researchers have complained about publication interface issues.

**Comment by ecsion** [comment]
Drew, this is an old issue, Are you still having this problem?

**Comment by Drew-Casey** [comment]
No one else has reported an issue and I could not duplicate it. I will close it for now.
