### ISSUE TITLE
RISG--Files won't delete in Projects Tab

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1003]
at this URL -
https://eseagrant.gso.uri.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=108992&mode=showRelatedList&tab_label=Project%20Documents
the file named "Bertin-Data Management Plan" and associated file <Sea-Grant-Data-Management-Plan.pdf> will not delete from the list when the trash can is selected.

Similarly, at this URL-
https://eseagrant.gso.uri.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=109019&mode=showRelatedList&tab_label=Project%20Documents
the file named "Davies-Data Management Plan" and associated file <Sea-Grant-Data-Management-Plan.pdf> will not delete from the list when the trash can is selected.

Please correct this problem so that files can be deleted. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
Fixed. Thank you.
