### ISSUE TITLE
RISG -- Add Fringe Rate in Justification for OTHER PERSONNEL

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1005]
Budget Justification for PI/SENIOR PERSONNEL lists Mos. Effort, SG and Match dollars, Benefits Rt. and Mos. Salary.

Budget Justification for OTHER PERSONNEL does not list the Benefits Rt. --- please add the Benefits Rt. to show for OTHER PERSONNEL.

Thank you.

**Comment by Dipali-Ecsion** [comment]
Added. Please check.

**Comment by alandesbonnet** [comment]
It is now showing, Thank You
