### ISSUE TITLE
RISG -- Report Call Closes in Error

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1006]
at this URL

https://eseagrant.gso.uri.edu/index.php?module=CallReporting&view=Edit&record=104170

When the "Close Report Call at end of due date" box is checked --- with the Due Date set at 4/20/2020 --- then saved, the Report Call closes and is not available. Please correct this so that the Report Call stays open, and will close on the noted data when the box is checked.
Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed.. Please check.

**Comment by alandesbonnet** [comment]
Works perfectly. Thank you.
