### ISSUE TITLE
URGENT: WASG - site down; shows blank page

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#1009]
Our Washington Sea Grant eSeaGrant site appears to be down.  We have a fellowship application deadline today and really need this fixed ASAP.  When you go to esg.wsg.washington.edu, you just get a blank page.
Please help!
Thanks

**Comment by ecsion** [comment]
Issue was caused due to error on deployment of some changes. This error has been fixed.
