### ISSUE TITLE
MASGC - Panel Reviewer Submit button not available?

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#1010]
Are we still supposed to use GitHub to submit issues?
Maybe I'm doing something wrong, but I am testing out functionality of the RFP reviewer part of eSeaGrant. I had some reviewers complain that they lost their work last year. It seems they were not "Saving" before "Submitting" and their work disappeared and I've been meaning to post the issue. The system should automatically Save before Submitting or not allow you to Submit unless you have Saved first.

I just tried this functionality on the new version of eSG and I have lost work twice now.  Here is what is happening now:

I have signed in as a panel reviewer and filled out a review form.  I filled in the COI statement.  I go to click on "Save" or "Submit" and there is a "No Symbol" (circle with a line) on both options.
https://eseagrant.masgc.org/operations.php?action=panel_reviewer_detail&guid=MDEwNDZFM0QtMzBDMy00MkRELTkwODktMThEQzJGRTZCOEI4&exuti=MTA3MzA0&propid=MTA0Mzcx&reviewer=MTA3MzA2&rid=LQ== 

![reviewer submission page 1 28 20](https://user-images.githubusercontent.com/22300443/73301626-b98d2d80-41d8-11ea-9cee-762f9f8141c0.JPG)

The only option available is to the "Print" button and if I click that, all of my data that has been entered disappears.

Thank you.
Loretta

**Comment by mzwolinski** [comment]
Texas Sea Grant had the same issue with this summer’s biennial research competition. Thank you for reporting this issue, Loretta.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
Office: 979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/

**Comment by Dipali-Ecsion** [comment]
Hi,
Reviewers are not able to save or submit because Due date is past currently it set as 07-29-2019. 
If you increase due date and set it in future they will able to Submit their review. 
Please check link and  screenshot. 

https://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=100057&phaseid=100059&tab_label=Full-Proposal&source=Panel

![image](https://user-images.githubusercontent.com/17423049/73332143-d898c780-428b-11ea-9288-1cb54703affc.png)


![image](https://user-images.githubusercontent.com/17423049/73332209-03831b80-428c-11ea-981e-7effcf8c5ce3.png)

**Comment by MASGCleist** [comment]
Thank you. It was user-error!
We are holding a small internal panel in March and I will test out the improvements more thoroughly then. I appreciate the help. It seems to work better than it did for me before over the summer so thank you for keeping it moving in the right direction!
Loretta

Loretta Leist
MASGC Research Coordinator
703 East Beach Drive
Ocean Springs, MS 39564
228-818-8835

**Comment by ecsion** [comment]
Closing this issue, reason - user error.
