### ISSUE TITLE
Not Sure if Project "Comments" Tab Working

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1011]
I am testing out the new "Comments" functionality using project 2018SP-A-Casey as a test. I used two accounts to make comments but it appears no other accounts can view those comments (including other administrators). I also tried it with a test project (# = X01-E-Test) and it does not work there either. 

I am not sure what functionality there is with the comments tab but shouldn't other administrators be able to see comments?

**Comment by ecsion** [comment]
Drew, So you want the comments visible to PI or limited to SGAdmin only?

**Comment by Drew-Casey** [comment]
I am not sure about the current setting, but currently, when one account enters a comment no other account can view that comment. 

Ideally, it would be nice if we could select if they are Public / Admin Only comments. But if that is not available, them being open to anyone who can view that project is fine.

**Comment by Dipali-Ecsion** [comment]
Fixed.
Now it will open to anyone who can view that project.

Please check

**Comment by Drew-Casey** [comment]
It is working. Thank you.
