### ISSUE TITLE
RISG: Phase Not Working Properly  CRITICAL

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1012]
at this URL: https://eseagrant.gso.uri.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask

a proposal has been created in a Phase 2 of an RFP. When I click on the proposal and go to this URL: 

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=110220&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

all the information is for the Phase 1 proposal, not Phase 2. 
This needs to be corrected as this proposal is due soon.
Thank you.

the RFP is found at:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&record=109677
titled Round 2 (of 3 phases)

**Comment by ecsion** [comment]
Closing this issue. Please reopen if this issue is not resolved.
