### ISSUE TITLE
WISG - issue adding a project to a report call

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1013]
I am having trouble adding in a project to a report call.
The project has 2 report calls associated with it already, but they need to report for another year.
I cannot see the project when I go the "Choose Projects" button to link it to the report call.

This is the report call: 
https://edrop.aqua.wisc.edu/index.php?module=CallReporting&view=Detail&record=115343

This is the project I want to add to it: https://edrop.aqua.wisc.edu/index.php?module=Projects&view=Detail&record=699&mode=showDetailViewByMode&requestMode=summary&tab_label=Project%20Information

There are also a few other projects that I cannot link. Am I doing something wrong?

Thanks.

**Comment by ecsion** [comment]
Tom, the reason you don't see certain projects is because these projects don't have their open/close status set to open. Once you do this, these projects will become visible in the report call selection.
