### ISSUE TITLE
MDSG: Font conversion error (Arial) prevents editing your PDFs in Adobe

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1014]
I'm trying to edit a PDF exported document from eSeaGrant to prepare the final award package. I regularly do this to update data on the PDF forms output by eSG. Today on output forms that are using the gray text (e.g. the data entered by the applicant), Adobe Acrobat is not recognizing your arial font and is instead trying to display it as a temporary font (Z@R3621.tmp). Adobe is able to edit all of the black text (the headers on your PDFs). I have tried this with multiple different proposals and the problem recurs.

Example: Download Proposal Docks Zip from this proposal: https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=116891&mode=showSubmissionPreview&tab_label=UHJvcG9zYWwgU3VtbWFyeQ&tab_label=UHJvcG9zYWwgU3VtbWFyeQ==

Open Project Summary Form, or other PDF from the zip file in Adobe Acrobat Pro DC.

Click to edit the PDF.
Click in one of the boxes that has small text and try to edit, font error comes up. It appears this is specific to the Arial font. Interestingly, when you have bold turned on, the font displays correctly, it's only not recognizable in its native, basic form.

![image](https://user-images.githubusercontent.com/31412413/73962465-7d468500-48dc-11ea-8ec7-9badc937a060.png)

**Comment by ecsion** [comment]
Mike, We have switch the fonts to Times New Roman and deployed the updated to Maryland Server. Could you please check and see if you are able to edit,

**Comment by mra142** [comment]
I've tried this on the PDF in question and on reports. Times has deployed correctly and is editable.
Thanks, Closed.

Mike
