### ISSUE TITLE
Issues with Project Status pick list

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1016]
1. I have six project status values I would like to use but the PI user screen only has two tabs (Open and Closed). If I assign any other value, the projects are not viewable on the PI interface. Can I have the other values coded as Open/Closed? 
Project Status Values
Open  (coded as Open)
Extended (coded as Open)
Renewed (coded as Open)
Completed (coded as Closed)
Canceled (coded as Closed)
Closed (coded as Closed)

2. I am trying to add completed projects to my "General Publications Submission" report call. So far only "Open" projects can be added. I need to be able to add any project status to a report call.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by Drew-Casey** [comment]
It works thank you
