### ISSUE TITLE
ORSG: Document Provider Instructions

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#1020]
In the document request page for document providers, the instructions listed on the submission page are for the PI or student applicant and the document provider has to click on the Instructions specific for them to view. Is it possible to have the “Document Provider” instructions be the default with the option to click on the PI instructions (rather than the other way around as it is now)?

This has caused some confusion for several fellowship letter writers, who have mistakenly thought that the instructions for the PI were for them and did not notice the option to view their instructions.

The screen shot attached has the two instruction options highlighted—the default is the PI instructions in green and the Document instructions link in yellow.
![doc-request_022420](https://user-images.githubusercontent.com/46287278/75201795-4cf54800-571e-11ea-8a92-ad453d86b452.png)

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by STI-ORSG** [comment]
Thank you, that looks great.

**Comment by mzwolinski** [comment]
Texas Sea Grant would like that edit as well, for a new fellowship RFP that we are about to release.

Regards,
Mia

Mia Zwolinski

Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street
O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
Office: 979-458-0449
mzwolinski@tamu.edu
http://texasseagrant.org/
________________________________

**Comment by Dipali-Ecsion** [comment]
Deployed this change to Texas SeaGrant & other SeaGrant Servers as well
