### ISSUE TITLE
Modify Publication

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1021]
TXSG has a few points about publications:
1. I cannot find where I can modify instructions for publications. Perhaps I simply missed it. 

2. We would like to make more items Required. 
(Primary Author, Other Author, Publisher Info, Abstract, Open Access, Embargo Date, Publication URL, Key Words, File Upload)

3. If more expansive changes are available, we have compiled a list in the attached document. Not sure if we can adjust the layout and fields of the publications form. 
[TXSG Publications Modifications.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/4257752/TXSG.Publications.Modifications.pdf)

**Comment by ecsion** [comment]
Drew, this is done, go to settings, pick list editor for publications & add values for focus area & grant number. The focus area in publications is different than the focus area in projects and have to be set separately.

**Comment by Drew-Casey** [comment]
Looks good. Thank you
