### ISSUE TITLE
ORSG: All Proposal Zip missing 1 letter

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#1022]
In the RFP Reports tab, "All Proposals Component Zip Download" is incomplete. The Zip folder appears to contain all proposals, but each application is missing one of the two letters of support. The second letter can be downloaded from each individual application, but is it possible to have the Zip Download include everything?

**Comment by ecsion** [comment]
fixed, please check.

**Comment by STI-ORSG** [comment]
Fixed. The Zip Download includes everything now. Thank you!

**Comment by mzwolinski** [comment]
Was this change also deployed to all other SeaGrant Servers as well?
Thank you,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
Office: 979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/

**Comment by ecsion** [comment]
This change was applied to all SeaGrant Programs.
