### ISSUE TITLE
WISG - Issue editting RFP

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1023]
We are having an issue where the site is not saving changes to our in-progress RFP.
The investigator goes in and makes changes to the form, saves it and moves on. When they go back to review the form, the data has not changed. The content in the "Financial Contact" section of the form does not save the changes correctly.

Here is where we are having the issue:
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=116422&mode=showMultiQuestionStem&QuestionId=116469&tab_label=MTA0KEcpIElQRVRUIFJlcXVpcmVkIEluZm9ybWF0aW9u&tab_label=MTA0KEcpIElQRVRUIFJlcXVpcmVkIEluZm9ybWF0aW9u

Thanks.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by ecsion** [comment]
There was a bug when using multiple people questions that caused this. This has been fixed and will be deployed to other SeaGrant programs on a rolling basis.

**Comment by tomxiong-aqua** [comment]
Fixed. Thanks!
