### ISSUE TITLE
Issues with PIER Questions

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1024]
Several of the new PIER forms have improper content (examples below). I can fix these issues but I would need to know the "SET KEY: selection" wording for:
P-12
Presentation & Workshops
Developed products, 

**Examples of Issues:**
PRESENTATIONS & WORKSHOPS (P) form:
  * Question 1 (Activity Type:) only has one option (Workshop/Training). 
  * Question 2 (Informal Education?) has options not appropriate for the question

P - 12 EDUCATION (P) form:
  * Question 1 (Were Teachers or Students targeted?) only has one option

**Comment by ecsion** [comment]
Drew, Did you speak with Alan Desbonnet both this?

**Comment by alandesbonnet** [comment]
My report call forms have the proper choices for each of the two pointed out by Drew. Evidently his version must have lost the choices during transfer or perhaps were somehow deleted?

Mine are fine, so I don’t think whatever is amiss is true to all user programs.
AD

Alan Desbonnet
Assistant Director

**Comment by Drew-Casey** [comment]
As Alan pointed out, there is an issue with my forms not having the correct answers.  I have submitted a new request to change the PIER form keys and will close this request. I want to move away from this question structure.
