### ISSUE TITLE
RISG: Custom Form Showing to PI in RFP when NOT selected/added by ADMIN

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1026]
At this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=110995&phaseid=110997&tab_label=RnVsbC1Qcm9wb3NhbA==&source=RFP

you will see that the Custom Form titled "Important Full Proposal Information" is NOT contained in the list of forms available for the RFP. However, when the PI logs in to eSeaGrant at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=111111&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

You see that the IMPORTANT FULL PROPOSAL INFORMATION custom form shows. How can this be removed/prevented in the future? I suspect it is a remnant of using the IMPORT PROPOSAL function. Thank you.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
fixed. thank you
