### ISSUE TITLE
Alaska: Instructions PDF button glitch on Current Tasks screen

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1029]
The button for "Instructions PDF" for a report on the PI's Current Tasks panel **incorrectly** indicates that the _file does not exist_. If you go into the report, and choose the "Instructions PDF" button in that location, it _does_ work, and lets you view and download the PDF instructions. So the button is working within the report, but not from the Current Tasks area.

![eSeaGrant Instructions PDF bug](https://user-images.githubusercontent.com/61889985/77470584-c471d200-6dc5-11ea-8539-2c30612519e0.png)

**Comment by dpartee** [comment]
Checking in on this issue. Thanks!
dave.partee@alaska.edu

**Comment by ecsion** [comment]
Hi Dave, The instruction file refers to the instruction file uploaded in the report call instructions. This file has not been added and so this popup is appearing. I believe the confusion stems from the fact that when the report is opened, there is a button for instructions that displays all the combined instructions of the various forms in 1 document. So the way we are proposing to fix this is as follows:
1. The file uploaded in Report Call will be called Report Call Instructions.
2. The file we auto generate by combining the various instructions from the forms will be called Form Instructions.
As a work around if you upload a simple report call instructions pdf, this issue will go away for you.

Let us know if this works for you.

**Comment by dpartee** [comment]
Yes, "Report instructions" and "Form Instructions" is a good distinction.
