### ISSUE TITLE
Instructions text in Standard Modules - can they be right up front? And the first entry, plz

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#103]
Thanks for adding the instructions text to the "Students Supported," "Impacts and Accomplishments," 
"Publications," "Narratives," and "Partners modules."
Is it possible for that text to appear right on the front page of those sections, so that the PI knows what is required? And if you can have the fields for an initial entry showing, that would be great.
Ideally, the PI would land on page that looks the same as "Professional Conferences, Meetings and Workshops" for each standard module.

**Comment by ecsion** [comment]
done.
