### ISSUE TITLE
RFP Module Document Request Form Issue

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1030]
Texas Sea Grant RFP "Grants-In-Aid FY2020-2022"  working on a release date of April 1, if you could please assist soon, thank you, Mia.

The document request form, "Reference Letters Request" had been added earlier to this RFP, as a form to request letters of reference. I made corrections to the form, saved, was satisfied with the form, so saved again as a template, as "Reference Letters Request (copy)".

I deleted the old form, then edited the updated form name from "Reference Letters Request (copy)" to simply "Reference Letters Request". 

In the RFP, deleted the old selected form and re-added the new form. However, the RFP from the PI's view left panel menu shows two "Reference Letters Request" forms, the updated form and also the old form. 

To resolve, went back to the form and saved as a template, to create another copy. Went back and edited that form name to a new form name: "Reference Letters Request Form".  Saved again as a template in order to delete the old one. Edited form name from "Reference Letters Request Form (copy)" to "Reference Letters Request Form". Deleted the old form. Confirmed that the document request forms library only shows this new form with the updated name.

However, in the RFP left menu, it now shows two forms, the updated new "Reference Letters Request Form" and still shows the old Reference Request form on the left menu, even though it is no longer in the forms library. Please see how to release the old form so that it is no longer listed on the left panel menu. I tried logging out, back in, etc., to no avail.

Screenshot of RFP forms selected and the webpage address is: 
http://eseagrant.texasseagrant.org/index.php?module=RFP&view=Detail&mode=createPhase&record=121711&phaseid=121712&tab_label=RnVsbC1Qcm9wb3NhbA==&source=RFP
![Screenshot_2020-03-28 RFP](https://user-images.githubusercontent.com/23663698/77836747-e7ceb100-7126-11ea-8aa2-883a148109a1.png)

Screenshot of PI left panel menu with two Ref Req docs and webpage link:
http://eseagrant.texasseagrant.org/index.php?module=RFPProposal&view=Detail&record=123613&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==
![image](https://user-images.githubusercontent.com/23663698/77836731-b35af500-7126-11ea-8d80-cf9710c383af.png)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mzwolinski** [comment]
Thank you, beautiful! This ticket may be closed.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/
