### ISSUE TITLE
RISG: Delegates can't open project files

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1031]
At this URL
https://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=111396&mode=showProjectInfo&tab_label=UHJvamVjdCBJbmZv&tab_label=UHJvamVjdCBJbmZv
the user wants to access the proposal narrative so they can see original project objectives for reporting purposes. The user is a Delegate to both the Report and to the Project.

However,At this URL
https://eseagrant.gso.uri.edu/index.php?module=OtherDocs&action=DownloadFile&record=100910&fileid=100911

You see that an error message is opened when the NARRATIVE file is clicked by the user. As a Delegate (to both report and project) the user should have access to this and other files. 

Please correct this permissions error as it is affecting annual reporting processes. Thank You,

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
Fixed. Thank you.

**Comment by alandesbonnet** [comment]
I closed the Case as it is fixed. Thank you!!

Alan Desbonnet
Assistant Director
