### ISSUE TITLE
RFP for Grants-In-Aid FY2020-2022 Not Sending Proposal Email Confirmations

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1032]
![image](https://user-images.githubusercontent.com/23663698/78086037-55c2e480-7382-11ea-9cef-11b882635527.png)

http://eseagrant.texasseagrant.org/index.php?module=RFP&view=Detail&mode=showProposals&record=121711&phaseid=121712&tab_label=RnVsbC1Qcm9wb3NhbA==

RFP for Grants-In-Aid FY2020-2022 
I did not receive an email confirmation of my submitted proposal.
We are releasing the RFP tomorrow. Assistance very much appreciated. Thank you, Mia at TXSG.

**Comment by ecsion** [comment]
Mia, We are closing this for now. Please reopen if you would like to trace something specific for you.

**Comment by mzwolinski** [comment]
I do not recall it ever being resolved.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
Office: 979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/
