### ISSUE TITLE
problems with budget worksheet, project summary form, 90-4, budget justification, additional personnel

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1033]
refer to:

Budget Worksheet : https://eseagrant.mit.edu/operations.php?action=budget&proposal_id=MTEzOTM1&id=913

Additional Personnel : https://eseagrant.mit.edu/index.php?module=RFPProposal&view=Detail&record=113935&mode=showMultiQuestionStem&QuestionId=116017&tab_label=QWRkaXRpb25hbCBQZXJzb25uZWw=&showList=&tab_label=QWRkaXRpb25hbCBQZXJzb25uZWw=

ISSUES

Project Summary Form:

1) the total months effort for PI Mike Triantafyllou should be SG:0 Grantee:0, not blank spaces

2) Rob Vincent (additional personnel - associate (faculty or staff)) should be listed under Other Investigator, with his months effort. The reason for this is that while he can't have PI (PI or Co-PI) status for proposals of this type where the Director must be PI, Rob is actually the project lead, and is listed as Senior Personnel on the 90-4.

Budget Worksheet:

Director Mike T's justification cannot be deleted. Lines with no fund request shouldn't have justification.

Rob is included as Additional Personnel in the proposal, but his name is not shown in the budget worksheet > Senior Personnel drop-down, even though his type (associate faculty/staff) does appear in the drop-down.

90-4:

Rob's mos effort and salary are appearing correctly in Section A1, but he's not counted in No. of People

Budget Justification:

Rob's justification is not appearing, and the Section 1 header components are missing entirely.

Additional Personnel:

This is a feature request ~ We need this form to offer optional CV upload.

**Comment by ecsion** [comment]
Ben, We are about ready to release v 2.5 which includes accessibility and many other updates. The updates and bug in this item will be in 2.5 release. Let us know we can deploy 2.5 to MIT

**Comment by Nebules** [comment]
sorry for the delay. please proceed at your earliest convenience

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Apr 6, 2020, at 11:38 AM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Ben, We are about ready to release v 2.5 which includes accessibility and many other updates. The updates and bug in this item will be in 2.5 release. Let us know we can deploy 2.5 to MIT

**Comment by Nebules** [comment]
will people need to log-out before the update?

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Apr 6, 2020, at 11:38 AM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Ben, We are about ready to release v 2.5 which includes accessibility and many other updates. The updates and bug in this item will be in 2.5 release. Let us know we can deploy 2.5 to MIT

**Comment by ecsion** [comment]
We have already deployed this change.

**Comment by Nebules** [comment]
What about this:

Additional Personnel:
This is a feature request ~ We need this form to offer optional CV upload.

That form is still locked.

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by ecsion** [comment]
Closing. If this is still an issue, please reopen and add comments.
