### ISSUE TITLE
ORSG- Text not saving in Peer-Review form

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#1035]
When text is entered into the reviewer comment box in the peer-review form, the text does not appear to save after hitting the save button. I have tried on Chrome and Firefox.
Many thanks for your help.

**Comment by ecsion** [comment]
The issue was that rating was not added and the current logic required rating. So now we have refactored the code so Reviewer will be able to save review even if the Peer Review has no rating form.

**Comment by STI-ORSG** [comment]
Got it, looks good now. Thank you for the quick fix!
