### ISSUE TITLE
RISG:: Popup Screen gets stuck

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1036]
At this URL: 
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=111367&mode=showMultiQuestionStem&QuestionId=111043&tab_label=UHJvamVjdCBTdW1tYXJ5IChGdWxsLVByb3Bvc2FsIC0gMjAyMC0yMDIyIFJlc2VhcmNoIFJGUCk=&tab_label=UHJvamVjdCBTdW1tYXJ5IChGdWxsLVByb3Bvc2FsIC0gMjAyMC0yMDIyIFJlc2VhcmNoIFJGUCk=
the popup screen gets stuck.....in other words will not close, as normally does, when clicking somewhere on the screen. Please correct this so that the information on the custom form can be accessed. Thank you

**Comment by ecsion** [comment]
Done, please check.
