### ISSUE TITLE
TXSG: New Registration with International Phone Number

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1037]
A graduate student is registering to submit a proposal to a RFP competition. Due to COVID-19, the student stayed at his parents' home in Mexico since his trip home during Spring Break. Texas A&M University guidelines advised all students to not travel/return to campus and this student is continuing online course work with Texas A&M. The student's personal cell phone is the international number which is not supported by eSeaGrant. Can you provide guidance and/or work-around to resolve due to this situation? Thank you, Mia.

**Comment by ecsion** [comment]
Mia, check your email.
