### ISSUE TITLE
Publish All works but goes to a blank page

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1038]
When I click publish all in a report call, it will in fact publish the report but the screen will be blank. Refreshing the page does not work. I either need to press the back button or simply abandon the tab. This is a minor issue since I am still able to publish report calls, it's just inconvenient. 
Web Address:http://eseagrant.texasseagrant.org/index.php?module=CallReporting&relatedModule=Projects&mode=showRelatedList&tab_label=Link%20Projects&view=Detail&record=125176

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
