### ISSUE TITLE
PIs add their own delegates

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1039]
Is it possible for PIs to add their own delegates? I thought they had that feature but I could not get it to work with my Dummy PI accounts. 

![Add delegates as PI](https://user-images.githubusercontent.com/44243756/80622722-d111c780-8a0e-11ea-81a0-fed3613c15e4.png)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/80823425-3f66ad80-8bfa-11ea-9d97-199de808dd53.png)

**Comment by Drew-Casey** [comment]
It is working. Thank you!
