### ISSUE TITLE
Justification: Senior Personnel missing in justification narrative 

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1041]
Referring to this proposal:
https://eseagrant.mit.edu/index.php?module=RFPProposal&view=Detail&record=118016&mode=showBudgetListingData&tab_label=QnVkZ2V0cw&showList=&tab_label=QnVkZ2V0cw==

The Senior Personnel section is missing entirely from the Year 2 justification narrative:
worksheet: https://eseagrant.mit.edu/operations.php?action=budget&proposal_id=MTE4MDE2&id=943#
justification narrative: https://eseagrant.mit.edu/operations.php?action=justification&id=943

In the corresponding 90-4, the SP section appears, but only the PI is listed

**Comment by Dipali-Ecsion** [comment]
Fixed Please check.

**Comment by Nebules** [comment]
Fix verified. Thanks!

Ben

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On May 6, 2020, at 12:11 PM, Dipali-Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Fixed Please check.
