### ISSUE TITLE
Project does not display all child projects

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1042]
The project NA18-A-Research2020 (Funded Research for the 2020-2022 cycle) does not display all ten of its child projects. it is missing 
1. 2018SP-R-Hardison-WQ3
2. 2018SP-R-Hetland-H8

http://eseagrant.texasseagrant.org/index.php?module=Projects&relatedModule=Projects&view=Detail&record=120483&mode=showRelatedList&tab_label=Child%20Projects

**Comment by ecsion** [comment]
Drew, It appears like the projects you mentioned were not added as a child project. If you add them, they will then appear. Or are we missing something here?

**Comment by Drew-Casey** [comment]
On my screen it is showing it as a child project:

**2018SP-R-Hardison-WQ3**
Parent Project: NA18-A-Research2020: Funded Research for the 2020-2022 cycle

**2018SP-R-Hetland-H8**
Parent Project: NA18-A-Research2020: Funded Research for the 2020-2022 cycle

**Comment by Drew-Casey** [comment]
Currently, the following projects are listed under the child project tab for NA18-A-Research2020: 
1. 2018SP-R-Armitage-H7
2. 2018SP-R-Scarpa-RCF1
3. 2018SP-R-Pollack-H9
4. 2018SP-R-Yazdan-CNH6
5. 2018SP-R-Montag-WQ4
6. 2018SP-R-Behzad-CNH7
7. 2018SP-R-Fox-SA1
8. 2018SP-R-Figlus-CNH1

When I search in the link projects popup for Parent Project "Funded Research for the 2020-2022 cycle", they do appear. When you look at "2018SP-R-Hardison-WQ3" and "2018SP-R-Hetland-H8" project information page, they list "NA18-A-Research2020" as a parent project. So this is an improvement, previously, not all projects would appear in the link project popup search. The only issue that remains is the Child Project tab.

**Comment by Drew-Casey** [comment]
There is another project not listed under the Child Projects (2018SP-R-RCE4).

**Comment by ecsion** [comment]
Drew, Just wanted to let you know that this issue is a bit complicated and will take time, we will let you know once fixed.

**Comment by Drew-Casey** [comment]
Works beautifully! Thank you. 

Here is a screenshot of it working
![image](https://user-images.githubusercontent.com/44243756/88826190-0fde2780-d18e-11ea-8b4e-ab04e848f1a8.png)
