### ISSUE TITLE
MDSG: 90-4s not populating the proposal zip file for PI

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1043]
We've created new budgets for a proposal. The 90-4s are included in the "proposal documents zip file" on the submission summary page for the administrator but not for the PI. Is this standard practice? I would like my PIs to have the 90-4s downloaded as part of the zip file (currently they only see the budget worksheet). Is there a setting for this?
Example:
https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=122593&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by mzwolinski** [comment]
Texas Sea Grant would like that functionality too, please.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
Office: 979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/

**Comment by Dipali-Ecsion** [comment]
Fixed on both servers.. Please check.

**Comment by mra142** [comment]
Checked on MDSG with several PIs logins. Works correctly. Thanks. Closed.
