### ISSUE TITLE
Cannot start report from "Project Reports" screen

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1044]
I click on the pencil icon for a "Not Created" project but it does not allow me to start the report. I am able to open reports that are already started and some projects. I tried it on two accounts. 

Cannot open 2016SP-R-Wetz-EQ8

 http://eseagrant.texasseagrant.org/index.php?module=CallReporting&relatedModule=Reporting&view=Detail&record=108661&mode=showRelatedList&tab_label=Project%20Reports

**Comment by Drew-Casey** [comment]
I was able to login as the PI and start it.

**Comment by ecsion** [comment]
Drew, If this happens again, let us know and if at all possible, do not start it from the PI Dashboard. We will take a database snapshot to trace the error. Thanks.
