### ISSUE TITLE
Justification: Senior Personnel missing in justification narrative. Again

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1046]
Referring to this proposal:

https://eseagrant.mit.edu/index.php?module=RFPProposal&view=Detail&record=118016&mode=showBudgetListingData&tab_label=QnVkZ2V0cw==&tab_label=QnVkZ2V0cw==

The Senior Personnel section is missing entirely from BOTH Year 1 and Year 2 justification narratives, titled "Aquaculture supplemental Anthony CJ's Edits Year 1" and "Aquaculture supplemental Anthony CJ's Edits Year 2", respectively.

In the corresponding 90-4s, the SP section appears, but only the PI is listed

**Comment by ecsion** [comment]
We have added additional checks. Could you please verify again.

**Comment by Nebules** [comment]
⁣
------ 

Web Developer, MIT Sea Grant 
Massachusetts Institute of Technology 
77 Massachusetts Ave NW98-165 
Cambridge, MA 02139 
phone: 617.252.1675 
e-mail:  bbray@mit.edu 
www:  https://seagrant.mit.edu

​

**Comment by ecsion** [comment]
Ben, Your reply has no comments.

**Comment by Nebules** [comment]
I haven’t replied yet. Your email was forwarded to Alexis and Caroline for their verification. I’m in a meeting until 2p

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On May 12, 2020, at 11:17 AM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Ben, Your reply has no comments.

**Comment by ecsion** [comment]
Ben, We are closing this issue. If you later find that this is not fixed, you can reopen this. Thanks.
