### ISSUE TITLE
MDSG: Change PI search function not working

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1047]
In a proposal, on the "start Here" page I'm trying to use the change PI button. The dropdown functions and I can select a PI, but the search/filter function in this dropdown is not working. It only lets me type in one letter at a time and it does not reduce/filter teh selections.

Example: https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=122442&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ&tab_label=U3RhcnQgSGVyZQ==

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![Screenshot from 2020-05-19 16-41-12](https://user-images.githubusercontent.com/17423049/82319705-b1f3cd80-99ef-11ea-8c21-b694cf650575.png)

**Comment by mra142** [comment]
Successful. Thanks.
