### ISSUE TITLE
Supported Student Form Outputs Numbers

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1050]
When I download the results of a form that contains the supported student question block, it only outputs a number that is not searchable or referenceable in eSeaGrant. Can you fix it so that it outputs at least the name and email address? Ideally, it would be nice if it outputed all fields. 
[PMA-03_Supported_Student (RQP-2020-Q1).pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/4692072/PMA-03_Supported_Student.RQP-2020-Q1.pdf)

**Comment by Dipali-Ecsion** [comment]
Drew, Currently Student Supported questions require a specific key for us to know how to handle the Student Supported question. That key was missing in the Student supported question and I have corrected that. The output is looking correct now.

We are analyzing this issue and in the future we will keep a flag in the db so the key issue can be avoided altogether.

**Comment by Drew-Casey** [comment]
It is now outputting with more cells but the columns are off. 

[PMA-03_Supported_Student (1).xlsx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/4702704/PMA-03_Supported_Student.1.xlsx)

**Comment by Dipali-Ecsion** [comment]
Drew, I was able to reproduce the issue. I will look into it further. In the meantime, please download the report from Custom Form responses and there it is working fine. I just need some more time to fix this issue and I will let you know once it is fixed.

http://eseagrant.texasseagrant.org/index.php?module=MultipartAnswers&parent=&page=1&view=List&viewname=169&orderby=&sortorder=&type=&showList=true&tab_label=Custom+Form+Responses&search_params=%5B%5B%5B%22answer%22%2C%22c%22%2C%22PMA-03+Supported+Student%22%5D%5D%5D

**Comment by ecsion** [comment]
fixed, please check

**Comment by Drew-Casey** [comment]
It is working. Thank you
