### ISSUE TITLE
URGENT: on-campus worksheets are not being exported

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1052]
email to PI...

"I reviewed your budgets and this seems to be bug in the Submission Preview - "Download Proposal Docs” export script, where the on-campus worksheets are not being exported.  A quick glance at one of the 90-4s shows that the budget worksheets are totaling properly into their respective 90-4. So the submitted data is intact, and the 90-4 forms that are generated from the worksheets are working.

I’ll notify the company that manages eSeaGrant to expedite a resolution, as far as your submitted budget data goes, there’s no problem.  Just ensure that the data in the worksheets is correct. And until the bug is resolved, to obtain a copy of the worksheets missing in the export script, you’ll need to click ‘EDIT’ to open the worksheet and then the printer icon at top right to export a PDF."

**Comment by ecsion** [comment]
fixed, please check

**Comment by Nebules** [comment]
fixed. thanks

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jun 2, 2020, at 11:20 AM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



fixed, please check
