### ISSUE TITLE
MDSG: Missing/Hidden button for indirect budget justification

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1054]
Hello, on the new budget module application that was just installed, the button/image to add a budget justification for indirect costs is missing. If you know to click on the space, you can do so if there is indirect values table, but you have to know it's there. When you save information to the indirect justification, the "added" icon does not pop up either. This is very important because applicants are missing adding this info!

Example: https://eseagrant.mdsg.umd.edu/operations.php?action=budget&proposal_id=MTIxNDEy&id=207

**Comment by ecsion** [comment]
fixed, please check

**Comment by mra142** [comment]
Looks good. Thanks.
