### ISSUE TITLE
Choose Projects Not Pulling all Projects

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1056]
I am attempting to do a report call and the choose projects will not show all the projects in a category. I was able to grab the projects by duplicating a past report. But for example: 2016SP-R-Cairns-EVT1 did not appear when searched by Project Number, PI, Project Status, etc. 

I created a new report call and it is still not working: https://eseagrant.texasseagrant.org/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=127800&mode=showRelatedList&tab_label=Select%20Projects

**Comment by ecsion** [comment]
We have simplified how projects are selected and this issue is no loner applicable. Closing this issue.
