### ISSUE TITLE
please change IDC defaults for our program

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1057]
MITSG defaults should be 0.59 as opposed to 0.065

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by Nebules** [comment]
confirmed. thanks

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jul 1, 2020, at 11:42 AM, Dipali-Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Done. Please check.
