### ISSUE TITLE
MDSG (maybe more broadly): Budget update has changed past submitted proposal budgets IDC

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1059]
When the budget module was implemented for MDSG with the new subaward functionality, it appears that the option for an "other" indirect cost category was replaced with the "subaward" category. This has made previously submitted proposals that had the other category change to subawards (Is this true for other institutions? See example 1). For some, this is a major change because there were multiple budgets under several categories of indirect cost charges. The "Other" category should be re-instituted in the droplist so that there are four options, on campus, off campus, other, subaward. Other is appropriate in several cases because not all universities use "on campus" or "off campus" rates only. Additionally, the "other" rate is still available to set up when putting together the budget (for example here: https://eseagrant.mdsg.umd.edu/index.php?module=RFP&view=Detail&record=113014&mode=showDurations&showList=&tab_label=QnVkZ2V0IFNldHVw&showList=All%20RFP,%20Fellowships%20and%20Internships)

Example 1: https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=113020&mode=showBudgetListingData&tab_label=QnVkZ2V0cw&showList=&tab_label=QnVkZ2V0cw==

**Comment by ecsion** [comment]
Fixed, Please check.

**Comment by mra142** [comment]
Thanks
