### ISSUE TITLE
Custom forms glitch when creating new report call based on selected call

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1060]
When I created a new report call based on a previous report call, the linked custom forms changed their order, and changed to NOT show to PI. Also, the hardcoded "Publications" form didn't copy over and I had to re-add it.  (Mac OS X Safari.)

Report call created from previous report call:
![image](https://user-images.githubusercontent.com/61889985/86621382-90807e00-bf6a-11ea-8366-58ddd5966017.png)

Original report call:
![image](https://user-images.githubusercontent.com/61889985/86621203-40092080-bf6a-11ea-8b21-586adc995fae.png)

**Comment by Dipali-Ecsion** [comment]
Fixed Please check

**Comment by ecsion** [comment]
Closing this. If you are still experiencing issues, then please reopen.

**Comment by dpartee** [comment]
Look to be working correctly, thanks!
