### ISSUE TITLE
email interface isn't working..."message body empty"

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1063]
I tried to send an email announcing to PIs the rebuttal phase, but upon selecting a template and clicking SEND, I get an error 'message body empty'.

**Comment by ecsion** [comment]
Hi Ben, Please provide the 
1. RFP, 
2. Phase, 
3. Email Template you used.

We will then try to reproduce the issue and get back.

**Comment by Nebules** [comment]
RFP / phase :
https://eseagrant.mit.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=112478&phaseid=112480&tab_label=RnVsbC1Qcm9wb3NhbA==&showList=RFP#

template : “Rebuttals Open (PEOPLE)"


------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jul 13, 2020, at 12:08 PM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Ben, Please provide the

  1.  RFP,
  2.  Phase,
  3.  Email Template you used.

We will then try to reproduce the issue and get back.

**Comment by ecsion** [comment]
Ben, The issue is fixed. Please check.

**Comment by Nebules** [comment]
confirmed. thanks for the rapid response

best
b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jul 13, 2020, at 1:35 PM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Ben, The issue is fixed. Please check.
