### ISSUE TITLE
TXSG: Past Due email not working

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1064]
The past due email is not automatically pulling the PI email when the email button is pressed and the email popup is opened. When the popup opens, the form is completely blank. When you select the email template, it does not pull the same template that is seen on the "Reminder Email Templates" tab. When the email is sent, the due date is the only coded item that is populated. The system worked as intended on the first attempt but subsequent attempts had the same errors. 

Email example:
"Hello $reporting-pi_name$,
Your report for $reporting-reporting_call$ project titled "$reporting-project_name$",
$reporting-project_number$, was due on 10 Jul 2020. You can submit the report from your eSeaGrant dashboard: https://eseagrant.texasseagrant.org/
If you have any questions, please contact the Texas Sea Grant Team.
Thank you,"

![image](https://user-images.githubusercontent.com/44243756/87561095-d1227a80-c681-11ea-8f55-eb935c982a54.png)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by Drew-Casey** [comment]
So far it appears to be working. I cannot check the "Past Due email" feature at the moment but the other automated email tabs are working. I have a report in two weeks so I will open a new request if it does not work then. Thank you Ecsion.
