### ISSUE TITLE
RISG: PDF Not Created Using New PDF Tool

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1065]
At this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=110688&phaseid=110690&tab_label=RnVsbC1Qcm9wb3NhbA==&showList=#
and clicking Proposal PDF to view the document, the following document is produced (see screen shot)
![Screen Shot 2020-07-17 at 1 10 14 PM](https://user-images.githubusercontent.com/18398763/87813103-3f587000-c82f-11ea-8c92-d09ade19618d.png)
Similarly, at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=110688&phaseid=110690&tab_label=RnVsbC1Qcm9wb3NhbA==&showList=#
if you click the Preview button the following is generated (see screen shot)
![Screen Shot 2020-07-17 at 1 08 52 PM](https://user-images.githubusercontent.com/18398763/87813203-762e8600-c82f-11ea-9b0c-ed8b0408b3a8.png)
A PDF document is NOT being created. This needs to be corrected. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
