### ISSUE TITLE
TXSG: Publication Form Issues

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1067]
When trying to submit a publication, the error message says {"success":false,"error":{"code":"Record you are trying to access is not found","message":"Record you are trying to access is not found"}}

This was discovered on QPM-2020-Q2 report call and AHR-2020-2019 Statements. I have unchecked all the "Show to PI" flags in the open report calls temporarily until the error is fixed. 

Also, the field "Publication URL or Related URL" says "contains illegal characters". What are the characters not allowed in this field?

**Comment by ecsion** [comment]
fixed, please check

**Comment by Drew-Casey** [comment]
It is working. Thank you.
