### ISSUE TITLE
TXSG: Closed report calls appear on "Current Tasks"

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1068]
https://eseagrant.texasseagrant.org/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask

In a few PIs' "Current Tasks" page, there are closed projects that appear. At first, I thought it was my error because I did not uncheck the "Temp Close" box when I checked the "Close after end" box. But I just confirmed that the report call " EMM-2019-October" appears on Nicole Pilson's current tasks and the "Temp Close" is un-checked.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by Drew-Casey** [comment]
So far so good. Thank you.
