### ISSUE TITLE
RISG: Error in email use/suggestion for "help" popup

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1069]
At this URL:

https://eseagrant.gso.uri.edu/index.php?__vtrftk=sid%3A45ff6f52f942fb867fc4c71ef5bc1c5749dc2500%2C1596630221&selected_ids=%5B%22112669%22%5D&excluded_ids=%5B%5D&viewname=177&module=Emails&view=ComposeEmail&callreportingid=&rfpphaseid=&search_key=&operator=&search_value=&search_params=%5B%5B%5D%5D&fieldModule=Projects&to=%5B%5D&selectedFields=%5B%22project_email%22%5D&triggerEventName=postSelection8209

when enacting the Spell Checker option, the screen show below (see screenshot) cannot be closed by clicking cancel, or by clicking the "X" in the top right corner, leaving the only option to quit the browser and lose all work. Please correct this so that the Spell Check screen can be closed/cancelled.

![Screen Shot 2020-08-05 at 8 23 18 AM](https://user-images.githubusercontent.com/18398763/89412630-6a7b0480-d6f5-11ea-9805-784740ff1696.png)

At the same URL as above, as shown in the screenshot below, the help bubble "Rich Text Editor, description" remains on the screen while typing in the email text content box. The bubble does not disappear and blocks out text that is typed. Can you please make the help bubble disappear after a 2 or 3 second time on screen? Thank you. While helpful in describing what function the email content box serves, it is annoying that it stays always on screen, and in the way. A second or two on screen is all that is needed, so please put a timer on that. Thank you.

**Comment by alandesbonnet** [comment]
![Screen Shot 2020-08-05 at 8 22 40 AM](https://user-images.githubusercontent.com/18398763/89412952-f2610e80-d6f5-11ea-8805-6c3f9651a29b.png)

Apologies. Here is the 2nd screenshot noted in original request above.

**Comment by Dipali-Ecsion** [comment]
We Fixed this issue. Please check and let us know.

![image](https://user-images.githubusercontent.com/17423049/89438332-56232000-d766-11ea-8658-ffaeb0efa52f.png)

**Comment by alandesbonnet** [comment]
The spell check function is now fixed Thank you.
 At some point please do look into fixing the way the help popup behaves when cursor is located in the email text composing box. It should turn off so as not to block out what is being typed; very annoying feature.
