### ISSUE TITLE
Register page on login screen

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#107]
For N.H. Sea Grant's instance, the eSGAdministrator and Retrieve Password links do not work.

![image](https://cloud.githubusercontent.com/assets/17415806/13751140/1b727768-e9df-11e5-8b83-cb525c7b8ebe.png)

**Comment by mcbridec** [comment]
For Oregon Sea Grant, our eSG Administrator link is not working. 
![2016-03-23_1212](https://cloud.githubusercontent.com/assets/17169131/13997933/a09ed0c6-f0f1-11e5-8c73-fce68affe950.png)

**Comment by ecsion** [comment]
done.
