### ISSUE TITLE
MDSG: Update to IDC rates in budget module

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1070]
Hello,
Can you please update the default IDC rates in the budget module for the Maryland system. The new rates are:
On campus: 0.545
Off campus: 0.26
Other: 0.00
These apply to all categories.
Thank you,
Mike

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by mra142** [comment]
Looks good. Thank you!
