### ISSUE TITLE
[Urgent] TXSG: Cannot download Custom Form Report

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1071]
On the "AHR-2020-2019_Statements" report call, I can download two of the three custom forms but I cannot download "Impact & Accomplishment Statements" responses. When I click on it, I get a blue screen and the following error message:
"Invalid cell coordinate 6
Please contact the Sea Grant Administrator for further assistance."

Here is the link:
https://eseagrant.texasseagrant.org/index.php?module=CallReporting&view=Detail&mode=DownloadCustomFormReports&record=127985&question_id=127986

**Comment by Dipali-Ecsion** [comment]
Fixed Please check.

**Comment by Drew-Casey** [comment]
It is working fine now. Thank you.
