### ISSUE TITLE
TXSG: Due Date 24 hours Early

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1073]
The exact time for a due date was at midnight the day of but recently it has been triggering midnight the day before. For example, our EMM-2020-August report deadline is Friday (Sep 11). Previously, eSeaGrant would show that is was due Friday, with late reports on Saturday. Now it shows late reports on Friday. Currently, it is Thursday 11:35 AM (Sep. 10) and it displays 12 Hrs 25 Mins remaining until the deadline. 

Is there a way to change the due time in the system (maybe 11:59 PM or 5:00 PM the day of)?

Drew

**Comment by alandesbonnet** [comment]
Drew,
This is a bug pointed out to Deepak earlier, and they are seeking a fix but I guess not completed yet. To compensate I set it for 1 day later, making note to applicants to be sure they understand.
AD

Alan Desbonnet
Assistant Director
