### ISSUE TITLE
ORSG- Emails not being sent

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#1076]
Yesterday it seemed the emails were not being sent at all from eSeaGrant. Trying again this morning, I get and error message "SMTP Connect() failed." Any help or advice on how to remedy this quickly would be great. Thank you.

**Comment by ecsion** [comment]
Oregon smtp server is refusing connection. Sending separate email on next steps.

**Comment by STI-ORSG** [comment]
Hi, this may be an issue with the Oregon State University server again, but I wanted to note that there are issues with sending emails from eSeaGrant again. The error message is below, and I have also reached out to IT support at OSU. Any help you can provide would be great.

SMTP Error: Data not accepted.
SMTP server error: 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:C93A0000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:442A0000, 1.36674:0E000000, 1.61250:00000000, 1.45378:492A0000, 1.44866:18050000, 16.55847:47180000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140FD58D1900F01F00000000, 20.50032:140FD58D8917F01F00000000, 0.35180:140FD58D, 255.23226:0A00

**Comment by ecsion** [comment]
We have made some changes to the form email and you will no lower have this issue. Please check.

**Comment by ecsion** [comment]
Closing this issue. Please reopen if you still encounter this issue.
