### ISSUE TITLE
Automated Reminder Emails not sending

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1077]
Hello Ecsion, 

I had brought up the automated emails not working before, so I ran a test with a dummy call and dummy projects. It still did not work and I am pretty sure no automated emails are being sent. 

I established a test report call (Test Report Call) and included some dummy projects but never received those emails. Here is a link to the report call. 
https://eseagrant.texasseagrant.org/index.php?module=CallReporting&view=Detail&record=129959&tab_val=Test%20Report%20Call

Here is the list of projects that were meant to receive the reminders.
Test Report Call | 2018SP-A-Casey | Drew Casey | drew.casey@tamu.edu | Past Due |  
Test Report Call | 2018SP-A-Extension | Reporting TXSG | txsgreporting@tamu.edu | Past Due |  
Test Report Call | NA18-M-Research2020 | Reporting TXSG | txsgreporting@tamu.edu | Past Due |  

List of Reminders
1 week before due date								  
2 days before due date								  
12 hours before due date								  

Both the PIs and the Administrators were meant to receive the emails but we did not get anything.

The due dates link: https://eseagrant.texasseagrant.org/index.php?parent=Settings&module=DueDates&view=DueDates

Please let me know if you need any more information. 

Thank you and Happy October,
Drew

**Comment by Dipali-Ecsion** [comment]
Setup Reminders.. Please check.

**Comment by Drew-Casey** [comment]
I created "Test Report Call" and had a few test projects on it. I also have heard that other report calls are not sending out messages. 

(REPORT LINK: https://eseagrant.texasseagrant.org/index.php?module=CallReporting&view=Detail&record=130334&tab_val=Test%20Report%20Call)
