### ISSUE TITLE
WISG - Submission preview does not display selected item in drop down boxes

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1078]
Drop down boxes do not display values in the submission preview tab.

Example: https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=118955&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&showList=&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

<img width="1005" alt="Screen Shot 2020-10-29 at 11 25 54 AM" src="https://user-images.githubusercontent.com/36545478/97602815-c0e89e00-19d9-11eb-8831-6f88b2a723f6.png">

<img width="968" alt="Screen Shot 2020-10-29 at 11 28 15 AM" src="https://user-images.githubusercontent.com/36545478/97602899-df4e9980-19d9-11eb-9267-bc28973b1477.png">

<img width="994" alt="Screen Shot 2020-10-29 at 11 25 34 AM" src="https://user-images.githubusercontent.com/36545478/97602832-c514bb80-19d9-11eb-9f8e-e2cab67bc804.png">

**Comment by ecsion** [comment]
This was due to old form that has a different data design. We have now converted the form to new data design and the problem is fixed. Please check.

**Comment by tomxiong-aqua** [comment]
It looks fixed.
Thanks!
