### ISSUE TITLE
WISG - Peer review invite proposal title is incorrect.

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1083]
The title of the proposal is incorrect when inviting peer reviewers. It displays the previous proposal title at the top of the box.
The email goes out fine, but it makes things confusing when going to add a reviewer to the next proposal.
It displays the correct title in the little grey box in the lower left. See the screenshot below.

<img width="1047" alt="Screen Shot 2020-12-01 at 3 19 06 PM" src="https://user-images.githubusercontent.com/36545478/100798207-ea398700-33e8-11eb-89f6-80f9eaec3710.png">

**Comment by ecsion** [comment]
fixed, please check
