### ISSUE TITLE
WISG - cannot send email out to peer reviewer

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1084]
We are having an issue sending the peer review email out to an email. The email address is ulrichb@d.umn.edu. The email is valid and correct. See screenshot of the error below:
<img width="1047" alt="Screen Shot 2020-12-01 at 3 19 06 PM" src="https://user-images.githubusercontent.com/36545478/100798593-78157200-33e9-11eb-9541-cedd56dfed59.png">

**Comment by ecsion** [comment]
fixed, please check
