### ISSUE TITLE
eSeaGrant - Document Request Form Issues

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#1085]
This afternoon, I received an email from a faculty member (condensed email below; bold text) who was unable to upload their letter of recommendation for an applicant’s proposal ([click here](https://vaseagrant.ecsion.com/operations.php?action=responseform&guid=67E6A450-DA3B-47BC-89B5-8FC0942851F7) for direct link to the document request form). I asked the faculty member to send me the PDF so I could troubleshoot the issue (attached “strohm_researchFellowshipLetter”). I seem to be experiencing the same problem using FireFox. I tried changing the file name, uploading the letter as a new Word document (attached), and attempted to upload both versions to my “test proposal” which I created when drafting the RFP in October. This is very strange since I tested the form on October 22 and it worked perfectly; however, it does not appear to be working now. 

I have included a series of screenshots below, capturing the upload process. Note that the final image displays the error message “No changes made, nothing to save!”, which occurs after the pop-up menu “Alert! Data saved successfully” is closed, and prior to being able to click the “Submit” button. 

Thank you for any support you can provide to quickly resolve this issue. We currently have 40+ applicants at this stage (totaling more than 120 letters) that we are anticipating in the next several days. 

All the best,
Sam
Samuel J. Lake, Ph.D.
Fellowship & Research Program Coordinator
Virginia Sea Grant College

Pronouns: he, him, his
Office phone: (804) 684-7436
Cell phone: (757) 645-8997
Email: sjlake@vaseagrant.org

**I have my letter in pdf format but it does not seem to upload. After I select the file, there is a message: “File not uploaded. Click Save button to complete uploading the file.” When I click Save, there is a progress window, then an Alert box that says “Data Saved Successfully”. When I close that, there is a message “No changes made, nothing to Save”. The Red circle is still around the number indicating nothing was uploaded. I tried in Safari, Firefox and Chrome with the same result. Any help you can offer would be appreciated.**

<img width="504" alt="image" src="https://user-images.githubusercontent.com/17860369/100935488-27237d80-34be-11eb-8162-83e309be584a.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/17860369/100935511-2d195e80-34be-11eb-9330-b25f3fa1e809.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/17860369/100935526-3276a900-34be-11eb-8033-929ddeb91900.png">
[strohm_researchFellowshipLetter.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/5632255/strohm_researchFellowshipLetter.pdf)

**Comment by ecsion** [comment]
This issue is fixed, please check.

**Comment by ecsion** [comment]
Sam, We are closing this issue, please reopen if this is not completely resolved.
