### ISSUE TITLE
ORSG: hyperlinks inside completed custom report forms

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#1086]
We usually can open hyperlinks inside completed custom report forms. These are the ones the reporter/PI uploads into eSeaGrant. Those particular hyperlinks for their document no longer work inside the form. Are we able to get those back to being live links or is there a reason those are no longer alive? We can download the separate pdfs, but this was a handy feature in the past. An example is here:

https://eseagrant.oregonstate.edu/index.php?module=MultipartAnswers&view=Detail&record=134984&tab_val=2020%20Final%20Summer%20Scholars%20Portfolio

![Screenshot 2020-12-17 114538](https://user-images.githubusercontent.com/17169131/102535794-8e643480-405d-11eb-811e-772d4475079f.jpg)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by ecsion** [comment]
Cathy, we are closing this issue. If this is not fixed, please email me at deepakseth@ecsioj.com and I will reopen.
