### ISSUE TITLE
RISG -- Mail List Export Not Functioning Correctly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1087]
at this URL:
https://eseagrant.gso.uri.edu/index.php?module=MailList&view=Detail&record=117691&tag_val=Barbara%20Ann
You will see first and last name (automatically concatenated to Full Name in eSeaGrant) exists (screenshot below)
<img width="1128" alt="Screen Shot 2020-12-17 at 3 34 02 PM" src="https://user-images.githubusercontent.com/18398763/102540639-4f45db80-407d-11eb-99f0-249f060d4dc5.png">
However, at this URL:
https://eseagrant.gso.uri.edu/index.php?module=MailList&view=List&viewname=265&tab_label=COVID%20Mail%20list
You will see that the Full Name data do not appear in the Custom Form search for that entry (screenshot below)
<img width="1247" alt="Screen Shot 2020-12-17 at 3 28 58 PM" src="https://user-images.githubusercontent.com/18398763/102540759-7f8d7a00-407d-11eb-9a4c-0c1fd28ec824.png">
If you click the topmost entry the record opens and shows first and last name data are there.
This is happening with multiple data entries, most of which were just recently entered and/or edited for correction. Since the first and last name data are not returned in the custom form search, the exported Excel workbook to be supplied to a printer to create mailing labels is incorrect. This must be fixed so we can complete our December mailing. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
The names now show up in the Custom Form search, but when I attempt to export all the program hangs up — the file is not exported and the eSeaGrant program becomes unresponsive and I must use Force Quit the browser.

Alan Desbonnet
Assistant Director

**Comment by alandesbonnet** [comment]
The names now show up in the Custom Form search, but when I attempt to export all the program hangs up — the file is not exported and the eSeaGrant program becomes unresponsive and I must use Force Quit the browser.

**Comment by alandesbonnet** [comment]
Fixed. Thank you.
