### ISSUE TITLE
TXSG RFP 2022-2024-TEST-Pre-prop Project Summary Download Missing PI Name

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1089]
The Project Summary included in the downloaded proposal doc zip file has the PI Name missing. The attachment included with the proposal submission email does correctly have the PI Name displayed. 
[Project_Summary_Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/5766877/Project_Summary_Form.pdf)
[131715proposal.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/5766885/131715proposal.pdf)

PIs are starting their pre-proposals today and are due 1/15. Will be helpful if the Project Summary can be corrected to display their name during this week. Thank you for your assistance, Mia Zwolinski, TXSG Assistant Director.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mzwolinski** [comment]
Yes working, just checked! Thank you!

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
