### ISSUE TITLE
TXSG: Researcher is not receiving the code to his cell phone and the retry button has not worked. He uses a Mac, Firefox yesterday and used Google Chrome this morning. Name is Peter Santschi at Texas A&M at Galveston, santchhi@tamug.edu and ph # 409-539-1007. Please review and advise. Thank you, Mia Zwolinski, Asst Director, Texas Sea Grant.

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1090]
TXSG: Researcher is not receiving the code to his cell phone and the retry button has not worked. He uses a Mac, Firefox yesterday and used Google Chrome this morning. Name is Peter Santschi at Texas A&M at Galveston, santschi@tamug.edu and ph # 409-539-1007. Please review and advise. Thank you, Mia Zwolinski, Asst Director, Texas Sea Grant.

_Originally posted by @mzwolinski in https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/902#issuecomment-755426157_

**Comment by mzwolinski** [comment]
Please assist.

**Comment by ecsion** [comment]
The eSeaGrant system makes a voice phone call, it currently does not send an SMS. We do this as many people use land line phones that do not have the SMS feature. 

If you phone is setup to go to vm for unknown numbers, then the incoming call would have gone to vm.

We grabbed the logs of phone activity with 409-539-1007 and our records show 6 phone calls being made that lasted approximately 16 seconds. See attached screenshot. 

Please check your phone records to see if you received a call from this number: 13049044357

<img width="1198" alt="Screen Shot 2021-01-07 at 2 48 47 PM" src="https://user-images.githubusercontent.com/1612666/103939041-243d2d80-50f9-11eb-8d74-ea7e9272f800.png">

**Comment by ecsion** [comment]
This turned out to be user error. The user blocked calls and so no longer received calls.
