### ISSUE TITLE
WISG - Preproposal pdf does not show some content

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1091]
Looks like it is just happening in this preproposal at the moment.
The pdf is missing field #14, the "Approach" field, in this preproposal:
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=120173&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&showList=&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by ecsion** [comment]
Closing this issue, please reopen if you still encounter this issue.
