### ISSUE TITLE
Alaska: No space between first and last name in 'add delegate' list

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1094]
From the "actions" menu in the RFP application, there is the option to Add/Update Delegates. There is no space between the first and last names in the list of people that appears.
![image](https://user-images.githubusercontent.com/61889985/104058231-e0e9ca00-519f-11eb-8db3-f580e0237d8a.png)

**Comment by ecsion** [comment]
This is fixed, Please check

**Comment by ecsion** [comment]
Closing this issue. Please reopen in case you still encounter any issues.

**Comment by dpartee** [comment]
Yes, looks good, thanks!
