### ISSUE TITLE
WISG - Password reset not working

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1096]
The user and I cannot reset the password for the account. 
See the attached screenshot:

<img width="684" alt="Screen Shot 2021-01-12 at 8 52 58 PM" src="https://user-images.githubusercontent.com/36545478/104400723-82627a00-5518-11eb-8598-9c96742c593d.png">

**Comment by tomxiong-aqua** [comment]
I reset the password and the user now gets this error when trying to log in.

![Screen Shot 2021-01-13 at 3 34 25 PM](https://user-images.githubusercontent.com/36545478/104513641-914b3a00-55b5-11eb-9a0d-f21a3c441727.png)

**Comment by ecsion** [comment]
This issue is fixed.

**Comment by ecsion** [comment]
fixed and verified.
