### ISSUE TITLE
NCSG - User Showing Inactive

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#1097]
I had a user that was trying to log in and I have reset her password - Sara Mirabilio as the investigator.  It is showing that her account is deactivated.  What needs to be done to get her account reset?  I tried to delete it and reset it but, it would not allow me.

**Comment by mebarrow** [comment]
Here is what I have done.  I have created a password myself - SaMiR2021!? and I use the email listed in the account - sara_seagrant@ncsu.edu.  When I try to log in I get this:
![image](https://user-images.githubusercontent.com/21174930/104495112-52ad8380-55a5-11eb-9bc3-608c4ed95455.png)

**Comment by ecsion** [comment]
fixed and verified.
