### ISSUE TITLE
TXSG Registration Issue

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1098]
PI cannot get further than password then screen says to get with Administrator. Pre-proposal due Friday. jessica.oconnell@utexas.edu

Communication:
Hi Mia,

I got through the email and phone verification, and on to the password
creation, which I think is the last step. I tried on two different
browsers. I was stopped in both cases at the password creation phase. I
tried several iterations of a password, and paid attention to the
password rules mentioned on screen. I also tried starting over and
making sure my last name didn't have special characters, in case that
was part of the problem. Nothing I did worked, so far.

Jessica

--
Jessica O'Connell, Ph.D
Assistant Professor, Department of Marine Science
University of Texas at Austin | Marine Science Institute
landscapemodeling.net

On 1/13/21 8:54 PM, Zwolinski, Mia wrote:
> Hi Jessica,
>
> I see that you were able to start the registration process, twice, per the two attached emails. Did you also receive the phone verification code? You have to actually answer the phone; it is not a code sent via text. I'm just thinking through some recent resolutions.
>
> Let me know if this is helpful.
>
> Regards,
> Mia

**Comment by mzwolinski** [comment]
Please assign and resolve. Pre-proposal due tomorrow, Fri Jan15. I can add the PI, but want to understand the problem so does not repeat for other registrants. Thank you, Mia Zwolinski, Asst Director, TXSG.

**Comment by ecsion** [comment]
We currently do not support special characters in the name during Registration. So we have added this user from backend. *The user should have received login info and should bebe able to use his account.*

We will add a new feature  in the February/March release that will allow registration users with special character in their name. In the meantime, if you have a user who wants to register and a special character in their name, please create a ticket fir us.

**Comment by mzwolinski** [comment]
Thank you for setting her up! PI did state that she did not use special characters…

PI has now submitted a pre-proposal.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
-------------------------------------------------------------------
