### ISSUE TITLE
TXSG  All Proposals Component Zip Download - zipfile is not valid

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1099]
All Proposals Component Zip Download - zipfile is not able to be opened. Properties show 5MB. Message states the Windows cannot open, that the zip file is not valid.  Pre-proposals are due Fri Jan 15.  
Thank  you for your assistance. 
Mia Zwolinski, Asst Dir, TXSG.
![image](https://user-images.githubusercontent.com/23663698/104666467-9b466900-5699-11eb-87ef-2bf793ba8bf9.png)

**Comment by ecsion** [comment]
Mia, We tried the download on Windows and Mac and it worked fine. Please try one more time to see if the issues fixes. Sometimes, bad internet connection may terminate the download of the file too soon. If you try this again, you will likely not face the same issue. Please let us know.

**Comment by mzwolinski** [comment]
Hello, Still unable to extract. Other excel downloads have worked. Zipfile Component PDF is not. I have not had any I’net issues. The download was never terminated. As mentioned yesterday, the properties had a size of 5MB; this morning’s is now 7MB. We already have 74 submissions with 12 in-progress. I use Firefox.

Will try with Google Chrome…

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University

**Comment by ecsion** [comment]
Ok got it. Please check on chrome. Also could you please ask one of your colleagues to try and check the results. It is working  fine on our end.

**Comment by mzwolinski** [comment]
Same exact error with Google Chrome.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program

From: Zwolinski, Mia
Sent: Friday, January 15, 2021 11:06 AM
To: 'ecsion/eSeaGrant-Client-Bug-Tracker' <reply@reply.github.com>
Subject: RE: [ecsion/eSeaGrant-Client-Bug-Tracker] TXSG All Proposals Component Zip Download - zipfile is not valid (#1099)

Hello, Still unable to extract. Other excel downloads have worked. Zipfile Component PDF is not. I have not had any I’net issues. The download was never terminated. As mentioned yesterday, the properties had a size of 5MB; this morning’s is now 7MB. We already have 74 submissions with 12 in-progress. I use Firefox.

Will try with Google Chrome…

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University

**Comment by mzwolinski** [comment]
Cindy and Deepak,

Were you able to not just download, but EXTRACT the files? That is where I received the error message that Windows could not open the zipfile, that it was invalid.

Thank you,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program


Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/

**Comment by mzwolinski** [comment]
Hi Mia,
I am not familiar enough with eSeaGrant to know where to extract the files from a zip file. I can access the individual PDF files but don’t see an option to download/extract all files from a zip. I am in meetings until 6:00 this evening.

Regards,
Cindy

From: Zwolinski, Mia <mzwolinski@tamu.edu>
Sent: Friday, January 15, 2021 12:36 PM
To: ecsion/eSeaGrant-Client-Bug-Tracker <reply@reply.github.com>; ecsion/eSeaGrant-Client-Bug-Tracker <eSeaGrant-Client-Bug-Tracker@noreply.github.com>
Cc: Author <author@noreply.github.com>; Lyle, Cynthia M <cynthia.lyle@exchange.tamu.edu>
Subject: RE: [ecsion/eSeaGrant-Client-Bug-Tracker] TXSG All Proposals Component Zip Download - zipfile is not valid (#1099)

Cindy and Deepak,

Were you able to not just download, but EXTRACT the files? That is where I received the error message that Windows could not open the zipfile, that it was invalid. I have attached my download.

Thank you,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program

**Comment by ecsion** [comment]
Issue resolved. Mia will install 7-zip and use that program to unzip.

Texas A&M IT Support: For your home dell desktop, go to https://ninite.com/ and under compression there is the 7-zip program.
