### ISSUE TITLE
WISG - RFP Peer reports does not include comments.

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1100]
When trying to export all proposals in 1 pdf, the comments are missing. The comments are there if you export by multiple pdfs (zipped).
This is the RFP report I am trying to get: https://edrop.aqua.wisc.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=118530&showList=&tab_label=UkZQIFJlcG9ydHM=&showList=All%20RFP,%20Fellowships%20and%20Internships

<img width="543" alt="Screen Shot 2021-01-20 at 9 52 20 AM" src="https://user-images.githubusercontent.com/36545478/105200225-39f12080-5b05-11eb-938e-3398124ea183.png">

**Comment by ecsion** [comment]
fixed, please check
