### ISSUE TITLE
MDSG Internship Portal: PDF stitcher not handling landscape files correctly

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1101]
Hello, The PDF stitching function in "Step 5: Upload Internship Application PDF for reviewers" is mishandling transcript uploads that are in landscape format. It is putting them together in portrait format and cutting off the right side of the transcript. 

Example: https://apply.mdsg.umd.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=473&phaseid=474&tab_label=SW50ZXJuc2hpcA==&showList=Internships

Rubin, Alexander row 6.

**Comment by ecsion** [comment]
Mike, We are analyzing this to see how to fix landscape vs portrait issue.

**Comment by ecsion** [comment]
Mike, This is fixed, Please check.

**Comment by mra142** [comment]
I tried to apply the PDF template with both Rubin row 7 and Leathrum row 59 and it did NOT work.
https://apply.mdsg.umd.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=473&phaseid=474&tab_label=SW50ZXJuc2hpcA==&showList=Internships

**Comment by ecsion** [comment]
Mike, This is fixed * (really fixed) *, Please check. We fixed it on Monday but the code was not updated in deployment build.

**Comment by mra142** [comment]
Yep! Works well. Thank you!
