### ISSUE TITLE
TXSG Pre-proposal RFP - Panel Review Request

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#1102]
The pre-proposal panel review request with link was just sent to our reviewers. The email that went to the reviewer did not have the deadline date inserted within the parenthesis ( ). The RFP is: Texas Sea Grant RFP 2022-2024 Pre-proposal Phase.

The deadline was setup in the form setup tab and is set to open status. The deadline is configured correctly at the landing page for each reviewer, because when I was in-process of providing a screen print of the assignment list to each reviewer last week, it did have the # of days remaining to review. So, it is just not being input into the email. 

It did show up in the email for a prior RFP competition that I tested a couple of weeks ago, so it appears that it is just not working in the current RFP competition reviewer email. 

Link to current RFP Form Setup:
https://eseagrant.texasseagrant.org/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=131724&phaseid=131725&panelnameid=12&tab_label=UHJlLVByb3Bvc2Fs&source=Panel&showList=All%20RFP,%20Fellowships%20and%20Internships

Email with the missing due date is attached.

Thank you for your assistance with high priority, as the reviewers are starting their reviews today.

,Mia Zwolinski, 
Asst Director, Texas Sea Grant

[Email.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/5867842/Email.pdf)

**Comment by ecsion** [comment]
Mia, We will get his fixed this week.

**Comment by ecsion** [comment]
Done, Please check.

**Comment by mzwolinski** [comment]
Yes, date now appears, thank you!

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
