### ISSUE TITLE
MDSG: URGENT: User account error

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#1103]
User Nardin (https://eseagrant.mdsg.umd.edu/index.php?module=People&view=Detail&record=107200) has some error in the account that I am not able to turn it from status "user role=None" to status "User role=investigator". 
Make user role function does not work -- popup says "user already exists".

This user is trying to submit a proposal TODAY. Can this get dealt with ASAP?

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mra142** [comment]
Verified. Thank you for your promptness!
