### ISSUE TITLE
ORSG- Request for Letters of Rec not received

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#1107]
We have received notice from a few students that their letter writers are not receiving their letter request and link in their email. To my knowledge this has occurred for at least two different students. The students have noted that one of their request was successful, while the other was not even after double checking that the correct email address was used. At least one of the letter writers had received a similar email in previous years, but did not receive the request this year (even in the junk folder). Is this something that can easily be fixed?

**Comment by ecsion** [comment]
Hi Sarah, Could you please email me name of fellowship and the name of the student at deepakseth@ecsion.com and we will further troubleshoot it.
