### ISSUE TITLE
WISG - Emails to delegates do not include project info

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1110]
Project info (title, project number) is missing when sending out emails to project delegates. It works on the PI email, using the same email template.
See the screenshots below:

PI:
<img width="495" alt="Screen Shot 2021-02-11 at 9 41 59 AM" src="https://user-images.githubusercontent.com/36545478/107663098-9bae3180-6c50-11eb-822c-f5b4e4653431.png">

Delegate:
<img width="465" alt="Screen Shot 2021-02-11 at 9 42 15 AM" src="https://user-images.githubusercontent.com/36545478/107663107-9ea92200-6c50-11eb-8c64-fce8b05e52f2.png">

**Comment by ecsion** [comment]
fixed, please check.
