### ISSUE TITLE
MNSG - please update focus area choices in 90-2

### ISSUE THREAD

**Issue by ValBrady** [ecsion/eSeaGrant-Client-Bug-Tracker#1114]
In our 90-2 form (MNSG PROJECT SUMMARY (NEW 90-2) FORM), can you please update the primary and secondary focus area choices to better match National's wording and to include diversity, equity, and inclusion? So we request the drop-down list choices be these: 
•	healthy coastal ecosystems, 
•	sustainable fisheries and aquaculture, 
•	resilient communities and economies,
•	environmental literacy and workforce development,
•	diversity, equity and inclusion

**Comment by ecsion** [comment]
done, please check.

**Comment by ValBrady** [comment]
Fixed. Thank you.
