### ISSUE TITLE
Minor Edit: Report cover page and submission preview (plus PDFs) heading information

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#116]
We'd much appreciate some "minor" edits to the header text in the report and the cover page:

First, we don't think the words "COVER PAGE" actually need to appear at the top of the Cover Page display. Second, we'd like some additional fields to display on the cover and submission preview pages (plus report PDF).

## **CURRENT**
project number, reporting period, submission date/time

REPORT
E/I-24
03/01/2015 - 02/29/2016
Submitted On: 03/09/2016 03:11:59 AM

and

COVER PAGE
E/I-24
03/01/2015 - 02/29/2016
Submitted On: 03/09/2016 03:11:59 AM

## **DESIRED**
Reporting call name, PI, title, project number, reporting period, submission date/time; and REPORT changed to ANNUAL REPORT; and COVER PAGE heading removed

ANNUAL REPORT
NMFS Fellows - 2015-2016
Christine Stawitz
NMFS/Sea Grant Fellowship - Population and Ecosystem Dynamics - Evaluating the importance of growth variation in marine fish population dynamics and stock assessment
E/I-24
03/01/2015 - 02/29/2016
Submitted On: 03/09/2016 03:11:59 AM

and

NMFS Fellows - 2015-2016
Christine Stawitz
NMFS/Sea Grant Fellowship - Population and Ecosystem Dynamics - Evaluating the importance of growth variation in marine fish population dynamics and stock assessment
E/I-24
03/01/2015 - 02/29/2016
Submitted On: 03/09/2016 03:11:59 AM

**Comment by mcbridec** [comment]
Because we ask for progress reports and updates as well as completion reports, Oregon probably just wants "Report" . Or, instead of all of the reports changed to be called Annual Reports, can we pull in the field for Report Call Types into the heading? Annual Report, Progress Report, etc? We all are going to have our special Report Call Types. Is this possible?

**Comment by mgduke** [comment]
That seems like a good idea, Cathy. I'm running this by our R/C, Kate Litle.

**Comment by mgduke** [comment]
Hey, Deepak and Cathy: If Cathy's above request is feasible (pulling report call type field, etc.), we like this, too.

**Comment by ecsion** [comment]
fixed.
