### ISSUE TITLE
Staff user role issue: Requested Information missing from Reports Submission Preview

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#117]
When comparing R/C versus Staff admin access, we note that staff are unable to see the components under "Requested Information" (e.g., publications, students supported, narrative). Staff should see all the same information in a report submission preview that R/C's can see. To compare R/C and Staff views, please use the staff login of chelkahn@uw.edu, ghbrb7 and see the following for example:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=18021&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

**Comment by ecsion** [comment]
done.
