### ISSUE TITLE
Permission denied for project

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#118]
Hi, Deepak: We've encountered another one of those pesky "permission denied" issues. This is for viewing project R/COCC-3 at URL:

http://esg.wsg.washington.edu/index.php?module=Projects&view=Detail&record=1976&mode=showDetailViewByMode&requestMode=summary&tab_label=Project%20Information

**Comment by ecsion** [comment]
Data migration issue has been fixed.
