### ISSUE TITLE
URGENT: Investigator issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#119]
When investigator Clare Ryan tries to start her 2015 annual report, she's getting a "permission denied" error message. Please note that she is one of the investigators for whom we just changed the email address from @u.washington.edu to @uw.edu. We hope this isn't the cause, but figured we better tell you.

Also, less critical: Investigator login for Clare Ryan is showing an incorrect project under "Funded Projects":  R/COCC-3. We are not seeing this when logged in as R/Cs/Admins.

**Comment by ecsion** [comment]
There was some issues in data migration which has been fixed.
