### ISSUE TITLE
User complaints in reporting

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#121]
These are verbatim comments from user entering her reporting:

- There doesn’t seem to be a link to see prior narrative reports.
- Under "Student support" Shows dissertation title and date of receipt of degree when in “edit” but it disappears in the summary of the report (just before pressing “submit”)
- Under "Publications"  There is no option for journal articles or book chapters
- Uploaded a presentation given at SfAA, but it does not show up in the review
- Under "Impacts/accomplishments"  It would be useful to be able to see the questions that guide the responses to relevancy, etc. while answering.  They only seem visible once you’ve filled them out and are reviewing, but then if you edit, they disappear again.
- The submission is taking forever to load.  I want to go home, but now I’m scared that all will be lost!!!!  Never mind, I think it worked. You have to click on the box that says report submitted even though there are still dots streaming by that make it look like it is still in progress!

**Comment by mgduke** [comment]
Kathy, I had to add journal articles and quite a few other pub cat types to the publications pick list. I think that was Ecsion's intent.

And yes, I concur on misleading progress indicators: Many times I get either a spinning blue ball with an arrow or the streaming dots that never stop until I click somewhere.

**Comment by ecsion** [comment]
done
