### ISSUE TITLE
Linking to the Instructions PDF

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#123]
In MIT's custom form "Economic Benefits; Patents"  can you please insert a link to the Instructions PDF from the mention highlighted below?  I tried but couldn't figure it out.

....... Economic impacts should not include employment or expenditures funded directly from the Sea Grant award (including match).  Please see the **_Instructions PDF_**  for details and examples. Other impacts on the community should be described .....

**Comment by ecsion** [comment]
Not easy to do. This requires more discussion.

**Comment by kdez** [comment]
Deepak and I decided that the smart workaround is to just have a link to the Instructions PDF on every page, built-in as it were. Forget about linking from the instructions field.

**Comment by mcbridec** [comment]
Sounds like a good idea.

**Comment by ecsion** [comment]
done.
