### ISSUE TITLE
Submission time on PI reports

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#127]
http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=262&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

![capture](https://cloud.githubusercontent.com/assets/17168500/13968157/5713745c-f038-11e5-85d0-f9ef10ee671e.JPG)

The submitted on time is incorrect. Is it in Eastern time? If so, Oregon Sea Grant would like Pacific time.

**Comment by ecsion** [comment]
fixed, please check
