### ISSUE TITLE
IMPORTANT - Custom Forms not saving

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#128]
http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=Edit&record=221&showList=
![capture](https://cloud.githubusercontent.com/assets/17168500/13969969/20d18d4c-f043-11e5-8495-bce1b59360de.JPG)

The input type, question label, and sequence fields are not saving in custom forms. This means that when the we send a report call to a PI, the form does not display properly.

![capture2](https://cloud.githubusercontent.com/assets/17168500/13970020/6dee982c-f043-11e5-97a8-60d51b739996.JPG)

**Comment by ecsion** [comment]
Can you double check because we do see the information saved.

**Comment by mcbridec** [comment]
It looks like whatever was going on has been remedied. Thank you
