### ISSUE TITLE
Deadlines: Replace Datepicker JS with Datetimepicker?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#130]
Deepak, we discovered that the datepicker calendar we use to set open and closing dates for reporting (and presumably for proposal calls) default to 12a.m. GMT of the selected date. 

This isn't very intuitive (e.g., an investigator tried to submit last night at 9pm and couldn't because of the GMT offset and the default to 12am) and, while we resolved the resulting issue by pushing back the deadline date, it would be most helpful to allow us to set the hours and minutes as well. 

Further, can you change from GMT to PDT (currently -7 GMT) or otherwise code for this dynamically?

**Comment by mcbridec** [comment]
Oregon would like this too. Thank you!

**Comment by mgduke** [comment]
Speaking of datepicker, Kate reports the following intermittent annoyance:

Seems like calendars are not going away once you enter the date.  That is, you actually have to click somewhere else on the screen for them to go away.  I noticed this specifically in the “Leveraged funds” custom form.
