### ISSUE TITLE
URGENT: File upload issue—limited to 8Mb??

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#131]
Deepak, we have urgent need to resolve the issue wherein PDF file uploads seemingly >8 Mb are getting “Invalid request” error messages. PDF files <8 Mb seem to be ok, although we’re not necessarily sure what the exact limit is. Note the label says file upload limit is 100 Mb, but I had already asked you to drop this to, I think, 30 Mb. Not sure how we wound up with ~8 Mb.

**Comment by ecsion** [comment]
fixed.
