### ISSUE TITLE
Form Locked Forever, it seems?

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#132]
Yikes! I locked a custom form and now I can't unlock it or change it. I can't edit or even retire it!
When I previewed it, I saw a necessary change. It looks locked forever.
What do I do now?

Custom Forms > Form Details
Form Title : NEW Extramural Funding in Addition to Matching Funds

Please unlock.
Thanks!

**Comment by mgduke** [comment]
I think I recall Deepak saying you have to ask them to unlock the form, which isn't all that practical, and I think some alternative was being proposed. The issue _may_ have been over what happens to data added prior to unlocking the form and changing/deleting fields. (Or not … ; > ) )

**Comment by mcbridec** [comment]
Yeah. I shouldn't have clicked that checkbox. We heard what curiosity did to the cat...
Time will tell, but I don't think we need to lock any forms permanently.

**Comment by ecsion** [comment]
temp fixed. we will remove lock option for sgadmin (we can still lock, but you have to call us)
