### ISSUE TITLE
Change Request: Navigating page to page in reporting as PI

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#133]
Please change the arrows for paging through the report to  <- BACK  and   NEXT->

Get rid of specifics like "Leveraged Funds ->" and please make sure it appears on every page - it is missing from the Metrics Questions page, which is confusing.

**Comment by ecsion** [comment]
Done. We called the Back button Prev , however, we will change this to Back on Monday.
