### ISSUE TITLE
Instruction PDF download in a report call

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#134]
Can we rename the PDF EXPORT button on the Instructions screen of the reporting call? Suggestions: DOWNLOAD INSTRUCTIONS  or
PDF of INSTRUCTIONS

It's not clear to the user what he or she is exporting when it simply says PDF EXPORT.

![image](https://cloud.githubusercontent.com/assets/17415806/14026663/4abbb898-f1ca-11e5-9a00-f3141ff44fdf.png)

**Comment by ecsion** [comment]
done.
