### ISSUE TITLE
Students Supported standard form

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#135]
I think "New or Continuing?" and "Degree awarded this period?" should be required fields since we need that information in order to enter student metrics into PIER.

Also, can we either include the text "if supported by this project" to the Thesis/Dissertation description, or add a field below it: Was the thesis/dissertation supported by this project?" with Yes/No radio buttons. We need to know this because we can't claim the thesis/dissertation if it wasn't supported by SG.

![image](https://cloud.githubusercontent.com/assets/17415806/14028984/d9eaedf8-f1d5-11e5-97fc-29779ef20ba4.png)

**Comment by kdez** [comment]
I support this change request(s)

**Comment by ecsion** [comment]
done.
