### ISSUE TITLE
Removing metrics

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#136]
Thank you for adding the functionality to delete metrics. I am trying to delete the ones I added erroneously and the system won't let me delete some (I get the message "This question is used") even after deleting all test report calls I created. Can you please unflag all N.H. Sea Grant's metrics for now so I can delete those that we don't need?

**Comment by ecsion** [comment]
Could you please provide the name of Metrics you want to delete that are not deleting.

**Comment by schalifoux** [comment]
SG Supported PhD Students - Continuing from last period		 	
SG Supported PhD Students - New this period		 	
SG Supported MS/MA Graduate Students - Degrees awarded this period		 	
SG Supported MS/MA Graduate Students - Continuing from last period		 	
SG Supported MSA/MA Graduate Students - New this period	 	
SG Supported Undergraduate Students - Degrees awarded this period

**Comment by ecsion** [comment]
done.
