### ISSUE TITLE
WSG Custom Forms: Unwanted validation

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#137]
Seems like the Economic Impacts custom form is requiring entries for non-required fields (i.e., requires a number in all fields you are not reporting, instead of just being able to leave blank…). An example can be found at:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=15965&mode=showMultiQuestionStem&QuestionId=15959&tab_label=Economic%20Impacts&tab_label=Economic%20Impacts

I checked the custom Economics Impact form, and none of the "Mandatory" checkboxes for numeric fields are checked.

**Comment by ecsion** [comment]
fixed.
