### ISSUE TITLE
Variables in e-mail messages

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#138]
How do we add values to fields like SGProgramName, EmailSignature and BaseURL? When I publish a report call and generate an e-mail, all of those fields are blank in the email.

Also, I tried to add the field for project title to the e-mail by selecting it from the Select Field Type picklist, but instead of filling in the value of the field in the e-mail, the e-mail included the text "$projects-project_title$" How do we add a variable to an-mail?

![image](https://cloud.githubusercontent.com/assets/17415806/14048573/7ab50b2e-f285-11e5-9652-0b7aeb13079f.png)

![image](https://cloud.githubusercontent.com/assets/17415806/14048634/ef7336f2-f285-11e5-95a6-1235393aaea5.png)

**Comment by ecsion** [comment]
fixed,
