### ISSUE TITLE
Custom form unchecked but PI still seeing it

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#140]
After testing by logging in as a PI on a project, we found that the PI is seeing the Custom Form called Administrative Use on their report, even though we unchecked the radio button for PI view of this form.  
![2016-03-25_1503](https://cloud.githubusercontent.com/assets/17169131/14054946/dad9424e-f29a-11e5-8538-cbb6f6094c3f.png)

**Comment by ecsion** [comment]
We logged in as Mary and we did not see Administrative Use Only form. See screenshot attached.
<img width="1175" alt="screen shot 2016-03-28 at 8 03 15 am" src="https://cloud.githubusercontent.com/assets/1612666/14077646/be68e862-f4bb-11e5-95ec-167867654a2f.png">
Please double-check and re-open this issue if there is still a problem.
