### ISSUE TITLE
PI Reports coming out with duplicate records

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#142]
The PI submitted, and duplicate records were on the report. Screen shot is of the reporting call, but the actual report has the same issue. Only two duplicated records were found - Patents... and Prizes....
![2016-03-25_1549](https://cloud.githubusercontent.com/assets/17169131/14055731/778a11a8-f2a1-11e5-85db-6a3d9771ddba.png)

**Comment by ecsion** [comment]
The issue was that each time save button was clicked a new record was being added. The button should have been called add (& not save) . This has been changed.
