### ISSUE TITLE
Change wording: Instructions PDF download butttons

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#143]
On the PI's "Instructions" page, in reporting:

Change the labels on the two download buttons:
>>Change first "DOWNLOAD INSTRUCTIONS" to "PDF THIS PAGE"
>>Change second "DOWNLOAD INSTRUCTIONS" to "REPORTING GUIDELINES PDF"

![image](https://cloud.githubusercontent.com/assets/17729848/14084286/00d576f8-f4e8-11e5-8a5d-f7b52991b676.png)

**Comment by ecsion** [comment]
done,
