### ISSUE TITLE
Bug?  Delete the link, not the project!

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#144]
In report call building, where you link projects to the call -- to de-link a project from that call, uou click on the little trashcan icon in the "Remove" column and you get this popup warning:

"Are you sure to delete published project and report associated with it?"

We certainly DO NOT want to delete the projectjust unlink it  - can you make the popup say:
"Are you sure you want to de-link the project from this call? Report data for this call will be deleted."

**Comment by mcbridec** [comment]
Yikes! Good catch!

**Comment by ecsion** [comment]
done.
