### ISSUE TITLE
Project record needs to be re-uploaded - MIT

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#145]
Casdcade Sorte's Blue Mussels project has the wrong data in Ecsion eSG; needs a refresh upload from MIT's FMP db:

![image](https://cloud.githubusercontent.com/assets/17729848/14088157/e70e79ea-f4fb-11e5-9409-34feab082731.png)

**Comment by ecsion** [comment]
done.
