### ISSUE TITLE
"PUBLISH" is not a helpful concept

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#147]
In Report Call:    "Publish" sends out an auto-email that is not informative or helpful. 

First the label for this action should be "Send PI Email" or "Announce Call"  -- not "Publish" which doesn't mean anything to us.

Second the email does not say anything useful - it should give them access and login instructions as well as some instructions about the call.

It would be simpler to use the Publish function just to "Open the Call - to make it "live" and accessible to the PIs without any email being triggered. Then the RCs can send their own custom-tailored emails out to the PIs, either through the system or individually. Login/Access auto-emails can be sent separately.

**Comment by mcbridec** [comment]
Doesn't the publish button for a reporting call send an email to the PIs to tell them they have a new task awaiting them? I like that this is automatic, but the email is a little off. We sent in a ticket to request to change the To: and From:. See #82 and 63. Maybe it needs more work than that.
I like the option to just open the call and let us choose a template or do a new email to send to PIs when we are ready. But I also like the ease of pushing the button and having the system do it too. 
As for the word "publish", it seems okay to me.
Anyone else want to weigh in here?

**Comment by kdez** [comment]
Oh okay,I guess it's a training issue FOR ME.  But I will write a text to go out to the PIs that actually makes senses.
