### ISSUE TITLE
Reports record order changes with sorting

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#15]
Order of records changed w/ea sort by PI. **Pending but not critical for upcoming reporting**. 

**Explanation**: There was no index by which the database could return the sort in a consistent order. Currently, sorts return consistently, but not in temporal order (i.e., 2012, 2014, 2013). Lower priority to fix w/additional sort criteria.

**Comment by ecsion** [comment]
fixed.
