### ISSUE TITLE
As an investigator I see a project that I don't think I should see...

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#150]
![screen shot 2016-03-29 at 2 09 59 pm](https://cloud.githubusercontent.com/assets/18152637/14124324/bfdd72d6-f5b9-11e5-9caa-ce8bed921bd9.png)

The R/BHT-21 Wheatcroft project should not be in my project list, or at least I don't know why it's showing up here (screenshot above). Let me know if you need more info.
Sarah Kolesar
sarah.kolesar@Oregonstate.edu

**Comment by ecsion** [comment]
Fixed,
