### ISSUE TITLE
Text for the auto-email responses

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#151]
As requested by Deepak Seth--

A1. Welcome email to New User.  Also Welcome email resend to new user or existing user.

To: [user email address]
From: [SGAdmin email address]
Subject: Welcome to eSeaGrant

Dear [user Name]

You have been given access to the online [Name of Sea Grant program] proposal and reporting system. Please access your account with this information:

Go to  [http://eseagrant.xxx.edu]

Your login is:
Email Address: [user email address]
Password: [user password]

Let me know if you have any problems or questions.

Best regards,
[SGAdmin fname lname]
[SGAdmin phone number].

A2. User Password is reset

To: [user email address]
From: [SGAdmin email address]
Subject: Password reset: eSeaGrant

Dear [user Name]

Your password to the [Name of Sea Grant program] online proposal and reporting system has been reset. Please use the information below to login at http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

A3. User password is set by SGAdmin. 

To: [user email address]
From: [SGAdmin email address]
Subject: Password to eSeaGrant

Dear [user Name]

Your password to the [Name of Sea Grant program] online proposal and reporting system has been set by the Sea Grant Research Coordinator, [SGAdmin fname lname]. Please use the information below to login at http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

A4. User Role is changed

To: [user email address]
From: [SGAdmin email address]
Subject: Your Role in eSeaGrant has been changed

Dear [user Name]

Your role and access level to the [Name of Sea Grant program] online proposal and reporting system has been changed by the Sea Grant Research Coordinator, [SGAdmin fname lname]. You can login in your new capacity at http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

A5. Confirmation email for #1, #2, #3 to SGAdmin (same email as sent to the User but no password included to SGAdmin)

A6. Report Submission Confirmation

To: [PI email address]
From: [SGAdmin email address]
Subject: Project Report Submitted

Dear [PI Name]

You have successfully submitted your report for your [Name of Sea Grant program] project titled “[Project Title],” [Project Number], for the period [Reporting Start Date] through [Reporting End Date].

You can continue to login and make changes to your report any time before the deadline on [Deadline date], by logging in at:

 http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

Best regards,
[SGAdmin fname lname]
[SGAdmin phone number].

A7. Document Request from third parties

To: [email address as given by PI]
From: [SGAdmin email address]
Subject: [Name of Sea Grant program] Proposal Document Request

Dear [Name]

[PI Name] has submitted your name in relation to the [RFP Call Title].

Please help by logging in to our online system and following the instructions given there. We will need your input by [Deadline date]. 

 http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

Let me know if you have questions.

Best regards,
[SGAdmin fname lname]
[SGAdmin phone number].

A8. Proposal Submission Confirmation to PI

To: [PI email address]
From: [SGAdmin email address]
Subject: [Name of Sea Grant program] RFP - Proposal Submitted

Dear [PI Name]

You have successfully submitted your proposal, [Project Title],” to [Name of Sea Grant program] in response to the [RFP Call Title] call.

You can continue to login and make changes to your proposal at any time up to the submission deadline on [RFP Deadline date]. You will receive a confirmation email each time you submit your proposal.

 http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

Best regards,
[SGAdmin fname lname]
[SGAdmin phone number].

A9. Rebuttal Submission Confirmation to PI (the invitation to rebut should be custom)

To: [PI email address]
From: [SGAdmin email address]
Bcc: [SGAdmin email address]
Subject: MIT Sea Grant - Review Rebuttals Submitted

Dear [PI Name]

You have successfully submitted review rebuttals for your [Name of Sea Grant program] Full Proposal. You may log-in and edit your rebuttals at any time up to the deadline.

To edit your rebuttal, go to:

https://[eseagrant.xxx.eduURL here]

Your login is:
Email Address: [PI email address]
Password: [password]

Also needed:  automatic submission confirmation to all reviewers, peer and panel.

To: [Reviewer email address]
From: [SGAdmin email address]
Subject:  [Name of Sea Grant program] Review Received

Dear [Reviewer Name]

You have successfully submitted your proposal review(s) to [Name of Sea Grant program] in response to the [RFP Call Title] call.

You can continue to login and make changes to your review(s) at any time up to the deadline. You will receive a confirmation email each time you re-submit.

 http://eseagrant.xxx.edu]

Email Address: [user email address]
Password: [user password]

Your contribution to our research program is much appreciated. Let me know if you have any questions.

Best regards,
[SGAdmin fname lname]
[SGAdmin phone number].

**Comment by ecsion** [comment]
done. Although we are enhancing it so we will allow you to add Set Password Link using merge tag. This will be available on Monday.
