### ISSUE TITLE
WSG: Student supported deleted from report, but still showing up in overall reports ("Students supported" list)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#152]
For example, in the 2014 annual report - staff reporting call:

Michael Barsamian was originally entered in report for A-Kahn; then deleted; then was entered in A-Sullivan.

If you go into A-Kahn report - he does not show up:

http://esg.wsg.washington.edu/index.php?module=Reporting&relatedModule=StudentsSupported&view=Detail&record=18620&mode=showRelatedList&tab_label=Students%20Supported

But, if you go into all reports - students supported list - Barsamian does show up for A-Kahn:
http://esg.wsg.washington.edu/index.php?module=StudentsSupported&view=List&showList=true&tab_label=Students%20Supported

**Note**: Barsamian also shows up for A-Sullivan in this list, which is correct.

**Comment by ecsion** [comment]
We found the issue and it has been fixed.
