### ISSUE TITLE
User complaint about icon visibility

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#154]
User complained that she had to scroll right to see the “Edit” “icons – I was not able to replicate this problem.  However, I found that the icons do not show up unless the cursor is on that line somewhere. Please make it so the View/Edit/Trash icons are always visible.
 
![image](https://cloud.githubusercontent.com/assets/17729848/14186636/496865b2-f74d-11e5-979a-85bb565ac8e4.png)

**Comment by ecsion** [comment]
Done.
