### ISSUE TITLE
User requests link to project information from each reporting page

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#155]
MIT SG user Julie Simpson has this request:
"Also my first comment on usability of eSG - when I go in to do reporting under Tasks > Current Tasks, I can click on all my projects but I have no idea which one is which because there's no title or description of the project, and no way to see what I proposed. I can leave the reporting section and click through to Projects > Project Information, read what I need, then click back through Reports (in menu on left), then a couple more clicks to get to the reporting page, but it's a bit clumsy.
So would it be possible to put the titles of the proposals on the Current Tasks page, and a direct link there to the proposal narrative, or at least the summary of methods, objectives etc.?"

**Comment by ecsion** [comment]
done.
