### ISSUE TITLE
 Custom form unchecked but PI still seeing it (similar to #140)

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#156]
Oregon Sea Grant's custom form called "Administrative Use Only" is unchecked so the PI cannot see it.
However, the PI does see it. We need this hidden from PI view.
See clips for the name of the call and project is "TEST-mcbride1".

![2016-04-01_1048](https://cloud.githubusercontent.com/assets/17169131/14215389/7173c4de-f7f7-11e5-8f89-556bd9791857.png)
![2016-04-01_1052](https://cloud.githubusercontent.com/assets/17169131/14215460/00cc2d6a-f7f8-11e5-877e-42650c1cc367.png)

**Comment by ecsion** [comment]
fixed.
