### ISSUE TITLE
Two change requests for "Linking Projects to Report Call View"

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#157]
1. Please add the project title to this view (Limit it to the first x characters, if that helps with layout)
   PROJECT NUMBER  PI NAME END DATE W. EXT.
2. I need a warning, when paging through selecting the projects to link, that if I move on to the next page I will lose all the marks I made on the previous page. I thought I was collecting one long list of projects to link, but then when you move to the next page all your work id'ing projects to link disappears.

**Comment by ecsion** [comment]
Added a alert: You have selected items that will not be carried over to next page, please consider linking these items before continuing."
