### ISSUE TITLE
Revision date on metric questions not updating

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#158]
The revision date does not update when an existing metric is edited. The revision date seems to remain as the creation date even when a metric is modified and saved.

![image](https://cloud.githubusercontent.com/assets/17415806/14260886/c9a60eba-fa7b-11e5-89e7-fa4f11527a16.png)

**Comment by ecsion** [comment]
This is as designed. Initially the revision label is automatically tagged with the for  creation date. Once the initial date is tagged, the revision label only changes when you change it. The intent is that you can change this label, for example v-PIER-2016 or something more meaningful to you.
