### ISSUE TITLE
Add button should be save

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#159]
As a PI filling out a report, a custom form says "Add" at the bottom of the page when it should say "Save," and sometimes it should have both options of "add" (when there are multiple responses) and Save should be available all the time. 

http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=646&mode=showMultiQuestionStem&QuestionId=227&tab_label=OUTREACH%20AND%20PRESENTATIONS&tab_label=OUTREACH%20AND%20PRESENTATIONS
![capture](https://cloud.githubusercontent.com/assets/17168500/14266110/c333d1f8-fa7a-11e5-9acb-de4316ff0432.JPG)

**Comment by ecsion** [comment]
Now custom forms have a different UX and so this bug is not relevant.
