### ISSUE TITLE
Reequesting change of text in auto-reply emails

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#162]
In auto emails, change eSeaGrant to Sea Grant when referring to the orgnaization. eSeaGrant only refers to the online software system, not the granting program itself.

Dear Andrew Kemp,

You have successfully submitted your report for your **_Sea Grant_** project titled "Late Holocene reconstructions and historical measurements of relative sea level in Boston",
2015-R/RC-142-PD, for the period 2015-02-01 through 2016-01-31.

You can continue to login and make changes to your report any time before deadline on 2016-04-22, by logging in at:

http://eseagrant.mit.edu/

Your login is: Email Address: Andrew.Kemp@tufts.edu

Best regards,
Katharine de Zengotita

**Comment by ecsion** [comment]
ll email templates are now editable by sgadmin
