### ISSUE TITLE
User complaint about navigating "Patners" entry after editing. (Project Reporting)

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#163]
A PI doing reporting states:   "I noticed while entering my partners, if I had to edit one of the entries I could not go back to the Add screen.  I would have to get all the way out and start from the main page for my report (A5), scroll down the left column menu and get back into the partner add page."

I hope his comment makes sense; let me know if it does not.

**Comment by ecsion** [comment]
fixed.
