### ISSUE TITLE
Possible Issue:  indicating to the PI that he can save, logout, and come back again later

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#164]
If you can think of a way to make this clear to the user, it would be great - we had this same complaint a lot with the original eSG also.

"I’ve been working on reporting all day, but I will have to finish it later this week.  How do I sign off from eSeaGrant without losing everything?  I don’t see a 'save and continue later' option."

**Comment by ecsion** [comment]
done.
