### ISSUE TITLE
WSG: Student supported module oddities

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#166]
1. In Students Supported, there appears to be a new field with a label that we don't recognize:

LBL_THESIS_DISSERTATION_SUPPORTED_BY_PROJECT: 

Where did this come from and, if we're keeping it, can it be named something more user friendly, and can it not be required?

http://esg.wsg.washington.edu/index.php?module=StudentsSupported&view=Edit&record=18345

<img width="1275" alt="screen shot 2016-04-05 at 2 41 41 pm" src="https://cloud.githubusercontent.com/assets/17168836/14299120/82712e4a-fb3d-11e5-9490-4afd9b76887a.png">

2. It appears an investigator was able to fill out the Student Supported form without indicating "New" or "continuing" for the "New or Continuing?" field, even though that field is marked as "required." However, when we checked this page, and without changing anything, tried to save, then we DID get the red balloon stating "* This field is required." ?!?

3. In the Submission Preview, "Degree awarded this reporting period" appears twice, with each having a different answer. See link and also 2nd screenshot.

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=18337&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

<img width="760" alt="screen shot 2016-04-05 at 2 40 50 pm" src="https://cloud.githubusercontent.com/assets/17168836/14299052/2a1107de-fb3d-11e5-9a09-102cfa8b5183.png">

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
One clarification: we don't want the field, "Was this thesis/dissertation supported by Sea Grant?," to be required. I'm not sure it actually is, but the red asterisk suggests it is, so please remove the asterisk and, if necessary, remove the validation for that field.
