### ISSUE TITLE
Metrics report result data not exporting

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#167]
Although there are metrics entered in the report, the export is blank.

![image](https://cloud.githubusercontent.com/assets/17415806/14326099/66e4dcd6-fbfa-11e5-95b0-9efa6180c452.png)

![image](https://cloud.githubusercontent.com/assets/17415806/14326109/79a4450a-fbfa-11e5-9ea7-50c64da37077.png)

http://eseagrant.unh.edu/index.php?module=MetricsSummaries&view=List&showList=true&tab_label=Metrics%20Report

**Comment by mcbridec** [comment]
The same thing is happening to us - Oregon Sea Grant.

**Comment by ecsion** [comment]
fixed.
