### ISSUE TITLE
When exporting reporting results, only the first entry for each Custom Form exports

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#168]
Two entries in each form, for example:

![image](https://cloud.githubusercontent.com/assets/17415806/14326204/f7deda66-fbfa-11e5-98fb-d65eee08177b.png)

But export only lists first entry (same behavior for all three of the custom forms in this report call):

![image](https://cloud.githubusercontent.com/assets/17415806/14326246/2e9810cc-fbfb-11e5-83de-24b192de4a39.png)

http://eseagrant.unh.edu/index.php?module=MultipartAnswers&view=List&showList=true&tab_label=Custom%20Form%20Responses

**Comment by mcbridec** [comment]
See if the exported file has tabs at the bottom, one for each question.

**Comment by ecsion** [comment]
fixed.
