### ISSUE TITLE
When exporting reporting results, publication data is incomplete

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#169]
An export of publication data (using the standard module) does not include the data contained in each record (e.g., type, citation,...).

Example of a record:

![image](https://cloud.githubusercontent.com/assets/17415806/14326610/c5c1af2a-fbfc-11e5-89a5-8cbe823900a8.png)

Export:

![image](https://cloud.githubusercontent.com/assets/17415806/14326625/dff5fc52-fbfc-11e5-9cc4-737d4752cdfc.png)

http://eseagrant.unh.edu/index.php?module=Publication&view=List

**Comment by mcbridec** [comment]
Hi- I simply create a custom view and used that to create the report with the elements I want to see.

**Comment by ecsion** [comment]
Please create a custom view and include the columns that you need and then export. This will export all columns of the custom view.
