### ISSUE TITLE
When exporting reporting results, student supported data is incomplete

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#170]
When exporting Student Supported data (using the standard module), the data in the record (e.g., email, institution, degree type) is not included.

Example of a record:

![image](https://cloud.githubusercontent.com/assets/17415806/14326921/0f45054c-fbfe-11e5-8938-2e29cbb40f83.png)

Exports like this:

![image](https://cloud.githubusercontent.com/assets/17415806/14326938/217b3cf4-fbfe-11e5-9def-3b847779f1a2.png)

http://eseagrant.unh.edu/index.php?module=StudentsSupported&view=List&showList=true&tab_label=Students%20Supported

**Comment by mcbridec** [comment]
This is another one of those report things where you have to make a custom view report and "export all".

**Comment by ecsion** [comment]
Please create custom view for fields that are needed. If you run into an issue then please reopen  or add another bug.
