### ISSUE TITLE
Partner entry not working quite right

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#171]
When entering Partners this Period, the picklist isn't displaying or selecting correctly. 

#1 The list is not in alpha order so it's difficult for the user to determine if the entry is in the list:

![image](https://cloud.githubusercontent.com/assets/17415806/14327273/95b8fccc-fbff-11e5-8cf9-c9dc2a9536e7.png)

#2 When the user enters text in the "Partner Name" field, a white box containing matching text pops up on top of the yellow list of partners. You cannot select from the "white box" - it doesn't fill in scale or type and the user has to manually click the X to close the pop-up - but you also can't find the entry in the "yellow list" that you need to select from in order to properly populate scale and type. I can't capture this in a screenshot because the "white box" goes away when you click anywhere else on screen, but it should be easy to re-create. It's the "white box" popping up on top of the "yellow list" that is problemmatic. I'm using Chrome if that matters.

http://eseagrant.unh.edu/index.php?module=PartnerReport&view=Edit&sourceModule=Reporting&sourceRecord=283&relationOperation=true

**Comment by ecsion** [comment]
We have now alphabetized the partner list. Also if you type more characters, it should automatically filter the name that may help you choose the right partner. The White box was a browser feature that we have now disabled.
