### ISSUE TITLE
Closed bug #135 needs to be re-opened

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#172]
This issue wasn't fixed quite right, partly because I provided the wrong text.

In Students Supported this was added:

"Was this thesis/dissertation supported by this project?"

It should be "Was this thesis/dissertation supported by Sea Grant?" and have Yes/No radio buttons rather than a checkbox. This field doesn't have to be required.

The fields that were to be made required are "New or Continuing?" and "Degree awarded this period?"

**Comment by mcbridec** [comment]
Oregon Sea Grant agrees and would like the same thing changed. Thanks!

**Comment by ecsion** [comment]
Text has been updated to""Was this thesis/dissertation supported by Sea Grant?". 

Since this is a fixed module and cannot be changed easily, we recommend that you use custom form which allow to have  fields of your choice.
