### ISSUE TITLE
Report Guidelines button not working

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#175]
As an RC, while in Sarahs Special Report Call:
Reports> Report Information> Report Guidelines  **PDF button is not working, no PDF results**
While using Mozilla Firefox.
-Cathy
Oregon Sea Grant

**Comment by ecsion** [comment]
If no PDF guideline is uploaded by the RC, the clock of this button will show an alert. "PDF Guidelines not found"
