### ISSUE TITLE
Display picklist items in custom forms as they were entered rather than all UPPERCASE.

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#177]
Can the picklist items in custom forms maintain the case (e.g., mixed case, lowercase) they were entered in when displayed to the user? Currently they are displaying in uppercase:

![image](https://cloud.githubusercontent.com/assets/17415806/14395999/2634a978-fda3-11e5-9a58-74566740d357.png)

These were entered in mixed case and would be much easier to read if displayed this way:

![image](https://cloud.githubusercontent.com/assets/17415806/14395838/381a3b40-fda2-11e5-91db-374dac5980ef.png)

**Comment by ecsion** [comment]
done.
