### ISSUE TITLE
Pick List Editor -- Projects --> Primary Award

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#178]
In the Pick List editor, working in Projects and then Primary Award numbers, I am trying to delete all of them so that I can then input the 2 award numbers needed for the Rhode Island Sea Grant program. While instructions note multiple award numbers can be selected by holding the Control key, this does not work, at least from a Mac OS / iMac platform. Also, I was able to delete many award numbers, but now it no longer is deleting them, or is saying it deletes but the list never gets any shorter. I have used the 1 award number I input --- NA14OAR4170082 as the "replace with" value, but to no avail.

**Comment by ecsion** [comment]
Fixed.
