### ISSUE TITLE
Variables in e-mail messages not translating

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#179]
I tried to use a system e-mail template (SysTemplate15) with login information added to generate an e-mail to announce a reporting call. Most of the variables remained variables in the received e-mail. The only variable that translated was the project name:

![image](https://cloud.githubusercontent.com/assets/17415806/14440666/f6bef6e0-fffe-11e5-82fc-495d77521c63.png)

**Comment by ecsion** [comment]
Email templates are a bit complicated to use in the current system and we are finding out that the email templates is confusing many users. We plan to simplify the email templates in 2.0. In the meantime, Ecsion will take responsibility for creating email templates for you. Please submit a request in Github and mark it email template change and Ecsion will get it done for you.
