### ISSUE TITLE
People Report label touchup needed

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#180]
When I create a report, I see these labels need an associated "nice" name: LBL_SMOWNERID, LBL_USER_ID, LBL_USER_NAME, LBL_CREATEDTIME, LBL_GUID.
I can re-label each column per report, but fixing would be good.
Example below.
![2016-04-12_1358](https://cloud.githubusercontent.com/assets/17169131/14475571/820704e6-00b7-11e6-9a09-62ea4ecdbcef.png)

**Comment by ecsion** [comment]
fixed.
