### ISSUE TITLE
PickList Secondary Award won't add new

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#181]
I want to delete all existing values in Picklist --- Projects --- Secondary Award and add award numbers unique to RI Sea Grant. Values are not added using the Add Value button.  Multiple values are not selected using the Control Key. Values are not deleted from the list using the Delete Value Key.

**Comment by ecsion** [comment]
please try again. We have made some fixed. If still an issue, please add new bug.
