### ISSUE TITLE
Custom form enabled, not shown to PI, but showing up as not submitted

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#184]
We enabled the Administrative Use Only form, but did not show it to the PI. When the PI goes to submit their report, they see this form as not completed. They should NOT see it as not completed because we did not give them the option to complete it.

![screen shot 2016-04-14 at 12 17 39 pm](https://cloud.githubusercontent.com/assets/17168500/14540762/96159184-023b-11e6-834b-c74d1a40e549.png)

**Comment by ecsion** [comment]
fixed.
