### ISSUE TITLE
Custom form completed, but showing up as not complete

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#185]
The PI marked the "SUPPLEMENTAL DOCUMENTS" custom form as complete as indicated by the green dot in the picture, but it was showing up as not submitted.
![screen shot 2016-04-14 at 12 17 39 pm 2](https://cloud.githubusercontent.com/assets/17168500/14540878/2bc8e42e-023c-11e6-80b2-e0374c628b32.png)

**Comment by ecsion** [comment]
fixed.
