### ISSUE TITLE
Lost Side Bar

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#186]
The PI got stuck at the below page with no clear way to return or choose another form ,etc. Her only choice was Edit, but that brought her back to the below. Previous pages had the side bar.

![screen shot 2016-04-14 at 12 23 43 pm](https://cloud.githubusercontent.com/assets/17169131/14571129/779d51f8-02fc-11e6-8ed7-dee1ff718908.png)

**Comment by ecsion** [comment]
fixed.
