### ISSUE TITLE
Email template change

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#188]
Could I please get a template created to send to PIs when I have created a report call? Thanks!

I would send the email from here, so this would be the "center where used" : http://eseagrant.unh.edu/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=440&mode=showRelatedList&tab_label=Select%20Projects 

Here is the template info:

Description: Tell PI report is needed

Subject: [program name] project -- report needed by [due date]

Dear [PI Name]

Reporting on your Sea Grant project titled “[Project Title],” [Project Number], is due by [Deadline date]. For this report, we ask that you provide information for the period [Reporting Start Date] through [Reporting End Date]. Detailed instructions are available online in the reporting system.

To enter your report, go to:

https://[eseagrant.xxx.eduURL here]

Your login is:
Email Address: [PI email address]
Password: [password]

This is a new system, so please let us know if there are technical difficulties, or if you have general questions about reporting requirements.

Best regards,
[RC fname lname]
[RC phone number]

**Comment by kdez** [comment]
How about if Ecsion makes it so the SG ADmin can create an email and then save it as a Template?
Because that would be great. It is also within scope, as the old eSG did that.

**Comment by ecsion** [comment]
done.
