### ISSUE TITLE
Data Migration: Request support for resolving duplicate record issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#19]
**Pending**: We unfortunately have duplicate accounts for some investigators (they registered multiple times, in many cases because a shorter UW eddress, @uw.edu, became available after the original domain names had been registered (@u.washington.edu).
While not ready to take specific action on this, if there is a MySQL query-based approach to this (merge records), we'd be interested in exploring this.

**Comment by ecsion** [comment]
old issue, closing. If this is still an issue, please reopen.
