### ISSUE TITLE
WSG: Meeting, Workshops, Conferences for old reports

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#191]
For migrated (historical) reports, the data mapping is incorrect for "Meetings, Workshops, Conferences - old". For reference, see:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=3794&mode=showMultiQuestionStem&QuestionId=7&tab_label=Meetings,%20Workshops,%20Conferences%20-%20old&tab_label=Meetings,%20Workshops,%20Conferences%20-%20old

In short, Project no. = report range, Type = Project #, Description = Type, No.of attendees = Description, event data = missing.

<img width="946" alt="screen shot 2016-04-20 at 9 34 11 am" src="https://cloud.githubusercontent.com/assets/17168836/14682586/22137d06-06db-11e6-8175-81f706a863bf.png">

**Comment by ecsion** [comment]
fixed.
