### ISSUE TITLE
WSG: Student supported module oddities—continued

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#192]
For migrated reports, the Students Supported field, "New of Continuing?" continues to not show a value when it should (i.e., still showing "Select an option"). See following link for example:

http://esg.wsg.washington.edu/index.php?module=StudentsSupported&view=Edit&record=15693&parent_id=3794&parent_module=Reporting&tab_label=Students%20Supported

**Comment by ecsion** [comment]
done.
