### ISSUE TITLE
WSG: Students Supported changes

### ISSUE THREAD

**Issue by ghost** [ecsion/eSeaGrant-Client-Bug-Tracker#193]
1. Please remove the red asterisk for "Was this thesis/dissertation supported by Sea Grant?" This field has no validation, btw, so no issue there.
2. Usability issue with aforementioned field and final field, "Financially supported?":
   Reporting parties have found the use of the checkbox confusing because the label is a question. Would it be easy enough to change these two fields to dropdown menus with "Select an Option," "Yes," and "No" being the values?

**Comment by ecsion** [comment]
Currently this is a fixed form. We will look into this.

**Comment by mgduke** [comment]
We don't have an issue with it being a fixed form, but why would that prevent you from effecting either change?
