### ISSUE TITLE
Exporting to Excel - add a field (PI's email)

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#195]
When doing an “Export” to Excel from the list of projects linked to a report call, such as http://eseagrant.mit.edu/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=14702&mode=showRelatedList&tab_label=Link%20Projects 

Please include the PI’s email address.

**Comment by ecsion** [comment]
done.
