### ISSUE TITLE
WSG: Minor typo in menu label—"Accomlishments"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#197]
The report navigation menu at left has a typo:  Accomlishments should be Accomplishments.

http://esg.wsg.washington.edu/index.php?module=Reporting&relatedModule=StudentsSupported&view=Detail&record=21208&mode=showRelatedList&tab_label=Students%20Supported

**Comment by ecsion** [comment]
This was a typo when you created the form. The solution was to simply go into the form editor and correct the typo. We have fixed it for you.

**Comment by mgduke** [comment]
Sorry, Deepak: I should’ve realized that. Thanks for fixing.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
