### ISSUE TITLE
WSG: List "nice to have" items

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#198]
1. Would be very helpful if PI column in Reports interface would be last name first, comma, first name. Much easier to find people that way.

2. This applies to the whole site: the record count that sits at the top right of any table of records doesn't list the total number of records until we click the two arcing arrows to the right of the count. Would be nice to not have to click to get the total record count.

Example page (for both requests):
http://esg.wsg.washington.edu/index.php?module=Reporting&parent=&page=2&view=List&viewname=111&orderby=pi_name&sortorder=ASC&search_params=%5B%5B%5B%22reporting_call%22%2C%22c%22%2C%222015%22%5D%5D%5D

**Comment by ecsion** [comment]
Point 1 has been combined with #229, so I am closing this. Point 2 is done.

**Comment by mgduke** [comment]
I see PIs are sorted by last name in the "Link Projects" view, but the URL noted above still indicates alphabetization is by first name for that page (Reports). Perhaps you just hadn't gotten to that one yet, but wanted to be sure you knew this still wasn't sorting correctly.
