### ISSUE TITLE
WSG: Oddity on central publications page

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#199]
Deepak, I'm pretty sure the long URL in the "Publications URLs" field at the following URL is causing the hyper-extension of the right margin starting with that field and affecting other fields below it. This is likely to happen with other records, so could you move that field further to the left to allow more room for these overly verbose URLs?

http://esg.wsg.washington.edu/index.php?module=Publication&view=Detail&record=22731
<img width="1709" alt="screen shot 2016-04-27 at 8 43 47 am" src="https://cloud.githubusercontent.com/assets/17168836/14858356/aae88ca6-0c54-11e6-9d0b-9292753b0e06.png">

**Comment by ecsion** [comment]
done.
