### ISSUE TITLE
Remove reporting "Instructions" and "Report Guidelines" everywhere under REPORTS tab

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#200]
Under the "REPORTS" tab:   Please remove all references to Instructions and Guidelines - these belong only under the "REPORT CALLS" tab.

For example, when you select REPORTS BY PROJECT in the Nav Pane, and then click on an individual project: delete the first page on that Individual Project view titled Instructions. --http://eseagrant.mit.edu/index.php?module=Reporting&view=Detail&record=16077&mode=showInstructions&tab_label=Instructions 

Also remove all instances of the button stating  REPORT GUIDELINES PDF

(Discussed with Deepak during phone conference 4/27)

**Comment by kdez** [comment]
Can you just please get rid of all references to Instructions and Guidelines Under the "REPORTS" tab?  This is the first thing you see when you click on a call under the REPORTS tab and it is totally meaningless and useless. Also - waiting since April for this to go away

**Comment by ecsion** [comment]
Kathy, We are not sure if we resolved issue for you or not. If it is still an issue, could you please provide screenshot and link. Otherwise would you close this.

**Comment by kdez** [comment]
Not there yet – On the main page under the “Reports” tab  you see a list of existing Report Calls – this is correct:

[cid:image003.jpg@01D2AA09.F06AE2D0]

When you click on one of those Report Call titles it brings up this “Instructions” Page:

[cid:image004.jpg@01D2AA09.F06AE2D0]

I don’t want to see this page -- I want to see “Report Call Info”:

[cid:image005.jpg@01D2AA09.F06AE2D0]

Please:

·        Add a PDF download link to this “Report Call Info” page to the ‘Instructions’ PDF for that call (prepared and uploaded by the Admin)

·        Move the “Instructions” link in the left nav pane to the bottom of the list – I don’t use this view at all, but some other programs may

Thanks, Kathy  (call me if this is not clear – 617-253-7042)

**Comment by kdez** [comment]
If the above instructions are not clear, let me know.  Not resolved at 12:15pm 3/31/2017

**Comment by ecsion** [comment]
Kathy, Thanks for the explanation. we are working on this. We will let you know once it is done.

**Comment by mcbridec** [comment]
I agree that we should move the "Instructions" down to the last item on the side bar. I like to see the instructions that the user followed, but not at the top. 
The pdf is also needed! Good ideas.

**Comment by ecsion** [comment]
Old issue. Closing, please reopen if this is still an issue.
