### ISSUE TITLE
In Reports: simplify layout of "Submission Preview"

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#201]
Under REPORTS tab -> REPORTS BY PROJECT -> Submission Preview

Simplify the METRICS & MEASURES section to a plain grid like so: 
![image](https://cloud.githubusercontent.com/assets/17729848/14890615/6a3c9520-0d31-11e6-9cad-1ea4eea1149f.png)

 Move the link to the “Narrative” to the end of the report

**Comment by ecsion** [comment]
done.
