### ISSUE TITLE
Change Reporting email template

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#202]
Delete the existing Reporting email ‘template’ – replace with:

Dear [User fname lname],

Annual Reporting for your MIT Sea Grant project, [title], Project Number [project number] is due on May 20, 2016. For this report, we ask that you provide metrics and other materials for the period Feb 1 2015 through Jan 31 2016. A narrative report is also required. 

You will receive a separate email with login information for our online system. Detailed instructions for reporting are on the website and in the attached document. 

Let me know if you have any questions. 

Kathy de Zengotita
617-253-7042.

The text should be editable and the edits should be kept when done.

**Comment by ecsion** [comment]
all email templates are now editable by the sea grant administrator.
