### ISSUE TITLE
Add "Embargo Date" field to Publications record 

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#203]
NEW FIELD on ADD PUBLICATION page in REPORTING http://eseagrant.mit.edu/index.php?module=Publication&view=Edit&sourceModule=Reporting&sourceRecord=12918&relationOperation=true   Have this appear at the very bottom, after the File Upload section

```
                Is there an embargo on publishing this before a certain date? If yes, enter date here:     
                [DATE FIELD]  
```

This field also needs to appear on the PUBLICATION DETAILS page, such as
http://eseagrant.mit.edu/index.php?module=Publication&view=Detail&record=15509
at the bottom, after the File Upload section

**Comment by ecsion** [comment]
Added.
