### ISSUE TITLE
WSG: Previous annual report PDFs different for R/C and Investigator 

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#204]
We don't know if this is consistent across investigators, but one (Hauser) reported that his downloaded PDFs of previous reports is missing the "Standard Questions" text entirely (the heading shows, but no ensuing text). 

However, Kate and I both downloaded and were able to see the text for this section. Ergo we wonder if the difference in user (PI vs admin) is effecting the dropout for the PI's standard questions.

Please see the following page:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17977&mode=showPreviousReports&tab_label=Previous%20Reports&tab_label=Previous%20Reports

**Comment by ecsion** [comment]
fixed, please check
