### ISSUE TITLE
Parent Project picklist should be Project Number, not Project Title

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#207]
ON the Project Information page when the RC goes into EDIT mode: the field "Parent Project" should offer a list of the Project Numbers, not the Project Titles 
 (There are at least 18 Projects titled “Sea Grant Program Management” and I cannot know which is the current one without the seeding the year in the Project Number.)

**Comment by mgduke** [comment]
Couldn't we have both title and number. BTW, I just looked at our interface and when I click the search icon for Parent Project, the popup does list project numbers (and no titles). Curious that it wouldn't then list the project number in the Project Info page by default.

**Comment by ecsion** [comment]
Done.
