### ISSUE TITLE
Data Transfer Error - crucial field in Publications records is empty

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#208]
In Publications the "Publication Number" appears to be missing in all pub records. This is the field called "Program ID" in old eSG db (there are 1782 pub records in old eSG, 1177 with pub numbers in program id field)

**Comment by mgduke** [comment]
Thanks for point this out. I've been meaning to report this for a while now.

**Comment by ecsion** [comment]
done, please check.

**Comment by kdez** [comment]
The person in “Staff” role is now able to download the report narratives in PM – so all’s well (that we know of!)

**Comment by kdez** [comment]
The pub numbers seem to all be there now…. thanks
