### ISSUE TITLE
Metric can't be saved

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Client-Bug-Tracker#213]
For some reason, PIs cannot save data to one of NHSG's metric questions (I tried a test and found the same behavior). Both the value and comment are wiped out when the user hits "Save." So far, this is the only metric we've had this problem with.

The metric: Number of seafood consumers per year that participate in community supported fisheries, farm-to-market venues and other seafood opportunities that are traceable back to the “boat.” (state PM)

http://eseagrant.unh.edu/index.php?module=MetricsAndMeasures&view=Edit&record=335

**Comment by mgduke** [comment]
Susan, I suspect this is happening for all eSG users. We reported this as well and I know Ecsion is working on it.

**Comment by ecsion** [comment]
fixed.
