### ISSUE TITLE
Calendar feature --> Alert "You have unsaved changes."

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#214]
When I am logged in as a PI, and answering a custom form on a report, when using the calendar function, I cannot move to a new month without an alert "You have unsaved changes on this page." It prevents me from selecting a future month, I have to type in the date.

http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=997&mode=showMultiQuestionStem&QuestionId=229&tab_label=NEW%20EXTRAMURAL%20FUNDING%20in%20ADDITION%20to%20MATCHING%20FUNDS&tab_label=NEW%20EXTRAMURAL%20FUNDING%20in%20ADDITION%20to%20MATCHING%20FUNDS
![capture](https://cloud.githubusercontent.com/assets/17168500/14929718/bf2c3422-0e13-11e6-8a39-cb9ae005ebe4.JPG)

**Comment by ecsion** [comment]
fixed.
