### ISSUE TITLE
WSG: Mismatched projects for reporting

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#217]
Investigator Amy Snover reports that she can't see her project, "Successful Adaptation: Identifying Effective Process and Outcome Characteristics and Practice-Relevant Metrics" (R/COCC/SS-3) in her reporting interface. She is seeing two others, one of which is Benjamin Miner's "Proposal to assess the prevalence and virulence of sea star Wasting Syndrome along the Washington Coast" (R/HCE/PD-1).

Something that may have contributed to this is the fact that, in the old FileMaker interface, I note that Amy Snover's project lists another Principal Investigator (i.e., _not_ a "co-PI" but a "PI" which is fairly unusual, I believe):  Pamela Matson (Stanford U) and, more important I think, the project ID in FileMaker is listed as "Matson_1702."

I'm not sure what additional information (e.g., links, screenshots) you would like in this case, so please contact me for specifics. I also hope to confer with later this morning to see if she can provide additional information that might help untangle this knot.

**Comment by ecsion** [comment]
done
