### ISSUE TITLE
Missing  < PREVIOUS and NEXT >  navigation pointers 

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#218]
< PREVIOUS and NEXT > nav links do not appear on the "Impacts & Accomplishments Q&A" page

http://eseagrant.mit.edu/index.php?module=Reporting&view=Detail&record=16339&mode=showMultiQuestionStem&QuestionId=11717&tab_label=Impacts%20&%20Accomplishments%20Q=&A=&tab_label=Impacts%20&%20Accomplishments%20Q&A

This page was built as a "Custom Form", FYI

**Comment by ecsion** [comment]
There is an issue with using special character, example '&' in custom forms. Please use alphanumerics only. You can change '&' to 'and'

**Comment by marypleasant** [comment]
I am having this problem with my "Biennial Budget" custom form. I removed my % signs, but the <Previous and Next> pointers still aren't displaying.

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=15351&mode=showMultiQuestionStem&QuestionId=15220&tab_label=Biennial%20Budget

**Comment by ecsion** [comment]
@marypleasant The issue was that there was a space after the form name: "Biennial Budget ". For now we have removed it. We will be adding a trim to the name so it would work even of there is space added at the end of Custom form name.

**Comment by marypleasant** [comment]
Thanks!
