### ISSUE TITLE
Reporting: Major conceptual issue

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#22]
Currently, only way to preview a report as you are building the report call is to assign projects and publish the call and then start a report. But once you've done so, you can no longer edit the report call (e.g., select new metrics) or questions contained therein.
Further…you can delete a reporting call, but there's no way to delete the reports themselves.
We may be missing something here: perhaps the issue is being addressed already, but we wanted to be sure this was on record in the bug tracker.
Essentially, this situation almost renders the system unusable for us because we have no way to "proof" our work before we publish it and no way to change it once published.

**Comment by mcbridec** [comment]
We also would like a way to preview a reporting call before it goes out. Every call is different, and it is critical to get each one correct before publishing. So we need to be able to review and make changes at least prior to "final" publishing. Being able to delete the associated reports would enable us to clean up the reports list.

**Comment by mgduke** [comment]
Yup; we actually spoke at length about this today with Deepak. I’m going to add something more on this to github. We felt fairly confident that all would agree with this. As we said to Deepak, “We’re flawed beings, and will never get it right the first time out.” We’re actually shooting for something even more ambitious, which is to be able to edit reporting calls et al. after they’ve been published. We can preview custom forms already, but not the entire call, so we’d like that, too, but if it had to be a choice, we felt post-publishing editing was the best bet. Might even cost a little extra, but unless Ecsion comes up with a killer preview interface, we think it’s imperative.

 <https://wsg.washington.edu/>	
Marcus Duke
Editing and IT Maven  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by mcbridec** [comment]
Is it not dangerous to fiddle with a reporting call after it has been published? : )

**Comment by mgduke** [comment]
Oh, yes, indeed. One must proceed with caution. But we have often had to tweak wording after getting feedback regarding ambiguities. But also never made any changes that would affect already entered data.
 <https://wsg.washington.edu/>	
Marcus Duke
Editing and IT Maven  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
fixed,
