### ISSUE TITLE
WSG rerun: Partners "type" and "scale" not auto-populating on partner selection

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#222]
I couldn't find the original ticket for this, so enter a new one:

While this has been fixed in the past, we once again have the situation where selecting partners for a report no longer auto-populates the "type" and "scale" fields.

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
I can't tell if you fixed only certain ones or fixed the entire Partners record set. I looked at a random selection of report Partners pages and for most of them, either one or the other field is not populated. I will compare with the old eSeaGrant and report back.

**Comment by mgduke** [comment]
OK, 2015 reports are fine. It's all about the migrated data. For example, see the following page and screenshot of the FileMaker Partners interface for Dan Cheney's 2014 report, but first:
Note that the first 3 items in the FileMaker screenshot all have Type and Scale data, but the Ecsion Partner's page equivalent fields just say "Select an option."
My question is: Would it be easier/better for us to just fix these ourselves by comparing with the FileMaker interface Partners data?

http://esg.wsg.washington.edu/index.php?module=Reporting&relatedModule=PartnerReport&view=Detail&record=3764&mode=showRelatedList&tab_label=Partners%20this%20period

<img width="1083" alt="screen shot 2016-06-17 at 1 42 59 pm" src="https://cloud.githubusercontent.com/assets/17168836/16164234/dda2248a-3491-11e6-830c-d0c368702b59.png">
