### ISSUE TITLE
WSG: Urgent—custom forms don't save if required field has no data

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#223]
Following up on phone discussion about issue reported by staff and investigator wherein custom forms were losing all data upon save.

I was unable to replicate this behavior until I omitted a "required" field. On clicking "Add," instead of getting an alert that the required field had not been filled in, I got the usual, pink "Save: Yes/No" popup and, on clicking "Yes," I immediately lost all data.

So apparently validation is not functioning at present. We're unsure why this issue has only manifested now, given many people have already submitted reports, but the malfunctioning validation seems the most likely cause.

**Comment by ecsion** [comment]
fixed.
