### ISSUE TITLE
OSG- Parent Project chooser screen fix

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#226]
1- When choosing a Parent Project, a list of projects come up, but the instructions at the top of the screen need to be changed. They make no sense. I did not notice this before.
2- Also within the same screen, the sort or filter function for the columns doesn't seem to work.

![2016-05-18_0918a](https://cloud.githubusercontent.com/assets/17169131/15366582/d9756f40-1cd9-11e6-8bc5-95b618f721ae.png)

**Comment by ecsion** [comment]
fixed.
