### ISSUE TITLE
OSG- Lost Ability to Edit Email Templates

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#227]
1- Today I cannot edit any email templates. The little edit icon is no longer there to choose.
2- Also I cannot advance to the next page of templates.
3- In addition, all of the edits I had previously made to the templates are gone. 

Note: This includes System as well as User email templates.

![2016-05-18_0942](https://cloud.githubusercontent.com/assets/17169131/15367323/64912c4c-1cdd-11e6-828e-8478b952f639.png)
![2016-05-18_0940d](https://cloud.githubusercontent.com/assets/17169131/15367333/66f0bc6e-1cdd-11e6-9ba7-f7277f41c918.png)
![2016-05-18_0938c](https://cloud.githubusercontent.com/assets/17169131/15367335/69f78d70-1cdd-11e6-910b-4e191f58ff22.png)

**Comment by ecsion** [comment]
We have reopened editing of email templates.
