### ISSUE TITLE
OSG- SAVE button issues again and also Red Alert text changes

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#228]
First, as a PI working thorough a report, I came across this red Alert warning. First, I see nothing to indicate on this page to tell me to "save changes" other than I did check the box at the top of the form to mark as complete. Please add a save button or else only warn me if I have not completed the form. Should the custom forms all have a SAVE button as well as a completed form checkbox?

Actually I had to ADD answers in order to move forward without a red Alert. Can we add a SAVE button on all report forms that is separate from, and in addition to an ADD button?

Secondly, the red Alert that dropped down asked me two questions; 1, Do I want to leave this page and discard my changes, and 2, Do I want to stay on this page. I have to choose Yes or No. Please ask only one question or tell me to choose yes to continue and lose my changes, or choose no to stay on this page. Thanks!

![2016-05-18_1437](https://cloud.githubusercontent.com/assets/17169131/15375823/449ac17c-1d06-11e6-80c9-b7e59dae3f16.png)
This is the page I was working in: http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=1181&mode=showMultiQuestionStem&QuestionId=777&tab_label=CERTIFICATIONS,%20LICENSES,%20and%20PATENTS

However, all of the other reporting forms for my call had this same issue.

**Comment by ecsion** [comment]
Fixed with v1.5. If you still have an issue, please reopen this issue or add a new one with example.
