### ISSUE TITLE
Alphabetizing the PI name column

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#229]
When we click on the PI column, it alphabetizes by first name instead of last name, which is useless (see image)

Please change so that it puts the PI name in order by last name, If necessary, show only the lname field in the PI column for the main view.

![image](https://cloud.githubusercontent.com/assets/17729848/15400995/a6355ac2-1dbb-11e6-8fa1-e89949888d1b.png)

**Comment by ecsion** [comment]
fixed.
