### ISSUE TITLE
Allow dashes in file names, plz

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#230]
There is a bug that prevents us from uploading/downloading files (in reporting, at least) when there is a dash in the name - I guess this is a “forbidden” character. But we will surely want to name name files after project and pub numbers -- which have many dashes 
I’ve talked to Deepak about this; i hope the dash character can be allowed in the naming protocol.

**Comment by mcbridec** [comment]
Good to know, and thanks.

**Comment by ecsion** [comment]
Kathy, we are already allowing a dash. Could you provide a link where you are facing an issue, so we can investigate further.

**Comment by kdez** [comment]
This is fine now - probably got fixed a long time ago.
However, in testing it I uncovered another problem - the field labeled "Publication URLs" seems to be "Required" in that I get an error message about it being blank, even though there is no red star next to it, and it should not be required. 
I will open an new but report for this.
