### ISSUE TITLE
WSG: Got a good one for you—grammar/syntax issue for Metrics Questions

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#232]
I thought you'd like something completely different for a change. We LOVE the validator on the Metrics Questions that alerts you to having unsaved changes. However, the question's either/or structure fails to equate syntactically with the "No" or "Yes" options. The question is "leave this page" or "stay on this page", but either answering "No" or "Yes" is ambiguous—that is, what are you saying no or yes too: leaving or staying?

I suggest changing the alert as follows:
"You have unsaved changes on this page. Do you want to leave this page (all unsaved changes will be lost)?" and leave "No" or "Yes" as is.

**Comment by mcbridec** [comment]
Good find. We have similar issues within Report Call when PI is reporting (issue #228)

**Comment by mgduke** [comment]
Thanks, Cathy.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
fixed.
