### ISSUE TITLE
WSG: Request Maintenance Mode to lock out users during open call

### ISSUE THREAD

**Issue by ghost** [ecsion/eSeaGrant-Client-Bug-Tracker#235]
For those occasions when developers et al. must effect changes to the system, we request a "maintenance mode" feature similar to that provided by CMS' such as WordPress.

This is to prevent investigators and staff from using the system during troubleshooting and resolution, which in some cases could result in lost data when it's being entered during that same timeframe.

**Comment by mcbridec** [comment]
Great idea, if at all possible.

**Comment by mgduke** [comment]
You said you already had something like this; fine. But what would the exact process be? How do we warn people who are actually using the system at the time that maintenance would kick in? Can we put advance warning (e.g., on login page or dashboard)? ??
