### ISSUE TITLE
WSG: New popup editing interface for custom forms needs some formatting

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#236]
We were just looking at the custom Impacts & Accomplishments form owing to reported missing data entered by a staff (Aaron Barnett), and discovered that there is now a popup window that appears whenever we want to edit one of the I&A entries. Not sure why this was necessary; not all that keen on it, but if other SG folk want it, ok. However, please see screenshot, which shows that the Goals checkboxes (near bottom) run on as if they're in a single paragraph. A new line break should separate each checkbox, please. URL of example I&A page is:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=20703&mode=showMultiQuestionStem&QuestionId=17403&tab_label=#

<img width="1005" alt="screen shot 2016-06-02 at 12 35 53 pm" src="https://cloud.githubusercontent.com/assets/17168836/15758404/4dcc8766-28bf-11e6-8c4c-5263c9324a97.png">

**Comment by ecsion** [comment]
fixed.
