### ISSUE TITLE
WSG: Possible to retrieve data from early May backup?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#237]
A staffer claims to have entered data on our custom Impacts & Accomplishments form, but on just looking at it recently, determined that what he saved is no longer there. While we can't prove if this was operator error, we would like to appease the staff member if possible by retrieving the data he supposedly entered and saved. Is that possible?

The staff person is Aaron Barnett, and the URL to his I&A page is:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=20703&mode=showMultiQuestionStem&QuestionId=17403&tab_label=#

**Comment by ecsion** [comment]
we can do this, contact Deepak by email if this is still needed.
