### ISSUE TITLE
WSG: Urgent—Custom form export "all" records (across pages) not working 

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#239]
We seem to have lost our ability to export all custom form records across all pages (i.e., when we click the yellow line with the text "Select all Reports (xxx)", getting the MySQL error:

{"success":false,"error":{"code":"Invalid cell coordinate 8","message":"Invalid cell coordinate 8"}}

However, we _are_ able to export all records displayed on a single Custom Forms page.

**Comment by ecsion** [comment]
fixed.
