### ISSUE TITLE
User role definitions

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#24]
What does each user role have access to do? So far, we think “Staff” cannot enter projects, at least. We figure this info is coming, but I think we need to have this in writing sooner as we assign staff to set up projects and test reporting calls, etc.

**Comment by ecsion** [comment]
RC has admin on Projects, Reports & RFP. Staff Role can only admin Projects & Reports. Staff does not have access to RFP. PI's have access to their own projects, reports and RFP
