### ISSUE TITLE
WSG: Dates missing editing popup window on custom form (Leveraged Funds) 

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#241]
When opening the edit window in a custom form (specifically, Leveraged Funds), we note the start and end dates disappear, but they are visible in the form data itself. Also, if we make any change in the edit view (to any field), we must re-enter the start and end dates.

Example link:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17994&mode=showMultiQuestionStem&QuestionId=15946&tab_label=Leveraged%20Funds&tab_label=Leveraged%20Funds#

<img width="1288" alt="screen shot 2016-06-06 at 3 11 09 pm" src="https://cloud.githubusercontent.com/assets/17168836/15839643/4694442e-2bf9-11e6-9784-500ad9dba7eb.png">

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
I confirm this is fixed. However, I note another anomaly: After I check one entry by clicking "edit," I noticed that when I click another entry, I can't edit it (nothing happens when I click "edit" link) until I've refreshed the page. (Might this be related to the mysql_free_result function?)
