### ISSUE TITLE
CASG: Adding Instructions Under Narrative 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#242]
Hi, 

For the 2017 Special Focus Awards RFP, in the "Instruction" tab, under "Narrative", can you please add the below?:

"The Project Narrative format may vary, however proposals should include the information listed below. The project narrative MUST not exceed 12 pages (INCLUDING, Introduction, Objectives, Approach, illustrations, charts, tables, and figures).   Proposals exceeding this size limit will not be reviewed."

![screen shot 2016-06-07 at 4 20 25 pm](https://cloud.githubusercontent.com/assets/17860279/15877942/f4491e14-2ccb-11e6-8b3c-34c93c296405.png)

Thanks. And thanks for fixing my key personnel issue!

**Comment by ecsion** [comment]
Added standard instructions for narratives for now. Please review and see if these are satisfactory, otherwise, we will change them to the text you requested.

**Comment by mumezawa** [comment]
It looks good, thanks.


Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160
mumezawa@ucsd.edu
https://caseagrant.ucsd.edu


From:  ecsion <notifications@github.com>
Reply-To:  ecsion/eSeaGrant-Client-Bug-Tracker
<reply+011086b71c24ecf6262d81d4ca2955a9aee8f7bf1078adce92cf00000001137139939
2a169ce097adc08@reply.github.com>
Date:  Thursday, June 9, 2016 at 7:05 AM
To:  ecsion/eSeaGrant-Client-Bug-Tracker
<eSeaGrant-Client-Bug-Tracker@noreply.github.com>
Cc:  Miho Umezawa <mumezawa@ucsd.edu>, Author <author@noreply.github.com>
Subject:  Re: [ecsion/eSeaGrant-Client-Bug-Tracker] CASG: Adding
Instructions Under Narrative  (#242)


Added standard instructions for narratives for now. Please review and see if
these are satisfactory, otherwise, we will change them to the text you
requested.


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/242#issuecomm
ent-224904685> , or mute the thread
<https://github.com/notifications/unsubscribe/ARCGtzh2ltz-t12ZeCTbxthP0orXsG
70ks5qKB2TgaJpZM4IwdHT> .
