### ISSUE TITLE
CASG: RFP -  Viewing Uploaded Documents - HIGH PRIORITY

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#243]
Hi, 

For the 2017 Special Focus Awards RFP, none of the pdf files that are uploaded (Project Narrative, Letters of Support, Matching Funds, etc.) are showing up when I click on them for BOTH as a PI and admin:

(This screen capture is me logged in as admin)

![screen shot 2016-06-08 at 10 00 12 am](https://cloud.githubusercontent.com/assets/17860279/15903119/e9a7617a-2d5f-11e6-8e8e-b8493f3ccc60.png)

Here's what it looks like (Logged in as a PI; it looks the same when I log in as admin):

![screen shot 2016-06-08 at 10 02 47 am](https://cloud.githubusercontent.com/assets/17860279/15903163/3198f69c-2d60-11e6-859c-b9a29f0b6669.png)

--

Also, as an admin, what is the best way to compile a proposal into one pdf? is the "Proposal pdf" tab supposed to look like this? Nothing happens when you click upload file either...: 

![screen shot 2016-06-08 at 10 06 55 am](https://cloud.githubusercontent.com/assets/17860279/15903296/e46ed4e4-2d60-11e6-8aa1-ae4ae2aeebd2.png)

Thanks so much.

- Miho

**Comment by mumezawa** [comment]
I'm still having the same issue with downloading submitted application materials and the applications materials which are downloaded through the zip folder are not coming through (as an admin). For example, the current and pending funds is pretty much blank but the PI has inputted information.

[cpsupport.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/307622/cpsupport.pdf)

This proposal is RFP Call: 2017 Special Focus Awards  |  Phase: Full-Proposal |  PI Name: Miho GMAIL  Title: TEST #1 |  Submission Status: Submitted

Thanks.

**Comment by ecsion** [comment]
fixed for new proposals. For existing proposals, delete and re-uplaod.
