### ISSUE TITLE
CASG: Automated Email 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#244]
Hi,

It seems as though the automated email shows the submission timestamp rather than the proposal submission deadline. Can you please look into this?

![screen shot 2016-06-08 at 10 15 44 am](https://cloud.githubusercontent.com/assets/17860279/15907522/5e8135ea-2d72-11e6-84ba-5ea1eac206cc.png)

Thanks,
Miho

**Comment by ecsion** [comment]
fixed.
