### ISSUE TITLE
CASG: Reporting Call Period Not Updating

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#245]
Hi, 

I changed the report call period as an admin for the NMFS Fellowship, but it's not updating as a PI. See under INSTRUCTION --> TEST: Are these dates supposed to be the project start/end dates or the reporting period? Regardless, it should be 6-1-2014 ~ 5-31-2016.

![screen shot 2016-06-08 at 3 32 22 pm](https://cloud.githubusercontent.com/assets/17860279/15913447/eac76b52-2d8e-11e6-9c2e-592f75a8a2ce.png)

It seems to be showing up correctly everywhere else. 

Thanks,
Miho

**Comment by ecsion** [comment]
fixed.
