### ISSUE TITLE
WSG: Custom form edit window's "Type of Event" dropdown menu reverts to default on save

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#246]
Our "Meetings, Workshops, Presentations" custom form is where we discovered this issue, but it may occur elsewhere where dropdown menus are used to select pre-established options.

When reviewing a "Meetings…" response, we click the "edit" link and, regardless of the Type of Event we had input previously, "Public or professional presentation" always appears in the edit window's dropdown menu for that field. If we click "Save" in the edit window, it automatically overwrites whatever had been previously listed in Type of Event with the default, "Public or professional presentation."

For example, see Response #3 on:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=19747&mode=showMultiQuestionStem&QuestionId=15948&tab_label=

**Comment by ecsion** [comment]
fixed.
