### ISSUE TITLE
CASG: NMFS Fellowship Reporting Call Requests

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#247]
Hi, 

I think we're almost ready to go with this reporting call, but I had a few additional requests:

**High Priority**
- For "Publications" form, make open/close access question mandatory. This will help us immensely in the long run. 

![screen shot 2016-06-09 at 9 55 04 am](https://cloud.githubusercontent.com/assets/17860279/15938519/64b5f9ee-2e28-11e6-9621-d7a6d5b091cc.png)

**Mid/Low Priority** 
- Take out "Report Guidelines PDF button" 
      Could we possibly have the instructions for each section show up instead?  This isn't critical but rather than downloading a pdf with a few sentences, it would be nice if the instructions just showed up. It does this on the custom forms, but I can't change any of the mandatory forms. 
- Can we take the instructions out of the box under "Requested Information" so they look more other sections?

![screen shot 2016-06-09 at 9 57 38 am](https://cloud.githubusercontent.com/assets/17860279/15938586/a2293ae8-2e28-11e6-9901-68c1a69a4bef.png)

Thanks,
Miho

**Comment by ecsion** [comment]
Miho, this was done several months ago but not closed. Can you please check and let us know if we missed something.
