### ISSUE TITLE
CASG: 2017 Special Focus Awards RFP Instructions 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#248]
Hi, 

I was wondering why the instructions for each section are not showing up in the "Instructions" tab? It's missing instructions for budget, title page, project summary, matching funds, and 90-2 forms. Each form should have instructions that you can pull from (except for Budget, 90-2 form).  I can send instructions for the budget and the 90-2 form too. 

Thanks,
Miho

**Comment by ecsion** [comment]
done.
