### ISSUE TITLE
Attachments not opening in submitted reports

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#249]
When logged on as an RC and looking at a submitted report (example, Peters NRPF Report Call, project number E/INT-145 E/A-16), the attached documents the PI submitted do not open.

For "Peters NRPF Report Call," the following documents submitted by the PI will not open or are blank:
- Exploratory_Analysis_JP.docx  
- Quart_Reports.pdf 
- Thesis_JRP_2016.pdf
- JRP_Stormwater_Final.docx 
- req_parameters.png
- In addition, under submission preview, when I click “download report docs zip,” I am able to download a folder, but not open it. 

Example illustrated in link and screenshot here: 
http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=1190&mode=showMultiQuestionStem&QuestionId=636&tab_label=PROGRESS%20and%20OUTCOMES&tab_label=PROGRESS%20and%20OUTCOMES
![capture](https://cloud.githubusercontent.com/assets/17168500/15949610/b5137580-2e5d-11e6-9845-2b36d696994c.JPG)

**Comment by ecsion** [comment]
fixed.

**Comment by marypleasant** [comment]
The attachments open, but still under submission preview, when I click “download report docs zip,” I am able to download a folder, but not open it. 

http://eseagrant.oregonstate.edu/index.php?module=Reporting&view=Detail&record=1190&mode=showMultiQuestionStem&QuestionId=636&tab_label=PROGRESS%20and%20OUTCOMES&tab_label=PROGRESS%20and%20OUTCOMES
![capture](https://cloud.githubusercontent.com/assets/17168500/15975053/695a29ec-2f00-11e6-98eb-f26558a797f5.JPG)
