### ISSUE TITLE
Incorrect contact info on RI Sea Grant eSeaGrant home page

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#250]
the contact information (see screenshot) is incorrect and should read 
Contact Alan Desbonnet aland@uri.edu  401.874.6813

![screen shot 2016-06-13 at 10 45 18 am](https://cloud.githubusercontent.com/assets/18398763/16011533/f55e6eee-3153-11e6-82e8-2e50de533c92.png)

**Comment by ecsion** [comment]
fixed.
