### ISSUE TITLE
CASG - RFP: URGENT Investigator & Key Personnel 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#251]
Hi, 

For 2017 RFP Special Focus Awards:

Under "Investigator" instructions,  please delete "You may use the SG resume template, or your own
format." in the instructions. I'm not sure what the SG resume template is. Please also delete "DO NOT include page numbers, headers, or footers". 

Under "Key Personnel", please delete the current instructions, "Please include all project PIs, Co-PIs, and Associate PIs." and replace it with "Please include all key personnel who are NOT listed as investigators (ex. Postdoc student).  NOTE: CVs cannot be uploaded for key personnel.". 

![screen shot 2016-06-10 at 3 52 58 pm](https://cloud.githubusercontent.com/assets/17860279/15980847/73ebd6e4-2f23-11e6-90e5-a41f27b45861.png)

Thank you.

**Comment by ecsion** [comment]
done.
