### ISSUE TITLE
CASG - RFP: 2017 Special Focus Awards Due Date

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#252]
Hi,

The due date is not updating - it should be July 15, 2016 at 4pm (NOT 12am). 
![screen shot 2016-06-13 at 9 15 34 am](https://cloud.githubusercontent.com/assets/17860279/16021087/aadbadc0-3165-11e6-86e2-8a85fa3dec27.png)

It seems to be showing up correctly everywhere else.

![screen shot 2016-06-13 at 12 50 44 pm](https://cloud.githubusercontent.com/assets/17860279/16021114/cd2140d4-3165-11e6-995d-54676b41a8f1.png)

Thanks,

Miho

**Comment by ecsion** [comment]
fixed
