### ISSUE TITLE
CASG: URGENT - Unable to Invite PIs under RFPs 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#253]
Hi, 

I keep getting a blank box today when I try to add PIs under 2017 Special Focus Awards. 
We need to invite PIs ASAP so they can start working on their proposals.

![screen shot 2016-06-13 at 4 30 02 pm](https://cloud.githubusercontent.com/assets/17860279/16026572/53dadc16-3184-11e6-8d33-aab0f0a62219.png)

Thanks so much.

Best regards,

Miho

**Comment by ecsion** [comment]
We cannot reproduce this error. This may have been a internet glitch. If you can reproduce, please provide exact steps.

**Comment by mumezawa** [comment]
It wasn't working the past two days, but now it is. I was able to invite the PIs. Thank you!
