### ISSUE TITLE
CASG: Special Focus Awards - Current & Pending Support

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#254]
Hi, 

The current and pending support information is not showing up on the backend when you download it as an admin.

[cpsupport.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/312891/cpsupport.pdf)\

![screen shot 2016-06-13 at 4 39 22 pm](https://cloud.githubusercontent.com/assets/17860279/16026748/80ff98c0-3185-11e6-84a7-1ec232eafc3e.png)

It shows up on the "Submission Preview", though... 

Thanks,

Miho

**Comment by ecsion** [comment]
We are not able to follow the issue. It will help us if you could provide the url link of the page where you re exporting. also what are clicking to export.

**Comment by mumezawa** [comment]
It's when I download the files as a zip: 

![screen shot 2016-06-15 at 10 32 45 am](https://cloud.githubusercontent.com/assets/17860279/16090510/928d4d2a-32e4-11e6-80f1-73a068c811a0.png)

[cpsupport.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/316827/cpsupport.pdf)

Link: http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=13703&phaseid=13704&tab_label=Full-Proposal%20Setup

Download Jim Eckman's proposal as a zip folder and open the file "cpsupport".
The information shows up correctly under the "submission preview" (see my first message).

Thanks.

**Comment by ecsion** [comment]
fixed.
