### ISSUE TITLE
CASG: URGENT Special Focus Awards - Project Time Schedule

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#255]
Hi,

Please delete "Project Time Schedule" under "Instructions" in the 2017 Special Focus Awards.
We're not using it and I haven't clicked the form in the backend but it's still showing up.

![screen shot 2016-06-13 at 4 42 21 pm](https://cloud.githubusercontent.com/assets/17860279/16026804/f032f0c0-3185-11e6-83ce-93d950b3f650.png)

Thanks,
Miho

**Comment by ecsion** [comment]
fixed.
