### ISSUE TITLE
CASG: URGENT Special Focus Awards Budget Duration

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#256]
Hi,

Although the budget duration is not identified on the backend, it's showing up at 1969 when the PI accesses it... 

Screen capture of backend (project duration NOT identified. I left it blank because not all the PIs may propose the same project duration)
![screen shot 2016-06-15 at 9 41 40 am](https://cloud.githubusercontent.com/assets/17860279/16088916/f5c050b0-32dd-11e6-8f2c-a033a5f0b42f.png)

Screenshot as a PI (The project duration was correct yesterday but then someone changed...)- 
![screen shot 2016-06-15 at 9 42 12 am](https://cloud.githubusercontent.com/assets/17860279/16088885/e5120d4e-32dd-11e6-8f15-05f452f0c2d2.png)

Can we leave it so that PI can select a budget duration or if must have a project duration, have it as 2/1/2017 - 1/31/2018?

Thanks,
Miho

**Comment by ecsion** [comment]
We are unable to reproduce this bug. Could you please provide steps on how to reproduce.

**Comment by mumezawa** [comment]
It seems to be working now. Thanks.
