### ISSUE TITLE
CASG: Special Focus Awards 90-2 Instructions

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#257]
Hi,

Thanks for all your help with this. 
Under the Instructions tab, please add the below for 90-2:

![screen shot 2016-06-15 at 10 26 36 am](https://cloud.githubusercontent.com/assets/17860279/16090282/aa25b504-32e3-11e6-9fcd-4625211a2722.png)

It is NOT necessary to include entries for most sections. We ask that you include some entries for “keywords” that relate to your proposal. Also, if you have a current or prior California Sea Grant award that is “Related” to, or is a “Parent” to, this proposal, please enter the Sea Grant Award number.
You can leave “Project number”, “Project Status”, “Grant Number”, and “Sub Program” blank.

--

Thanks,

Miho

**Comment by ecsion** [comment]
done.
