### ISSUE TITLE
Downloading 90-2 Forms as an Excel Document

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#259]
Hi,

I spoke with our grants and contracts specialist and she said it would be helpful to access the 90-2 forms as an excel. Is this a possibility? 

When we package federal grants, we prefer having the 90-2 forms as an excel document. 
You can find a template here: http://seagrant.noaa.gov/fundingfellowships/seagrantformsandtemplates.aspx

(see "Sea Grant Project Summary Form")

Thanks so much.

**Comment by ecsion** [comment]
this is part of 90-2 work we are doing with NOAA and separately tracked. Closing this one.
