### ISSUE TITLE
CASG: Promoting Proposals to Projects 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#261]
Hi, 

I'm looking at the 2015 Delta Science Fellowship RFP and it looks like all the submitted proposals were promoted (even the ones that weren't funded). 
However, they aren't showing up as projects. Do I need to create a new project for each funded proposal  or is there an easier way? 

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=promoteProposal&record=5990&phaseid=6617&tab_label=Full-Proposal%20Setup

Here are the 12 projects that were funded (NOTE: The PIs submitted the proposal and not the fellow so the names are different.) This website has the fellow's names: https://caseagrant.ucsd.edu/news/twelve-early-career-scientists-named-delta-science-fellows
The project titles are the same though. 

Thanks.

**Comment by ecsion** [comment]
I think we dropped the ball on this one. Could you please let us know if the original request is still valid and pending

**Comment by mumezawa** [comment]
We've dealt with this one. Thanks.
