### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#262]
Hi, 

Are there varying levels with administrative privileges? 
I plan on giving our fiscal team access to the backend so they look can look at projects, but they won't be using the RFP and proposal management side of things. 

What privileges do "staff" get? 

Thanks,
Miho

**Comment by mcbridec** [comment]
Hi- The answer to issue #24 might help.

**Comment by mumezawa** [comment]
Perfect, this is exactly what I was looking for!
Thanks. 


Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160
mumezawa@ucsd.edu
https://caseagrant.ucsd.edu


From:  Cathy M <notifications@github.com>
Reply-To:  ecsion/eSeaGrant-Client-Bug-Tracker
<reply+011086b7ad84ba8d5ca5e37d0e1d40730fd4f181f39b97fd92cf0000000113852ff79
2a169ce09aad8cf@reply.github.com>
Date:  Friday, June 24, 2016 at 10:29 AM
To:  ecsion/eSeaGrant-Client-Bug-Tracker
<eSeaGrant-Client-Bug-Tracker@noreply.github.com>
Cc:  Miho Umezawa <mumezawa@ucsd.edu>, Author <author@noreply.github.com>
Subject:  Re: [ecsion/eSeaGrant-Client-Bug-Tracker] User Roles (#262)


Hi- The answer to issue #24
<https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/24>  might
help.


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/262#issuecomm
ent-228408797> , or mute the thread
<https://github.com/notifications/unsubscribe/ARCGt4gYJCfFd7v-7w7zOi9rkQ8uCc
UYks5qPBP3gaJpZM4I99PH> .

**Comment by ecsion** [comment]
Roles Access is below
SGAdmin Role: All Tabs (People, Projects, RFP, Proposals, Reviews, ReportCalls Reports, Bookshelf)
SGStaff: People, Projects, ReportCalls, Reports, BookShelf
Investigator: RFP + their own: Proposals, Projects, ReportCalls, Reports
