### ISSUE TITLE
CASG: Adding Delta Science Fellowship

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#263]
Hi,

Under the drop down menu for "Project Type", can you please add "Delta Science Fellows"?
It's a growing program so would be helpful to classify them rather than putting them as "other". 
For example, project # R/SF-70 is part of the Delta Science Fellowship program.  
http://eseagrant2.ucsd.edu/index.php?module=Projects&view=Edit&record=16834

Thanks,

Miho

**Comment by ecsion** [comment]
done.
