### ISSUE TITLE
CASG: 2017 Special Focus Awards - Peer Reviews

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#264]
Hi,

I've started testing the peer review function and the link is not working.
I set up my test account as a peer reviewer and received the below email message:
--
Dear Miho Testing ,

Thank you for accepting to peer review the proposal titled: TEST #1 (Full-Proposal), submitted by Miho GMAIL for RFP titled: 2017 Special Focus Awards .

Click on the on link: http://eseagrant2.ucsd.eduoperations.php?action=peerresponseform&guid=FD9E0BDF-C275-44F1-8262-4E2E77BD68FE to submit your review. This is your personalized link for the peer review task. You may access this link till the deadline to edit your reviews. You will receive a confirmation email each time you submit your reviews.
Sincerely,

Miho Umezawa | Research & Fellowship Coordinator

-- 
When I click the link (http://eseagrant2.ucsd.eduoperations.php/?action=peerresponseform&guid=FD9E0BDF-C275-44F1-8262-4E2E77BD68FE), I get this:

![screen shot 2016-06-27 at 9 03 51 am](https://cloud.githubusercontent.com/assets/17860279/16386714/85837256-3c46-11e6-9a4e-b4f83f676b4d.png)

We need this fully functioning by July 17. 

Thanks,

Miho

**Comment by ecsion** [comment]
There was an issue with the link generation which has been fixed. links in old email won;t work, but new generated links should be fine. Please check and if you still have an issue, please reopen ticket.
