### ISSUE TITLE
Custom Form not update in User view/data not saved

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#265]
I created a Level of Effort custom form, and added it to a reporting call. I then edited the custom form, adding a 4th question as a selectable list and rearranging the sequence. At the user interface, the new question shows up when editing existing responses, but when saved it is NOT saved and does not show up in the user data screen. IF a new response is added, then all works correctly.

Is it possible to have updated forms behave correctly and Save and then show edits as noted above?

**Comment by ecsion** [comment]
done. Please check.
