### ISSUE TITLE
CASG: Delta Science Fellowship - Grosholz 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#267]
Hi,

Grosholz's project "Mechanisms for the Effective Biological Control of the Invasive Water Hyacinth, Eichhornia crassipes, in the Sacramento-San Joaquin River Delta, California" was already promoted in the backend but it's not showing up as a project and I can't edit the proposal to assign a project number.

The project number should be R/SF-69. 

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=promoteProposal&record=5990&phaseid=6617&tab_label=Full-Proposal%20Setup

Thanks,

Miho

**Comment by ecsion** [comment]
There are 146 Projects in the mittsg summary_info table. Unfortunately, R/SF-69 is not there and that is why it is missing from the new system, Can you double check that you can access this project in the old system? If so, please provide details and open a new bug.
