### ISSUE TITLE
CASG: Automated Notification Emails 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#269]
Hi,

Rather than having the notification emails cc'd to me, can you please change it to sgproposal@ucsd.edu?

Here are two examples: 

![screen shot 2016-06-28 at 4 36 07 pm](https://cloud.githubusercontent.com/assets/17860279/16435910/731e5a0a-3d4e-11e6-85ce-f239c4ade81a.png)

![screen shot 2016-06-28 at 4 36 31 pm](https://cloud.githubusercontent.com/assets/17860279/16435920/8aba57b8-3d4e-11e6-9cee-0e89ba36156f.png)

Thanks,
Miho

**Comment by mumezawa** [comment]
This change hasn't happened yet:
Rather than having the notification emails cc'd to me, can you please change it to sgproposal@ucsd.edu?

Also, I recently got married so please change my name to Miho Ligare (mligare@ucsd.edu).
Please also make the update to login page: http://eseagrant2.ucsd.edu/index.php 

Thank you.

**Comment by ecsion** [comment]
done. Please check and reopen this issue if you feel it is not fixed and in that case provide details.
