### ISSUE TITLE
Update Report not able to be deleted

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#271]
I set up a test Reporting Period (admin) and a test Report (user). After testing, I have successfully deleted the false reporting call, but the user-based report cannot be deleted. The user has no option to delete it, and since the reporting call is deleted, the report is not seen in the admin view to be deleted.

how can this be rectified?

**Comment by ecsion** [comment]
We can't find any test reports associated with a deleted reporting call. Please provide a link so we can investigate.

**Comment by ecsion** [comment]
closing this issue. In case it is still a problem, please reopen or simply add another one. Do provide the relevant link to assist us in debugging.
