### ISSUE TITLE
partner data not updating

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#272]
I editing Partners data in Report Call module, but the changes are not reflected in Reports module, Partners This Period. These data should be identical and updated simultaneously. This needs to be corrected to function properly.

**Comment by ecsion** [comment]
The functionality we have coded is to keep the name of the partner that was selected by the PI and not its numeric code. Thus in reports the PI Selects from a pick list but we store the actual value selected. If we did not do it this way, a SG Admin or a Staff member could change the partner name and make it appear like that's what the PI selected which will be incorrect. 

This is a feature to ensure that reports keep the value selected by PI.
