### ISSUE TITLE
CASG: Panel Review - Submission Confirmation Emails

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#274]
Hi, 

I'm not receiving confirmation emails any time I submit a panel review despite the below email message. 
I set up another account to test the panel review function (email: casg.panelist@gmail.com).  

Dear CASG Panel, 

This email notification is to inform you that Panel Review for 2017 Special Focus Awards ,   Full-Proposal phase is now open.

Click  http://eseagrant2.ucsd.edu/operations.php?action=panel_reviewer&guid=M0U2MDgyMEQtMUYyRC00MUM0LUJBRUQtQTRFMkRFNUQzRjZC&exuti=MjYwMDY= to submit your review. This is your personalized link for the panel review task. You may access this link till the deadline to edit your reviews. **You will receive a confirmation email each time you submit your reviews.**

Sincerely,

Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant 
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160

-- 

Can you please look into this matter? 

Thanks,

Miho

**Comment by ecsion** [comment]
done. Please check.
