### ISSUE TITLE
CASG: RFP Access Issues

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#275]
Hi,

Once I create a new RFP (Delta Science Fellows Program - 2017 and 2017 State Fellows), I don't have access to continue: 

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&record=16829

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&record=26012

![screen shot 2016-07-01 at 11 42 26 am](https://cloud.githubusercontent.com/assets/17860279/16531365/0102870e-3f81-11e6-94d7-634c94fab18d.png)

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.
