### ISSUE TITLE
Bookshelf Preview

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#277]
Hi,

What's the purpose of the bookshelf preview and/or the best way to use it?

Thanks,

Miho

**Comment by ecsion** [comment]
You can store key SeaGrant documents, for example annual Ombibus document here. This way all the SG admins & all SG Staff roles will have 1 place to go to to view key documents. Note these documents are viewable by anyone who falls under SGAdmin to SGStaff roles.
