### ISSUE TITLE
CASG: Budget Worksheet - Total Cost Issue

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#279]
Hi, 

The grantee share's total cost is not adding up correctly (last column). 
It should add the total direct cost (section G), SG IDC rate , and Inst. IDC rate, but it currently is not adding the Inst. rate. 

For example, Colgan's grantee share total should be $35,956 (23196+2320+10440) but it's showing up as $25,516.

![screen shot 2016-07-08 at 4 14 21 pm](https://cloud.githubusercontent.com/assets/17860279/16704007/3b4737f6-4527-11e6-8e48-2fc625c205b0.png)

Here's the link: http://eseagrant2.ucsd.edu/operations.php?action=budget&proposal_id=MTYzMzQ=&id=693&update=1

It doesn't seem to matter whether the "Wavied IDC As Match" box is checked or not. 

Thanks,

Miho

**Comment by ecsion** [comment]
fixed. please check and reopen if this is still an issue.

**Comment by alandesbonnet** [comment]
works as expected. Thank You.

Alan Desbonnet
Assistant Director
