### ISSUE TITLE
CASG: Inviting PI Issue

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#280]
Hi,

Every so often, my screen to choose PIs to invite to submit a PI goes blank. 
It was happening all day yesterday and it just happened again. It's happened several times the past few weeks too. 
It was working earlier today but now it's not. Do you have any advice for how to stop this from happening? 

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=invitedPIListing&record=16829&phaseid=16830&tab_label=Fellowship%20Application%20Setup

If I click "Add PI" this is what I get:

![screen shot 2016-07-12 at 3 53 51 pm](https://cloud.githubusercontent.com/assets/17860279/16786349/eb996c04-4848-11e6-9321-5e44a60dd87c.png)

I'm not sure if you can duplicate this issue, but it's been frustrating because it happens from time to time and I have to stop working on it. Any suggestions would be appreciated.

Thanks,
Miho

**Comment by ecsion** [comment]
Miho -- It takes a few seconds for the page content to show. Firefox is the preferred browser. Try it and if after a few seconds, nothing shows up, then reopen/reenter the issue. Please mention the platform used (pc/mac) browser, browser version and also provide the url link.
