### ISSUE TITLE
CASG: URGENT Special Focus Awards RFP - Current & Pending Support

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#281]
Hi,

I've now received messages from two PIs working on their 2017 Special Focus Award RFP that the Current and Pending Support is not saving.

Is there a particular web browser I can recommend (for both PC and Mac)?
Please look into this matter. Their applications are due this Friday so many of the PIs are working on their applications this week. 

Thanks,
Miho

**Comment by ecsion** [comment]
checked and it is saving. We are closing this. If this is still an issue, please provide a link and screenshots and open a new issue.
