### ISSUE TITLE
CASG: URGENT Special Focus Awards - Budget Worksheet - Total Cost Issue #2

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#283]
Hi,

I'm having the same problem with the grantee share's total cost is not adding up correctly (last column). It should add the total direct cost (section G), SG IDC rate , and Inst. IDC rate, but it currently is not adding the Inst. rate.

It's for Ryan Walter's Special Focus Award proposal: 
http://eseagrant2.ucsd.edu/operations.php?action=budget&proposal_id=MTYzNzM=&id=717

![screen shot 2016-07-14 at 9 23 33 am](https://cloud.githubusercontent.com/assets/17860279/16847244/e2c65efe-49a4-11e6-9034-a13476ce565a.png)

Please look into this ASAP. 

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, it worked fine when we open the spreadsheet. 
<img width="1162" alt="screen shot 2016-07-27 at 9 04 48 am" src="https://cloud.githubusercontent.com/assets/1612666/17163089/59165e4a-53d9-11e6-99aa-2997bb45f550.png">

try refreshing the screen and all numbers will fill up. Possible reason for the issues many be internet glitch. I am closing this issue, however, If this persists then reopen or reenter this issue.
