### ISSUE TITLE
CASG: Special Focus Awards - Current and Pending Support 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#284]
Hi,

Some of the PIs are still have issues adding new current and pending support.
Also, if they try to enter decimals, it gives them an error message: 

![screen shot 2016-07-14 at 10 26 23 am](https://cloud.githubusercontent.com/assets/17860279/16850151/a95f6878-49b2-11e6-80ef-c1b69a427bae.png)

The first one seemed to work but you can't input additional current and pending support. 
Can you please have it so that we can numerical values that aren't whole numbers?
Please also note that sometimes, a person may commit less than one month too. 
As an example, this is happening to Walter's proposal: http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=16373&mode=showMultiQuestionStem&QuestionId=13702&tab_label=Current%20and%20Pending%20Support&tab_label=Current%20and%20Pending%20Support

Thanks,
Miho

**Comment by ecsion** [comment]
fixed.
