### ISSUE TITLE
CASG: RFP Budget Worksheets

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#286]
Hi,

Most of the budget worksheets under Section G are not downloading properly. 

For example, here is Cavanaugh's budget worksheet (under 2017 Special Focus Area RFP): http://eseagrant2.ucsd.edu/operations.php?action=budget&proposal_id=MjYzMjM=&id=703

http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=26323&mode=showBudget_90_4&tab_label=Budget%2090-4&tab_label=90-4%20(SG%20Admin%20Only)

But when you download it as a pdf, this is what Section G looks like:
![screen shot 2016-07-20 at 9 45 38 am](https://cloud.githubusercontent.com/assets/17860279/16994999/c2884e40-4e5e-11e6-9c69-10df13d5e668.png)

I've had to go through and manually change it. 

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.
