### ISSUE TITLE
CASG: URGENT Peer Review Confirmation Emails 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#288]
Hi,

Confirmation emails are still not being sent every time a reviewer sends a submission.

Please fix this or delete the following sentence in the automated email " You will receive a confirmation email each time you submit your reviews.":
--
Dear James Morris,

Thank you for accepting to peer review the proposal titled: Will coastal wetlands in southern California keep pace with sea level rise? A remote sensing approach to inform vegetation biological feedbacks (Full-Proposal), submitted by Kyle Cavanaugh for RFP titled: 2017 Special Focus Awards .

Click on the on link: http://eseagrant2.ucsd.edu/operations.php?action=peerresponseform&guid=CACF0F16-A07C-4FAD-A385-25899ADE3617 to submit your review. This is your personalized link for the peer review task. You may access this link till the deadline to edit your reviews. You will receive a confirmation email each time you submit your reviews.

Sincerely,

Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant 
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160

--

http://eseagrant2.ucsd.edu/index.php?module=EmailTemplates&view=Detail&record=30&type=AutoSystemEmails#

I'm starting to assign peer reviews now so please fix this asap.
I sent a similar bug (#274) a few weeks ago. 

Thanks,

Miho

**Comment by mumezawa** [comment]
It seems as though confirmations emails are being sent, but the deadline is wrong:

Dear Vince Buonaccorsi,

You have successfully submitted your review of the proposal titled: Developing a Striped Bass genetic sex marker as a first step towards identifying the cause of extreme sex ratio skew in a POD species, submitted by Andrea Schreier for RFP 2017 Special Focus Awards .

You may access your personalized review page by clicking this http://eseagrant2.ucsd.edu//operations.php?action=peerresponseform&guid=ADA74826-8937-451B-8108-413CD653D078 at any time up until the deadline (**05 Sep 2016**) to edit your reviews. You will receive a confirmation email each time you submit your reviews.

Submission Date and time: 26 Aug 2016, 08:24 AM

Sincerely,

--

The deadline is today, August 26. Please change this ASAP. Thanks.

**Comment by ecsion** [comment]
done, please test and reopen if this is still an issue.
