### ISSUE TITLE
Fellowship Applicant Permission Denied

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#289]
**As a fellow trying to access a fellowship application, I get a permission denied when I click on the opportunity.** 
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2022&mode=showInstructions&tab_label=Instructions
![capture1](https://cloud.githubusercontent.com/assets/17168500/17116398/7830130c-526c-11e6-8fcf-0c96e5b12881.JPG)

**Even though I know I have a user account:** 
![capture2](https://cloud.githubusercontent.com/assets/17168500/17116439/a8603110-526c-11e6-8d61-cf3ed7868028.JPG)

**As an RC, I can see that this person is in the system:**
![capture3](https://cloud.githubusercontent.com/assets/17168500/17116444/b0f915ee-526c-11e6-803f-cb6690229e8c.JPG)

**And added to the Fellowship Application Invite PI's list:**
http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=invitedPIListing&record=2018&phaseid=2019&tab_label=Fellowship Application Setup
![capture4](https://cloud.githubusercontent.com/assets/17168500/17116449/b8e91c86-526c-11e6-8284-96b667a39db2.JPG)

**Why can't this user access the fellowship application?**

**Comment by ecsion** [comment]
fixed.
