### ISSUE TITLE
Support Letters Request By Date

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#290]
As an applicant applying to a fellowship, using the Support Letters custom form, the "Request By" date allows me to put in a date that is past the application deadline. This should not be an option as it could be a point of confusion for the the letter writer. (Support letters submitted past the deadline at Oregon Sea Grant disqualify the application). The deadline also specifies a time (5:00 pm), which you cannot specify in the request by date. 
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2022&mode=showTasksData&&tab_label=Support Letters&questionid=1266
![capture](https://cloud.githubusercontent.com/assets/17168500/17116711/d042799e-526d-11e6-9373-0e9724553585.JPG)

**Comment by ecsion** [comment]
Mary, this can be done but will take some time, For now, please advice the applicant to use a date that is a day or 2 earlier than the deadline. In future we will allow the applicant to specify a date & time for document request.

**Comment by marypleasant** [comment]
Hi, I am just checking back in on this change request. It was still causing confusion in our latest fellowship competition. Is there a timeline for when it will be fixed?

**Comment by ecsion** [comment]
We are working on this  ometime early next week

**Comment by ecsion** [comment]
done.
