### ISSUE TITLE
Support Letters Instructions

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#291]
**As an RC, when writing instructions in the Support Letters custom form, I can only write instructions for the letter writer and not the applicant.** 
http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=Detail&record=1266&viewname=213&showList=RFP&show_retire=
![capture](https://cloud.githubusercontent.com/assets/17168500/17116868/8b2da134-526e-11e6-8a38-2267c31e731f.JPG)

**As an applicant to the fellowship, I see the instructions to the letter writer (not instructions for the applicant) under the Instructions tab.** 
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2022&mode=showInstructions&tab_label=Instructions&tab_label=Instructions
![capture1](https://cloud.githubusercontent.com/assets/17168500/17116973/fdd1d1e2-526e-11e6-9f8c-6d1e268940bc.JPG)

**And no instructions can be added to the Support Letters page for the applicant:**
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2022&mode=showMultiQuestionStem&QuestionId=1266&tab_label=Support Letters&tab_label=Support Letters
![capture3](https://cloud.githubusercontent.com/assets/17168500/17116982/04e75916-526f-11e6-8779-3fd2ea549101.JPG)

**Can we make the instructions to the letter writer only appear to the letter writer, and be able to write instructions for the applicant on the Support Letters page?**

**Comment by ecsion** [comment]
Mary, currently we don;t have inline instructions for Document Request for the applicant. We can do this but this will take some time, For now, you will have to put it in general instructions (as I see you have done). We will however capture this change request and get it done in the next build.
