### ISSUE TITLE
PI cannot access project documents

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#292]
A PI (Eli Meyer) that reported to us using our report call, said that documents under Project Info were not accessible to him. He got a permissions error when he tried to access them. 

Project documents from Project R/HBT-19-PD M/A-02 should have been available to him. Here are the project documents we wanted him to be able to access:
http://eseagrant.oregonstate.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=681&mode=showRelatedList&tab_label=Project%20Documents
![capture](https://cloud.githubusercontent.com/assets/17168500/17117301/64be5758-5270-11e6-9372-273212df85d1.JPG)

And the report call we sent him:
![capture1](https://cloud.githubusercontent.com/assets/17168500/17117315/76d6ada0-5270-11e6-953a-8c3c707c6195.JPG)

**Comment by ecsion** [comment]
fixed.
