### ISSUE TITLE
Project Information Request

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#293]
Hi,

Under the "Projects" tab, and "Project Information", can we have the ability to enter and edit "Award and Sponsor Information"? It would be great to able to capture this information on the post award side of things. 

I'm not sure how to add to the drop down menu and it doesn't save anything: 
![screen shot 2016-07-28 at 9 52 14 am](https://cloud.githubusercontent.com/assets/17860279/17221534/088f39da-54a9-11e6-8f1f-218e5907e00e.png)

Thanks,

Miho

**Comment by ecsion** [comment]
Please got to pick list editor and add values for Primary Award, Primary Sponsor & SG Classification. Then you have values to pick from.

http://eseagrant2.ucsd.edu/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9
