### ISSUE TITLE
Projects: Budget Worksheet and 90-4 Form Request

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#294]
Hi,

Is there a way so that the budget worksheets and 90-4 form tabs from the proposal side show up under projects? This would be helpful to track budget changes once the project is funded and we can keep detailed budget information without needing to go back into proposals.

Thanks,

Miho

**Comment by ecsion** [comment]
Hi Miho, This is a change request and can be done but will take some time. We will include this in the next build. I am closing this for now but we have it recorded as a change request.
