### ISSUE TITLE
Panel & Peer Review Formatting

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#295]
Hi,

Is there a way so that reviewer comments won't be one big paragraph when they submit? 
Can they use basic coding so that they can at least create paragraphs?

It's hard to read and our reviewers sometimes break their sections up based on the evaluation criteria.

Thanks,

Miho

**Comment by ecsion** [comment]
We can provide HTML editor but this change will take some time.

**Comment by ecsion** [comment]
fixed, please check.
