### ISSUE TITLE
CASG: Inviting PI Issue (Issue #280)

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#296]
Re: Issue #280.

I use a mac - Safari; Version 9.1.2 (10601.7.7) and am still having the same issue. 

A few examples: 
When click "select C
http://eseagrant2.ucsd.edu/index.php?module=Projects&relatedModule=People&view=Detail&record=17206&mode=showRelatedList&tab_label=Co-Investigator

![screen shot 2016-07-29 at 4 31 35 pm](https://cloud.githubusercontent.com/assets/17860279/17266214/517e9c7e-55aa-11e6-98cc-701ac63f5a93.png)

And for adding a panel reviewer: 
http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=13703&phaseid=13704&tab_label=Full-Proposal%20Setup&listtype=invitedpanel

![screen shot 2016-07-29 at 4 32 57 pm](https://cloud.githubusercontent.com/assets/17860279/17266208/4698d98c-55aa-11e6-95f0-4d86075f8f27.png)

If I wait half a day or so, it usually fixes itself.
But it would be nice if it worked consistently and thought you should know. 

Thanks,

Miho

**Comment by ecsion** [comment]
We are having difficulty reproducing this issue.  If we can nail when this bug happens, it will help us to understand and fix the issue faster.

**Comment by ecsion** [comment]
Miho, we are closing this issue for now. Please reopen if you are still experiencing this issue.
