### ISSUE TITLE
Panel Review Request: Email Template

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#297]
Hi,

The "RFP - Panel Review Request" email template is missing a comma after the person's name (Dear NAME):

![screen shot 2016-08-01 at 10 02 09 am](https://cloud.githubusercontent.com/assets/17860279/17302070/3d61ab1a-57cf-11e6-9990-b003d3923cd3.png)

Here's the link: http://eseagrant2.ucsd.edu/index.php?module=EmailTemplates&view=Detail&record=26&type=AutoSystemEmails

And the email body:

Dear Steve Rumrill

This email notification is to inform you that Panel Review for 2017 Special Focus Awards ,   Full-Proposal phase is now open.

Click  http://eseagrant2.ucsd.edu/operations.php?action=panel_reviewer&guid=OEQ1ODAwRUYtRjQ5QS00RThFLTg1QzUtMUUyNDRBMzhBQjYx&exuti=Mjc5MTM= to submit your review. This is your personalized link for the panel review task. You may access this link till the deadline to edit your reviews. You will receive a confirmation email each time you submit your reviews.

Sincerely,

Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant 
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160

--

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, we have now given you ability to edit templates. Go to the dropdown by your name on top left and edit templates. Also added coma.
