### ISSUE TITLE
Data Migration: ELWD Missing in Tools, Technologies, Information Services

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#30]
The 2014 reports should include a field about ELWD (yes/no field) - but that does not appear to be there for any of them. See screenshot of eSG example.

![screen shot 2016-02-18 at 11 58 20 am](https://cloud.githubusercontent.com/assets/17168836/13156686/97854188-d638-11e5-9f0a-ca9ff578f39a.png)

**Comment by ecsion** [comment]
Please provide the sql table name and file name in the old sergeant system so we can map.

**Comment by mgduke** [comment]
Filename:  rep_tech.php
MySQL table:  rep_tech

**Comment by ecsion** [comment]
fixed.
