### ISSUE TITLE
SG Classifications entered in Picklist Editor don't show up for user

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#300]
SG Classification Values entered under RFP Proposal in the Picklist Editor do not show up to the user when developing a proposal in an open RFP. Please correct this.

**Comment by ecsion** [comment]
We have some corrections to css and hoping that this error is fixed. Please check 
if issue is fixed and if  not fixed, send us a screenshot along with the platform (pc, mac etc), browser (firefox, chrome etc.) and browser version so we can investigate further.

**Comment by alandesbonnet** [comment]
fixed. thank you.
