### ISSUE TITLE
PI/User ability to add "new" budget years

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#301]
when a PI/user clicks "budgets" when developing a proposal, they are given the option to create a new budget year ---- users SHOULD NOT have the option of creating new budget years as they MUST follow the budget year associated with the RFP created by the SG ADMIN. Please remove this option for Rhode Island Sea Grant. Thank you.

**Comment by ecsion** [comment]
fixed.
