### ISSUE TITLE
Support Letters

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#302]
Hello,
The Support Letters custom form worked for most, but not all cases, for our Fellowship Application. This is somewhat confusing as they are both for the same application and same RFP (http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&record=2159). 

**Request for letter one went out successfully (the link works):**
![support letter 1](https://cloud.githubusercontent.com/assets/17168500/17682725/60563f9e-6302-11e6-8d29-9b6cd1fbe1b1.JPG)

Dear Michelle McKinley,

Giselle Shmitz has submitted your name in relation to the Oregon Sea Grant Legislative Fellowship Application.

 Please click on the following link  http://eseagrant.oregonstate.edu//operations.php?action=responseform&guid=0B177AB0-4388-4E3C-A074-2EC2865592AA  to complete the request. We will need your input by .

Let me know if you have questions.
 Best regards,

**But Letter 2 was not successfully requested, (link leads to a page that does not have the Support Letters instructions or upload option):**
![support letter 2](https://cloud.githubusercontent.com/assets/17168500/17682761/a189f9ec-6302-11e6-9622-55df2c8b6498.JPG)

Dear Ashley Erickson,

Giselle Shmitz has submitted your name in relation to the Oregon Sea Grant Legislative Fellowship Application.

Please click on the following link  http://eseagrant.oregonstate.edu//operations.php?action=responseform&guid=42D5195E-E524-46AF-8F1D-F6D183D87842  to complete the request. We will need your input by 2016-08-15.

Let me know if you have questions.

Best regards,
Mary Pleasant

**Comment by ecsion** [comment]
we have manually fixed this. If this happens again, please note down the screen flow (steps) to reproduce this issue.
