### ISSUE TITLE
Cannot assign role to reviewer or panelist

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#304]
as eSG ADMIN, I am not being given the option to assign a role of "panelist" or "reviewer" to users. Please correct this so that reviewers can be assigned to proposals.

**Comment by ecsion** [comment]
Current eSeagrant supports 3 roles: SG Admin, SG Staff & SGAdministrator. Panelists, reviewers & 3rd party document providers do not have an account in eSeagrant. They get a coded link to do some work. You amy tag them using eSeagrant History (for ease of search), however, there is not role associated with the panelist, peer reviewer or document provider function.
