### ISSUE TITLE
investigators associated with incorrect "my funded projects"

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#306]
as investigators are given access to their eSG accounts, and assigned eSG History and Role of "investigator" they are being associated with, and allowed access to, incorrect project data.
For instance, below screen shot is the correct data to be associated with the investigator, as I see it under People as eSG ADMIN

![screen shot 2016-08-16 at 1 28 18 pm](https://cloud.githubusercontent.com/assets/18398763/17709224/4d71cae2-63b6-11e6-9a34-2b10baa1724f.png)

The screen shot below shows what the investigator sees under My Funded Project when they login to eSG. The project shown are not correct. They could DELETE the projects that are not theirs, removing them from the eSG system creating significant chaos and loss of data. This MUST be corrected.

![screen shot 2016-08-16 at 1 28 56 pm](https://cloud.githubusercontent.com/assets/18398763/17709329/ac464534-63b6-11e6-8aa5-b5ab99159c1d.png)

**Comment by ecsion** [comment]
fixed.
