### ISSUE TITLE
Pick list Editor ordering does not remain as saved

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#307]
in the Picklist Editor I entered all Sea Grant Classification codes, then saved the ordering so that they were arrayed numerically from least to highest. Upon checking them today, they are no longer ordered numerically. How can they be reordered as desired without having to individually select and drag a rather long list? Please numerically arrange them as they were originally done and saved. Thank you.

**Comment by ecsion** [comment]
Currently the only way to make sorting changes is to drag the items to the correct order. We can work to simplify this for large lists but this is currently not in scope. Adding it to change request and closing.
