### ISSUE TITLE
WSG: Urgent Data Loss Issue—Impacts & Accomplishments Form

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#308]
When editing an Impacts and Accomplishments record, previously selected Goals disappear and must be reselected before saving to prevent data loss. This occasionally happens with the Secondary Focus Area as well. <Visualize sad emoji here>

As example instance, see:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=20760&mode=showMultiQuestionStem&QuestionId=17403&tab_label=Impacts%20and%20Accomplishments

We clicked edit, the "Aquaculture operations and shellfish harvests are safe…" goal becomes deselected, and if we then Save the record without reselecting this goal, we lose this data.

**Comment by ecsion** [comment]
fixed, please check.
