### ISSUE TITLE
Adding People

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#309]
I am having a hard time adding people to the system.  Are there instructions?  We haven't used our system much and need to get it set up.

**Comment by ecsion** [comment]
Instructions are here:
[eSeaGrantInstructionsManual-Sept7-2016-draft1.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/467490/eSeaGrantInstructionsManual-Sept7-2016-draft1.pdf)
