### ISSUE TITLE
PI Ability to Delete Projects

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#310]
At present, Investigators may select DELETE as an ACTION option (see screen shot). Investigators SHOULD NOT have the ability to delete funded projects; ONLY the SG ADMIN should have the ability to delete a funded project. Please remove the ability for Investigators to delete projects. Thank you.

![screen shot 2016-08-22 at 11 22 11 am](https://cloud.githubusercontent.com/assets/18398763/17860311/06482d92-685b-11e6-81e4-d7718372b57c.png)

**Comment by ecsion** [comment]
fixed.
