### ISSUE TITLE
Staff ability to edit/save Report Call Instructions

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#311]
At present, users with a role of "STAFF" have the ability to edit and save instructions for reporting calls (see screen shot)
![screen shot 2016-08-22 at 1 40 13 pm](https://cloud.githubusercontent.com/assets/18398763/17865520/e7b2d344-6870-11e6-96fb-f6e0bd990089.png)
.  Staff SHOULD NOT have this ability; ONLY the eSG ADMIN should have the ability to edit and save reporting instructions. Please change this permission. Thank you.

**Comment by ecsion** [comment]
no longer used
