### ISSUE TITLE
eSG ADMIN "only" check box not limiting access

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#312]
I created a Custom Reporting Form (Impacts & Accomplishments), making one input open to all users, and then adding several other input frames and checking the box for "eSG ADMIN ONLY". The custom form works correctly for investigators, but allows user = staff to access those items marked for eSG ADMIN ONLY access (see screen shot). Please correct this user privilege conflict. Thank you.

![screen shot 2016-08-26 at 11 35 07 am](https://cloud.githubusercontent.com/assets/18398763/18011104/a126976c-6b81-11e6-9146-6b178f4f71ba.png)

**Comment by ecsion** [comment]
This is fixed. Please check. If you still have an issue, please reopen and provide screenshot and link.
