### ISSUE TITLE
Wrong Sea Grant Program in Tab Title

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#313]
When a user = Investigator is working on a Budget Worksheet, the Tab title says "MIT Sea Grant College Program" but should say "Rhode Island Sea Grant College Program" [see screenshot]

Thank you for correcting this.

![screen shot 2016-08-30 at 9 13 52 am](https://cloud.githubusercontent.com/assets/18398763/18090802/74063650-6e94-11e6-8a0b-1ea412f23cce.png)

**Comment by ecsion** [comment]
fixed.
