### ISSUE TITLE
Wrong Sea Grant Program in 90-2 Form text

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#314]
for user = Investigator, text in the 90-2 for says "California Sea Grant" and should say "Rhode Island Sea Grant" [see screenshot]  Thank you for fixing this.

![screen shot 2016-08-30 at 9 25 20 am](https://cloud.githubusercontent.com/assets/18398763/18090868/b135e066-6e94-11e6-83d3-bace92cc8bd0.png)

Also, Rhode Island Sea Grant does not use much of this information, and most of the rest should be entered ONLY by user = eSG ADMIN. I would prefer if the 90-2 screen for user = Investigator ONLY request input of keywords.

**Comment by ecsion** [comment]
We have added keywords on the main page of the proposal. 90-2 form should no longer be used for new RFP. Also you can now change instructions on locked form.
