### ISSUE TITLE
Removal of unused & inappropriate input fields

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#315]
for user = Investigator, in the SG Classification & Focus Area input screen [see screenshot], the AWARDS information should ONLY be completed by user = eSG ADMIN (investigators have no idea what award number will be associated with their proposal; this can only be completed later in the process by the eSG ADMIN) and I request that this field be removed or inactivated for user = Investigator.

Also, Rhode Island Sea Grant does not Affiliation Codes, so I request this field be removed to avoid confusion. Thank you.

![screen shot 2016-08-30 at 9 05 26 am](https://cloud.githubusercontent.com/assets/18398763/18091204/df419f58-6e95-11e6-91f0-ae104135808e.png)

**Comment by ecsion** [comment]
Alan, we have added seperate forms for Focus Area and SG Classifications. Please use these custom forms,.
