### ISSUE TITLE
Incorrect IDC rates / how to customize IDC rates

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#316]
The indirect cost rates (IDC) on the user = Investigator budget worksheets are incorrect for the Rhode Island Sea Grant program. How / where does the eSG ADMIN access these criteria to set them to current/correct rates? Thank you. 

Also, Rhode Island Sea Grant does not have a "default" indirect cost rate, [see screenshot] and I would like to have the "Set Default SG Rates" button removed from the budget worksheet for our program. Thank you.

![screen shot 2016-08-30 at 9 51 58 am](https://cloud.githubusercontent.com/assets/18398763/18091823/04c17a6c-6e98-11e6-90c6-e3371dcf624e.png)

**Comment by ecsion** [comment]
Please provide the IDC rates and we will program them for you.

**Comment by alandesbonnet** [comment]
Please use 0.535 (53%) and the default institutional rate.  Please use 0.535 (53%) as the default Sea Grant rate as well. 
Thank You.


Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
fixed.
