### ISSUE TITLE
Indirect Costs Calculate Incorrectly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#317]
the budget worksheet is incorrectly calculating several values (see screenshot). Please correct this so that budgets created for Rhode Island Sea Grant calculate correctly. Thank You.

![screen shot 2016-08-30 at 10 39 49 am](https://cloud.githubusercontent.com/assets/18398763/18094191/97454974-6ea0-11e6-8018-90fd086f9447.png)

**Comment by ecsion** [comment]
fixed. If there is still an issue, please reopen and provide url of the sheet your re working on.

**Comment by alandesbonnet** [comment]
here is the URL

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=MzgyNg==&id=141

it still inserts 0.065 for default IDC rates.

Alan Desbonnet
Assistant Director

**Comment by alandesbonnet** [comment]
I’m sorry, but this is still not working correctly. Here is the URL

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=MzgyNg==&id=141

clicking either “set default rates” button inserts 0.065 NOT 0.535
 
Alan Desbonnet
Assistant Director
