### ISSUE TITLE
PDF budget not identical to eSG worksheet

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#318]
as user = SG ADMIN, the values shows in the created PDF version of the budget worksheet do not match those in the actual worksheet (see screenshot showing mismatched values for Personnel). This MUST be corrected.

![screen shot 2016-08-30 at 11 16 00 am](https://cloud.githubusercontent.com/assets/18398763/18095297/885aab9e-6ea4-11e6-8a17-66e6c7006711.png)

**Comment by ecsion** [comment]
fixed. Please check and reopen if you still have issues.

**Comment by ecsion** [comment]
Also please add url so we can crosscheck.
