### ISSUE TITLE
PI inability to create PDF of budget worksheets

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#319]
At present user = Investigator is unable to create a PDF version of their budget worksheet and budget justification. The option to create a PDF of the budget worksheet & justifications must be available as Investigators needs a PDF to bring to their respective administrators for approval and sign off. Please provide an option for user = Investigator to create such a PDF.

**Comment by ecsion** [comment]
done.
