### ISSUE TITLE
PDF of eSG Budget Worksheet is incomplete

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#320]
the PDF created of the budget worksheet is missing several key values needed for review at the university level. Please see the screenshot below pointing out the information that MUST be included on a PDF of the budget worksheet. Thank You for correcting this.

![screen shot 2016-08-30 at 12 02 54 pm](https://cloud.githubusercontent.com/assets/18398763/18096986/1c5b8fd4-6eaa-11e6-83ca-8cb5a0a3a3bd.png)

**Comment by ecsion** [comment]
fixed, please check. We are closing this issue. Please reopen if the issues is not resolved.
