### ISSUE TITLE
For V.2 of eSG Publications Reporting

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#322]
We need to simplify the PI reporting page for publications.  MY Communicator wants only a Citation field, two Y/N toggle questions (Open-access? and Peer-reviewed?) , the embargoed? date field (as requested in another issue by kdez), and then a PDF upload button.  That's it.
Instructions for a "full citation" would be spelled out to include all possible info about any article or document (e.g., include DOI)
This format has to be agreed on by all the Sea Grants as Publications is a Standard Module.

**Comment by mcbridec** [comment]
Oregon Sea Grant agrees with this change (Cathy, Mary and Sarah).
