### ISSUE TITLE
Non-funded Proposals Remain Open for Editing?

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#324]
The set CLOSE date/time for an RFP has long since past (see screenshot below).

![screen shot 2016-08-31 at 12 09 06 pm](https://cloud.githubusercontent.com/assets/18398763/18136812/07fb7a0c-6f74-11e6-8e03-0b3ea37fa5b7.png)

However, when I look at a non-funded proposal submitted to that RFP, I see a "Due Date" of 31 Jan 2018 (see screenshot below), which is actually the Project End Date for funded projects. 

![screen shot 2016-08-31 at 12 09 34 pm](https://cloud.githubusercontent.com/assets/18398763/18136874/4e6295e8-6f74-11e6-9c8f-d36109c32b5b.png)

This makes no sense and should be "turned off." Non-funded proposals should be able to be toggled to an OFF position so that they are both non-responsive, as well as not showing that there is still time left to do "something" with the proposal. Since the eSG ADMIN does not have the capability of seeing passwords so they could login as an investigator, I have no way of knowing if the applicant still has access to a "live" proposal.  And they should not. 

This is confusing, as well as potentially damaging. Non-funded proposals should be completely shut down once the RFP is closed, and they most certainly SHOULD NOT be tied to the Project End Date for funded projects. This needs to be corrected.

**Comment by ecsion** [comment]
fixed. Please check and reopen if this is still an issue.
