### ISSUE TITLE
90-2 Mandatory on RFP

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#326]
Hi there,

In setting up the RFP for full proposals, the 90-2 is mandatory. We would like to have the option to not include this form. http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=2335&phaseid=2336&tab_label=Full-Proposal%20Setup
![capture](https://cloud.githubusercontent.com/assets/17168500/18148289/8754fc10-6f8d-11e6-976b-416b8870adbd.JPG)

**Comment by MASGCleist** [comment]
I was going to bring this up too.  Thanks!  
While we do require a 90-2 for FPs we really only want the Objectives, Methodology and Rationale, maybe keywords too. Much of the other parts of the form are redundant.  I'm going to suggest we just ask for those in addition to a cover form which would give most of the other information.

**Comment by ecsion** [comment]
done.
