### ISSUE TITLE
Incorrect information on Budget Worksheet

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#327]
the budget worksheet incorrectly says "(Default Rates = MIT)" [see screenshot]
it should state "(Default Rates = URI)"  

![screen shot 2016-09-01 at 8 54 24 am](https://cloud.githubusercontent.com/assets/18398763/18168234/c35802b2-7022-11e6-815c-2f53c69bb587.png)

**Comment by ecsion** [comment]
Please provide URI SG & INST rates and we will program them for you.

**Comment by ecsion** [comment]
Removed -- (MIT)
