### ISSUE TITLE
user = investigator option to "Add Budget Duration" issue

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#328]
user = investigator has the option to add new budget durations [see screenshot], and should not have. ONLY the eSG ADMIN should have the privilege to create new, or alter existing, budget durations. Please remove this privilege for ALL users except the eSG ADMIN. thank you.

![screen shot 2016-09-01 at 10 37 35 am](https://cloud.githubusercontent.com/assets/18398763/18174465/a7efff98-703b-11e6-8112-c43515c02ab6.png)

**Comment by ecsion** [comment]
removed.
