### ISSUE TITLE
"Select Duration" dropdown not working

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#329]
the "Select Duration" dropdown, which I presume should allow options to select a single or multiple budget years [see screenshot], is not providing any options. This should be corrected.

![screen shot 2016-09-01 at 10 44 13 am](https://cloud.githubusercontent.com/assets/18398763/18174687/6661c312-703c-11e6-89be-e7552970f271.png)

**Comment by ecsion** [comment]
fixed.
