### ISSUE TITLE
Errant "Annual" Report

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#330]
As user=investigator, I see two open Reports for Program Administration, one having no call title and that contains no information in the report [see screenshot below]

![screen shot 2016-09-07 at 8 34 19 am](https://cloud.githubusercontent.com/assets/18398763/18312120/0b05e75c-74d6-11e6-9777-63ff3751cc39.png)

As user=eSG ADMIN, for user=investigator=Nixon, I do not see the report (that is not associated with a reporting call). I also note in the upper right corner of screenshot [below] it shows 1 to 12 of 13 possible records, but the 13th cannot be accessed.

![screen shot 2016-09-07 at 8 28 52 am](https://cloud.githubusercontent.com/assets/18398763/18312257/c9a53a64-74d6-11e6-9c5f-e5ad612527d5.png)

Is #13 the "unattached" Program Administration" report? Can this be accessed to be deleted? As user=investigator it cannot be deleted, and as user=eSG ADMIN it cannot be accessed. It makes no sense to have data in a database that cannot be accessed, especially by the ADMIN user.

Please correct this so user=eSG ADMIN can access this report, and delete it.
Thank You.

**Comment by ecsion** [comment]
fixed.
