### ISSUE TITLE
Incorrect Information on "Permission Denied" screen

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#331]
as user=staff, on the Projects tab [see screenshot below], 

![screen shot 2016-09-07 at 1 36 21 pm](https://cloud.githubusercontent.com/assets/18398763/18322390/6cf52df4-7500-11e6-9d4c-55f96a195245.png)

when either "Add Document" or the file/project is clicked on, the screenshot below is called up.

![screen shot 2016-09-07 at 1 36 34 pm](https://cloud.githubusercontent.com/assets/18398763/18322403/7d9f6444-7500-11e6-82ea-ca2b11942a47.png)

Please replace MIT Sea Grant with Rhode Island Sea Grant, or simply remove the name completely and simply have the "Permission denied" screen pop up.

Thank You

**Comment by ecsion** [comment]
fixed.
