### ISSUE TITLE
Report Narrative Does Not Load/Open

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#332]
as user=staff [see screenshot below], in Reports tab, when the Narrative file PDF is clicked, a blank screen is generated, but no file is opened. This should be corrected.

![screen shot 2016-09-07 at 1 50 43 pm](https://cloud.githubusercontent.com/assets/18398763/18322782/774ee1d0-7502-11e6-92a9-666ce932dddb.png)

Thank You

**Comment by ecsion** [comment]
fixed.
