### ISSUE TITLE
WSG: Reporting sidebar menu custom sort?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#334]
Deepak: we thought that at some time in the past we were able to determine the order of all the reporting models that the user would see in the left-margin vertical menu, but we see no way to reorder at present. Are we imagining that this was ever possible (Kate's convinced we used to be able to do this)? If so, would it be possible to enable us to sort all the models to our preference (i.e., not alphabetically sorted; it would be by context as determined by the RC).

**Comment by ecsion** [comment]
done
