### ISSUE TITLE
WSG: Reporting module with one question not use popup?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#335]
Deepak: We're wondering if there's any way to avoid having to use popups to answer reporting questions when there will only be one answer for a given module. I've gotten several fairly strong complaints about this (basically want to minimize # of clicks to accomplish tasks). We understand that the popups are the logical solution when there can be multiple answers to a given question.

**Comment by ecsion** [comment]
done
