### ISSUE TITLE
CASG: URGENT Delta Science Fellowship RFP - Budget Worksheet (Project Duration Issue)

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#337]
Hi,

The option to select a budget duration for the Delta Science Fellowship is not showing up for some PIs.  I'm not sure how to duplicate this issue as I was able to do it in the backend accessing their proposal, but please look into this. Here's their link - 
 
http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=29192&mode=showBudgetListingData&tab_label=Budgets

And what the PI saw: 
[Screen.Shot.2016-09-16.at.4.20.34.PM.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/477841/Screen.Shot.2016-09-16.at.4.20.34.PM.pdf)

Thanks,

Miho

**Comment by mumezawa** [comment]
I can't seem to set the budget durations as an admin in the backend either now. 
We need to at least be able to do one or the other immediately.
http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&record=26012&mode=showDurations&tab_label=Budget%20Periods%20Setup

The budget durations would be 2/1/17 ~ 1/31/2018 AND 2/1/2018 ~ 1/31/2019
Applications are due a week from today. Thank you.

**Comment by ecsion** [comment]
We have temporarily added the ability of the PI to add budget durations. Suggest this be discussed between all participating Sea Grant programs as some do not want PI to be able to add budget duration.
