### ISSUE TITLE
MASGC: New users are not receiving their access password email

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#338]
When a new user attempts to register, they input their name and email address and go through the "I am not a robot" steps then they either receive a blank page or an error. An email with a temporary password is not sent to them to complete their registration. 
![upon attempted registration](https://cloud.githubusercontent.com/assets/22300443/18639854/327210ca-7e5b-11e6-9bab-65dc32f26859.JPG)

If an administrator logs in we can see the attempted login but with "Access denied" on their account status (see highlights):

![access denied at login capture](https://cloud.githubusercontent.com/assets/22300443/18640036/f3a3b8b6-7e5b-11e6-9f59-e5284eb445f7.JPG)

Users have been able to attempt to register, fail, but get in by selecting "Forgot Password?"

**Comment by ecsion** [comment]
fixed.
