### ISSUE TITLE
MASGC: Invitation email shows the wrong "from" email address

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#339]
On our email to Invite PIs to apply for a competition, the email shows as coming from "jeckman@ucsd.edu" and not from the appropriate sender.  (an administrator at Mississippi-Alabama Sea Grant).

![eckman invitation to apply fo research rfp 2](https://cloud.githubusercontent.com/assets/22300443/18641450/48d7b3fe-7e62-11e6-8867-a6546d05b3d0.JPG)

Related - the email signature is not from the user and in this particular example the phone number in the signature isn't correct.

![wrong signature and phone number](https://cloud.githubusercontent.com/assets/22300443/18641246/698851fe-7e61-11e6-87f5-f3be865c039f.JPG)
Note that I may have given you the wrong phone number at some point so that is my mistake, but it does need to be updated.

This doesn't appear to be something we can change on our end.  I assume other email templates need to be updated as well.
Thanks.

**Comment by ecsion** [comment]
There was a wrong value entered in smtp configuration. It has been fixed.
