### ISSUE TITLE
MASGC: blank "array" email going out through system

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#340]
Most emails that are generated through eSG are blank and just say "array".  We don't know why because we have had some go through ok.

![sempier arrary email 2](https://cloud.githubusercontent.com/assets/22300443/18641393/075a8762-7e62-11e6-9cc8-2e0ad0370f86.JPG)

**Comment by ecsion** [comment]
It appears like  a user error. Someone changed the "Center where used" field which should not be changed to system email templates. We have now removed that option for SG Administrators. 

Everything should be fixed now. Please try and log another issue if you are still having problems.
