### ISSUE TITLE
NCSG:  Publish RFP

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#343]
The RFP section has changed since I was on the planning committee, how do we publish a RFP for anyone to view?

**Comment by ecsion** [comment]
Go to phase setup  - pre proposal setup or full proposal setup. Then click on Step 2 - Set Access & Open/Close Dates. Choose open to all. This will make the RFP open to all Investigators who have a login account on the eSG system.
