### ISSUE TITLE
drop down menu difficult to see / limited view

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#345]
as user = SG ADMIN, in Projects module, Edit Project Information [see screen shot below], the SG Classification drop down menu is difficult to use as it shows only 2 or 3 options at a time. Is it possible to make the drop down open towards screen top (rather than screen bottom as at present) so that more options are visible? This will make this much easier to use. Thank you.

![screen shot 2016-09-22 at 10 50 09 am](https://cloud.githubusercontent.com/assets/18398763/18754287/2286a204-80b6-11e6-89cc-7fe5003cd7da.png)

**Comment by ecsion** [comment]
fixed.
