### ISSUE TITLE
Drop down menu items not visible

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#346]
as user = SG ADMIN, in Projects module, edit Project Information, the drop down menu for Secondary Award is not wide enough to show the entire entry and therefore the correct value cannot be selected. Please correct this so that the entire drop down value is visible. Thank you.

![screen shot 2016-09-22 at 10 52 10 am](https://cloud.githubusercontent.com/assets/18398763/18754610/48cba5d0-80b7-11e6-86e0-73793a17a714.png)

**Comment by ecsion** [comment]
fixed.
