### ISSUE TITLE
"Select Proposal for Funding" command does not complete itself

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#347]
as user = SG ADMIN, in the RFP module ---> Full Proposal Setup ---> Select Proposal for Funding ---> Promote to Project.  Once the command is issued to Promote to Project, black dots circulate at screen top while processing occurs. However, the processing is never completed until the user quits eSG then logs back in. The command Promote to Project is completed correctly, but the process should end without the user having to log out then log back in. This should be corrected. Thank you.

**Comment by ecsion** [comment]
fixed.
