### ISSUE TITLE
MASGC: blank "array" email going out through system RESUBMISSION

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#348]
In attempting to invite PIs, some selected receive the blank "array" email.
This is directly related to the recently closed issue: See issue #340 

The email went to one recipient successfully.

![email was successful to steve](https://cloud.githubusercontent.com/assets/22300443/18845245/8ddd4fe8-83e6-11e6-99d2-1882aebf7888.JPG)

But others received just a blank email with the word "Array" in the text.

![email wasnt successful to ladon](https://cloud.githubusercontent.com/assets/22300443/18845453/62d31e80-83e7-11e6-98f6-c2b6e322700f.JPG)

![email wasnt successful](https://cloud.githubusercontent.com/assets/22300443/18845462/67d39252-83e7-11e6-9c76-5e34865e1021.JPG)

Thank you!

**Comment by ecsion** [comment]
fixed. Please reopen if you still have issues.

**Comment by MASGCleist** [comment]
I'm not sure how to re-open an issue.  
This is still a problem. We used the user templates like you suggested and it still sends out "Array" emails.
