### ISSUE TITLE
Adding Project Documents 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#352]
Hi,

Are project documents that are uploaded in the backend accessible to project PIs if they log-in? If so, what's the best the way to archive internal documents without PIs being able to see it?

Example:

http://eseagrant2.ucsd.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=30543&mode=showRelatedList&tab_label=Project%20Documents

![screen shot 2016-10-03 at 1 44 04 pm](https://cloud.githubusercontent.com/assets/17860279/19053372/8ecdd48e-896f-11e6-8d3e-ccc29adde45a.png)

Can PIs see project documents on their end? We would prefer that they didn't. 

Thanks,

Miho

**Comment by mcbridec** [comment]
Great question

**Comment by ecsion** [comment]
Currently PI will be able to see all documents loaded in projects. We can allow for some documents to  be not viewable by PI by that will require coding change and will be change request.
