### ISSUE TITLE
CASG: URGENT Delta Science Fellowship Review Panel

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#353]
Hi,

I'm setting up a review panel, but accidentally selected "5 Star Rating with Criteria (Preview)" rather than "5 Star Rating" and now I can't change it.  Can you please change it for me or tell me how to do it? 

Link: http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=26012&phaseid=26013&tab_label=Fellowship%20Application%20Setup&listtype=invitedpanel

![screen shot 2016-10-03 at 3 51 04 pm](https://cloud.githubusercontent.com/assets/17860279/19056971/8975b2ce-8981-11e6-8acc-d4ce908d27b8.png)

Also, is there a way to delete or edit panel members? 

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.
