### ISSUE TITLE
CASG: Name Change

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#354]
Hi,

I recently got married and changed my name from Miho Umezawa to Miho Ligare.
It seems like some of the name changes have already taken place, but can you make sure it's consistent throughout the whole system? My new email is mligare@ucsd.edu.

Example:

![screen shot 2016-10-04 at 11 42 30 am](https://cloud.githubusercontent.com/assets/17860279/19087666/b81dceb2-8a27-11e6-8003-031d20535403.png)

Thank you,

Miho

**Comment by ecsion** [comment]
done. Please check and let us know if you still have any issues.
