### ISSUE TITLE
MASGC: "Download Zip" color

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#355]
You mentioned in our meeting that we should remind you to make the "Download Zip" links blue so we can tell they are hyperlinks.

http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=439&phaseid=440&tab_label=Pre-Proposal%20Setup

**Comment by ecsion** [comment]
fixed.
