### ISSUE TITLE
MASGC: 90-2 Form not allowing edits

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#357]
Based on our conversation I think we are supposed to be able to mark the fields on the 90-2 as "mandatory" or "SG Admin Access Only" but I can't seem to get it to work.

http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Detail&record=1 

![90-2 form entry](https://cloud.githubusercontent.com/assets/22300443/19131455/16d90ec4-8b15-11e6-9cc2-b3290b33b588.JPG)

When I hit edit I can only change the instructions field:
http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Edit&record=1&showList= 

![90-2 form ed](https://cloud.githubusercontent.com/assets/22300443/19131505/415b8f6e-8b15-11e6-8ad9-b76b97f82b51.JPG)

**Comment by ecsion** [comment]
fixed.
