### ISSUE TITLE
MASGC: 1969 Budget Duration

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#358]
It seems that when we set the budget duration on the RFP the system wants to revert to the year 1969 after a period.  I guess it wants to re-live the _Summer of _Love__
I can't seem to pinpoint when it happens, though. It seems that when we set it at first it will be correct for a while and then it just (seemingly) randomly reverts back to December 1969.

http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&record=439&mode=showDurations&tab_label=Budget%20Periods%20Setup

![1969 budget rfp](https://cloud.githubusercontent.com/assets/22300443/19131978/337746b6-8b17-11e6-90cf-20ee78590dba.JPG)

It evidently does the same for the PI in the budget section and I have that link too:

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=446&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets

![1969 budget pi](https://cloud.githubusercontent.com/assets/22300443/19131889/e153cf80-8b16-11e6-8639-5bcff4ec068e.JPG)

**Comment by ecsion** [comment]
We believe this issues was happening only when the date was entered in the incorrect format, i.e. not in mm-dd-yyyy. To repent this issue from happening, we have added validation and so this should no longer be happening. Obviously any previous data will have to be re-entered correctly. If you still find this issue, please note steps you took and reopen this bug.
