### ISSUE TITLE
MASGC: Zip files are not what we need for reviewers

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#360]
When we go to retrieve our proposals and package them for review in the "Download Zip" area, it works fine, but does not give us all of the proposal components that we are asking for.

http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=240&phaseid=241&tab_label=Pre-Proposal%20Setup

Here is a screen shot of what we get in the zip:

![what comes in the zip](https://cloud.githubusercontent.com/assets/22300443/19132479/3f36eeb4-8b19-11e6-9ad8-b17d220bb252.JPG)

What we should be seeing is the forms that we selected for our RFP: Cover form, Narrative, budgets and budget justifications, Letters of support and CVs (which are not currently in our RFP forms but will be soon).

On the same subject, it would be very helpful to have the budget pages export as excel files and not PDFs.

**Comment by ecsion** [comment]
Current eSeagrant does not have provision for cover page for Proposals. The work around for this would be to make a custom form for cover page however you won't be able to control the layout.
