### ISSUE TITLE
MASGC: budget sub-award wording

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#361]
Below you will see the question about a “Non-MS-AL investigator.”  Marking yes is the only way to get your budget to show that you have a subaward.  I don’t know why the question just can’t say “Does your project include a subaward?” or something similar.  

http://eseagrant.masgc.org/operations.php?action=budget&proposal_id=NDY4&id=10 

We think it would be easier for everyone if it said:
1. Does this project include a sub-award?  Yes/No

*If yes, please include a separate budget worksheet for the sub-award if the sub-award has been identified. 

![budget subaward wording](https://cloud.githubusercontent.com/assets/22300443/19132913/667ac430-8b1b-11e6-91e9-5942b08d480f.JPG)

**Comment by ecsion** [comment]
Noted, we will chang.,

**Comment by ecsion** [comment]
this form has changed, improvements in v 2.5
