### ISSUE TITLE
WSG: Reporting module with one question not use popup?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#365]
Kate was 
loading PDFs into our eSG and encountered an inconsistency:

If we search Proposals for “2015” and “pre-proposals,” you get 55 pre-proposals. But if we go through the 2015 RFP menu and go to the pre-proposal set up section (where we upload the proposal documents), we only get 53 proposals submitted and one started.

What would be the cause of the difference in # of proposals?

**Comment by ecsion** [comment]
fixed. Marcus will reopen if the issues surfaces again.
