### ISSUE TITLE
VASG Budget Issue

### ISSUE THREAD

**Issue by abigailhils** [ecsion/eSeaGrant-Client-Bug-Tracker#366]
#Budget VASG duration selection

On our Budget Spreadsheet, we would like to create 3 different FY Duration Periods. So far we can only create one selection. 

If possible, could you please advise us on how to do this or fix the budget spreadsheet to list FY2017 (6/1/17-01/31/18), FY2018 (2/1/18-1/31/19), and FY2019 (2/1/19-5/31/19)

Thanks,
Abigail

**Comment by ecsion** [comment]
Abigail, On the RFP detail screen, LHS Navigation has an option for budget period setup. On this screen you can add the budget periods. These durations will then show up on budget sheets dropdown list. See attachment.
![screen shot 2016-10-25 at 8 43 49 am](https://cloud.githubusercontent.com/assets/1612666/19686497/6a630458-9a8f-11e6-977f-d032f1647761.png)
