### ISSUE TITLE
Problem with reading a PDF file on the user side

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#368]
In eSeaGrant RFP call - We upload a PDF document with instructions, which is visible on the Admin side (see first screenshot). The User can view the instruction PDF from the initial page - before the proposal is created (see second screenshot). But once the User has clicked "Start Proposal" the instruction PDF is no longer visible. The link is there, but opens a blank PDF (See third screenshot). 
[OSG RFP PDF Instructions Issue.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/549209/OSG.RFP.PDF.Instructions.Issue.docx)

**Comment by ecsion** [comment]
fixed.
