### ISSUE TITLE
Investigator Navigation Menu Bar is missing Fellowship, RFP, and other Modules 

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#369]
We just received word from one of our investigators that they are no longer able to access the fellowship applications on our eSeaGrant Site (Virginia). I know those options were available on Friday of last week, but they are no longer listed on the Navigation Menu Bar once the investigators log in (please see attached screen shot). 

Please contact us if you have any questions (804) 684 7918.  

Best,
Sam

<img width="1165" alt="screen shot 2016-10-25 at 10 03 24 pm" src="https://cloud.githubusercontent.com/assets/17860369/19711103/49c6591c-9b01-11e6-81b3-a509887494e1.png">

**Comment by ecsion** [comment]
fixed.
