### ISSUE TITLE
WSG: Various issues/questions for RFP module

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#370]
## **Building an RFP**

We discovered the following issues/questions:
1. Open access not working:
   When we build an RFP call that is open to all, it does not show up in "Current Tasks" for investigators. If we invite an investigator, it does, but that defeats the purpose of "open access." It is absolutely critical that we can make calls open and available to anyone who logs into the system without our having to invite them.

**UPDATE:** Deepak said there was a bug which was fixed 10/26/16. Checked again and appears to be resolved.
1. Investigators/Key Personnel oddities:
   a)  We are able to add a 2nd PI — this shouldn't be possible at all.
   **NOTES FROM DISCUSSION**: Deepak suggested removing "PI" from Key Personnel" Type dropdown list. Also, we can emphasize this in the instructions for the given form and in the general instructions. 
   Also, suggested having single PI form (i.e., can't add co-PIs or associates to this form), a new Co-PI form (because it also requires CV), and retain Key Personnel for other positions. 
   On further discussion, however, we concluded that, as long as only the PI acct can be used to login, we see no need to have both Investigators _and_ Key Personnel. Ergo, we suggest eliminating Key Personnel altogether; in Investigator, have dropdown only be Co-PI and, if required by other SGs (we don't need it), associate investigators.
   
   b)  We are able to upload non-PDF files. 
   **NOTE**: This is deliberate to allow flexibility across SGs.
   
   c)  Instructions to upload only PDFs should omit reference to Acrobat as not everyone uses it.
   d)  If we didn't fill in all required fields or if we didn't upload a CV, and click "Save," nothing happens (i.e., it neither saves and closes the window nor gives error explanation).
   **UPDATE**:  Deepak will fix this.
2. Project Summary
       "Funded Project Information" should be revised to "Project Summary".
   **NOTE**: Please see this page:
   http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33179&mode=showProjectSummary&tab_label=Project%20Summary&tab_label=Project%20Summary
3. Budget
   a)  "Add budget worksheet" opens new window—Is this intentional? We ask because, when we save, nothing happens. We have to close that window with no "save" confirmation, return to the preceding page/window, and then refresh before we see that the budget worksheet was in fact saved.
   **UPDATE**: at least have save confirmation popup that instructs user to refresh main budget page to then see new worksheet (or updated pre-existing sheet).
   
   b)  No warning or requirement for budget justifications if they're missing. Being able to fill out worksheet and save without justifications is useful, but we should ALWAYS get a warning that the justifications are incomplete (as was the case in the old eSG). Also, preventing final submission of proposal if justifs are missing would be most helpful.
   **UPDATE**: Old eSG had two different budget worksheets: at preproposal there was no "Justification" component, but we did have this feature in the full proposal. _This is a critical distinction/feature._
   
   c)  Default rates for indirect costs should be set in the admin's RFP setup; investigators shouldn't have this option (but PIs require ability to override default rates and settings).
   **UPDATE**: Please eliminate "set default rate" buttons for SG and Inst , have Ecsion set rate, but there must be two different rates: one for on- and one for off-campus.
   
   d)  "Include 90-4" should not be visible to PI.
   **UPDATE**:  Deepak will remove from PI view.
   
   e)  Do we really need "Grantee" field? Seems confusing/unnecessary. **Please see link and screenshot**:
   http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33196&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets

<img width="920" alt="screen shot 2016-10-27 at 8 42 47 am" src="https://cloud.githubusercontent.com/assets/17168836/19774305/753a72c4-9c21-11e6-9e59-f1b8bdba2f97.png">

```
f)  Need note saying "no commas" for numeric figures in worksheets, or calculation doesn't work.
```

**UPDATE**: Deepak will fix this or, better yet, code to auto-delete commas.

```
   g)      Budget worksheet, question 4: text should be "Is this award to a non-University of Washington investigator?"  See:
```

http://esg.wsg.washington.edu/operations.php?action=budget&guid=3B5597B1-6C4F-4C38-83D1-8C4F8F80AF17&proposal_id=MzMxOTA=
1. Where do Narrative directions get input?
   **UPDATE:** Deep to look into this.
2. When first creating RFP, on "RFP Information," noted that "Click to select" checkboxes for pre-, full and fellowship proposals must be checked before we save this page; after saving, these boxes are grayed out. Seems like asking for trouble: Could we have some kind of alert if they're not checked? After all, what's the point of saving this page if none of the three options is selected?
   **UPDATE:**  Deepak fixed this. We can now check additional boxes, but you can't uncheck a box that was checked before the first save. Also added caveat text above it. We still don't understand why saving should even be possible if no boxes are checked, but we can live with it as is now.
3. Custom forms in the RFP don't seem to be editable. We're confused about this.
   **UPDATE:** Some are locked. Deepak will add note for those locked  forms, including "if need change, contact us."
4. What if any control do we have in determining what shows up on a cover sheet?
   **UPDATE:** No control available for now. If we want control, provide details to Deepak for implementation in r2.0.
   **NOTE:** We are very concerned about when 2.0 would be released—don't want issues arising when RFP is already active, but possibly do between preproposal and full proposal.
   **However,** the cover page as is now is unusable and represents a serious impediment for us in terms of using the entire system.
## **Pre-existing RFP (WSG 2015 RFP)**
1. RFP preproposal shows rebuttals (54 uploaded). Rebuttals were disabled for this RFP's preproposals, so they shouldn't be listed. Further, the full proposals shows 30 rebuttals submitted, but actually, no rebuttals were were migrated from old to new eSG, so we're not sure why this number isn't "0".
   **UPDATE:** For preproposals, see:

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=showPhase&record=1823&phaseid=2869&tab_label=Pre-Proposal%20Setup

<img width="1039" alt="screen shot 2016-10-27 at 9 12 58 am" src="https://cloud.githubusercontent.com/assets/17168836/19775751/44bc0f22-9c26-11e6-9afc-95ff4fba6321.png">

For full proposals, see:

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=showPhase&record=1823&phaseid=2888&tab_label=Full-Proposal%20Setup

<img width="1042" alt="screen shot 2016-10-27 at 9 16 57 am" src="https://cloud.githubusercontent.com/assets/17168836/19775770/558f7b04-9c26-11e6-9c31-2ce40905cd72.png">
1. Unsure why 2015 RFP shows 9 PIs under "Enable PI Access." What does that mean? See:

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=showPhase&record=1823&phaseid=2888&tab_label=Full-Proposal%20Setup

<img width="1018" alt="screen shot 2016-10-27 at 9 33 08 am" src="https://cloud.githubusercontent.com/assets/17168836/19776318/6fc940de-9c28-11e6-936a-242fe235da98.png">

**Comment by ecsion** [comment]
#1 -- Open access fixed. 
#2 -- Fixed -- Removed Pi & CoPi selections from Key personnel as they did not belong there.  The custom forms currently do not support any sort of logic and so we cannot prevent a PI from entering 2 PI in the investigator form. However you can add text in instructions advising the investigator about only 1 PI will be accepted or something  to that effect.
#3 -- Done
#4 -- Partially fixed.
#5 -- Narratives are custom forms and instructions are part of custom forms.
#6 -- Fixed.
#7 -- Custom forms in general are editable except for a handful  where we have locked them and so please contact Ecsion for changes.  Example of locked forms are Investigator, Key personnel, Project Summary etc.
#8 Currently no control for cover sheets. If you want this, please addd this as a requirement for R2
