### ISSUE TITLE
Cumulative Budget

### ISSUE THREAD

**Issue by abigailhils** [ecsion/eSeaGrant-Client-Bug-Tracker#371]
#Budget Fiscal Year Discussion

So we have come to another understanding of the budget section. In regards to the fiscal year, we are hoping to either:
A) Put Text values in the fiscal year option. For example, instead of 2017/2018/2019 to be Year 1, Year 2, Year 1&2. 

OR 

B) Create a cumulative budget spreadsheet for Year 1 and Year 2....

**Comment by ecsion** [comment]
Abigail, Currently we only support numeric for fiscal year field. We will enhance this in R2. For now, you can simply add 1 for Year1, 2 for Year 2 etc.

**Comment by abigailhils** [comment]
How do we then do a cumulative year? Put 3 for Year 3 doesn't make sense. We also cannot put 1&2, seeing as this is only for numeric values. 

If not, I will work this out with my colleague and see where we go from here.
