### ISSUE TITLE
WSG: Budget justification question

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#373]
The old eSG had different budget worksheet behaviors for preproposal and full proposal: 
At preproposal there was no "Justification" component, but we did have in full proposal. This is critical. We do not want to require justification in the preproposal phase, so we don't even want it to be an option.
However, at the full proposal stage, they are required, but the system doesn't tell you this. To be clear, we don't want to prevent the PI from moving on, but we at least need them to be alerted that they haven't completed the justification(s). 
Ultimately, submittal should be contingent on all justifications having been completed.

**Comment by ecsion** [comment]
Justifications removed from pre-proposal budget sheets. Please check.

**Comment by mgduke** [comment]
Confirmed. Thank you. Would it be possible to remove the "Justification [View]” heading as well?
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
