### ISSUE TITLE
Email template not available for use

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#374]
When I, as an admin, add a user to an RFP I send them an invitation email so that they can begin completing their proposal through eSeaGrant. We created an email template to use for this invitation, however, when I select email templates in the actual email, our template does not appear. Instead I have to copy and paste the email template I want into the email box that pops up.

[Email Template Issue.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/554541/Email.Template.Issue.docx)

**Comment by ecsion** [comment]
Module Type is a required field but it was not clear. We have change the label and now clearly show module type as required field.
