### ISSUE TITLE
Budget not saving for PIs but shows up for Admin; some numbers disappear but are calculated into the total

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#376]
The budget form does not save for investigators in the RFP module. The user enters budget information, saves it, and moves on to the next tab. Some users report that data disappear from fillable boxes, but are calculated into the total budget. When returning to the budget tab it shows no record that the budget was completed. The is is the same when looking at the submission preview (no budget shows up under Budget Summary). The Admin side also shows no Budget Summary and no record of a Budget, but the budget numbers show up in the 90-4 (SG Admin Only). The Budget Justification is nowhere to be found.
[OSG GitHub Budget Bug.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/554630/OSG.GitHub.Budget.Bug.docx)

**Comment by ecsion** [comment]
There is due to a  bug which basically only lists budget sheets that have duration field entered. We will get this fixed by tomorrow. Till then, just endure that the duration field is selected.

**Comment by SEK-OSG** [comment]
That’s the problem – the budget duration field doesn’t have any drop-down options. Is that a code error, or something to address in setting up the RFP call?
Take care,
Sarah

**Comment by ecsion** [comment]
We have made changes so the budgetsheet will now appear in listing even if budget year is not selected.  The choices for budget year are added from rfp detail view LHS navigation. See attached screenshot
<img width="1116" alt="screen shot 2016-10-28 at 11 01 53 am" src="https://cloud.githubusercontent.com/assets/1612666/19811163/4091cd6e-9cfe-11e6-849c-19bbfd3cc479.png">
