### ISSUE TITLE
Wrong Phone # on Document Request Emails

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#377]
The phone number that is automatically included in the System Email Templates - "Document Request for third parties" (and possibly others automated system emails) is incorrect and does not match the "Office Phone" number include in My Profile. 

When I opened the System Email Templates I noticed that the signature line references "$users-phone_work$" (see attached). I am assuming that the "804 684 7918" number included in the example email (attached) is buried somewhere in the system as my old "work phone number" but doesn't match My Profile "Office Phone" 804 684 7436.

![screen shot 2016-10-27 at 12 16 17 pm](https://cloud.githubusercontent.com/assets/17860369/19775679/32a7d30c-9c3f-11e6-8031-b2b407062940.png)

![screen shot 2016-10-27 at 12 21 30 pm](https://cloud.githubusercontent.com/assets/17860369/19775865/eb6961b2-9c3f-11e6-835c-b5924907a983.png)

**Comment by ecsion** [comment]
updated phone number.
