### ISSUE TITLE
Letters of Support not visible to user that requested letter

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#378]
We have an RFP out where users request letters of support to be submitted. Once these letters are submitted, we want the actual letter to be visible to the user that requested it. However, currently users can only see that the letter was submitted and the request that they sent out, not the actual letter. We checked the box that said Show to PI under the support letters section in the pre-proposal set-up > select forms tab. The letter is visible to admin and the person that submitted the letter, but not to the user that made the request.

**Comment by ecsion** [comment]
We can change document request so PI can view submitted documents. However, this will become an issue for confidential documents such as Recommendation letters. To support both conditions we will have 2 different type of document requests: 1. Direct Submissions (not visible to pi) 2. Document Request (visible to pi). We will do this but we need 7 to 10 days to get this done. Meanwhile, please suggest edits to document types 1 & 2 above in case you want to see some other labels when selecting the type of form.

**Comment by SEK-OSG** [comment]
I agree that two kinds of requests are needed. Not visible requests should be labeled "Letters of Recommendation", and appear in student fellowships applications. Visible requests should be named "Letters of Support", which come from project partners and likely apply to proposal submissions.

**Comment by ecsion** [comment]
done.
