### ISSUE TITLE
Automated email not filling in all parts

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#379]
When a person has submitted a letter of support they receive a confirmation email from eSeaGrant. In the email the name should be included after "Dear", but it's blank. Also, under the first paragraph it should have the name of the document that was uploaded, but this is also blank. This is what the email looks like:

Dear ,

You have successfully submitted the following documents for Test Epperly for the research proposal: TEST for the Oregon Sea Grant Resilience Competition 2016-2017 competition.

You may access your personalized document submission page by clicking  here at any time up until the deadline (28 Oct 2016, 05:00 PM) to update your submission. You will receive a confirmation email each time you click the submit button with your latest updates.

Submission Date and time: 27 Oct 2016, 10:15 AM

Sincerely,

Oregon Sea Grant
eSeaGrant Coordinator
Corvallis OR 97333
541-737-2714

**Comment by ecsion** [comment]
fixed.
