### ISSUE TITLE
Automated email still not filling in all parts.

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#381]
When a support letter writer submits a letter on behalf of someone they get an automated email that says they have submitted the document. The email they receive is supposed to show them which document they submitted, but this is still blank (see below under the first paragraph):

Dear Haley Epperly,

You have successfully submitted the following documents for Test Epperly for the research proposal: TEST for the Oregon Sea Grant Resilience Competition 2016-2017 competition.

You may access your personalized document submission page by clicking  here at any time up until the deadline (29 Oct 2016, 05:00 PM) to update your submission. You will receive a confirmation email each time you click the submit button with your latest updates.

Submission Date and time: 28 Oct 2016, 09:34 AM

Sincerely,

Oregon Sea Grant
eSeaGrant Coordinator
Corvallis OR 97333
541-737-2714

**Comment by ecsion** [comment]
Noted. This will be fixed next week.

**Comment by ecsion** [comment]
fixed.
