### ISSUE TITLE
WSG: Investigator UI issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#382]
First, we don't know why our numbered lists below are all "1"—they appear correctly in edit view. So, sorry about that. Here goes:

1. Deepak, you noted:
"The custom forms currently do not support any sort of logic and so we cannot prevent a PI from entering 2 PI in the investigator form."

We don't necessarily understand why this precludes the functionality we requested, but we still must ask: Is it possible to remove "PI" from the dropdown list? At least for WSG, we never have >1 PI, so why would we need this to be in the dropdown menu in the first place?

2. We are easily able to change the PI—should this be allowed?
We wondered if the PI record be locked in the proposal (i.e., no edits to Response 1), _but_ add a note that edits can be done via the profile page. **However**, as you already know, the investigator page is not synced with the profile page. That said, what's the point of having the profile page? Is it used elsewhere? If our request is at all feasible, note that WSG staff would need to be able to edit/change PIs, which we think is not possible now. FYI, the following page informed this discussion:

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33367&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators

Also, there is an additional issue with auto populating fields from Google records. Is there are way to prevent auto population?

3. **Nice to have's**: 
    a) Don't auto-collapse additional investigator content upon saving (leave expanded always).
    b) Change label from "Response 'n'" to the investigator's name.
    c) Department field should follow right after Affiliation field.
    d) Best if affiliation could be chosen from dropdown menu, with final option being "Other" and accompanying text field to enter other affiliation. _Reason_: Prevent many varying versions for the same affiliation (e.g., UW Oceanography; University of Washington Oceanography; School of Oceanography, Univ… etc.).

**Comment by ecsion** [comment]
We use the investigator Form info in 90-2 which includes the PI info and so the PI is required. We currently cannot pull this data from the people record. Additionally, current method provides the PI the flexibility to have the resume tailored to the proposal he is submitting.

The suggestion you have under the category Nice to have:
1. Currently forms logic applies to all forms. We collapse the previous answer as it becomes unwieldy when large forms are involved.

2. In the current Custom Forms, it is nontrivial to say investigator name instead of Response (n). We can consider this enhancement in R2.

**Comment by mgduke** [comment]
That makes sense; it even somewhat occurred to me after my submittal that some flexibility in PI info would be desirable.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
