### ISSUE TITLE
WSG: Task List Title Field Truncated

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#383]
In the PI's task list, long titles are truncated. The complete titles are in tact in the database because we can see the full titles elsewhere, so it's only here where they get chopped. We suggest doubling the length, so if it's 128 char now, make it 256, please.

Heh heh; I would've thought you knew by now how verbose our researchers can be!

**Comment by ecsion** [comment]
Noted. This will be done next week.

**Comment by ecsion** [comment]
fixed.
