### ISSUE TITLE
WSG: Left menu red/green status dots

### ISSUE THREAD

**Issue by ghost** [ecsion/eSeaGrant-Client-Bug-Tracker#384]
**Really Nice to Have:** Just like we have for reporting, can we have those handy red and green bullets for each menu item in the left margin so that users can easily see the status of the tasks associated with the menu items.

**Comment by ecsion** [comment]
Noted, however, there are other change requests that are higher in priority. So this may take some time.

**Comment by mgduke** [comment]
Understood. It isn't mission critical, but is important if for no other reason than to be consistent with Reporting features.

**Comment by ecsion** [comment]
done,
