### ISSUE TITLE
OSG: Budget justification fillable form not working

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#385]
The budget justification button was working yesterday, but does not work anymore. Pressing the justification “Add” button leads to a pop-up window that says “Budgetsheet saved successfully!”, rather than the budget justification dialog box.
[OSG The budget justification button was working yesterday GutHub Bug.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/559515/OSG.The.budget.justification.button.was.working.yesterday.GutHub.Bug.docx)

**Comment by ecsion** [comment]
We have removed budget justification for PreProposals as advised by Washington (Markus Duke). 
We forgot to remove the header  and so it gives the wrong impression that the save button is for justifications. We will remove the header next week.

So now after the change requested by Washington, we have  budget justifications for full proposal only. If you have an issue with this, please confer with Washington and other colleagues and let us know what we should do.

**Comment by ecsion** [comment]
fixed.
