### ISSUE TITLE
WSG: SG Classification & Focus Area

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#386]
1. We need to be able to limit pick list options for a given RFP. Specifically, we need a way to omit “old” focus areas as options for a specific RFP, but cannot remove those from master picklist because these old focus areas apply to other projects in the system.
   **Best solution**: can we set focus areas individually for each new RFP? **Next best solution**: clone existing pick list and edit (but am assuming this could be problematic).
2. Percentages for all focus areas should add up to 100% before allowing PI to save form.
3. Please remove award # and affiliation code.

**Comment by ecsion** [comment]
#1 is not trivial and would have to be done in R2. 
#2 This is also not trivial because currently, the custom forms do not support logic. 
#3 Please get a consensus on removing award# & affiliation code with your sea grant colleagues and let me know and we will be glad to remove it.

**Comment by mgduke** [comment]
Could we at least add some text to emphasize what _not_ to do for (1) and (2) until we can determine if it's appropriate for R2?
OK re (3); will confer. The collaborative online tool we discussed would help. How big a deal is that for you to set up?
