### ISSUE TITLE
WSG: Budget Worksheet Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#387]
1. Please remove "Justification [View]" heading for preproposal interface.
2. When entering G. Other Costs - Remove option: “Sub-award NOT subject to indirect…"

**Comment by ecsion** [comment]
Marcus -- can you check with your colleagues if they agree with #2.

**Comment by ecsion** [comment]
Closing now. Please add another issue once you have input for #2.

**Comment by mgduke** [comment]
Sarah Kolesar requested this option, "Sub-award NOT subject to indirect…," be retained. Case closed.
