### ISSUE TITLE
WSG: Current and Pending Support

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#388]
Regarding Person-Months per Year Committed to the Project:
1. Would prefer to have single field; we don't break it down to Cal, Acad and Sumr. We're not even sure what Cal means although guess it was for the entire year.
2. If we must keep these, please spell them out (Calendar (presumably), Academic and Summer).

**Comment by ecsion** [comment]
Noted, We will have these updates in the next release.

**Comment by ecsion** [comment]
Fixed. Also this form is no longer locked, so you can change it per your convenience.
