### ISSUE TITLE
WSG: Change request: Make preproposal budget worksheet justifications optional

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#390]
The original MIT eSeaGrant by default omitted the justifications for the preproposal phase, so we mistakenly assumed this should be the case for the new eSG. Unfortunately, this is not the case and we caused problems for another SG in the middle of an RFP (so sorry, Sarah K!).

Consequently, we would like to make preproposal budget worksheet justifications optional.

**Comment by ecsion** [comment]
ok will do. We will be addressing several change requests this week and have a release later this week or early next week. This request will be addressed then.

**Comment by mgduke** [comment]
Outstanding, Deepak! Thanks much.

**Comment by ecsion** [comment]
reverted.
