### ISSUE TITLE
OSG- Custom Form list pages not viewable

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#391]
In the reporting module, the custom forms list shows forms 1-14 of 17, but as an administrator I cannot use the forward arrow to view our forms 15-17.
![custom_forms_pagination2016-11-01_1010](https://cloud.githubusercontent.com/assets/17169131/19899305/d94adc96-a01c-11e6-9bda-b0477a4f2b6e.png)

**Comment by ecsion** [comment]
fixed.
