### ISSUE TITLE
OSG- Report errors in Custom Form Report

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#392]
1. As an administrator in the Projects module, when pulling up a **Report** of **all** our custom form responses, regardless of checking all boxes or not there is only one choice, Export. Should there also be Export All and Download Multi Zip file choices?
![report_test_2016-11-01_1036](https://cloud.githubusercontent.com/assets/17169131/19901836/b7d9d13a-a025-11e6-8cd9-4fa99654bab4.png)

2. When choosing "Export" it should create a big spreadsheet, instead I get this error:
{"success":false,"error":{"code":"Invalid cell coordinate 6","message":"Invalid cell coordinate 6"}}

Note that this error doesn't occur whenever I choose just a few forms to export, and it doesn't happen when I request a Report for all Publications or another non-custom form.

**Comment by ecsion** [comment]
fixed.
