### ISSUE TITLE
ORSG- Reporting spreadsheet coding

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#393]
In Reporting within the exported Excel spreadsheets- the original bullets, apostrophes and quotation marks are showing up as code:
![quotes_2016-11-01_1140](https://cloud.githubusercontent.com/assets/17169131/19902435/0504177a-a028-11e6-81c8-606770320fd2.png)
![apostrophe_2016-11-01_1138](https://cloud.githubusercontent.com/assets/17169131/19902434/05043110-a028-11e6-885f-aa4216c51b7f.png)
![bullets_2016-11-01_1137](https://cloud.githubusercontent.com/assets/17169131/19902433/0503f5f6-a028-11e6-9adf-779cabadabc5.png)

**Comment by ecsion** [comment]
We are getting this data from MIT seagrant system which is not compatible with HTML. We will look to see what if any transformations we can run on this data.
