### ISSUE TITLE
NC - Fellowship

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#394]
We have created a Fellowship RFP and when we go into the PI side, the RFP will not come up to complete the application.

**Comment by ecsion** [comment]
Appears to be a timezone issue or some other time issue. We have temporarily fixed it by starting the Fellowship at 2:00 AM instead of 2:00 PM. We will have this fixed in the upcoming release in the next few days.

**Comment by ecsion** [comment]
fixed.
