### ISSUE TITLE
Cannot view letters of support in proposal summary tab 

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#395]
We have an RFP that recently closed and we are now compiling all of the information that the applicants submitted through eSeaGrant. In the proposal summary tab there is a section titled support letters, and we would like to be able to download the support letters from this tab. We can download the narrative from this tab, and we can view the budget summary and budget justification here.
![support letters](https://cloud.githubusercontent.com/assets/23087213/19940298/73e3129c-a0e9-11e6-8d1f-ba9a25a4e1b1.png)

**Comment by ecsion** [comment]
Noted. We will add a hyperlink.

**Comment by ecsion** [comment]
done.
