### ISSUE TITLE
OSG - what happened to reviewer / panelist roles?

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#396]
I'm setting up proposal review, but I can't assign the roles of "peer reviewer" or "panelist" to my personnel: 

![image](https://cloud.githubusercontent.com/assets/18152637/19945105/d93e8290-a0fb-11e6-9b4d-b65939adbe76.png)

Please help ASAP

**Comment by ecsion** [comment]
Peer Reviewers and panel Reviewers do not log into the eSeagrant system and thus they do not have a role in eSeagrant system. They will get an email with a coded secret link. This link will give them access to the peer review or panel review that they have been invited to.
