### ISSUE TITLE
NC - New User Errors

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#397]
When we create a new user, the user is not sent a password.  I went into the system and had to make the user "active" before I could send a password.  Will this have to be done with every person who registers for eSG or is there a bug in our system?  When I try to send an email to the new user, I get this error message:  SMTP Connect() failed.

**Comment by ecsion** [comment]
NCSU has blocked email outgoing port 587,. Please have your IT folks fix this and the email issue will be resolved. Have them run this command: 
nc -zv smtp.sendgrid.net 587
