### ISSUE TITLE
Cannot create peer review without criteria system

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#400]
We are moving into the review phase for proposals we have received through eSeaGrant. For our peer reviewers, we do not want them to use a peer review rating (5 star rating with criteria and 5 star rating are the two options provided). We are just having these reviewers recommend or not recommend the proposal for funding. I would like to be able to invite peer reviewers to review a proposal without having to choose one of those ratings in the peer review form setup tab.
![peer review ratings](https://cloud.githubusercontent.com/assets/23087213/20082714/ce6ae2cc-a50c-11e6-983c-70f333147b88.png)

**Comment by epperlyh** [comment]
I've noticed that there is a "none" option in the PANEL review ratings, that would work for the peer review ratings as well.

**Comment by ecsion** [comment]
Noted. We will add.

**Comment by ecsion** [comment]
done.
