### ISSUE TITLE
WSG: Rebuttal page not showing score

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#403]
In testing the PI rebuttal page, we note the score is not visible:
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33443&mode=showRebuttalForm&tab_label=Rebuttal&tab_label=Rebuttal

<img width="1041" alt="screen shot 2016-11-09 at 12 26 41 pm" src="https://cloud.githubusercontent.com/assets/17168836/20156111/c8bae548-a683-11e6-899d-0cb97f699737.png">

**Comment by ecsion** [comment]
Done.
