### ISSUE TITLE
WSG: "View Panel Contents shows other panelists' reviews

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#404]
In our preproposal panel review form (via panelist login), the "View Panel Comments" link allows  the panelist to see other panelists' reviews. Please hide the other panelists' reviews.

http://esg.wsg.washington.edu/operations.php?action=panel_reviewer&guid=N0NCODg4MkQtNEE3OS00Nzc2LUIwNDctRUQzRjJFNDVGQTc1&exuti=MzM1MTI=#

<img width="672" alt="screen shot 2016-11-09 at 3 14 07 pm" src="https://cloud.githubusercontent.com/assets/17168836/20158570/e3973298-a68f-11e6-8ef4-44ed93d78c32.png">

**Comment by ecsion** [comment]
Is everyone ok to hide other panelist review?

**Comment by mgduke** [comment]
Checking; back to you soon.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
done.
