### ISSUE TITLE
WSG: Minor typo in Continuing & Pending (CP) Support

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#405]
Too funny! I had no idea my requested edit would be taken so literally. Please see screenshot and remove "(presumably)" from the "Calendar" label.

<img width="839" alt="screen shot 2016-11-10 at 1 34 55 pm" src="https://cloud.githubusercontent.com/assets/17168836/20195316/dfa633e4-a74a-11e6-8fdb-e6148e0b6760.png">

**Comment by ecsion** [comment]
fixed.
