### ISSUE TITLE
MASGC: Custom forms not showing properly when downloaded from zip

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#406]
This is directly related to the recently closed issue #360 

We created a custom form and called it "MASGC 90-2 Project Summary Form (in contrast with the "mandatory" "90-2 Form" that we don't want to use for this competition.
http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=createPhase&record=777&phaseid=778&tab_label=Pre-Proposal%20Setup 

A PI will fill in the custom "MASGC 90-2 Project Summary Form" and it saves fine.

![custom 90-2 filled by pi](https://cloud.githubusercontent.com/assets/22300443/20196611/105b1bd8-a761-11e6-92a8-bcb2a8f4a2cc.JPG)

The proposal is saved and submitted by the PI.

When we, as admins, go to download the proposal documents (As "Download Zip" here:
http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=777&phaseid=778&tab_label=Pre-Proposal%20Setup

It downloads the following:
![this is what is downloaded in the zip](https://cloud.githubusercontent.com/assets/22300443/20196732/a7b044a4-a761-11e6-9d75-54ae227f245c.JPG)

The "mandatory" "90-2 Form" appears as a blank document, but the custom "MASGC 90-2 Project Summary Form" is nowhere to be found.

Similarly there are other files missing such as I don't see the "Key Personnel" and that should be in that zip.

**Comment by ecsion** [comment]
fixed.
