### ISSUE TITLE
WSG: Panel Review Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#407]
See following webpage and screenshot for these issues:

1. PHP escape character or other issue with special characters:  See "Kate\&#039;s 2017 test preproposal".

2. Preproposal (or presumably proposal, too) download not working in Chrome. Error is:
    The esg.wsg.washington.edu page isn’t working
    esg.wsg.washington.edu sent an invalid response.
    ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

3. If peer review is not enabled, panel reviewer should not see View Peer Reviewer/Rebuttal as an option 

4. What is the link to view panel comments? If we are already in that mode why do we need this?

5. In the past, for our preproposal panel stage, we allow panelists to see all pre-proposals but do not ask them to review them all. Would love a method to allow us to select which ones to for each panelist to review.

http://esg.wsg.washington.edu/operations.php?action=panel_reviewer&guid=QTBCRjNFQ0QtOTYyRi00MDNELUFBQTYtQUEzRTg3MDkxMUE1&exuti=MzM0ODE=
<img width="1423" alt="screen shot 2016-11-10 at 3 07 10 pm" src="https://cloud.githubusercontent.com/assets/17168836/20198062/7e73a662-a757-11e6-9585-3638694a4360.png">

**Comment by kdez** [comment]
Regarding #5 "In the past, for our preproposal panel stage, we allow panelists to see all pre-proposals but do not ask them to review them all. Would love a method to allow us to select which ones to for each panelist to review"    MIT instructs by email to take responsibility for particular proposals, but we encourage them to read and comment on any that interest them. The same for our Advisory Committee - we point the towards the ones they have expertise in but ask for opinions on all of them re: usefulness to stakeholders; community education value, etc.
That said, if Ecsion allows us to select which proposals they can see/score, we can always just check off all of them....

**Comment by mgduke** [comment]
Or even have one of those “unselect” all checkboxes.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
1,2 3, & 4 done. 
Point 5 will be added as R2.0
