### ISSUE TITLE
Need to change review form setup after review has started

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#408]
We are working on conducting a peer review for an RFP that recently closed. In order to test this review process, I sent a request to review a test proposal to myself. We wanted the option for this review to not have a rating system in the review process, which you added this option in yesterday. I went back to try and change the review form in the "peer review form setup" tab to include no rating system, but now it will not let me change the form because "ratings cannot be changed once the review has started". I need to edit the review form, test it again, and possibly edit it some more, so how can I do this?

**Comment by ecsion** [comment]
please provide a link

**Comment by epperlyh** [comment]
http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=2373&phaseid=2374&tab_label=Pre-Proposal%20Setup

**Comment by ecsion** [comment]
Rating changes are not supported after an investigator has added a rating. We can manually do this for you but it will wipe all the ratings that have been entered. Do you want us to do this?

**Comment by epperlyh** [comment]
No, we have already sent out instructions to our reviewers to just select "5" on the rating scale and we will disregard it.
