### ISSUE TITLE
OSG: Peer review print function

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#409]
![image](https://cloud.githubusercontent.com/assets/18152637/20285634/e0ee5e7c-aa77-11e6-8b6b-04a5fc474b0e.png)

What does the “print” icon do? Ideally, it would print a copy of the submitted review, but it doesn’t seem to be working? I’m on a PC using Chrome.

**Comment by ecsion** [comment]
Noted, we will add this in the next build.

**Comment by ecsion** [comment]
done.
