### ISSUE TITLE
Date format inconsistency

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#410]
in RFP Setup dates are format = YEAR-MO-DY
in Budget Setup dates are format = MO-DY-YEAR

Date format should be consistent throughout all Setup forms/screens. MO-DY-YEAR is preferred.

Please reconcile so there is consistency throughout the eSG program regarding date format

Thank you.

**Comment by ecsion** [comment]
Noted, this will be changed.

**Comment by ecsion** [comment]
fixed.
