### ISSUE TITLE
CASG: 2018 Knauss RFP - Submission Issue 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#411]
Hi,

We made the "Knauss Fellowship: Out of State Applicants only" form NOT mandatory, but an error message pops up when you try to submit an application without uploading a document. 

http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=30868&mode=showSubmissionPreview&tab_label=Submission%20Preview 

![screen shot 2016-11-15 at 10 45 33 am](https://cloud.githubusercontent.com/assets/17860279/20318986/5fb88bb6-ab21-11e6-8201-80b71355e3a3.png)

Thanks,

Miho

**Comment by ecsion** [comment]
Noted, we will fix.

**Comment by ecsion** [comment]
fixed.
