### ISSUE TITLE
NCSG - Pick list Adding

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#415]
In the pick list options, I do not see where we could add a type of person.  Currently in the RFP, there is only an option for investigator and co-investigator and we would like an option to add collaborator.  Can this be added on your end since I do not see a pick list option?

**Comment by ecsion** [comment]
Currently the PI, Co-PI options are hardcoded. We will add Collaborator to the list in the next build.

**Comment by ecsion** [comment]
We added Collaborator option to the Investigators form. If this is not what you want, then reopen or open new issue.
