### ISSUE TITLE
Cannot "accept" reviews

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#416]
Reviews have been submitted, but there is no way to "accept" the reviews (see attached). Additionally, what changes when do accept the reviews?

[Accepted reviews.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/595682/Accepted.reviews.docx)

**Comment by ecsion** [comment]
done.
