### ISSUE TITLE
MASGC- Ability to limit text field size

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#418]
Can we get the ability to limit text field size on our custom forms?  I know my PIs will go on forever if I don't corral them somehow.

An example of where this would be useful is on our Custom "MASGC 90-2 Project Summary Form" in the questions 4, 5 and 6. In the "Text Area Input" type fields.

http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Edit&record=117&showList=RFP

**Comment by ecsion** [comment]
done.
