### ISSUE TITLE
Instructions for letters of rec not viewable to applicants

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#419]
Instructions for applicants on who to send letters of rec to where included in the custom form created. The instructions are visible from the admin side, but are not visible from the applicant side. See screenshots and explanation attached.

[Letters of rec instructions.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/596051/Letters.of.rec.instructions.docx)

**Comment by ecsion** [comment]
Noted, we will add.

**Comment by epperlyh** [comment]
Do you know when this bug will be fixed? I have been waiting for this to be fixed to sign students up for a fellowship application and it's been a couple weeks now.

**Comment by ecsion** [comment]
Done. Please verify that we have have done the changes you requested. I am closing this right now. If this is still an issue, please open this issue or add a new one.
