### ISSUE TITLE
MASGC: wrong phone number in configuration

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#420]
This was originally reported with issue #339 

The phone number used in my signature isn't correct.  My profile has the right phone number so I think this must have happened early on when the system was set up for eSG.  It does not show up in the configurations that was sent to me last month so I don't know where it is.

![wrong phone number in loretta signature 2 labeled](https://cloud.githubusercontent.com/assets/22300443/20394713/26b1e5b6-aca6-11e6-852f-2cf1a9d57b87.jpg)

It shows up on this email template:
http://eseagrant.masgc.org/index.php?__vtrftk=sid%3Ac627fe88da069f21415b2741d6a4b0a62b41191e%2C1479395657&selected_ids=%5B%22815%22%5D&excluded_ids=&viewname=&module=Emails&view=ComposeEmail&callreportingid=&rfpphaseid=870&search_key=&operator=&search_value=&search_params=null&fieldModule=People&to=%5B%5D&selectedFields=%5B%22email%22%5D&triggerEventName=postSelection1137

![email signature template labeled](https://cloud.githubusercontent.com/assets/22300443/20394862/9eb1c6b2-aca6-11e6-9bbe-193ebf8921eb.jpg)

**Comment by ecsion** [comment]
done.
