### ISSUE TITLE
MASGC: erroneous warning about proposals not complete

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#421]
Investigators receive a warning "Some forms have not been completed!" when they select to submit their proposal. However, we have verified that all components have been completed.

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=886&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission%20Preview

 
![forms have not been completed](https://cloud.githubusercontent.com/assets/22300443/20395446/9672e880-aca8-11e6-9824-f9a44919553a.jpg)

I wonder if this is happening because we are not using any "Mandatory" forms.  We are only using custom forms.  Can we not have "mandatory" forms for the RFPs?

**Comment by mumezawa** [comment]
CASG has encountered the same issue too. If you click "Continue", it will let you submit although it's better not to have it if the box is blank. Thanks. 

- Miho

**Comment by ecsion** [comment]
fixed.
