### ISSUE TITLE
URGENT: Mandatory Form Not Editable 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#422]
Hi, 

I was able to edit mandatory forms and now I can't.
Under "Key Personnel", the "Type" only has one option (Associate (Faculty Or Staff)).
Can we add more options such as "student",  "professional", etc. (same as the drop down menu in the budget workshop under other personnel), or delete it in the form? 

http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=30954&mode=showMultiQuestionStem&QuestionId=14066&tab_label=Key%20Personnel&tab_label=Key%20Personnel

![screen shot 2016-11-17 at 10 11 38 am](https://cloud.githubusercontent.com/assets/17860279/20401599/4fbf75a6-acae-11e6-8378-c726e7b74142.png)

Thanks,

Miho

**Comment by ecsion** [comment]
done.
