### ISSUE TITLE
MASGC: Paragraph return issue on preview and final files -text input field

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#423]
We created a form that uses several "Text Area Input" fields.
When the investigator types in these fields they can put in paragraph breaks and bulleted lists and it looks correct. However when the completed form is saved and the investigator goes to the proposal submission preview it runs all of the paragraph returns together.

![paragraph input labeled](https://cloud.githubusercontent.com/assets/22300443/20406759/246e3e2a-acd4-11e6-858e-56192cdd14d0.jpg)

![what pi sees when form is saved - runs together labeledf](https://cloud.githubusercontent.com/assets/22300443/20406767/2e022974-acd4-11e6-8794-b4a97c3c94f6.jpg)

It shows up in the Submission Preview:
![submission preview runs on](https://cloud.githubusercontent.com/assets/22300443/20406796/5e24a80c-acd4-11e6-8262-254771a192fb.JPG)

Most importantly this is what we see in the pdf output of the downloaded form:
![narrative form output](https://cloud.githubusercontent.com/assets/22300443/20406899/d6cbbc28-acd4-11e6-84ef-85ec34cd169e.JPG)
This concerns us because this is what a reviewer will see of the proposal.

We think this issue probably has something to do with how the text input field reads hard and soft returns.

**Comment by ecsion** [comment]
Noted. We need some time to fix this. Should be done by next week.

**Comment by ecsion** [comment]
fixed.
