### ISSUE TITLE
MASGC: Investigators form - additional required fields 

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#424]
On the mandatory form "Investigators", currently the only required fields are the name, email  and affiliation.  We would like to make most of the fields required for all investigators: phone number, address 1, city, state and department.  I think there should also be a required title field. It helps to know if someone is a technician, a student, a professor, a director, a mayor, etc.

http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=createPhase&record=868&phaseid=870&tab_label=Pre-Proposal%20Setup

![investigators field as seen by the admin preview](https://cloud.githubusercontent.com/assets/22300443/20407313/664befd4-acd6-11e6-821e-e4efa8753cb8.JPG)

![investigators form as seen by pi](https://cloud.githubusercontent.com/assets/22300443/20407349/9631d5b0-acd6-11e6-86d3-0dcffe7c2eb1.JPG)

**Comment by ecsion** [comment]
The fields appear automatically when field type is People. So any changes to the "required" fields will affect all SeaGrant programs. Can you check this with your colleagues. If everyone is ok, we will be glad to make this change.
