### ISSUE TITLE
CASG: Confirmation Emails 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#425]
Hi,

Can you please change the proposal submission confirmation emails to go to sgproposal@ucsd.edu rather then mligare@ucsd.edu?  

![screen shot 2016-11-17 at 1 17 00 pm](https://cloud.githubusercontent.com/assets/17860279/20407912/2886c588-acc8-11e6-91da-7773d342c6cd.png)

Thanks,

Miho

**Comment by mumezawa** [comment]
Can you also make sure that ALL the automated emails are sent to sgproposal@ucsd.edu and NOT mligare@ucsd.edu? I'm leaving town for a few weeks and want to make sure other people can see these emails. Thank you.

For example, the peer review request emails are still going to my personal email.

Thanks,

Miho

**Comment by ecsion** [comment]
done.
