### ISSUE TITLE
MASGC: numeric fields are text fields

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#426]
I just added a bunch of numeric only fields and they are allowing text to be saved in those fields.

http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Detail&record=117
![numeric fields entered](https://cloud.githubusercontent.com/assets/22300443/20408131/cad9925a-acd9-11e6-8ff3-6747ca6e83c2.JPG)

![numeric field with text](https://cloud.githubusercontent.com/assets/22300443/20408174/e76279a0-acd9-11e6-80cb-36488560af04.JPG)

**Comment by ecsion** [comment]
fixed.
