### ISSUE TITLE
MASGC: non-selected form shows on the submission preview

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#427]
In our RFP set up, we do not require the mandatory "Key Personnel" form.
http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=createPhase&record=868&phaseid=870&tab_label=Pre-Proposal%20Setup

![key personnel not selected labeled](https://cloud.githubusercontent.com/assets/22300443/20408394/e195cabc-acda-11e6-9615-685fe2cfb172.jpg)

However, this form shows up when the investigator goes to "Submission Preview"
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

![no key pers submission preview lasbeled](https://cloud.githubusercontent.com/assets/22300443/20408514/70c811a4-acdb-11e6-8076-91fcbf0907ef.jpg)

I think this may be related to issue #421

**Comment by ecsion** [comment]
Noted, we will fix.

**Comment by ecsion** [comment]
done.
