### ISSUE TITLE
MASGC: Key Words don't show up on Submission preview or the output.

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#428]
On the "Start Here" Page the "Key Words" box should be mandatory.
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showProposalTitle&tab_label=Start Here
(Note, it should also not be so big!)

![key words text box](https://cloud.githubusercontent.com/assets/22300443/20408663/13ba497c-acdc-11e6-97d0-d9adda24427a.JPG)

The Key Words are missing on the "Submission Preview" page
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

We request that the Key Words show up on the submission preview.

**Comment by ecsion** [comment]
done.
