### ISSUE TITLE
MASGC: Restrict to only 1 person identified as PI

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#429]
On the Investigator input, is it possible to restrict it so that only 1 person can be identified as a PI under "Role"?

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators
![pi restrictions](https://cloud.githubusercontent.com/assets/22300443/20409324/d5c69eba-acde-11e6-9df0-35f306edd18f.JPG)

Along those same lines, I think you could add additional options in the dropdown:
(Keep PI and Co-PI)
Co-PI, Proposal Point of Contact
Non-PI Collaborator
Student/Fellow
Advisor to Student/Fellow
Institutional Authority

I'd think those options would be very useful.

**Comment by ecsion** [comment]
we have separated the investigator form to PI form & Co-PI form. So PI form now only has the ability to add 1 record. You can add a new form with additional roles. If you still have an issue, please reopen or add a new issue.
