### ISSUE TITLE
MASGC: Investigators Form is labeled as a "Key Personnel" form

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#430]
On the mandatory Investigators form it is labeled "Key Personnel".
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators
![investigator form says key personnel label](https://cloud.githubusercontent.com/assets/22300443/20410581/6de57528-ace3-11e6-8823-312481178be6.jpg)

This shows up in a few different places such as on the admin preview of the form, but I assume if you fix it here it will be fixed everywhere else.

**Comment by ecsion** [comment]
Noted.

**Comment by ecsion** [comment]
done.
