### ISSUE TITLE
MASGC: Investigator form "Upload CV" section is confusing. Needs rewording.

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#431]
On the mandatory form, "Investigators":
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

Before you hit "Edit" it looks like there is an option to immediately upload the CV without opening "Edit"
![upload resume before you hit edit label](https://cloud.githubusercontent.com/assets/22300443/20410779/62ee1d72-ace4-11e6-88e6-64c2a6bdb6b6.jpg)

This should be changed to just saying view CV/Resume/Bio instead of "Upload Resume/CV" or something.
The way it is now was confusing to our beta-testers.

On a similar note, can I suggest that we change the instructions on the "Edit" page to say something like 
"Upload a maximum 2-page CV/Resume/Bio"

**Comment by ecsion** [comment]
Noted.

**Comment by ecsion** [comment]
done. However, other sea grant programs may have a need to have a longer cv, so we removed the word: 2-page
