### ISSUE TITLE
MASGC: No description in the "...forms are not complete" box

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#433]
Directly related to Issue #421 -
The box that says "Some forms have not been completed" upon attempting to submit a proposal is blank.  I think this form should say something about what it is that is missing?

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

![forms have not been completed](https://cloud.githubusercontent.com/assets/22300443/20411127/c9b80a6c-ace5-11e6-84ff-140f65f27ce7.jpg)

**Comment by ecsion** [comment]
fixed.
