### ISSUE TITLE
MASGC: "Add" button in Investigators form 

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#434]
Can we change the "ADD" button in the investigator's form to say "Add Another Investigator" or something more clear?

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

![add investigator button label](https://cloud.githubusercontent.com/assets/22300443/20411552/9f43c396-ace7-11e6-93bb-5922b8ee1573.jpg)

This area was confusing to our beta testers.

**Comment by ecsion** [comment]
Noted. We will make the button text editable.

**Comment by ecsion** [comment]
Done. We now allow to add the button text in the custom form.
