### ISSUE TITLE
MASGC: Reword the instructions on Investigator form

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#435]
The instructions at the top of the mandatory Investigator form is very confusing and needs to be reworded.

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

![investigator form instructions labeled](https://cloud.githubusercontent.com/assets/22300443/20411885/294bee0a-ace9-11e6-8583-0ff7b5f1ab30.jpg)

It currently reads: "A curriculum vitae* (resume) is required for each investigator. To upload a resume, click 'Save Investigator' or 'Update Investigator' below. To replace a prior-uploaded resume, simply upload a new resume.   IMPORTANT Only Acrobat documents (pdf) are accepted. "

We suggest something like:
"Fill in the name, email, affiliation and address for each PI or Co-PI and upload a maximum 2-page CV, resume or bio for each.  Click "Edit" to add to your profile below and upload a resume. Additional investigators can be added by clicking "Add" at the bottom of the form.  To replace a prior-uploaded resume, simply upload a new resume.   IMPORTANT Only Acrobat documents (pdf) are accepted."

**Comment by ecsion** [comment]
We will change instructions to the text provided, however note, you can do this yourself for all forms including Investigator form as well (even though Investigator form is locked for editing questions)

**Comment by ecsion** [comment]
done.
