### ISSUE TITLE
Fellowship Budget Worksheet Issues

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#436]
Good morning,

Our fellowship applicants are beginning to enter their budgets into the embedded "Budgets" worksheets in Virginia's eSeaGrant system, and they are running into several issues.

1. Investigators (and through my access as an administrators) we are unable to add any values to section B. Fringe Benefits. We need to be able to add Grantee Share cost to that section and currently we can not edit it at all. 

2. Through both Investigators and through my access as an administrators we are able to edit section G. Other Cost to add a single Descriptions and Sea Grant and Grantee costs. However, when they click the "ADD" or "SAVE" button they do not save to the form. 

Please see pictures below and contact me if you have any questions. 
![screen shot 2016-11-18 at 9 27 57 am](https://cloud.githubusercontent.com/assets/17860369/20433423/80b7a00c-ad71-11e6-8c2b-3d1f288851d0.png)
![screen shot 2016-11-18 at 9 28 31 am](https://cloud.githubusercontent.com/assets/17860369/20433425/80b88990-ad71-11e6-9887-eec056e7424c.png)
![screen shot 2016-11-18 at 9 28 46 am](https://cloud.githubusercontent.com/assets/17860369/20433424/80b87658-ad71-11e6-9a9d-00ec4820f7e3.png)
![screen shot 2016-11-18 at 9 29 19 am](https://cloud.githubusercontent.com/assets/17860369/20433426/80b8bf46-ad71-11e6-8d8f-7c0757d9be3a.png)

**Comment by SamuelJLake** [comment]
As a follow up, we have been exploring this issue a little more and have also determined that when you edit the "Budgets" form and hit "SAVE" the main window of the "Budgets" Form (attached screen shot) will update with the added cost. However, when you are still in the form they are not displayed, nor do they add up to the same total (see second attached screen shot). 

![screen shot 2016-11-18 at 9 42 09 am](https://cloud.githubusercontent.com/assets/17860369/20433814/4d6b974c-ad73-11e6-97c4-98d18415222a.png)

![screen shot 2016-11-18 at 9 42 54 am](https://cloud.githubusercontent.com/assets/17860369/20433853/67c187f0-ad73-11e6-9682-beb8ae4f254a.png)

**Comment by SamuelJLake** [comment]
We have one additional, somewhat related request. Some of our applicants would like to include additional "1. SENIOR PERSONNEL" to the "Budgets" form, and while they are able to add themselves and select "Select Personnel" on the form, they are unable to add a description for that person (you are able to do this under the subsequent "2. OTHER PERSONNEL" section.

Would it be possible to add that ability - i.e. to "Enter Full Name" under the Senior Personnel section?

![screen shot 2016-11-18 at 1 15 20 pm](https://cloud.githubusercontent.com/assets/17860369/20441106/133a3f06-ad91-11e6-8249-ef4fb278f320.png)

**Comment by SamuelJLake** [comment]
Hi Deepak, 

If possible it would be useful for us to select individual personnel that were going to have IDC charged to them. I would be happy to chat about this some more on Monday, but in this case only  one of the 3 personnel were being used as Grantee Share - via IDC. 

Best,
Sam

**Comment by ecsion** [comment]
1. Fringe Benefits is a calculated field and so is not editable. To change the values on Fringe benefits, simply update the column "Benefit %". This could be confusing, so we will add a popup stating something like: This field is a calculated field and is affected by Benefit % column.

2. The issue on G (Other Costs) is that currently the drop down is a required selection. To avoid any confusion, we will add a popup that provides a reason what the Other Costs field was not saved.

3. Looking into having the selection have name & role of key personnel and then showing the name instead of the role field when selected.

4. If this is urgent, we will add this capability before R2. However, we will need a week to do this.

**Comment by SamuelJLake** [comment]
Thanks for taking the time to talk to us today Deepak!

To follow up on our conversation. It would be helpful if PIs could add a second "Senior Personnel" to the Budgets form. Many of our fellowship applicants are required by their universities to list their advisors as the PI on their 90-4 Budget forms. Currently, they are listing them under "Other Personnel" on the online form, but that does not match the 90-4 Budget Excel files that they are submitting.

When you have time, please update the personnel section of the Budgets form to accept names with an apostrophe. Currently, that fill-in section does not accept names with an apostrophe (e.g. "O'Reily")

Thanks for all of your help everyone!

**Comment by ecsion** [comment]
The 4 issues resolved. The last change request (to be able to accommodate advisor is a little complicated and will be in R2.0

**Comment by ecsion** [comment]
We have resolved the apostrophe issue as well as the ability to add Advisor in Key personnel. We have however not pushed these changes to Virginia server. Let us know when you want us to push these changes. However, note, if we do push changes, all changes till that date will automatically also be pushed.
