### ISSUE TITLE
MASGC: Auto-filled Investigator form is blank in "Edit"

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#439]
Thank you for making so many changes for me.  I know we are bombarding you lately.

This popped up after some changes were made yesterday. It was working correct when we tested it earlier but it isn't now.

On the Investigators form
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=982&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

it is usually pre-filled with the info for the person who logged in.  Then they go to "Edit" and fill in the blanks and upload their CV.  

![prefilled investigator labeled](https://cloud.githubusercontent.com/assets/22300443/20436900/9435a5b0-ad77-11e6-84e1-7c588b421916.jpg)

However, now when they click "Edit" the form is blank and they have to re-fill everything.

![blank pi form](https://cloud.githubusercontent.com/assets/22300443/20436955/d23fedc0-ad77-11e6-9a7d-0228b338a8ea.JPG)

**Comment by ecsion** [comment]
fixed.
