### ISSUE TITLE
MASGC: Submission error still not quite right

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#440]
When the PI goes to Submission Preview and selects to "Submit" or "Resubmit" it pulls up an error but all of the required fields are filled in.

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=873&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

This says the Investigator section is not complete:
![investigators are not complete](https://cloud.githubusercontent.com/assets/22300443/20437167/90f7ac8a-ad78-11e6-825b-4b387dbdce10.JPG)

However, I triple checked and the required fields on the Investigator form are all filled and a PDF has been uploaded into the CV section:

![properly filled investigator form](https://cloud.githubusercontent.com/assets/22300443/20437263/f8c40976-ad78-11e6-9eb9-2a7b9ad2415c.JPG)

**Comment by ecsion** [comment]
fixed.
