### ISSUE TITLE
MASGC: Key words don't appear on Submission Preview

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#441]
On the Start Here page:
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1030&mode=showProposalTitle&tab_label=Start Here&tab_label=Start Here

There is a box for Key words and the PI can change the title.

![labeled](https://cloud.githubusercontent.com/assets/22300443/20438309/bcff38e4-ad7c-11e6-9b9f-06ca42e60ce1.jpg)

On the submission preview page the title shows at the very top. The keywords are not shown anywhere

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1030&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview
![key words don t show up on submission prev labeled](https://cloud.githubusercontent.com/assets/22300443/20438317/c33baa58-ad7c-11e6-8e22-8a4fa4d9c3e9.jpg)

**Comment by ecsion** [comment]
done. We put keywords as the first section before other form data.
