### ISSUE TITLE
Peer reviewers need to be anonymous - currently visible to panel reviewers

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#442]
We would like our peer reviewers to be anonymous to both the PIs and the panel reviewers. Currently, when we invite a panel reviewer they are sent an email with a link that takes them to the page with all of the proposals. On that page there are links under each proposal to view the peer reviewers' comments. When they click on the link to view the peer reviewers' comments the name of the peer reviewer that wrote those comments is shown. We do want the panel reviewers to be able to see the peer reviewers comments,  but we do not want the panel reviewers to know the identities of the peer reviewers. 
[Peer Review Anonymity.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/600957/Peer.Review.Anonymity.docx)

**Comment by ecsion** [comment]
done.
