### ISSUE TITLE
Have to click "accept" button twice to accept peer reviews

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#443]
From the admin side when I go into the peer reviews, click "change" under the accepted peer review column, and click the box next to "accept" for one of the reviews, and then close out of the dialogue box, it does not show that the review has been accepted. It still says 0/3 reviews have been accepted. When I click on "Change" again under the Accepted Peer Review column, and click the accept box for the same review again and then close out of the box, then the number finally changes and says 1/3 accepted. Every time I have accepted a review I have had to do this twice.
[Accept button.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/601033/Accept.button.docx)

**Comment by ecsion** [comment]
We could not reproduce the issue. Here is what may be happening:
1. Once you close the popup dialogue after chasing the accept for 1 of the reviews, the background page then refreshes. If you are on a slow connection, it may take a few seconds. Thus it may appear like the accept change was not registered.
