### ISSUE TITLE
NCSG - New Users

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#446]
New users are not able to log in when they create an account.  I have tried as well with the given user name and password.  When you try to log in it  it tells me it is an invalid user name or password.  I have gone in as the RC and made them a user but, that did not work either.  I thought when anyone registered they had access to view as an investigator.  I have included the screen grab of the email to the user.
[User Screen Grab.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/606259/User.Screen.Grab.docx)

**Comment by mebarrow** [comment]
The user has now logged in.  Was that there anything that you did or that I did?

**Comment by ecsion** [comment]
Will take this on email / phone.
