### ISSUE TITLE
Document Request Form - Email Issue

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#449]
Good afternoon, 

In a previous Issue we noted that in the Budgets form PIs were unable to add names that had an apostrophe. This afternoon I was trying to upload a letter of recommendation for an applicant and I was unable to add the referee's email address to the form because it also had an apostrophe "rob.o'reilly@XXXX.XXXX.XXX". I will ask the referee for another email address that we can use for this fellowship applications, but please address this issue when you can. 

Have a wonderful holiday!

Best,
Sam

<img width="819" alt="screen shot 2016-11-23 at 2 25 01 pm" src="https://cloud.githubusercontent.com/assets/17860369/20575766/b2b32ad4-b188-11e6-969f-b28bc0b02801.png">

http://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=763&mode=showTasksData&&tab_label=VASG%20GRF%20-%205%20Outreach%20Mentor%20Letter%20of%20Commitment&questionid=539

<img width="845" alt="screen shot 2016-11-23 at 2 31 07 pm" src="https://cloud.githubusercontent.com/assets/17860369/20575928/8964ba84-b189-11e6-81d0-8f05d25d601b.png">

**Comment by ecsion** [comment]
resolved. However holding to push to Virginia server till we get a green light from you.

**Comment by ecsion** [comment]
fixed.
