### ISSUE TITLE
RISG -- Budget Justification text not included with 90-4 budget form PDF output

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#450]
When user = ADMIN clicks the PDF EXPORT option under PROPOSALS, the PDF contains the budget output correctly, but the budget justifications page does not contain the actual justifications input when creating the budget/editing the budget worksheet. See link below for the PDF.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=RFPProposal&view=Detail&record=5854&mode=showBudget_90_4&tab_label=90-4%20(SG%20Admin%20Only)%20&tab_label=90-4%20(SG%20Admin%20Only)

below is a screen shot of one budget justification that should be included in the PDF file (there are several others not shown by the screen shot)

![screen shot 2016-11-28 at 11 43 38 am](https://cloud.githubusercontent.com/assets/18398763/20677129/14ea0c60-b560-11e6-98ce-1f157e1d94b9.png)

**Comment by ecsion** [comment]
noted, will get it done this week.

**Comment by ecsion** [comment]
done. Please check and reopen if you find any other issues.
