### ISSUE TITLE
Virginia SG Proposal Document Request

### ISSUE THREAD

**Issue by abigailhils** [ecsion/eSeaGrant-Client-Bug-Tracker#451]
Afternoon!

Almost have our first round of applications completed by 5pm today. 

One note is comes from requesting documents for Recommendation Letter Writers. The writers receive this email with a wrong date. 

Dear XXX,

Kenneth has submitted your name in relation to the 2017 VASG Graduate Research Fellowship.

Please click on the following link  here  to complete the request. We will need your input by 31 Dec 1969, 07:00 PM.

-->When the date should really be November 28, 2016, 5:00PM. I am not sure what happened, but if you can check up on this that would be lovely.

**Comment by ecsion** [comment]
We have done a hot fix for this. Please check and let us know if you still have this issue.

We have made several other updates which we will push once you remove the hold on new updates.
