### ISSUE TITLE
WSG: Add another "investigators"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#452]
1. Button at bottom of Investigators form says "Add another investigators." Please remove the final character, "s," in the button label (link and screenshot below relate to this item).
2. When adding another investigator, you should not be able to select them as a PI. Only the person logged into the system should be the PI.

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33601&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators
<img width="925" alt="screen shot 2016-11-28 at 10 03 43 am" src="https://cloud.githubusercontent.com/assets/17168836/20679990/04bcc1d8-b552-11e6-9daf-585dea28fa44.png">

**Comment by ecsion** [comment]
This has been fixed for Wa. We will fix for other programs this week. Also we have decided to give this control to sgadmin on locked forms.

**Comment by ecsion** [comment]
done.

**Comment by mgduke** [comment]
Deepak, on the investigator form, the PI can still specify another investigator as a PI. Unless you've heard objections from others about preventing the designation of additional PIs, as opposed to Co-PIs, can you make this change, too?

Also, have you enabled sgadmin access to locked forms yet? I don't think this is a super high priority, and I do have some concern that admins could really screw things up if they're not careful, but to do things like fixing minor typos, it does make sense.
