### ISSUE TITLE
WSG: Budget Worksheet Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#453]
1. Budget worksheet title does not save.
2. Other personnel "name" does not save.
3. Tabbing across fields is not logical.
4. Other cost name fields (below each dropdown menu) are not saving.
5. "Set default rates" buttons need to be hidden from PI view and need to be set by RC/Admin.
6. What's the meaning of the "Prevent this page from creating additional dialogs" message (a message we don't seem to get consistently, btw)?

Screenshot not really useful for this, but see following webpage:
http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=MzM2MDE=&id=588

**Comment by ecsion** [comment]
1 thru 4 done. Need conversation on 5. 6 is happening due to browser. we will need to remove javascript alerts and replace with custom alerts. This will take some time,
