### ISSUE TITLE
RISG -- Budget justification for Fringe Benefits does not save

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#454]
In the budget worksheet as USER = Investigator (see link below), when adding a justification for B. Fringe Benefits, the text is input and the SAVE button selected. No [Delete] option (in red) is visible after saving as it is for other options above it (see screen shot). AND upon opening the budget justification to edit it, the text just input has not been saved; the budget justification is empty. 

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

![screen shot 2016-11-28 at 1 28 16 pm](https://cloud.githubusercontent.com/assets/18398763/20681232/b10547ee-b570-11e6-8521-cf04b9e63232.png)

The program needs to save the budget justification when the SAVE button is selected. Thank you.

**Comment by ecsion** [comment]
done.
