### ISSUE TITLE
WSG: 90-4 Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#455]
1. No duration showing in overall 90-4 (combined 2-year total). Individual 90-4s do show duration.
2. When we download Component PDF's "Download Zip" from the "Upload Proposal PDF for reviews" page, we do not get an overall 90-4 and this is required.

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=33201&phaseid=33203&tab_label=Full-Proposal%20Setup
<img width="1282" alt="upload proposal for reviewers page" src="https://cloud.githubusercontent.com/assets/17168836/20681730/b3d22e18-b559-11e6-84f7-ce4d08ea6696.png">

**Comment by ecsion** [comment]
noted, will get it done this week.

**Comment by ecsion** [comment]
done.

**Comment by mgduke** [comment]
Still no duration showing in the downloaded overall 90-4. But we are getting three files now (overall and individual years), so that's good! So close, eh?
