### ISSUE TITLE
RISG -- Budget Worksheet Malfunctions

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#456]
Justifications are not saved for:
B. Finge Benefits
D. Expendable Supplies
E. Travel
F. Publications
G. Other

Input text is not saved for:
C. Permanent Equipment
G. Other Costs (does not save text for any item selected in the drop down)

JUSTIFY button (red) does not save and/or turn green text/gray box after saving a justification for:
B. Fringe Benefits
C. Permanent Equipment
D. Expendable Supplies
E. Travel
F. Publications
H. Indirect Costs

See link below for problem page. There are multiple problems with the budget worksheet, making it totally unusable by USER = INVESTIGATOR at this point. This must be corrected so that each fillable element of the budget worksheet functions properly (e.g., such as it does for Senior Personnel at top of budget worksheet. Thank you.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

**Comment by ecsion** [comment]
done, please check and let us know if this is working correctly for you.

**Comment by alandesbonnet** [comment]
It appears to be working correctly. However, a DELETE option must be added to  D. Expendable Supplies, E. Travel Domestic and F. Publications. Otherwise there is no way to clear these from the budget worksheet once entered. Thank you.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
As discussed, D, E & F cannot be deleted. We are working on new budget sheet that has a erase capability that will clear the data without having to delete the section itself.
