### ISSUE TITLE
OSG: Cannot view reviews on peer review tab

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#457]
From the admin side: When I select review on the top bar, and then select peer reviews under that it brings me to a page titled "PEER REVIEWS LISTING AND SCORES" (see link below). I can see the scores and averages for each proposal, but there is no where I can click that will bring me to the actual review a reviewer submitted. Whenever I click on anything in this tab it brings me back to the proposal, but not the review. I would assume that in the review tab we should be able to open completed reviews.

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=List&review_type=peer&tab_label=Peer%20Reviews

**Comment by ecsion** [comment]
We have changed how reviews are accessed. This tab is being removed. You can now access reviews by RFP Phase from The RFP detail page.
