### ISSUE TITLE
RISG -- Budget Worksheet Malfunctions #2

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#458]
See link on Issue #456 (or below) for this comment as well. 

ADD buttons should accompany each fillable budget line item. At present the following do not have the ADD button option, forcing the user to go to top or bottom of the worksheet and click the SAVE worksheet option, which is confusing and inconsistent with the rest of the worksheet. Please add the ADD button to the following budget lines:
D. Expendable Supplies
E. Travel 1. Domestic
F. Publications

Thank you.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

**Comment by ecsion** [comment]
Noted, we are updating the ux to add 3 buttons (as appropriate) : add, save, justify. This will take some time. Targeting to release this week.

**Comment by ecsion** [comment]
fixed.

**Comment by ecsion** [comment]
done
