### ISSUE TITLE
MASGC: Title and Keywords on Download output

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#459]
Thank you for making so many changes for us! The system seems to be running much more as expected lately. I have a couple more things for you related to the final output.

When the PI enters the Title and Keywords they now show up on the submission preview (Issue #441   thank you!) http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1086&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

However they do not show up anywhere in the download output.
The admin goes here:
http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=1069&phaseid=1071&tab_label=Pre-Proposal%20Setup
Selects "Download Zip"

and receives a folder with the forms and uploaded documents:

![dowload zip doesnt include title and keywords anywhere](https://cloud.githubusercontent.com/assets/22300443/20685500/50c63f46-b57a-11e6-8e89-9f356e8a8248.JPG)

Perhaps those two entries on the "Start Here" page:
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1086&mode=showProposalTitle&tab_label=Start Here&tab_label=Start Here

Could be turned into their own form?  Alternatively, it might be nice to have the submission preview come out as a downloaded form in the output folder for the admin.

This page could be pdf-ed and included in the forms downloaded.  
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1086&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

**Comment by ecsion** [comment]
noted, will get it done this week.

**Comment by ecsion** [comment]
done. Please check.
