### ISSUE TITLE
MASGC: Bullets and Paragraph returns don't show up in output properly

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#460]
This is directly related to Issue #423 

The output for the PI looks much, much better with the bullets and paragraph returns appearing properly! Thank you!  
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1086&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview
![paragraph returns look good on the submission preview labeled](https://cloud.githubusercontent.com/assets/22300443/20685781/776534da-b57b-11e6-9d72-08b5d3189ae4.jpg)

It also look right when the PI clicks "PDF this page"

However it does not translate into the downloaded pdf properly for the admin:
![narrative form output 2 labeled](https://cloud.githubusercontent.com/assets/22300443/20685941/2b10faf0-b57c-11e6-8c72-0a92425a961f.jpg)

Again, maybe the PI's "Submission Preview" would be good to include in the downloaded zip for the admin? (see my previous issue #459)

**Comment by ecsion** [comment]
done for proposals, please check. 

Still working on the same issue on some other places in the application. Will get it done throughout the application in couple of days.

**Comment by MASGCleist** [comment]
This looks much better! Thanks!

**Comment by MASGCleist** [comment]
![bullets correct](https://cloud.githubusercontent.com/assets/22300443/20715145/dbe81da8-b613-11e6-8355-9304b39cffd3.JPG)
