### ISSUE TITLE
RISG: Budget Worksheet Corrections Needed

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#462]
At the link below, and in the screenshot, the budget worksheet is calculating and posting a value for waived indirect. This should not happen as the Waived Indirect checkbox is not checked. I see that the value is added in and then subtracted out, but it would be better if NO VALUE were shown when the waived IDC box is NOT checked. Posting the value is confusing, and I suggest it only be shown when the box is checked.

Also, Indirect Cost is not being applied to the Grantee Share values. The indirect cost SHOULD be applied (at least for RI Sea Grant) to the Grantee amount, then shown in the appropriate place in the Grantee column on the far right. RISG can claim indirect costs on the grantee (match) portion of the budget, and then use that as further match. This correct MUST be made for the budget worksheet to be usable by RISG. Thank you.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

![screen shot 2016-11-29 at 11 09 42 am](https://cloud.githubusercontent.com/assets/18398763/20717972/47e9b21c-b625-11e6-86c1-08cf86dd5c6c.png)

**Comment by ecsion** [comment]
fixed. If still experiencing issue, please reopen this issue.
