### ISSUE TITLE
RISG: Budget Worksheet incorrect calculations

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#463]
The budget worksheet, as filled in at the link below, is working correctly EXCEPT for the following:

1.)  In H. Indirect Costs --- the line for Sea Grant Rates, the value in the Grantee Share column is shown as "0" [see screenshot]  but is should be the IDC Subtotal for Grantee ($22,701) * the IDC Rate (0.535) which is $12,145. This needs to be corrected, at least for RISG. I would presume other Sea Grant programs do the same but I cannot verify that. This value MUST be corrected to calculate as above for RISG to use the budget worksheet. 

2). In H. Indirect Costs --- the line for Inst. Rates shows a value of -29306 in the Grantee Share column. This value MUST be removed and should ONLY be shown, when the Waived IDC As Match check box is activated. At present, a fiscal approver will read this incorrectly, thinking it should be subtracted from the value for Total Direct Costs, and it should not and is not reflected as such in the Total Costs line. This is confusing, and will cause approvers to Deny Approval. 

These 2 items MUST be corrected. Thank You. 

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

![screen shot 2016-11-29 at 11 41 55 am](https://cloud.githubusercontent.com/assets/18398763/20719109/f37ce8ee-b628-11e6-8b14-44c85f7856e4.png)

**Comment by ecsion** [comment]
fixed in v1.5. Please reopen if still experiencing issue.
