### ISSUE TITLE
RISG: Budget Worksheet Correct for Waived Overhead box = Checked

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#464]
See link below and screen shot to make corrections to budget worksheet when Waived Indirect As Match check box is activated.

1. Grantee Share box (farthest right column) in H. Indirect Costs --- SG Rates should be 6,810 [Grantee Share (22,701)  *  SG Rate (0.30)  =  6,810]

2. Grantee Share box (farthest right column) in H. Indirect Costs --- Inst. Rates (with Waived IDC As Match activated) should be 5,335  [Grantee Share (22,701)  *  Inst. Rates (0.535)] - [Grantee Share (22,701)  *  SG Rates (0.30)] = 5,335  which is the correct amount of waived overhead.

3. Grantee Share for Total Costs should be 48,792  (Total Indirects Costs [36,647] + SG Rate Grantee Share [6,810] + Inst Rate Grantee Share [5,335]

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTg5NQ==&id=145

![screen shot 2016-11-29 at 11 58 15 am](https://cloud.githubusercontent.com/assets/18398763/20720206/4b70e08e-b62c-11e6-9417-56019a19575f.png)

**Comment by ecsion** [comment]
fixed.
