### ISSUE TITLE
OSG: Want to see peer review comments in PDF, not excel

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#465]
When looking at the reviews for a proposal (see link below) I can see the panel comments in a PDF export, but I can only view the peer review comments in an excel export. Our peer reviews have a lengthy written section, and therefore it would be much more convenient if we could view these in a PDF format rather than in excel.

http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=2373&tab_label=RFP%20Reports

**Comment by ecsion** [comment]
noted, we will get a pdf output for peer reviews this week.

**Comment by ecsion** [comment]
done. Please check and reopen if there are issues
