### ISSUE TITLE
RISG -- Budget Worksheet Calculation Explanation

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#466]
This post relates to Issue #464 and I hope clarifies the issue, and provides an understandable correction.

See screenshot below. ALL calculations are being performed correctly, as best as I can determine, EXCEPT as indicated in the screenshot. If that calculation can be corrected, it appears that the budget sheet is acting correctly otherwise.  This MUST be corrected for the budget worksheet to be usable. 

Also as noted in the screenshot, the indicated value associated with the Waived IDC As Match checkbox, is calculated correctly, but SHOULD NOT BE SHOWN when the associated box is not checked. While all calculations are correct, the value being visible when it is not being used in calculations is very confusing and is sure to cause rejection of budgets by approvers. The also MUST be corrected.  Thank You.

![screen shot 2016-12-01 at 10 30 01 am](https://cloud.githubusercontent.com/assets/18398763/20799748/2504e7fc-b7b1-11e6-994b-d68a24826b55.png)

**Comment by ecsion** [comment]
fixed in v1.5 release. Please reopen this issue if not fixed.
