### ISSUE TITLE
WSG: SG Classification and Focus Area form

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#469]
We are confused: In the RC/Admin view, the SG Classification, Awards and Affiliations fields are visible, but in the PI view, none of these 3 fields are visible.
The PI needs to see the Classification field — please restore. And, we (SGs) have already agreed that neither PI nor RC/Admin need the Awards and Affiliation fields — please remove them.
URL is Admin view:
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33601&mode=showClassification&tab_label=SG%20Classification%20&%20Focus%20Area=&tab_label=SG%20Classification%20&%20Focus%20Area

**Comment by ecsion** [comment]
Could we make this a custom form? This way you will have flexibility to show all fields to PI or select some to hide. However, in that case, you will have to add SG classifications and focus area pick list in the custom form. Please advice.

**Comment by ecsion** [comment]
We have added sg classification & sg focus area questions that you can use to build your own custom form.
