### ISSUE TITLE
WSG: Budget Worksheet Default IDC Rates

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#470]
Please remove "Set Default Rates" buttons for PI view.
Default rates should be set by RC.
New feature: Please add IDC default rates to the Budget Periods Setup page (this is similar to old system, which combined budget periods and rates in one lookup table - see screenshot).
http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&record=33593&mode=showDurations&tab_label=Budget%20Periods
<img width="925" alt="screen shot 2016-12-01 at 9 53 27 am" src="https://cloud.githubusercontent.com/assets/17168836/20805567/07bc19d6-b7ac-11e6-9558-3613e24f1cf8.png">

**Comment by ecsion** [comment]
The IDC rates are split by section in the budget sheet. However, this view does not split the idc rate by section. Please advice.

Once we have clarity we will scope this change. May need couple of weeks to do.

**Comment by ecsion** [comment]
done.
