### ISSUE TITLE
WSG: Investigators Form — Only Can Add "Co-PI"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#471]
Sorry, but we don't understand what the problem is with limiting the Investigator form dropdown menu to being only Co-PI. 
First, the person logging into the system should automatically be locked into being the PI on this page (i.e., cannot change first entry in form from PI to Co-PI).
Assuming you can oblige:
 a. eliminate the "Role" dropdown menu entirely
 b. change the "Add Additional Investigator" label to "Add Co-PI"

**Comment by ecsion** [comment]
the issue is that currently the forms don't have the ability to gather data from the proposal.

**Comment by mgduke** [comment]
Confused - we are not talking about gathering any data from the proposal.  Current form behavior has the person logged into the system automatically filled out as "response 1" in the investigator form.  All we are asking is that this person be locked as the PI, and any additional people added be Co-PIs.

**Comment by ecsion** [comment]
Looking into this. We will update you later this week.

**Comment by mgduke** [comment]
Solve by separating PI and co-PI forms.
If you edit these forms, it back-saves to the People record.

**Comment by ecsion** [comment]
done.
