### ISSUE TITLE
WSG: Critical—Show/Hide Toggle for Justification Buttons on Preproposal Worksheets

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#472]
We established that some grants will (or likely will) need the justifications feature in a preproposal budget worksheet. But we absolutely do not want those.
Therefore, please enable toggling for the justification function.

**Comment by ecsion** [comment]
noted, will add.

**Comment by ecsion** [comment]
done.
