### ISSUE TITLE
WSG: Wrapping up #113 (Hauser)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#473]
For Lorenz Hauser, move all projects from  lhauser@u.washington.edu at:
http://esg.wsg.washington.edu/index.php?module=People&view=Detail&record=53&mode=eSeaGrantHistory&tab_label=eSeaGrant%20History

to lhauser@uw.edu
http://esg.wsg.washington.edu/index.php?module=People&view=Detail&record=477&mode=eSeaGrantHistory&tab_label=eSeaGrant%20History

**Comment by ecsion** [comment]
noted.

**Comment by ecsion** [comment]
Marcus, can you check if this is completed and if so can you please close.

**Comment by mgduke** [comment]
Checked; confirmed; closed. Thanks much!

 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
