### ISSUE TITLE
WSG: Investigator Form—Add investigator required fields misbehavior

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#475]
When adding another investigator, it does not let you save without uploading a CV, which is good.

But the required field error message points to the phone field _whether it has data or not_ and this field is supposedly not required.

I pondered whether autofill was the culprit, but on manually retyping all fields on both existing and brand new forms, I had the same problem. And after manually _retyping_ the phone field, I still get the error message.

If you then attach a CV (without filling out phone field), the error goes away and allows you to save. So, system is working properly, but telling you wrong things in reference to the error.

Also, I often get multiple alerts (seems to happen when I trigger multiple alerts for the same field but not positive), but the red-alert arrow only appears over one field. I then tested by just uploading a CV but filling in no fields otherwise, and then I got three red alerts (first name, last name, email) above their respective fields, but _no alert for affiliation_.

FYI - this red bubble going in the wrong place happens in multiple forms.

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33443&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

**Comment by ecsion** [comment]
The recent changes has caused this bug. we will get this fixed by the end of the week.

**Comment by mgduke** [comment]
Some things seem fixed, but submittal process no longer throws up alerts (e.g., I deleted the narrative pdf but submittal did not provide me an alert).

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
OK, good progress (no phone field issues now) and maybe we can live with this as is, but I have several observations:

There is no alert arrow any more, having been replaced but what I assume is a javascript onFocus to place the cursor in the missing field. But this can't work for the Upload's "Choose file" button. 

Further, if multiple fields are missing, the user may not know this because (presumably) only the first one in the form gets focused. User has to fill in this first missing field, but potentially may then try to submit again, at which point the next missing field will be focused. 

Is there any way to have the alert text do one of the following:
1. Ideal—list the missing fields.
2. Next best—change if >1 field is missing. 
3. Least best but easy—change the alert text to "Required field**(s)** cannot be empty"?

**Comment by ecsion** [comment]
Validation for required fields has been totally overhauled in the new custom form update. There are no longer red bubbles.
