### ISSUE TITLE
MIT:  PI's Current Tasks view

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#476]
The current tasks list does not tell the PI what project s/he is being asked to report on. Please replace the current listing with this

Report on:  [Project Title]
2017 Staff Reporting Deadline: 01 Apr 2017, 12:00 AM
Instructions PDF  Start Report

old view: 
[CurrentTasks.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/627950/CurrentTasks.pdf)

**Comment by ecsion** [comment]
done.
