### ISSUE TITLE
WSG: Submit Proposal Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#477]
In trying to submit a proposal (see link), we found several issues with the “Some forms have not been completed!" warning:
 1. Alert says Investigators form is not complete, but it is…repeated attempts to ensure Investigator form really _is_ complete (e.g., retyping all fields) do not prevent the alert from recurring.
 2. If we complete a form (e.g., add a narrative file), but then “uncomplete” it (i.e., delete the very narrative file that you uploaded), then we do _not_ get a warning about that form, even though that form is now incomplete.
 3. PI info is automatically loaded into Investigators form, but CV is not included, which may be deliberate, but we get no warning on submitting the proposal if we hadn't uploaded a CV for the PI.

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33443&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission%20Preview
![screen shot 2016-12-02 at 10 36 30 am](https://cloud.githubusercontent.com/assets/17168836/20845992/6a27914c-b87c-11e6-9d2a-897c8bfd38ee.png)

**Comment by ecsion** [comment]
fixed.
