### ISSUE TITLE
WSG: Proposal Information form feature requests

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#479]
On the Proposal Information form (initial title page - “Start Here”):
 1. There is a keyword field already on this form - can that field populate the “keyword” field on the 90-2 output?
 2. Can we add Project Initiation and Project Completion Dates (date pickers) fields to this form?  And have those be what populates same fields on the 90-2 output?

**Comment by ecsion** [comment]
noted.

**Comment by mgduke** [comment]
Needs to flow into the 90-2 PDF form (not into the 90-2 custom form).

**Comment by ecsion** [comment]
done.
