### ISSUE TITLE
WSG: Remove "Import Data" from Investigators

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#480]
There is never a situation where we want to copy Investigators data from one proposal to another, only from preproposal to full proposal for the same proposal.

Thus, can you remove the "import data" button?

We think the Investigator data entered in the preproposal is already automatically advanced to the full proposal stage, but please confirm. If it is auto-advanced, this obviates the import data function.

**Comment by ecsion** [comment]
Instead of removing this feature, we will instead give you a selection when designing the custom form.
