### ISSUE TITLE
WSG: Remove Grantee and Include 90-4 Fields from Submission Preview

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#481]
Please remove the "Grantee" and "Include 90-4" fields from the submission review page (i.e., PI view). They are irrelevant to the PI (first is self-evident, and RC can access 90-4 through his/her interface). This was done for the budget worksheets, and no one objected, so we infer doing the same for the preview also shouldn't raise objections.

**Comment by mgduke** [comment]
Deepak, it looks like you effected this change already, but you didn't close the comment yet, so I'm hesitant to do so in case you had any remaining questions/issues.

**Comment by ecsion** [comment]
done.
