### ISSUE TITLE
WSG: RC Hide unselected forms from contextual (vertical) menu

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#482]
As an RC/Admin, when we view a proposal (via the RFP/Pre-Proposals "View Proposal Listing" box or from the proposal list page itself), forms that we did not select for the given RFP appear in the contextual (vertical) menu. We REALLY don't want to see these.

Using the below URL for example, we selected the following forms:

90-2, Investigators, Narratives, Suggest Reviewers, Budget Wksht

But we're seeing a lot more forms than those in the menu (e.g., Project Summary, SG Classification & Focus Area). 

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33730&mode=showProposalTitle&tab_label=Start%20Here&mode=showProposalTitle&tab_label=Start%20Here

**Comment by ecsion** [comment]
done.
