### ISSUE TITLE
WSG: 90-2 form "project number" field should not be required

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#483]
On the 90-2 form, the project number is currently a required field (and populates the 90-2 output form).

However, proposals do not get assigned project numbers until they are selected for funding. So, this field should not be required at this point in the process.

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33730&mode=showMultiQuestionStem&QuestionId=1&tab_label=90-2%20Form&tab_label=90-2%20Form

![screen shot 2016-12-02 at 12 23 22 pm](https://cloud.githubusercontent.com/assets/17168836/20849164/323a1738-b88a-11e6-9eb1-bb2908e6b9ac.png)

**Comment by ecsion** [comment]
done.
