### ISSUE TITLE
OSG: Cannot see instructions for letters of commitment

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#484]
Earlier I had this issue with instructions not being visible to the applicant for letters of recommendation. That got fixed, but now I am having the same problem for instructions for letters of commitment not being visible to the applicant or to the admin.

This is the view from the applicant side: http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2822&mode=showMultiQuestionStem&QuestionId=2796&tab_label=Sea%20Grant/NMFS%20Fellowship%20Letter%20of%20Commitment&tab_label=Sea%20Grant/NMFS%20Fellowship%20Letter%20of%20Commitment

When previewing the form from the admin side you can't see the instructions either: http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=2789&phaseid=2791&tab_label=Fellowship%20Application%20Setup

Looking at the form I created on the admin side I CAN see the instructions: http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=Detail&record=2796&viewname=213&showList=RFP&show_retire=

**Comment by ecsion** [comment]
The custom form is required to have atlas 1 question. Your form had none and so instructions were being hidden. A section separator also suffices. So we have now added a section separator and now the instructions are showing.
