### ISSUE TITLE
MITSG:  Individual project view link to proposal

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#485]
Remove the first two lines from the individual-project view: “Proposal Information” and “Proposal Title”
Add a quicklink “Proposal” that bounces you back to the proposal for that project.

![coverpage](https://cloud.githubusercontent.com/assets/17729848/20934076/ecd04b2e-bba7-11e6-942a-1b7d8464dd19.gif)

**Comment by ecsion** [comment]
noted, will add.

**Comment by ecsion** [comment]
done. Please check and reopen if this is still an issue. Please provide additional comments in case you reopen the issue.
