### ISSUE TITLE
OSG: Browse button not visible to letter of commitment writer

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#487]
Applicants for a fellowship send their mentor a document request to submit a letter of commitment. When the letter writer opens the link in the email to complete the request the browse button is not available to upload a document. The save and submit button are still available, but you cannot save or submit a document if you can't upload one in the first place. See link below.

http://eseagrant.oregonstate.edu/operations.php?action=responseform&guid=0C550DC6-F01E-4A2E-960B-422AEC6E4920

**Comment by ecsion** [comment]
Haley, you don't have a file upload question added is why there is no browse button. Once you add a file upload question, you will then see a browse button. I have added a file upload question for you and now the file selector is appearing.
