### ISSUE TITLE
OSG: Not able to submit letters of recommendation

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#488]
An applicant for a fellowship sends a document request to someone for a letter of rec. That letter writer receives an email and clicks on the link to submit their letter. The writer uploads their letter, clicks save, and then clicks submit, however, nothing is happening when she clicks submit. The status at the top still says "not submitted" and no follow-up email is being sent stating that the letter has been submitted. See link below.

http://eseagrant.oregonstate.edu/operations.php?action=responseform&guid=0C161B7A-11E9-4CC6-95D6-5C8BB38BADD2

**Comment by ecsion** [comment]
fixed.
