### ISSUE TITLE
OSG: Multiple issues with applicant adding/editing documents for fellowship

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#489]
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2822&mode=showMultiQuestionStem&QuestionId=2794&tab_label=Sea%20Grant/NMFS%20Marine%20Resource%20Economics%20Fellowship%20Application

From applicant side. An applicant for a fellowship uploads their multiple, individual documents for the fellowship. If the applicant then tries to edit one document, they are unable to because it changes all documents previously uploaded to the one new document they just uploaded. Additionally, the applicant should be able to delete each document individually, not only have the option to delete all uploaded documents. See link above and explanation with screenshots attached.
[Doc Upload Issue.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/634862/Doc.Upload.Issue.docx)

**Comment by ecsion** [comment]
File upload issue is resolved. We are currently doing delete for files. It will neb done by end of week.

**Comment by ecsion** [comment]
We are working to change UI for custom forms for the applicant side . This is taking some time. The delete will be available when new UI is released. We will have this done before Jan 1.

**Comment by ecsion** [comment]
done. If not fixed, please reopen or add a new issue.
