### ISSUE TITLE
OSG: Cannot easily input decimal value in budget for benefits %

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#490]
From the applicant view filling out the budget:

http://eseagrant.oregonstate.edu/operations.php?action=budget&guid=6AC654AD-AAF3-4920-AE7F-3B278BDEA8C9&proposal_id=MjgyMg==

In the second column "Benefits %" it says to enter a decimal value "(Decimal: 0.XX)". However, when you attempt to start the entering in a decimal value the decimal keeps getting deleted. The only way to get a decimal in there is to write a number in the box, and then go to the beginning of that number and insert a decimal. This will likely be confusing to applicants.

**Comment by ecsion** [comment]
please start with a number then a decimal. So instead of **.5** type in **0.5** and it will work.
