### ISSUE TITLE
OSG: When clicking "save" in budget, most of the filled out budget disappears

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#491]
From the applicant view: After filling out the beginning of the budget form on the budget tab for a fellowship application I clicked save. After the page refreshed I could no longer see any numbers that I had entered into the budget form.
http://eseagrant.oregonstate.edu/operations.php?action=budget&proposal_id=MjgyMg==&id=24

 The numbers I had previously entered were still visible in the budget summary, and under "list of budget worksheets" on the budget tab as a summary. 
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2822&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets 

One last side note, when I go to the budget tab and click on "view" under justification it opens up a new window with my budget justification. The name displayed on that new tab is "MIT Sea Grant College Program". We might want to change this to something more intuitive like "Budget Justification" to avoid confusion for applicants not applying through the MIT program.
http://eseagrant.oregonstate.edu/operations.php?action=justification&id=24

**Comment by ecsion** [comment]
This was due to budget sheet being saved without selecting pi/co-pi from dropdown. We have now made some changes so this issue won;t occur.

**Comment by epperlyh** [comment]
How can you select a pi/co-pi from the dropdown? When I go to "select personnel" there is no one for me to click on so I have to leave it as is. (see screenshot attached)

http://eseagrant.oregonstate.edu/operations.php?action=budget&proposal_id=MjgyMg==&id=24
[Select Personnel Error.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/640966/Select.Personnel.Error.docx)
