### ISSUE TITLE
MITSG:  For PI in RFP - Change Task sequence and title

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#492]
When the PI comes in to do a proposal:

**FIRST** TASK in left nave panel and in the sequence of forms = INVESTIGATORS
CHANGE "Key Personnel" to "Additional Personnel"  (most proposals won't have any entries for this - it's almost irrelevant) and make it the **second** task

**Comment by ecsion** [comment]
done.
