### ISSUE TITLE
MIT - Correction to Excel Sheet download in RFP Reports 

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#493]
In RFP, under RFP Reports - http://eseagrant.mit.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=32772&tab_label=RFP%20Reports

The second and third download choices...
     Panel Comments and Score (Excel Export) and 
     Panel Score (Excel Export) 
...should pull info for either all the Pre-proposals **OR** all the Full Proposals. Please make sure they are pulling the right data - I have no test data and correct the Header on the sheets to
     "Panel Review - Comments and Scores" 
     "Panel Review - Average Scores"

**Comment by ecsion** [comment]
not an issue. If you find some issue, please reopen.
