### ISSUE TITLE
WSG: File naming convention

### ISSUE THREAD

**Issue by ghost** [ecsion/eSeaGrant-Client-Bug-Tracker#494]
We request a file-naming convention be applied to eSG files as follows:

	[PI LastName]_[RFP Short Title]_[Pre/Full]_[####]_[file type abbr].pdf

where #### = auto-assigned and auto-incremented ID (e.g., assigned by MySQL). For example:

	Duke_RFP 2017_Pre_1313_narr.pdf

And for the file type naming conventions, we would propose:

narr
90-2
90-4
res_lastname
sppt
BW
sched
CP
sub1-lttr
sub1-budg
sub2-lttr
sub2-budg

Note we conferred with other SGs over this and received no objections, only some suggestions over details, which we've applied.

**Comment by mgduke** [comment]
Deepak, please let us know if the filename abbreviations are not obvious.
