### ISSUE TITLE
r2.0: WSG: PI Revision Phase

### ISSUE THREAD

**Issue by ghost** [ecsion/eSeaGrant-Client-Bug-Tracker#495]
Request new feature: PI revision (i.e., after deadline has passed) phase with ability to open for revision on an individual proposal basis.

This is to enable PIs to make changes after the call has closed, rather than requiring us to (1) reopen the call for everyone (bad) or (2) implement the changes for the PIs.

**Comment by ecsion** [comment]
Noted, we will add in R2
