### ISSUE TITLE
WSG:  Budget Worksheet Functionality When Other Costs (G) = Sub-award

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#496]
IDC needs to be calculated correctly across budget worksheets when using the "sub-award" item: That is, calculate IDC on first $25K of sub-award/subcontract only. For example:

If $10K to “Example Sub-award Institution A” in Year 1 and $20K to “Example Sub-award Institution A” in Year 2, then:

Calculate IDC on whole amount in Year 1
Calculate IDC on only $15K of Year 2

Moreover, a revision to Year 1 must be dynamically reflected in the calculation for Year 2 budget. For example:

If you then change the Year 1 allocation for “Example Sub-award Institution A” to $15K, then:
Year 2 IDC automatically recalculates to only charging IDC on $10K of Year 2 funds

Our understanding is that this relationship was effected by the use of identical sub-award “labels” in year 1 and year 2 worksheets in the old system (i.e., the label text became the ID by which Year 2 could then complete the IDC calcs). This worked by having the Year 1 subaward label (e.g., “Example Sub-award Institution A”) be automatically made available in Year 2 (see 1st screenshot).

If we implement this functionality and ensure everything is working as expected, please (1) remove the $25k alert (see 2nd screenshot) for the Sub-award AND (2) remove the “Sub-award NOT subject to indirect” option altogether (3rd screenshot).

![subaward-no-1](https://cloud.githubusercontent.com/assets/17168836/21030187/1986e88e-bd52-11e6-8bc2-f5d960bd8e0e.jpg)

![subaward-no-2](https://cloud.githubusercontent.com/assets/17168836/21030200/2369bf5c-bd52-11e6-9ab5-3ce99a7be284.jpg)

<img width="1046" alt="screen shot 2016-12-08 at 2 30 15 pm" src="https://cloud.githubusercontent.com/assets/17168836/21030386/0e8728b2-bd53-11e6-96e0-f0bcc9fdcddd.png">

**Comment by mgduke** [comment]
Deepak, just to be sure we're following protocol: now that we posted this, we need to discuss with other SGs before moving forward.

**Comment by ecsion** [comment]
replaced by #522
