### ISSUE TITLE
WSG: Sub-award Scope of Work and Budget Documentation

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#497]
The current budget worksheet does not have any way to upload/attached sub-award scope of work and budget documentation. We attach a screenshot that shows the interface for doing this in the old system. However, we are open to suggestions for alternative, and hopefully better, ways to accomplish this. 

Note: The old system only supported PDF upload, but we would much prefer that the sub-award budget upload function allow, or even require, Excel files.

Let us know if you need more info than what the screenshot provides (sorry, no URL is easily available for you).

<img width="650" alt="screen shot 2016-12-08 at 2 35 21 pm" src="https://cloud.githubusercontent.com/assets/17168836/21031508/b394be78-bd58-11e6-8664-b181aef659be.png">

**Comment by ecsion** [comment]
Marcus In the new budget sheets, we can provide for uploading sub award SOW.  

Don;t totally follow how for budget template would work. Would you load the budget template for each phase and then they will complete it and upload it in case of sub awards?

Need to discuss.

**Comment by mgduke** [comment]
Yes, Kate and I will go over your voicemail and below tomorrow morning and get back to you. 

Sorry for the delay on resolving the over budget issues/needs, but as you likely saw, eSeaGrant Whip Kathy put the brakes on us and scheduled a summit for 5-6 SG members to hammer out how the budget worksheet/sub-awards will work next Tuesday. That’s the best we could do, given we’re coming up hard on the holiday break.
 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator
Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by mgduke** [comment]
Deepak, following up on your phone call from yesterday, we respond:

You are correct in that there are three things on that sub-award justification interface:

1. Statement of Work file upload

2. Sub-award budget upload

3. This is the justification text, which in the past has been entered in a text box just the same as all the other justification text boxes (and this is shown at the very bottom of the screenshot we uploaded to #497). The only difference from the other justif fields is the justification in this box needs to cover ALL budget categories for the subaward. A potential alternative could be that there is a separate budget justification upload, similar to (1) and (2) above, for uploading a PDF. The important question is “How does this budget justification get integrated into the larger budget justification file (i.e., 90-4 printout).

Attached highlights example sub-award content as part of the 90-4.

[90-4 subaward example.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/655921/90-4.subaward.example.pdf)

**Comment by ecsion** [comment]
replaced by #522
