### ISSUE TITLE
WSG: Awards to Non-Home Institution PI

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#498]
This is what question #4 at the top of the budget worksheet refers to (see 1st screenshot). Note: the new system text currently reads "Does this award include a sub-award?", but that is not the right question. In the old system, it read "Is this award to a non-UW investigator?"

This is important, because these awards officially get processed with the SG director as the PI and the entire award as a sub-award to the non-UW investigator.  Therefore, addition 90-4 documentation reflecting this is required.

In the old system, when the investigator answered "Yes" to question #4 it activated the little green "sub award cover page" button in the FileMaker interface (see 2nd screenshot).

When you pushed that button it automatically created a new 90-4 with the SG director as the PI, University of Washington as the Grantee, and the total award amount included on the sub-award line of the budget (see 3rd and 4th screenshots).

Then when 90-4s were exported, you got an overall 90-4 for University of Washington and an overall 90-4 for non-UW investigator institution (see 1st PDF attachment); and duplicate individual year 90-4s as well (see 2nd PDF attachment).

In addition, because the entire award is essentially turning into a sub-award, we need somewhere to add the additional IDC (sub-awards are charged UW IDC on first $25K).  This is something that we never figured out how to do elegantly in the old system... so could think about how this could best be handled in the new system.

And finally, in omnibus preparation, it was essential to be able to "turn the duplicate 90-4s off" for the purposes of calculating the full omnibus summary 90-4 so that this award did not get double-counted (see 4th screenshot).

<img width="907" alt="web-worksheet-greenbutton" src="https://cloud.githubusercontent.com/assets/17168836/21032840/1eb92a06-bd61-11e6-8fd5-2d60c0b08860.png">

<img width="845" alt="fm-budgets" src="https://cloud.githubusercontent.com/assets/17168836/21032845/369d7a1e-bd61-11e6-98a5-995878babe50.png">

<img width="860" alt="fm-budgets-postclick" src="https://cloud.githubusercontent.com/assets/17168836/21032850/4bac1884-bd61-11e6-8d7e-1403aff2e6f0.png">

<img width="884" alt="green-button-worksheet 90-4" src="https://cloud.githubusercontent.com/assets/17168836/21032970/16330a86-bd62-11e6-9f15-b7a64569480d.png">

[Stark_9756_90-4s.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/640889/Stark_9756_90-4s.pdf)

[Stark_9756_Overall_90_4s.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/640888/Stark_9756_Overall_90_4s.pdf)

**Comment by mgduke** [comment]
PS: We KNOW you are going to be confused about this (hell, we are!), so when you're done trying to absorb this and have picked yourself up off the floor, let's schedule a time (probably with Join.me) to go over this in real time with you, Kate and me.

**Comment by ecsion** [comment]
replaced by #522
