### ISSUE TITLE
RISG---4 Year Projects show only 2 Year budget values in Project Module

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#499]
while most research projects reflect a 2-year span, several "core" projects, such as Program Administration, Communications, etc. reflect a 4-year time horizon. At present, in Project Module, 4-year projects only show values for the first 2 years as shown in the screenshot below, and at this link:

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=Projects&view=Edit&record=547

![screen shot 2016-12-12 at 10 19 44 am](https://cloud.githubusercontent.com/assets/18398763/21104560/036bfe76-c055-11e6-8565-56b7205a3d5d.png)

Project End Date correctly shows 1-31-2018. Summary Information for the project should show SG and Match values for each year of the 4 year project timeline. Thank You.

**Comment by ecsion** [comment]
Alan, Currently we support only 2 years budget. Could you use Budget notes to save the info for year 3 & 4?
