### ISSUE TITLE
WSG: Small budget worksheet bugs 

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#500]
1. We are unable to change the subaward title (under section G) once entered.

2. As we noted with you via phone, some of the worksheet tabbing is not logical:
    For example, if you focus on a description field under G. Other Costs, and then tab, this action takes you to the top of the page.
    Focus on the "Enter Full Name" field under A. Salaries and Wages, and tabbing takes you to a G. Other Costs field.

3. Benefit rates: "0." is required in typing this into the fields. Either make it so we can just start with the decimal (.xx), or provide a note or tooltip indicating the "0." is required.

Sample worksheet:

http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=MzM3MzA=&id=600

**Comment by ecsion** [comment]
Noted, we will fix this in the new budget sheet implementation.

**Comment by ecsion** [comment]
done. Please start a new issue if there are aspects not fixed.
