### ISSUE TITLE
OSG: Email CCed to me when applicants submit their proposals on eSeaGrant

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#502]
I am being sent an email whenever applicants submit a fellowship application on eSeaGrant, but I'm not sure why. (My email address is haley.epperly@oregonstate.edu.) I did create these fellowship RFPs in the system, but I don't remember selecting any box that would make it so I was sent an email whenever applicants submitted their applications. The email announcements are also being sent to the email address we created for this purpose, eseagrant@oregonstate.edu. I only want updates sent to the eseagrant email address, not to my email address. How do I make this happen?

**Comment by ecsion** [comment]
Haley, currently we don;t have a setting to disable emails to the SGAdmin who created the fellowship application. We will add a setting in R2 for this.
