### ISSUE TITLE
URGENT - MASGC Form no longer appearing in download

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#503]
Related to Issue #360 
We want to have everything working right before we release our RFP by the end of the week. Our hope was to have it all set up by Wednesday so we could make minor tweaks Thursday, A number of things were working as we planned but now suddenly they are not.

Example: This was working fine a couple of weeks ago but something changed recently and its no longer working.

We ask for a few custom forms and a couple of mandatory forms:
Investigators (mandatory)
Support Letters (mandatory)
Commitment Form (custom)
Budget Workbook (custom)
Narrative form (custom)

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1533&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

![narrative form required](https://cloud.githubusercontent.com/assets/22300443/21150505/c970caf0-c124-11e6-9550-22b0c44bdb73.JPG)

When we go in on the admin side we no longer get a list of the investigators like we used to, just the CVs.
AND we don't see our "MASGC Preproposal Narrative Form" at all.  It doesn't show up in the Download Zip.  This document is the meat of our proposal and we need to see it.

We go here:
http://eseagrant.masgc.org/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=1451&phaseid=1453&tab_label=Pre-Proposals

![download zip](https://cloud.githubusercontent.com/assets/22300443/21150673/6e72db06-c125-11e6-906e-ed6f7cd58f4d.JPG)

This is what we see in the zip:
![zip output](https://cloud.githubusercontent.com/assets/22300443/21150717/9a407bc6-c125-11e6-85eb-e84c295a301e.JPG)

ALSO: We don't ask for the (mandatory) 90-2 but it shows up here anyway and we would like it not to.

Summary: 
1. requested forms with text don't show up in admin output, seems to work for forms with attachments (CVs and support letters, and budget excel file)
2. 90-2 shows up in output and shouldn't because we didn't request it.

**Comment by ecsion** [comment]
This was done based on the following basecamp request. https://basecamp.com/2782140/projects/13305906/messages/64715723
We will reverse this for now and discuss this in basecamp for a solution that works for all programs.

**Comment by ecsion** [comment]
reversed for now.
