### ISSUE TITLE
MASGC: dates don't show up in output

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#504]
Related to issue #459 

Project dates are now requested on the main proposal page:
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1533&mode=showProposalTitle&tab_label=Start Here&tab_label=Start Here

However, they do not show up on the admin download output but the title and keywords do:

![title and keywords show up but not dates](https://cloud.githubusercontent.com/assets/22300443/21150983/808ab0ba-c126-11e6-8572-0afaffc4dacc.JPG)

**Comment by ecsion** [comment]
Noted. We will keywords and date fields to output.

**Comment by ecsion** [comment]
done.
