### ISSUE TITLE
"Download Proposal Docs Zip" button does not include letters

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#505]
We are currently downloading all of our fellowship applications; however, when we click the "Download Proposal Docs Zip" button on the Proposal Summary form it does not include the recommendation letters and letters of commitment as part of the zip file. We have had to go back and individually download the corresponding letters for each application separately.  We are working around it, but I am sure that other programs (including us in the near future) would like to download all of the documents and letters at once.

Thanks in advance for anything you can do to help streamline that process! As always, please let me know if I can clarify or help.

Best,
Sam

http://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=891&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Proposal%20Summary

![screen shot 2016-12-13 at 12 19 08 pm](https://cloud.githubusercontent.com/assets/17860369/21150838/6c295812-c12e-11e6-8f20-a5f1fe7b8734.png)

**Comment by ecsion** [comment]
Noted. This was a oversight and we are fixing it now to include uploaded letters.

**Comment by ecsion** [comment]
done.
