### ISSUE TITLE
OSG: Unable to "select personnel" from "senior personnel" dropdown in budget form

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#506]
I reported an issue with budgets not working and you provided an explanation of why they were not working (see correspondence via GitHub below). I am still having issues with the budget working, so I commented on this issue you had closed last week, but I have not heard anything back so I decided to create a new issue (see Update to issue below).

**Update to issue:**

How can you select a pi/co-pi from the dropdown? When I go to "select personnel" there is no one for me to click on so I have to leave it as is. (see screenshot attached)

http://eseagrant.oregonstate.edu/operations.php?action=budget&proposal_id=MjgyMg==&id=24
Select Personnel Error.docx

**My original issue:**

From the applicant view: After filling out the beginning of the budget form on the budget tab for a fellowship application I clicked save. After the page refreshed I could no longer see any numbers that I had entered into the budget form.
http://eseagrant.oregonstate.edu/operations.php?action=budget&proposal_id=MjgyMg==&id=24

The numbers I had previously entered were still visible in the budget summary, and under "list of budget worksheets" on the budget tab as a summary.
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=2822&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets

One last side note, when I go to the budget tab and click on "view" under justification it opens up a new window with my budget justification. The name displayed on that new tab is "MIT Sea Grant College Program". We might want to change this to something more intuitive like "Budget Justification" to avoid confusion for applicants not applying through the MIT program.
http://eseagrant.oregonstate.edu/operations.php?action=justification&id=24

@ecsion
Owner
ecsion commented 6 days ago

This was due to budget sheet being saved without selecting pi/co-pi from dropdown. We have now made some changes so this issue won;t occur.

**Comment by ecsion** [comment]
We are adding a note below the Key Personnel dropdown.
Note: This dropdown is populated from values in Investigators form & Additional Personnel form.

This should clear the confusion.

**Comment by epperlyh** [comment]
Thank you for explaining that. In some of our fellowship forms we require a budget, but we do not use the investigators form. Are we required to use the investigators form if we wish to also have the PI/applicant create a budget?

**Comment by ecsion** [comment]
Looking into this. We are investigating adding PI or Fellowship Applicant automatically without a need for Investigator form.  This will take some time.

**Comment by ecsion** [comment]
done. Please reopen if you still have an issue. Please provide screenshot and links if you reopen the issue.
