### ISSUE TITLE
Uploaded File Unaccessable due to Apostrophe 

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#507]
We just finished downloading files for our fellowship and I wanted to relay an issue we noticed with one of the associated files. The file had an apostrophe in the file name (see below)- although we could see the file name on eSG (and that it had been uploaded before the deadline) we were unable to download the file as part of the fellowship application. 

For your reference the file name was "Rob O'Reilly CV.docx" 

I have already reached out to the PI and asked for a copy of the file (removed the apostrophe) and uploaded it to their application.

http://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=763&mode=showMultiQuestionStem&QuestionId=535&tab_label=VASG%20GRF%20-%201%20Resumes%20or%20CVs

**Comment by ecsion** [comment]
Noted. Apostrophes and special characters in file names gets tricky to manage. So we will put a validation check in uploaded files to disallow apostrophes.

**Comment by ecsion** [comment]
We now remove special characters from uploaded file names.  Please check. Old uploaded files may still be an issue. If you let us know which ones, we can manually fix them.
