### ISSUE TITLE
Email Templates: PEOPLE 'honorific' field, please add

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#508]
Some Admins would like to use the honorific form the PEOPLE record in email templates.

1. If necessary, add an "Honorific" field
2. Make that field available to all email templates

**Comment by ecsion** [comment]
Noted. Adding a new fields to People -- Title (Salutation) which will hold Dr., Mr, Miss etc. or can be empty . This field will be available in email templates.

**Comment by ecsion** [comment]
Added Salutation field to People. We are working to change the templates. Need a few days to change the templates,

**Comment by ecsion** [comment]
done. Please check.
