### ISSUE TITLE
MASGC: hyperlinks not showing as links and non-hyperlinks indicated as so

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#509]
When adding instructions on forms I would like my email address to be an email link. It shows up correctly in blue underline in the custom form instructions:

http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Edit&record=118&showList=

![email shows as hyperlink](https://cloud.githubusercontent.com/assets/22300443/21159510/1f670330-c147-11e6-9ec0-f94692e6f24a.JPG)

But when the PI sees it - the phone number shows up as a hyperlink and the email address does not. For the record, if you click on the email address it works but it just doesn't highlight in blue underline.

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1540&mode=showMultiQuestionStem&QuestionId=118&tab_label=MASGC Pre-proposal Commitment Form&tab_label=MASGC Pre-proposal Commitment Form

![email not highlighted as link](https://cloud.githubusercontent.com/assets/22300443/21159579/614f829a-c147-11e6-989e-8b0451293f79.JPG)

**Comment by ecsion** [comment]
Noted, we will get this fixed.

**Comment by ecsion** [comment]
done.
