### ISSUE TITLE
MASGC Typos on Start Here instructions

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#510]
Some minor things when you have a moment:

There are some things that need editing on the text at the top of the start here page:

http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1632&mode=showProposalTitle&tab_label=Start Here

![start here page text](https://cloud.githubusercontent.com/assets/22300443/21161164/1d84024c-c14d-11e6-853b-b229fabe2748.JPG)

•	“For the current call for proposals New Test RFP 12.5.16 , we ask that you carefully….” – Delete the space before the comma.

•	“When you have understood the requirements, please fill out the online forms -- navigation is either through the left-hand navigation pane or by clicking the "Next" button.”  -- change to: “When you understand the requirements, fill out the online forms. Navigate by using the left-hand navigation pane or by clicking “Next.”   (“Next” isn’t a button.)

Also I think the text font is different in the last paragraph.

**Comment by ecsion** [comment]
Noted. We are fine the comma issue and making the Prev & Next links into buttons.

**Comment by ecsion** [comment]
done.
