### ISSUE TITLE
Custom Panel Review Form - Won't select

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#511]
I have created a custom Panel Review Ratings Form for our Graduate Fellowship Review panel; however it won't allow me to select that form since I already sent myself an invitation to test review the applications. No one else has started the review. Is there a way to select the "Graduate Research Fellowship - Panel 1- 5 Star Rating with Criteria" form?

<img width="1040" alt="screen shot 2016-12-14 at 10 43 21 pm" src="https://cloud.githubusercontent.com/assets/17860369/21211252/051dcb8a-c250-11e6-9cd2-2fd2fd84814f.png">

<img width="1036" alt="screen shot 2016-12-14 at 10 46 19 pm" src="https://cloud.githubusercontent.com/assets/17860369/21211242/f54226f2-c24f-11e6-8674-9c1c31047de1.png">

http://vaseagrant.ecsion.com/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=529&phaseid=530&tab_label=Fellowship%20Applications&listtype=invitedpanel

**Comment by ecsion** [comment]
Sam, would you please add info on what you did that reverted the rating form back to 5 star rating form.

**Comment by SamuelJLake** [comment]
Thank you for resetting the panel review, per our request about. 

I just spoke with Deepak and there must be a bug in the system because I went in 30 minutes ago, selected the correct form, hit save; however the panel review reverted back to the "5 star Rating" form as soon as I tried to access eSG as a reviewer.

Please feel free to call me at (804) 684-7436, when you have reset the form and we can verify that it is working correctly.


http://vaseagrant.ecsion.com/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=529&phaseid=530&tab_label=Fellowship%20Applications&listtype=invitedpanel

**Comment by SamuelJLake** [comment]
Sorry I had to jump on a conference call. I just hit “comment” on GitHub - Custom Panel Review Form - Won't select #511

Sam

**Comment by SamuelJLake** [comment]
I went into the systems after it was reset, selected the correct form ("Graduate Research Fellowship - Panel 1- 5 Star Rating with Criteria"), hit save; however the panel review reverted back to the "5 star Rating" form as soon as I tried to access eSG as a reviewer.

Please call me at (804) 684-7436, we need this form to be live today. I would be happy to discuss the details and verify that it is working correctly.

**Comment by SamuelJLake** [comment]
FYI you can also reach me on my cell at (757) 645-8997

**Comment by ecsion** [comment]
fixed.
