### ISSUE TITLE
MASGC Forms in download - again

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#512]
I'm deleting my previous post but I'm amending it because there is still an issue.
When the PI downloads their package from the "Submission Preview" page "Download Proposal Zip" button:
http://eseagrant.masgc.org/index.php?module=RFPProposal&view=Detail&record=1540&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Submission Preview

they get the blank pdf pages with just the link to the uploaded files as well as the uploaded files.  We think this is confusing to the PIs and need that fixed. We are less worried about what comes through on the Admin download.

**Comment by ecsion** [comment]
noted, we will fix.

**Comment by ecsion** [comment]
fixed.
