### ISSUE TITLE
NCSG - New User Access

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#513]
When new users are trying to register in eSG, there is an error message that reads this:

[Screen Grab.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/657300/Screen.Grab.docx)

**Comment by mebarrow** [comment]
Registration could not be completed, Please contact the Sea Grant Administrator.

**Comment by mebarrow** [comment]
Now Captcha is failing and not allowing me to register.

**Comment by ecsion** [comment]
This is due to url going to the University Server. Once David maps URL to AWS server, this issue and registration will be fixed.
