### ISSUE TITLE
Panel review download proposal formatting

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#514]
![peer review](https://cloud.githubusercontent.com/assets/17168500/21281537/8159da56-c3a2-11e6-97df-a8aa8c86cf05.JPG)

As a panel reviewer, the links to Download Proposal and View Peer Reviewer/Rebuttal are not spaced correctly and look like a single link, although they are really two separate links. This only occurs on large screens.

**Comment by ecsion** [comment]
fixed. please check.
