### ISSUE TITLE
Copy VA SG's Custom Forms to other Sea Grant sites

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#516]
All the eSeaGrant programs except North Carolina would like you to copy VA SG's Custom forms to their sites, with the understanding that:
1) These forms from VA will be add-ons, they will not over-write any existing custom forms
2) The VA forms will be editable and delete-able (unitl they are used)

**Comment by ecsion** [comment]
Noted. We plan to have the VA forms available to all eSeaGrant programs (except NCSU) by end of year. We will send an email once this is done.

**Comment by ecsion** [comment]
This is done.
