### ISSUE TITLE
Multiple files for download

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#517]
Would we be able to have the option to provide more than one file to download per custom form for applicants? It would be nice to provide applicants with a couple different templates at times. 

http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=Edit&record=3157&showList=RFP
![capture](https://cloud.githubusercontent.com/assets/17168500/21325779/c78bf842-c5dc-11e6-9a02-4f1e9a3f290d.JPG)

**Comment by ecsion** [comment]
We will get this done in R2.

**Comment by ecsion** [comment]
done,
