### ISSUE TITLE
RISG -- Proposal Budget Not Saving Entered Values

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#518]
When I enter a dollar value into the Sea Grant column, for instance in E. Travel, then click Justify to enter a justification and click Save in the justification, upon return to the budget worksheet, the dollar value entered has not been saved. Save result with D. Expendable Supplies. I had to click SAVE at top or bottom of worksheet after entering a value for them to be saved. This is VERY inconvenient and not a functional way to work n the budget worksheet and must be fixed. Thank You.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTkzMw==&id=147

Entered values are saved if the user hits the Enter key on their keyboard after entering the value. If this is a required keystroke to save values after entry, this should be explicitly and very visibly be stated to the user.

**Comment by ecsion** [comment]
We have save button by row in v1.5. This has improved ux. We are closing this issue. If you want changes, please open another one referencing the new worksheet
