### ISSUE TITLE
RISG -- Data Shown in Budget Justification Wrong and/or Confusing

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#521]
In the budget worksheet, when clicking the JUSTIFIED button for B. Fringe Benefits, the data shown in the grey box is incorrect and/or confusing. The initial value after a name correctly reflects the fringe applied to the Sea Grant funds at the shown fringe rate, EXCEPT that it should read as "$1300 at 52.5%"---52.5% is the rate applied; 0.52 is the mathematical factor applied to make that correct calculation NOT 0.52% ($2500 * 52% = $1300 while $2500 * 0.52% = $13 which is a HUGE difference). 

The following value ($0 SG .. $0 Grantee) makes no sense as there are values for both categories in the budget worksheet. The value after than (e.g. $11040SG), while being the total fringe applied to Sea Grant funds, does not make sense in this context. The values next line down -- $0 Waived IDC makes no sense here as waived IDC is not calculated until total worksheet values are calculated. Also, the value of ..11040Grantee is incorrect as the value shown on the worksheet is 3900.  

The information shown be, if to be of value, for the PI for example --- $1300 at 52% SG; $3900 at 52% Grantee

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTkzMw==&id=147#

![screen shot 2016-12-21 at 12 05 28 pm](https://cloud.githubusercontent.com/assets/18398763/21398573/cbbf1bb6-c775-11e6-9e18-4d684b666f11.png)

**Comment by ecsion** [comment]
Please provide pdf of Ben's budget sheet and justification so we can did similar.

**Comment by alandesbonnet** [comment]
It appears that all the pertinent data used to conduct budget calculations for personnel have been removed from the budget justifications since this GitHub message was posted. This is unfortunate since those data were useful in understanding how the budgets were calculated.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Alan, we have not removed any data. I think the issue may be that you are using was url that is no longer working:

http://eseagrant.gso.uri.edu/production/operations.php?action=budget&proposal_id=NTkzMw==&id=147#

Using was url will create issues for you. Instead you should use the eseagrant.gso.uri.edu url.

check this url that we have manually modified:
http://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=NTkzMw==&id=147#

**Comment by ecsion** [comment]
Hi Alan, Could you please provide screenshot of how the data snippet above justification should look for each budget section.

**Comment by alandesbonnet** [comment]
I have gone through several budget worksheets and all the justification appear to be correct. I am not sure why they were showing in error previously, or if it was just the one that I was working with at that time. I will close the issue in GitHub and will reopen if I find the issue to occur once again. My apologies for reporting something that does not appear to exist at this point in time. 

Alan Desbonnet
Assistant Director
