### ISSUE TITLE
RISG -- Random data showing up in Budget Worksheet

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#524]
I created a new budget worksheet as user = investigator (follow enclosed URL). As I was filling out the worksheet, under E. Travel there appears data for "ICES Conference" at a cost of $1500 that I did not enter (see attached screenshot). This needs to be investigated to be sure that 1) random data are not inserted into worksheets and 2) that random data are not inserted where data exist---I have not seen this occur but given this instance I would find it possible that it could happen.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/operations.php?action=budget&proposal_id=NTkzMw==&id=148

![screen shot 2016-12-22 at 8 26 36 am](https://cloud.githubusercontent.com/assets/18398763/21427401/5f8d6008-c822-11e6-8e20-9921eee57902.png)

**Comment by ecsion** [comment]
fixed.
