### ISSUE TITLE
RISG -- Budget Worksheet Page does not automatically refresh

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#526]
After creating a new budget worksheet, completing data entry, and saving the worksheet, upon return to the Proposal page (see URL), the newly saved budget worksheet does not show up. The browser must be refreshed in order for the worksheet to become visible to the user. This is not intuitive, and may cause users to panic, and create another budget worksheet when they don't need to. Please correct the process so that upon saving a new budget worksheet, the Proposal page is refreshed to show that a new budget worksheet has been created. Thank You.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=RFPProposal&view=Detail&record=5933&mode=showBudgetListingData&tab_label=Budgets

**Comment by ecsion** [comment]
fixed.
