### ISSUE TITLE
WSG: Provide character counter

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#527]
We would appreciate a character counter for the three big fields on the Project Summary form (i.e., a "count-downer" that shows the PI how many characters he/she has left before reaching the character limit). BTW, we've usually allowed 2000 characters. If these fields don't allow that much, please increase to 2k.

**Comment by mcbridec** [comment]
Is there a character limit for that field? OSG requests 300 words or less but allows PIs write as long as needed to relay the information. We re-write their stories anyway. I understand the need to put some sideboards on data storage-wise. If we must limit them, could we set it much larger, say 5,000 characters for each field? That's about 800 words.

**Comment by mgduke** [comment]
Cathy: typically there will be a default character limit for a text field. What I'm wondering now is whether Deepak could arrange for us to select the character limit for a field as we build/edit forms so that each SG could have their own limits. 

What do you say, Deepak? Is this an easy feature to add?

**Comment by ecsion** [comment]
We are working on the character and word counter and this should be available mid to late next week along with several other enhancements to custom forms view.

**Comment by ecsion** [comment]
done.
