### ISSUE TITLE
RISG: Error in RFP/Full Proposals Data Display

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#528]
As noted in the screenshot and at the URL provided, the information shown states that 1 Rebuttal has been received, but no rebuttals have been produced or submitted to the RFP as yet. This is misleading and confusing and should be corrected. It appears that Rebuttals Submitted number increased to 1 once a proposal was submitted. Submittal and rebuttal should not be linked in this way. Please correct. Thank you.

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=RFP&view=Detail&mode=showPhase&record=5928&phaseid=5929&tab_label=Full-Proposals

![screen shot 2017-01-03 at 7 48 05 am](https://cloud.githubusercontent.com/assets/18398763/21608641/cd99303c-d18b-11e6-9e49-710ccde59072.png)

**Comment by ecsion** [comment]
fixed.
