### ISSUE TITLE
RISG: 90-4 PDF Yr1 Budget Justification Incorrectly Reproduced in Total Project Budget

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#530]
At the URL below, when the Download ZIP button is used, the "budget90-4_full.pdf" file created (attached) contains the budget justification from Year 1. The FULL budget 90-4 should have NO budget justification associated with it. Please correct this output format as it is confusing and cause approvers to not approve budgets. Thank You.

[budget90-4_full.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/682379/budget90-4_full.pdf)

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=5928&phaseid=5929&tab_label=Full-Proposals

**Comment by ecsion** [comment]
fixed.
