### ISSUE TITLE
Criteria Ratings Missing - Panel Comments and Score (Excel Export) 

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#531]
We are currently downloading review panel comments and ratings from eSG, but the exported Excel file only contains one rating score - not the overall score as well as the 3 different criteria. Is it possible to access the ratings for each of the criteria? 

RFP Panel Management Page - http://vaseagrant.ecsion.com/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=529&phaseid=530&tab_label=Fellowship%20Applications&listtype=invitedpanel

Export Page - http://vaseagrant.ecsion.com/index.php?module=RFP&view=Detail&mode=DownloadReport&record=529&tab_label=RFP%20Reports

**Comment by SamuelJLake** [comment]
If possible, it would be helpful if the panel review forms where listed/sort-able by PI name (last) - so that they were in alphabetical order.

http://vaseagrant.ecsion.com/operations.php?action=panel_reviewer&guid=RjEwRTJFRjYtQzkwRS00QTJGLUE3MkQtN0Q4NTNBQ0IyNTg1&exuti=Mjc4Ng==

**Comment by ecsion** [comment]
Sam, we have added the criteria rating to excel export of panel reviews. Also added to panel review pdf.
