### ISSUE TITLE
Custom Form Date Fields do not work

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#532]
When adding date fields for custom forms, they do not drop down to select a date, they only work as text fields.  
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=4187&mode=showMultiQuestionStem&QuestionId=4180&tab_label=A.%20Biennial%20RFP%20Cover%20Page&tab_label=A.%20Biennial%20RFP%20Cover%20Page
![dates](https://cloud.githubusercontent.com/assets/17168500/21822037/83420fa0-d72a-11e6-9ab3-638963c8fc23.JPG)

**Comment by ecsion** [comment]
fixed on v1.5
