### ISSUE TITLE
Investigators Form Instructions Incorrect

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#533]
The standard Investigators Form gives incorrect instructions about adding a CV.
Update Investigator is not an option; you must click "edit" to add a CV
![investigators](https://cloud.githubusercontent.com/assets/17168500/21822500/4459bcc8-d72c-11e6-8bfb-cdaf2f3f2f1e.JPG)

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=4187&mode=showMultiQuestionStem&QuestionId=2&tab_label=Investigators&tab_label=Investigators

**Comment by ecsion** [comment]
Hi Mary, you can go to custom forms, select the Investigators form and then click edit. You will then be able to modify the instructions.

Here's a link to the Investigator edit page: http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=Edit&record=2&showList=

Or post the updated verbiage as a comment to this issue and we will update it for you.

**Comment by ecsion** [comment]
Closing this issue. If this is still a problem for you, please reopen or add a new bug.
