### ISSUE TITLE
URGENT: Panel Reviewers Unable to See Submitted Reviews 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#534]
Hi, 

For the 2017 Delta Science Fellowship RFP, The peer reviews that are submitted are showing up, but panel members cannot see each others reviewers. Please change this so that the panel reviewers can see each others comments and scores (as well as the peer reviews).  The peer reviews should remain anonymous/blinded, but we don't mind if the reviewers see each other's names. 

For example, Johnnie Moore has submitted many comments and scores but none of them are showing up. 

http://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=showPanelReviewerList&record=26012&phaseid=26013&tab_label=Fellowship%20Applications&listtype=invitedpanel 

Thank you. 

Kind regards,

Miho

**Comment by ecsion** [comment]
Hi Miho, We used to have the panel reviewers see each other reviews. However, there was a discussion   amongst Sea Grant members and one of the SG members  requested us to not share other panelist reviews. 

We had more discussion and it was agreed that we will implement the process used by NSF: See Mona's comments here: https://basecamp.com/2782140/projects/13305906/messages/64956987

However the new functionality for panel reviews will take a few weeks. If you need this urgently, we will add a flag for this purpose and if checked, panelists will see each others reviews. Let us know. Thanks.

**Comment by mumezawa** [comment]
Thanks for sending me the thread. 
We will hold off for now and use the current system for next week's panel. 

But we do agree that SG programs should be able to make the panel reviewer's comments visible or not on the backend.

**Comment by ecsion** [comment]
Miho, we have added the flag a few weeks ago. Closing this issue. If this is still not resolved for you, then please reopen or add  a new bug.
