### ISSUE TITLE
Issue with Adding Custom Forms 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#535]
Hi, 

I am unable to save/create a new custom form. I filled in all the mandatory fields, hit "save" and the screen will refresh but nothing is saved. I've tried on multiple occasions and nothing seems to stick. Please look into this matter. 

http://eseagrant2.ucsd.edu/index.php?module=MultipartQuestionStem&view=List&showList=true&viewname=214&tab_label=Custom%20Forms 

Thank you. 

Kind regards,

Miho

**Comment by ecsion** [comment]
fixed.
