### ISSUE TITLE
Current Project - Need to load past reports, publications, & related material

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#536]
Hello,

We are currently trying to load past reports and publications to eSeaGrant, but we are unable to add records to the current projects as administrators. We can add "Project Documents" but we can not add to the "Reports" or "Publications" pages. This is a critical function we need to populate the system. Please let us know what we need to do, or if there is another way to upload these documents to the system. 

Thanks in advance for your help!

http://vaseagrant.ecsion.com/index.php?module=Projects&relatedModule=Reporting&view=Detail&record=376&mode=showRelatedList&tab_label=Reporting

**Comment by ecsion** [comment]
Hi Sam, The steps to follow are:
1. Create the old projects, 
2. Create reporting calls and select the appropriate forms that match up with old reports. If the forms don;t exist, you can create them.
3. Link the projects to the reporting call
4. Open the reporting phase.
5. Login as the PI and start the report for the selected project. At that point a record will be created in the system and a SGAmin role person can manually enter the data for project report.

The other option is to have a SOW with Ecsion and we will analyze your electronic data and write scripts to import the data programmatically. Note that there is a charge for importing data.
