### ISSUE TITLE
Auto-emails text for the Document Request process in RFP

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#538]
The following auto-notification emails should go out in relation to the Doc Request form in RFP--

•	When the request email goes to the document-request target, auto email the PI:  “Dear [PI_fname PI_Lname), An email requesting input from [Recommender] has been sent.”  
•	When the document-requested-person hits SUBMIT you can just auto-cc the PI on the acknowledgement email that goes to the document-request target (there is one, right?) or a separate email can go to the PI as follows:  “Dear [PI_fname PI_Lname), [Recommender] has submitted the input requested”

**Comment by ecsion** [comment]
done.
