### ISSUE TITLE
RISG -- VASG Custom Forms show after being deleted

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#540]
There were several custom forms provided by VASG that we will not use, and so I deleted them. However, as seen in the URL below and screen shot, 

![screen shot 2017-01-17 at 10 09 28 am](https://cloud.githubusercontent.com/assets/18398763/22026013/806d9524-dc9d-11e6-822f-9de3962a01cf.png)
several still show up on screen when configuring an RFP call. 

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=RFP&view=Detail&mode=createPhase&record=5848&phaseid=5849&tab_label=Fellowship%20Applications

The forms shown in the screen shot/URL are not visible when working under "Manage Custom Forms" as per the URL following:

http://ec2-52-2-73-59.compute-1.amazonaws.com/production/index.php?module=MultipartQuestionStem&parent=&page=2&view=List&viewname=213&orderby=&sortorder=&search_params=%5B%5B%5D%5D

Please correct this so that forms that have been deleted do not continue to show up. Thank you.

**Comment by ecsion** [comment]
fixed.
