### ISSUE TITLE
RISG -- Reporting Call Calendar Picker starts Nov 1999

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#541]
When selecting a start / end date for reporting call, the calendar date picker starts at November 1999 (the screenshot shows Jan 2000 though the default is Nov 1999). This renders the calendar date picker useless. Please correct this so that the calendar date picker originates in the current month and year. Thank You.

![screen shot 2017-01-18 at 1 59 08 pm](https://cloud.githubusercontent.com/assets/18398763/22078585/7d6bf174-dd86-11e6-9655-74202865dd53.png)

http://eseagrant.gso.uri.edu/index.php?module=CallReporting&view=Edit&record=5193

**Comment by ecsion** [comment]
This is fixed. Please reopen if you still find issues.
