### ISSUE TITLE
Email Acknowledgement needs to go to PI as the cc, not me

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#542]
The system auto-acknowledge email to the Recommender/document submitter (Subject: MIT Sea Grant RFP - Documents Submitted) needs to cc the PI instead of me, the RC.   Picture of email I received below; I forwarded this to the Fellowship kid. Also the document title should appear only once.

![image](https://cloud.githubusercontent.com/assets/17729848/22119841/17abd668-de4b-11e6-92da-5351fd31659c.png)

**Comment by ecsion** [comment]
This has been done and will be in the next release. The duplicate files are due to 2 import questions for the same file.
