### ISSUE TITLE
URGENT: Panel Review Scores are not saving

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#543]
As a panel reviewer, using our own custom scoring criteria form, when a panel reviewer saves or submits their scores, the scores do not save. For example, I gave an applicant a score of 5 - Excellent for each of my 6 criteria (total score rating should be 5) and the total score when saved or submitted reverts to 1.75. This lower score also appears in RFP Reports Panel Comments and Score Excel Report.

http://eseagrant.oregonstate.edu/operations.php?action=panel_reviewer&guid=NjdBQjRERjQtQjMxMC00MUM1LTg3QTQtMUZDRUI4NzQ1RkM2&exuti=NTE0NA==

![capture](https://cloud.githubusercontent.com/assets/17168500/22226008/75a371d2-e179-11e6-8aa9-4e464709152f.JPG)

**Comment by ecsion** [comment]
The apostrophe in the labels was causing the issue. We now allow apostrophes and the issue has been fixed. Please check and reopen if issues has not been fixed.
