### ISSUE TITLE
VASG - Letter of Recommendation File (unable to download due to apostrophe)

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#544]
Good afternoon,

This has happened previously with another fellowship, but the file name has an apostrophe in it, which is causing an error and we are unable to download the file from eSG. If I remember correctly from last time, Ecsion is still able to download those files (and possibly modify the file name). Before we contact the letter writer, is it possible for you to download and send us the letter on this page? If its possible to allow the use of apostrophes in file names that would be a huge help since this has now happened multiple times. 

http://vaseagrant.ecsion.com/operations.php?action=responseform&guid=C0C74AB8-D414-4457-9DFA-7BFF85BEA784

![screen shot 2017-01-24 at 3 43 06 pm](https://cloud.githubusercontent.com/assets/17860369/22265866/d4e05ce6-e24b-11e6-8c57-ec841180803e.png)

Thanks in advance for your help!

Best,
Sam

**Comment by ecsion** [comment]
fixed.
