### ISSUE TITLE
OSG- Hidden items or faulty page mechanism

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#545]
After filtering for a list of Reporting Calls with the word "test" in the title, a list of two calls is presented. However the page feature tells me there are four calls, not two. It appears I am missing additional calls.
![2017-01-24_1358](https://cloud.githubusercontent.com/assets/17169131/22269263/934c9ce2-e23f-11e6-8157-7fc96c594501.png)

After clicking on the Reports tab, a list of 18 reports appears. However the page shows 20 reports. There is no second page.
![2017-01-24_1407](https://cloud.githubusercontent.com/assets/17169131/22269340/d652acd4-e23f-11e6-8317-36243668a10c.png)

Are there hidden reports I cannot see? I hope not because I need to see them all, for reporting purposes. Please fix.

**Comment by ecsion** [comment]
Looking into this.

**Comment by ecsion** [comment]
http://eseagrant.oregonstate.edu/index.php?module=Reporting&parent=&page=2&view=List&viewname=111&orderby=&sortorder=&search_params=%5B%5B%5D%5D
fixed. please check. We are closing this but if still an issue, please reopen.
