### ISSUE TITLE
Custom Form Question Label Character Limit

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#548]
Can the character limit for the question label text fields in custom forms be increased? When building forms, it would be useful to be able to put more information in the question label, and currently necessary text is cut off. 

![capture](https://cloud.githubusercontent.com/assets/17168500/22342971/20d65fb4-e3ab-11e6-9e0a-e025a9cf3ac0.JPG)

**Comment by ecsion** [comment]
done. We have increased the size of question text.

**Comment by ecsion** [comment]
Please go in and add additional question text and now it should work.

**Comment by marypleasant** [comment]
Thank you!
