### ISSUE TITLE
Budget worksheet does not save

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#549]
When completing a budget worksheet as a PI, I complete the budget template, and click save, and the saved budget worksheet doesn't show up in the budget tab. 

http://eseagrant.oregonstate.edu//index.php?module=RFPProposal&view=Detail&record=5472&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets
![capture](https://cloud.githubusercontent.com/assets/17168500/22344883/b888fde2-e3b2-11e6-99a2-4d1048c1ac78.JPG)

**Comment by ecsion** [comment]
Budge sheet saves but does not auto refresh this page. Please refresh the page. We are working on opening the budget sheet on the same tab so refresh will not be required but this will take some time.

**Comment by marypleasant** [comment]
Ok, thanks, that worked.
