### ISSUE TITLE
Budget worksheet does not calculate

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#550]
When completing the budget as a PI, I complete the necessary fields (e.g., Mo. Salary, Benefits %, Sea Grant Mos Effort, Grantee Mos Effort), and the Sea Grant Funds and Grantee Share fields do not auto calculate. 

http://eseagrant.oregonstate.edu//operations.php?action=budget&proposal_id=NTQ3Mg==&id=33
![capture](https://cloud.githubusercontent.com/assets/17168500/22344961/0f1b01f0-e3b3-11e6-8499-ec294366146e.JPG)

**Comment by ecsion** [comment]
Could you please provide instructions on how to reproduce this issue.

**Comment by marypleasant** [comment]
In Oregon Sea Grant's RFP titled "Test Resilience," I go in as a PI (my PI account is Mary Pleasant TEST 2), and try to work on the budget (http://eseagrant.oregonstate.edu//index.php?module=RFPProposal&view=Detail&record=2330&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets). When I complete the necessary fields (e.g., Mo. Salary, Benefits %, Sea Grant Mos Effort, Grantee Mos Effort), and the Sea Grant Funds and Grantee Share fields do not auto calculate (see pic for an example; the highlighted yellow fields should auto populate, but they do not, even after saving -- at least when logged in as a PI)
![capture](https://cloud.githubusercontent.com/assets/17168500/22385356/1eb39170-e487-11e6-82f7-b558de7871c8.JPG)

**Comment by ecsion** [comment]
Mary, we logged into the investigator account and did not find this issue. Are you experiencing this problem on a specific browser or on all browsers. Please send us what OS & version are you using and what browser and version you are using. Also try on another browser and see if the same issue happens on another  as well. Thanks.

**Comment by marypleasant** [comment]
Hello Again,

It did not work in internet explorer, but it did work in FireFox and Chrome. My OS is Windows 7.

**Comment by marypleasant** [comment]
Sounds good. Thank you!

**Comment by ecsion** [comment]
fixed on v1.5
