### ISSUE TITLE
OSG: Issue sending mass emails through eSG

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#551]
I am attempting to send emails to all applicants included in the eSG system for one of our fellowships. (http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=invitedPIListing&record=2999&phaseid=3001&tab_label=Fellowship%20Applications). There are approximately 250 applicants currently, so I split up the emails. I sent the email to the first 100 people, then the second hundred people, and then the last fifty people, making three separate emails. I added in my own email address to the email list on all of these emails so that I could see when the emails went through. It has been approximately 5 hours, and I still haven't received the email, which makes me wonder who else hasn't received the email. However, I just received a reply from one of the applicants to that email, so apparently at least one of the applicants has received the email. Thanks for your help!

**Comment by epperlyh** [comment]
Hi Deepak, I was wondering if there were any answers for my issue yet. I'm going to be sending out emails to everyone that applies for this fellowship shortly (likely about 300 people) and I need to make sure that the emails actually get to everyone.

**Comment by ecsion** [comment]
Hi Katie, We  have a lot of emails that are showing sent & delivered to your account. Check the attached excel sheet. Did you check your bulk/junk folder?
[Emails-To-Haley.xlsx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/760856/Emails-To-Haley.xlsx)

If the excel is missing emails, we will have to look into it further for you.
