### ISSUE TITLE
WSG: PI issues relating to proposals

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#552]
1. Megan Dethier is missing as a PI on her full proposal in the 2015 RFP. This is for the proposal titled:

Settlement or death? Factors affecting early growth and mortality of juvenile clams in diverse Washington waters

We need this fixed because we cannot promote her to a project at this point, which means we cannot set her up for reporting, which is coming up very soon.

2. For some reason unknown to us, Craig Bailey's 2015 RFP project, "Experience Maritime Project (EMP) - A Hands on introduction to Careers and Pathways in the Maritime Industry" was already promoted but there isn't actually a project record for this project. Please "unpromote" this project so that we can re-promote in hopes that this create a project record (or advise otherwise).

**Comment by ecsion** [comment]
fixed, please check & close or else give us more detail.

**Comment by ecsion** [comment]
closing this issue. Please reopen if you believe it is not fixed and in that case provide screenshot and link.
