### ISSUE TITLE
Not all projects in report call showing up in Reports

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#553]
I have 10 projects linked to a report call. 2 reports have been submitted, 8 are not submitted, as indicated here:
http://eseagrant.oregonstate.edu/index.php?module=CallReporting&view=List&viewname=179&tab_label=Open%20Reporting%20Calls

However, under Reports, when I search for the report call and a "Not submitted" status, only 4 projects show up. Where are the other 4 Not submitted projects? See two pics below for further explanation.

![capture1](https://cloud.githubusercontent.com/assets/17168500/22480046/e6909d6c-e7a4-11e6-8b82-71e8ccdbc6a4.JPG)

![capture](https://cloud.githubusercontent.com/assets/17168500/22480064/f899af6c-e7a4-11e6-8041-8f18070f6c5b.JPG)

**Comment by ecsion** [comment]
Mary, The other 4 projects are not started yet and so don;t have a report in the system,. To avoid this confusion we will add another column on the first screen named Not Started. This will have 4 projects on it. This will take some time however.

**Comment by marypleasant** [comment]
Great, thanks!
