### ISSUE TITLE
RISG -- No Upload option for Proposal PDF

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#554]
At the URL noted below, and see screen shot, when logged in as user = eSG ADMIN, the Proposal PDF function does not have a button to upload a PDF of the comprehensive project proposal. This must be corrected so that a copy of all proposal materials can be on file in eSeaGrant. Thank You.

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=6231&mode=proposalpdfform&tab_label=Proposal%20PDF&tab_label=Proposal%20PDF

![screen shot 2017-02-01 at 9 13 26 am](https://cloud.githubusercontent.com/assets/18398763/22510147/cdcc3fba-e85e-11e6-9521-0e36886d50df.png)

**Comment by ecsion** [comment]
Hi Alan, The upload of Proposal PDF is a SG Admin functions and can only be done from the RFP Tab. Go to Preproposals, **Step 5 - Upload Proposal PDF for reviewers** Then find the right proposal and click the upload button.

**Comment by alandesbonnet** [comment]
Got it. Thank You.

Alan Desbonnet
Assistant Director
