### ISSUE TITLE
RISG -- Issue with Fellowship RFP and Custom Forms; Can't delete unused forms

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#555]
These issues relate to the RFP titled "2017 NMFS-SG Resource Economics Fellowship" and the proposal within that RFP titled "2017 NMFS/SG Resource Economics Fellowship - Michael Weir"   The URL for the proposal is:

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=6231&mode=showProposalTitle&tab_label=Start%20Here

Background: I set up the RFP using the VASG NMFS-SG fellowship custom forms templates. After starting a proposal with those custom forms I realized they did not suite the purposes of the RISG program, and so designed new custom forms. I amended the RFP "Select Forms" option to reflect use of the new custom forms (see URL). I did not delete any of the materials uploaded to the VASG templates prior to deselecting their use in Select Forms. I then added the newly created custom forms and completed the proposal and submitted it.

All worked as expected EXCEPT:
1. When in PROPOSAL SUMMARY and clicking DOWNLOAD PROPOSAL DOCS ZIP, the files that are download contain some files from previous/unused VASG templates. See yellow highlighted files in edited PDF of screenshot below.

[Screen Shot 2017-02-01 at 9.24.08 AM.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/745139/Screen.Shot.2017-02-01.at.9.24.08.AM.pdf)

These files, not used by RISG using the new custom forms, still remain associated with the proposal, and should not. 

2. When I go to MANAGE RFP CUSTOM FORMS to delete the unwanted VASG custom forms, I cannot do so as I receive an error saying the custom form is already in use. See screenshot below.

![screen shot 2017-02-01 at 9 44 19 am](https://cloud.githubusercontent.com/assets/18398763/22511254/187f136c-e863-11e6-835b-457afea1a10d.png)

I understand that perhaps I should have deleted files or done something other prior to deselecting the old forms in Select Forms in the RFP set up screen, but without guidance documentation I have to proceed by guessing/trial & error. 

I want to have all the old files associated with the VASG templates removed permanently, and I want to have the VASG custom form templates removed permanently, but cannot accomplish this with the resources and permissions available to me eSeaGrant.

The Custom RFP Forms I want to KEEP, and the files associated with them, use the naming convention --- "NMFS/SG Marine Resource Economics Fellowship 1. Title Page" --- there are a total of 12 custom forms using this name convention, and numbered 1 through 12.

The Custom RFP Forms that I want permanently removed, and the files associated with them, use the naming convention --- "NMFS-Sea Grant Fellowship - 9c. Data Sharing Plan". There are a total of 14 custom forms containing the numbers: 00, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9aa, 9a, 9b, 9c, 

Feel free to contact me as this may be somewhat confusing.

**Comment by ecsion** [comment]
In R2.0, we have changed how forms are attached for a RFP phase and in the new way, you will be able to delete the form without affecting any RFP where the form is attached.
