### ISSUE TITLE
RISG -- Project Documents not available to all users

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#556]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=566&mode=showRelatedList&tab_label=Project%20Documents

and logged in as user = sSG ADMIN, I am able to see 2 documents, as seen in the screenshot below:

![screen shot 2017-02-01 at 1 41 57 pm](https://cloud.githubusercontent.com/assets/18398763/22521059/b14ee8d0-e884-11e6-8a54-eef9b7812472.png)

When at the following URL:

http://eseagrant.gso.uri.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=566&mode=showRelatedList&tab_label=Project%20Documents

logged in as user = STAFF, I can only see 1 project document, as seen in the screenshot following:

![screen shot 2017-02-01 at 1 42 29 pm](https://cloud.githubusercontent.com/assets/18398763/22521123/e9039ba4-e884-11e6-925d-af9ff0f71b84.png)

My understanding is that STAFF should be able to see all project documents, but not be able to edit or delete them, which appears not to be happening here. This should be corrected so that STAFF are able to access all project documents. Thank You.

**Comment by ecsion** [comment]
fixed.
