### ISSUE TITLE
NCSG - Peer Review

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#557]
We need a way to edit peer review data once added.  For example - if you send to the incorrect person or if you send to the same person more than once, we need to delete these people from the review of the proposal.

**Comment by kdez** [comment]
Agreed. We need the ability to both delete a particular review, and to remove a peer reviewer from an RFP altogether.  In the view below, under both the “Completed” and “Pending” tab, we should have a DELETE option… 
![pr_delete](https://cloud.githubusercontent.com/assets/17729848/23466075/0a4ceb82-fe68-11e6-866c-da31d0ad6f35.jpg)

In the "Manage Peer Review" view below, change the tab from "Invite Peer Reviewers for Proposals" to "Manage Peer Reviewers" and provide a DELETE option.
![pr_manage](https://cloud.githubusercontent.com/assets/17729848/23466352/d7502022-fe68-11e6-9cad-50bc426ec7e6.jpg)

**Comment by ecsion** [comment]
Yes, we have noted this request and will add the delete peer reviewer as a enhancement on a future release.

**Comment by ecsion** [comment]
done. Please check.
