### ISSUE TITLE
MASGC: Button to "Add Another" on custom forms does not use supplied text

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#558]
As an administrator I have the opportunity to supply text to the buttons to add additional records in custom forms:
http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Detail&record=4&viewname=214&showList=true&show_retire=

![add another button arrow](https://cloud.githubusercontent.com/assets/22300443/22560111/f6b65980-e938-11e6-9103-25021d1d1483.jpg)

However, the user's version of the form does not keep the new text, it defaults to the original.

http://eseagrant.masgc.org/index.php?module=Reporting&view=Detail&record=1851&mode=showMultiQuestionStem&QuestionId=4&tab_label=C. Economic Benefits Derived&tab_label=C. Economic Benefits Derived

![add another button result arrow](https://cloud.githubusercontent.com/assets/22300443/22560232/75a40472-e939-11e6-9a85-88ed9421fec6.jpg)

![add another button result 2](https://cloud.githubusercontent.com/assets/22300443/22560274/9d7bc9a8-e939-11e6-8dfd-057c73e15677.JPG)

**Comment by ecsion** [comment]
fixed. Please check. if not fixed, please reopen or add new bug.
