### ISSUE TITLE
MASGC: System email not showing a "From" 

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#560]
When the investigator submits their report:
http://eseagrant.masgc.org/index.php?module=Reporting&view=Detail&record=1851&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission Preview
![submit report arrow](https://cloud.githubusercontent.com/assets/22300443/22561054/50a7c5fc-e93c-11e6-92fc-ec6b9208f996.jpg)

They get a system-generated confirmation email.  This email does not show anything in the "From" section in their email inbox. This is a problem because emails like this go to Junk boxes.

![report submitted unknown sender label](https://cloud.githubusercontent.com/assets/22300443/22561092/7b9410a4-e93c-11e6-9027-93611a71c8da.jpg)

Here is the email template in question. I have not altered it in any way.
http://eseagrant.masgc.org/index.php?module=EmailTemplates&view=Edit&record=49&type=AutoSystemEmails

**Comment by ecsion** [comment]
fixed.
