### ISSUE TITLE
VASG - Project Information Budgets

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#565]
Hi Deepak,

If/when you do a future update and have time to expand the funding section to include year 3 and year 4 that would be helpful for some of our longer term projects. For example the NMFS fellowships that last 3 years in length (see screen shot below) and our larger extension awards that are 4 years long (the full omnibus period). 

Best,
Sam

![screen shot 2017-02-02 at 3 48 50 pm](https://cloud.githubusercontent.com/assets/17860369/22567858/89a32d60-e95f-11e6-839b-f89dc2dcde4b.png)

**Comment by ecsion** [comment]
done.
