### ISSUE TITLE
MASGC: font color on custom forms

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#566]
We noticed that the font in some places on our forms was grey and this looks like they are not available options. Can this be fixed so that the fonts are all dark?

Similarly, is there a way to control font size on these? It seems awfully small.
![font is greyed out on forms arrow](https://cloud.githubusercontent.com/assets/22300443/22568064/ec1e92f2-e957-11e6-9dd4-90d3e86b1690.jpg)

**Comment by ecsion** [comment]
done.
