### ISSUE TITLE
MASGC: character limit on custom form questions

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#567]
I am having a problem with my questions being cut off on the custom forms.
http://eseagrant.masgc.org/index.php?module=MultipartQuestionStem&view=Detail&record=2192&viewname=214&showList=true&show_retire= 
![custom form question length input view](https://cloud.githubusercontent.com/assets/22300443/22571423/42e0a5aa-e965-11e6-98f0-c6423112e70c.JPG)

![custom form question length pi view](https://cloud.githubusercontent.com/assets/22300443/22571429/4875b17c-e965-11e6-933c-e74685c5d49f.JPG)

**Comment by mcbridec** [comment]
We had this issue also at OSG. We ended up changing the question but retaining the meaning as much as possible. Required reporting elements from NOAA are lengthy. We'd like to be able to use more words/characters too.

**Comment by ecsion** [comment]
we will increase the size of the field and make the text box an text area so you can view all the text.

**Comment by ecsion** [comment]
fixed.
