### ISSUE TITLE
MASGC: PI name in project list needs comma

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#568]
When a user registers for eSG their name shows up in their project's form as "Last name First name".
Can we put a comma between the last and first name so that it is obvious we are looking at the last names?

![pi name needs comma arrow](https://cloud.githubusercontent.com/assets/22300443/22601817/4bc712b6-ea06-11e6-89ca-56108c9fe3f4.jpg)

**Comment by ecsion** [comment]
fixed. please check and if there is still an issue, please open or enter new bug. Please provide link.
