### ISSUE TITLE
Oregon Sea Grant: Budget Form Default Rates Incorrect

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#569]
As a PI, when you are completing the budget form and you click "set default SG rates" or "set default institution rates" the rates are incorrect. 

The default rates for Sea Grant (at least for Oregon Sea Grant) should be:
On-campus (organized sponsored research): 0.47
On-campus (organized sponsored research): 0.26
Other: 0.35

The default institution rates should all be zero. 

http://eseagrant.oregonstate.edu/operations.php?action=budget&guid=9DC22F02-1FE5-4567-A0A0-90C5DF3DE222&proposal_id=NjQ4MQ==
![capture](https://cloud.githubusercontent.com/assets/17168500/22610130/d154819a-ea18-11e6-98f1-937971e6aa25.JPG)

**Comment by ecsion** [comment]
This will be corrected when we Oregon upgrades to v1.5.   There are other enhancements that are there in v1.5, for example,  you will now be able to set rates by rap and by year and of course on campus/ off campus & other.

**Comment by ecsion** [comment]
You have v1.5 that allows you to set rates yourself.
