### ISSUE TITLE
Reporting: Publications page issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#57]
1. In Publications Details:
   a. Currently, the Publication URL is required. Please make it not required. Not all publications will be available online.
   b. When I upload a file, it seems to work, but on saving the publication form, the file disappears.
   c. Citation for Coverpage: What's this for? That is, why couldn't you just pull this info from the Citation field a few rows above the "Citation for Coverpage" field instead?
2. I don't understand why there's a separate "Authors" tab for the publication. I wonder if this is because you based this on the old system, but moving forward, it doesn't make much sense. Authors should really be a field on the Publication Details page; even better, 1 field for primary author and another for all others (better make char limit 512; these days we're seeing pubs with dozens of authors).

**Comment by ecsion** [comment]
Marcus -- call me to discuss this.

**Comment by mgduke** [comment]
Maybe talk tomorrow (Thursday), ok? More important to get Kate back on track.

**Comment by mgduke** [comment]
http://esg.wsg.washington.edu/index.php?module=Publication&view=Edit&sourceModule=Reporting&sourceRecord=21564&relationOperation=true

**Comment by mgduke** [comment]
http://esg.wsg.washington.edu/index.php?module=Publication&view=Edit&record=21589&parent_id=21564&parent_module=Reporting&tab_label=Publication
