### ISSUE TITLE
"people" when I try to search

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#570]
When I try to search for a persons name to link them to a project it ends up saying "people" in the PI box.  It won't list their name.  I am trying to send you a screen shot, but it won't let me (or I don't know how).

Katie
Louisiana Sea Grant

**Comment by ecsion** [comment]
Katie, please open this if it happens again, please cut and paste the url on github and include the screenshot.  This helps us  reproduce the issue.
