### ISSUE TITLE
NCSG  - Peer Reviewer Page

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#571]
The email that is sent to Peer Reviewers does not clearly show where they electronic version of the proposal is available.  We had feedback from our reviewers stating they did not see the "Download Proposal" link.  If this could be in bold or bigger, that would be helpful in the future.

**Comment by ecsion** [comment]
got it. We will make that link a bit highlighted so reviewers will see it clearly.

**Comment by ecsion** [comment]
done.
