### ISSUE TITLE
NCSG - Peer Reviewer Spell Check

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#572]
Is there a way that spell-check can be installed for the written sections of reviews that are entered? It's brutal to have the words underlined as misspelled but not to be able to quickly right click select correct spelling and move on.

**Comment by ecsion** [comment]
This should't be too complicated. We will research this.

**Comment by ecsion** [comment]
Mary, we will dd this to the wish list for R2
