### ISSUE TITLE
"Current Tasks" tab has closed tasks

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#573]
Under "Current Tasks" in Chrys' account there are all kinds of closed Report Calls showing up, such as the one below. These should appear under "Closed Tasks." 

Report Call
Report on: Sea Grant Project Development Opportunities
Deadline: 29 Apr 2016, 12:00 AM
Instructions PDF
Start Report

**Comment by ecsion** [comment]
Kathy, You have to close report calls manually. They don;t close automatically on deadline date. Could you please try and see if this problem you are facing resolves.

**Comment by kdez** [comment]
In setup it says "Close Report Call at end of due date" which I have checked. I don't see a way to close it manually - see screenshot.  FYI, there are 34 old Report Calls in my system that appear under "Closed Reporting Calls" but which still show up as active tasks to the PI.

![image](https://cloud.githubusercontent.com/assets/17729848/22980110/8bcce2a0-f366-11e6-822e-e32d5980ed63.png)

**Comment by kdez** [comment]
Hi Ecsion – on GitHub I answered:  “In setup it says "Close Report Call at end of due date" which I have checked. I don't see a way to close it manually - see screenshot. FYI, there are 34 old Report Calls in my system that appear under "Closed Reporting Calls" but which still show up as active tasks to the PI.”

Are you saying I should click on “Temp Close?”

[cid:image001.png@01D28773.F4C118D0]

**Comment by ecsion** [comment]
ok we will check. This appears to be a  bug.

**Comment by ecsion** [comment]
fixed on v1.5.
