### ISSUE TITLE
RISG -- Can't create Add Custom View in Reports Module

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#576]
At the URL following:

http://eseagrant.gso.uri.edu/index.php?module=Reporting&parent=&page=1&view=List&viewname=111&orderby=&sortorder=&search_params=%5B%5B%5B%22reporting_call%22%2C%22c%22%2C%222017+Completion%22%5D%5D%5D

I am unable to create a custom view. An error saying Please Select At Least One Mandatory Field is given and the form not saved -- see screen shot below.

![screen shot 2017-02-14 at 8 28 31 am](https://cloud.githubusercontent.com/assets/18398763/22930783/028baa70-f290-11e6-90d8-cb5456f8f8ed.png)

Please correct this so I can access project reporting assignments. Thank you.

**Comment by ecsion** [comment]
removed required field requirement.
