### ISSUE TITLE
RISG -- No Actions available in Report Call Module

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#577]
at the following URL;

http://eseagrant.gso.uri.edu/index.php?module=CallReporting&view=Detail&record=5193

no actions are displayed in the drop down when selected. Are no actions available or is this not working? 
Thank you.

**Comment by ecsion** [comment]
fixed. Somehow invalid html got inserted into instructions. In the past we have seen some plugins inserting html code that causes this issue.
