### ISSUE TITLE
WSG: Custom View Confusion

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#578]
In the “Proposal” menu - if you make a custom view (i.e., only 2017 RFP proposals) - the filters we select also apply to the main “Proposals” view (i.e., the full proposals list goes away and you cannot get it back until you delete the custom view that you just made).

It's possible we're not doing something right, but either way, please help resolve this. Custom views could be a very useful feature, if only we can get it to work.

**Comment by ecsion** [comment]
Looking into this.

**Comment by ecsion** [comment]
fixed. Please check. Reopen this if still an issue or add a new issue.
