### ISSUE TITLE
Email address not unique identifier because of different capitalization

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#579]
Under people, an email address is not a unique identifier if the entry uses different capitalization. For example, I could add Mary.Pleasant@oregonstate.edu and mary.pleasant@oregonstate.edu. See image for the example in the OSG system.
![capture](https://cloud.githubusercontent.com/assets/17168500/22952197/e050c4d2-f2c0-11e6-8faa-a12d85e1c732.JPG)

**Comment by ecsion** [comment]
Mary, We are having difficulty reproducing this issue. Could you give us the steps to reproduce this issue. Thanks.

**Comment by marypleasant** [comment]
As an administrator, I added Greg Rorrer to people to Sea Grant using the email address Gregory.Rorrer@oregonstate.edu. Greg also registered himself through the eSeaGrant portal (http://eseagrant.oregonstate.edu/) with the same email address, but without capitalization gregory.rorrer@oregonstate.edu. I have since deleted the latter account to avoid confusion for him.

**Comment by ecsion** [comment]
fixed on v1.5
