### ISSUE TITLE
MASGC - Instructions tab "No records found"

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#580]
In the Reporting Call, the first page that comes up is the "Instructions" page.
I am only using Custom Forms for my next call.
3 items show up at the top of this form that appear to be associated with the Standard Modules and/or the standard metrics forms or other non-custom forms: 

- Site Use Instructions
- Metrics & Measures
- Requested Information

Even when these items are not being used in a particular reporting call, they appear on the "Instructions" page and the PDF output as well.  We feel that this will be confusing to the person completing the report and would like them removed from the Instructions page when they are not being used.

![metrics and standard items not used show up on instructions labeled](https://cloud.githubusercontent.com/assets/22300443/22993559/0e0a5c80-f389-11e6-9215-8d1ae3bc030e.jpg)

**Comment by ecsion** [comment]
fixed on v1.5
