### ISSUE TITLE
Cannot delete project document

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#581]
I have tried several times to delete a project document that was a test document, but am unable to do so. The document I am trying to delete is titled abc.txt at this link: http://eseagrant.oregonstate.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=210&mode=showRelatedList&tab_label=Project%20Documents
![capture](https://cloud.githubusercontent.com/assets/17168500/23001648/d99c62e2-f39a-11e6-95c4-e5ed779af3a5.JPG)

**Comment by ecsion** [comment]
fixed manually. Still looking t root cause.

**Comment by marypleasant** [comment]
thanks
