### ISSUE TITLE
CASG: URGENT - Knauss RFA 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#582]
Hi,

I made a custom form for "Out of State Applicant" only and did not select mandatory, but it's showing up as required on the front end. Please change that so applicants are NOT required to upload a form. 

Custom Form Link: http://eseagrant2.ucsd.edu/index.php?module=MultipartQuestionStem&view=Detail&record=30865&viewname=&showList=&show_retire=

![screen shot 2017-02-16 at 9 15 04 am](https://cloud.githubusercontent.com/assets/17860279/23032290/bcc52972-f428-11e6-81d5-bd5beef9b947.png)

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, we have changed the required message to avoid confusion.
