### ISSUE TITLE
PI auto-field incorrect in Projects module User Email Template

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#583]
Under User Email Templates, using the Projects module type and PI auto-fill field, the name of the PI lists lasts name, then first, when it should be first name, then last. For example, the email reads, Dear Pleasant Mary instead of Dear Mary Pleasant. Please see attached email and screenshot.

![capture](https://cloud.githubusercontent.com/assets/17168500/23032834/bb51e7cc-f42a-11e6-8129-fe9319c4afa8.JPG)

[Oregon Sea Grant Project Report Update DUE 3_10_2017.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/780989/Oregon.Sea.Grant.Project.Report.Update.DUE.3_10_2017.pdf)

**Comment by ecsion** [comment]
done.
