### ISSUE TITLE
RISG -- URGENT --- Budget Worksheet not Auto-calculating values

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#584]
At the following URL:

http://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=NjcxNw==&id=169

use data input into budget worksheets is NOT auto-calculating and filling in total boxes to right. See screen shot.

![screen shot 2017-02-16 at 1 58 40 pm](https://cloud.githubusercontent.com/assets/18398763/23036286/42e16468-f450-11e6-995a-7b018624c49f.png)

This must be corrected swiftly. Investigators are finishing budgets for a RFP that closes tomorrow, the 17th of February at 4:00PM eastern time. They must be able to have correct budgets when they submit their proposals. Thank you.

**Comment by ecsion** [comment]
closing. Please reopen if you encounter the same issue again.
