### ISSUE TITLE
RISG -- Weird Rule Bar in Manage Report Call Custom Forms

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#585]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Detail&record=6514&viewname=214&showList=true&show_retire=

there is a bizarre rule that extends across the screen, and will not go away (see screen shot). 

![screen shot 2017-02-17 at 10 40 31 am](https://cloud.githubusercontent.com/assets/18398763/23071884/d1ff572e-f4fd-11e6-9879-97d76f838e8d.png)

It only appears on this particular custom form, not any others that I have opened to edit. It does not seem to have any function, other than being distracting and annoying. The SG ADMIN working on creating this form was working from the Chrome browser, and had cut-and-paste text from Word into the instruction text box. The cut-and-paste text turned into machine code upon saving.

I thought it was possible to cut-and-paste into eSeaGrant? Is this not the case? 
Thank you for guidance on cut-and-paste and for removing the errant rule bar.

**Comment by ecsion** [comment]
it seems like it is fixed. Please let us know what you did to remove the bar.
