### ISSUE TITLE
WSG: Report sort by change

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#588]
Within a report call - in link project screen - when you click on PI Name header to sort by this column, it currently sorts by first name. Please change the sort to ORDER BY last name.

**Comment by ecsion** [comment]
Will will make this change.

**Comment by ecsion** [comment]
fixed. Please check and reopen if you feel issue is not fixed. Please provide screenshot and url if you are reopening.

**Comment by mgduke** [comment]
Confirming this feature request has been effected. Thank you!

 <https://wsg.washington.edu/>	
Marcus Duke
Editing and IT Maven  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
