### ISSUE TITLE
RISG -- ADMIN ONLY checked items in custom report form are available to all

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#589]
At this URL:
http://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=6193&mode=showMultiQuestionStem&QuestionId=6514&tab_label=Project%20Impacts%20&tab_label=Project%20Impacts

and see screen shot:
 ![screen shot 2017-02-20 at 9 19 22 am](https://cloud.githubusercontent.com/assets/18398763/23128646/b086a53c-f74d-11e6-93aa-6e285d29c61d.png)

Users are seeing, and able to edit, items that have been checked in the custom report form found at this URL:
http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=6514&showList=true
 
and see screen shot:
![screen shot 2017-02-20 at 9 21 16 am](https://cloud.githubusercontent.com/assets/18398763/23128720/f350c0d2-f74d-11e6-98cc-06e4d0f7b176.png)

that have been marked by the SG ADMIN as "SG ADMIN access only" 
This must be corrected; we have an open reporting call and users will be entering and/or editing information that should only be available to the SG ADMIN. Thank You.

**Comment by ecsion** [comment]
fixed.
