### ISSUE TITLE
RISG -- user can delete SG ADMIN only file

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#590]
At URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=5973&showList=RFP

I have a custom RFP form marked as SG ADMIN Access Only (see screen shot)

![screen shot 2017-02-21 at 8 34 10 am](https://cloud.githubusercontent.com/assets/18398763/23166947/b12ffe02-f810-11e6-8caf-1364693d114b.png)

User = investigator however, can readily delete files the SG ADMIN has uploaded into eSeaGrant. 
The same happens with the custom RFP form found at URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=5972&showList=

This needs to be corrected so that users cannot manipulate files, etc. marked as SG ADMIN Access Only. Thank You.

**Comment by ecsion** [comment]
Sg Admin only fields are now hidden.
