### ISSUE TITLE
CASG: URGENT Permission Denied Messages 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#591]
Hi, 

I've created "dummy" projects to test the report call function under my "Miho GMAIL" account and none of them are showing up so I can't link them to the report call. However, under "People", the projects are showing up (Link: http://eseagrant2.ucsd.edu/index.php?module=People&view=Detail&record=13725&mode=eSeaGrantHistory&tab_label=eSeaGrant%20Transaction%20History) 

The projects I've been using is Project #: "Test 2" and mainly "R/SSFS-TEST". When I click on these projects, I get the permission denied message. I'm working on the Delta Science Fellowship Report Call - http://eseagrant2.ucsd.edu/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=31686&mode=showRelatedList&tab_label=Link%20Projects

I can see that there are eleven projects that are linked to this call, but only nine are showing up (which are the actual projects). 

![screen shot 2017-02-21 at 10 58 47 am](https://cloud.githubusercontent.com/assets/17860279/23181151/b45f98e0-f828-11e6-9d95-fd483d11e9d7.png)

Thanks,

Miho

**Comment by mumezawa** [comment]
It's also happening with our PIs.
Please fix this ASAP as their reports are due on February 28 and they need access to this.

Here's an example: 
Report Call Link: http://eseagrant2.ucsd.edu/index.php?module=CallReporting&relatedModule=Reporting&view=Detail&record=32136&mode=showRelatedList&tab_label=Project%20Reports

For project #: R/HCME-06 (PI: Peter Raimondi) 

http://eseagrant2.ucsd.edu/index.php?module=Reporting&view=Detail&record=33523&mode=showInstructions&tab_label=Instructions

Thank you.

**Comment by ecsion** [comment]
Miho, everything should now work. However, the R/HCME-06 project had no data and so we soft deleted it. if you need it back, we can, but may be better if you recreate the project with the same name and link the new project to report call.

**Comment by ecsion** [comment]
Mini, ignore the earlier comment. R/HCME-06 is also in reporting call.
