### ISSUE TITLE
RISG - Panel instructions not showing in Rating Form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#592]
at this URL:

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=MUE4RTUxNTktMEJGNi00OTk1LUEyNTktRTg1QTZGMDcwNThG&exuti=NzM2MA==

no instruction shows in the Instruction box for this Rating Form (see screen shot below)

![screen shot 2017-02-22 at 10 22 58 am](https://cloud.githubusercontent.com/assets/18398763/23218100/505aff26-f8e9-11e6-9f43-887b01043fed.png)
![screen shot 2017-02-22 at 10 26 15 am](https://cloud.githubusercontent.com/assets/18398763/23218117/5cd61f74-f8e9-11e6-8cab-7273cc7e4e1a.png)

despite instruction having been entered at this URL:

http://eseagrant.gso.uri.edu/index.php?module=ReviewRating&view=Edit&record=7356

and see screen shot below. Please correct this ASAP as Knauss review panels cannot see their instructions. Thank You.

**Comment by ecsion** [comment]
Working to fix this.

**Comment by ecsion** [comment]
done.
