### ISSUE TITLE
RISG -- Panel Comments don't print

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#594]
at this URL: 

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=MUE4RTUxNTktMEJGNi00OTk1LUEyNTktRTg1QTZGMDcwNThG&exuti=NzM2MA==#

with view seen in this screen shot

![screen shot 2017-02-23 at 7 11 11 am](https://cloud.githubusercontent.com/assets/18398763/23258704/5bcd8348-f997-11e6-907c-6ef7779c03ee.png)

when I hit the print button I get the following output (see screen shot)

![screen shot 2017-02-23 at 7 09 09 am](https://cloud.githubusercontent.com/assets/18398763/23258711/69a089b6-f997-11e6-9d1d-b380af989326.png)

The print option is not working, and needs to be fixed so that comments can be printed. Thank you.

**Comment by ecsion** [comment]
Working to fix this
