### ISSUE TITLE
NCSG - Pre-Proposal Peer Review Score

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#595]
When we are in the NCSG system looking at the peer review scoring, we have the option to click on the change hyperlink under accepted peer review to see the ratings given.  When we click on the accept review, the average score on the main page  does not update based on the selected reviews.   We will need to have this corrected so we can see the average score based on the reviews that we want to select.

**Comment by ecsion** [comment]
done.
