### ISSUE TITLE
Mass download of proposals

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#597]
It would be great to have a feature to download submitted proposals in mass in some future iteration of eSeaGrant. Currently, you have to go into each submitted proposal, and click "proposal summary" --> "Download Proposals Doc Zip" for each proposal, which is fairly time consuming. 

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=6069&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Proposal%20Summary
![capture](https://cloud.githubusercontent.com/assets/17168500/23313099/22996bb6-fa71-11e6-96fe-6041bf0c1929.JPG)

**Comment by ecsion** [comment]
yes, we will add this feature in R2

**Comment by marypleasant** [comment]
Great,. Thanks!

**Comment by Dipali-Ecsion** [comment]
Done.

![image](https://user-images.githubusercontent.com/17423049/62546539-49cd6400-b881-11e9-964d-ac28e23f9f31.png)
