### ISSUE TITLE
Mass download of proposals for Panelists

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#598]
Our panel reviewers have requested to have a feature where you can download all proposals at once, instead of one by one. It would be great if some future iteration of eSeaGrant had this feature. 

http://eseagrant.oregonstate.edu/operations.php?action=panel_reviewer&guid=NDc0REY4MzUtN0RFNC00RDI0LThCODktQUJFQTc5MDFDMTcy&exuti=ODI0Mg==
![capture](https://cloud.githubusercontent.com/assets/17168500/23313067/fd02b1c8-fa70-11e6-89b2-8111613dde9e.JPG)

**Comment by ecsion** [comment]
Yes, we will add this feature.

**Comment by marypleasant** [comment]
Yay! Thanks.
