### ISSUE TITLE
CASG: Project Not Linking to Report Call

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#601]
Hi,

I can't get Project #: SCC15-060 to link with Report Call "Sea Grant Extension Program: Annual Reporting". I can find it the the project when under "Choose Projects" but when I click it, it does not show up. Please help.

http://eseagrant2.ucsd.edu/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=32360&mode=showRelatedList&tab_label=Link%20Projects 

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, It is on page 2. Please click next page and you will see it.
