### ISSUE TITLE
MIT - Missing PIs: data transfer error in Projects

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#602]
Seventy PIs did not get transferred over from old eSG with their projects. Attached is a list of project records in new eSG that are missing PIs (the ones that have no PIs in old eSG are marked.)
Please transfer.
[New_eSG_Missing_PIs.xlsx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/804540/New_eSG_Missing_PIs.xlsx)

**Comment by ecsion** [comment]
Kathy, send me the list we discussed and we will make an update.

**Comment by kdez** [comment]
Deepak,

This is the list I sent yesterday – the one we discussed, yes?  It’s from old eSG and lists the PIs and their projects and their email addresses (when available.)

If you search by PI under the Projects tab in new eSG:  there are 13 projects by Eric Adams in old eSG: new eSG has one.  Old eSg has 20 projects with James Bellingham as PI, new eSG has one. Alexander Klibanov has several projects in old eSG and none in new eSG – his email address is klibanov@mit.edu<mailto:klibanov@mit.edu> and I don’t believe it’s not in old eSG, which I cannot access from here – Ben made this list from old eSG, I think he made some mistakes.

On the other hand, John Leonard’s projects, ranging from 1978 to 2007 are fine. This is a right old mess, really….

Kathy
