### ISSUE TITLE
WSG: Admin vs PI interface showing different proposals

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#603]
We have a student (Kadie) testing eSeaGrant for us and we've discovered an anomaly:

Kadie has two full props submitted (we can see them as admins): 

![screen shot 2017-02-27 at 4 42 54 pm](https://cloud.githubusercontent.com/assets/17168836/23410482/4415853e-fd84-11e6-958f-c174c0d54c28.png)
http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=showProposals&record=34570&phaseid=34572&tab_label=Full-Proposals

But in the PI view, we can only see one of her full proposals:
![screen shot 2017-02-27 at 4 41 45 pm](https://cloud.githubusercontent.com/assets/17168836/23410534/669031fe-fd84-11e6-895f-fa0b590e899c.png)
http://esg.wsg.washington.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask

**Comment by ecsion** [comment]
fixed.
