### ISSUE TITLE
WSG: Permission denied to rebuttal stage

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#604]
We are unable to test and see what the rebuttal stage looks like. When our student tester tried to access rebuttal from task list as a PI, she got this: 
![screen shot 2017-02-27 at 4 45 08 pm](https://cloud.githubusercontent.com/assets/17168836/23410590/981ca162-fd84-11e6-99f7-290b863aec0b.png)
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=34675&mode=showRebuttalForm&tab_label=Rebuttal

Here's what we see in admin view:
![screen shot 2017-02-27 at 4 45 49 pm](https://cloud.githubusercontent.com/assets/17168836/23410607/a6d1c0ac-fd84-11e6-8029-b21a7a0b4a36.png)
http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=34570&phaseid=34572&tab_label=Full-Proposals

**Comment by ecsion** [comment]
fixed.
