### ISSUE TITLE
WSG: Peer review form instructions loses paragraph breaks

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#605]
Seems today GitHub is unable to upload screenshots, so links will have to suffice:

When we publish peer review form instructions, they lose their paragraph breaks, resulting in one long, run-on paragraph. 

Instruction entry showing that paragraph breaks are in place and working:
  http://esg.wsg.washington.edu/index.php?module=ReviewRating&view=Detail&record=22

Reviewer view, showing run-on paragraph:
  http://esg.wsg.washington.edu/operations.php?action=peerresponseform&guid=FE443620-C5B4-45C5-9287-FEAE2D0DFDD4

Also, if possible, can we have HTML formatting options and/or a formatting toolbar?

**Comment by ecsion** [comment]
yes, we will fix.

**Comment by ecsion** [comment]
done
