### ISSUE TITLE
OSG: Cannot open LOR

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#606]
We just closed the application period for an undergraduate fellowship. We are now reviewing the applications. For a few of the letters of recommendation that were submitted, I can see the title of the document that was submitted, but when I click on the link, nothing happens. See example here: http://eseagrant.oregonstate.edu/operations.php?action=responseform&guid=FB2CE86B-1926-41BB-B7A1-4B67F24871A6

**Comment by ecsion** [comment]
Haley, the link stops working on the expiry date & time: This form will expire on: 24 Feb 2017, 05:00 PM

However, if you are logged in as sgadmin, then the expiry date is ignored.
