### ISSUE TITLE
OSG: Letter writers should not be able to submit without uploading

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#607]
Some of the letter of recommendation writers for one of our fellowships were having difficulty navigating the document request page for a letter of recommendation. This confusion led to some of those letter writers not uploading a document, but still clicking 'submit'. This resulted in an email being sent both to the letter writer and the applicant saying that the letter was submitted, when in fact it was not. Letter writers should not be able to submit their document request before they've uploaded a document.

**Comment by ecsion** [comment]
Did you set the file upload as a required field? 

We will look into this and fix it.

**Comment by epperlyh** [comment]
We did not set file upload as a mandatory field. Thank you for the tip!
