### ISSUE TITLE
OSG: Cannot open LOR

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#610]
We just closed the application period for an undergraduate fellowship. We are now reviewing the applications. For a few of the letters of recommendation that were submitted, I can see the title of the document that was submitted, but when I click on the link, nothing happens. See example here: http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=9026&mode=showMultiQuestionStem&QuestionId=3027&tab_label=Summer%20Scholars%20Letter%20of%20Recommendation&tab_label=Summer%20Scholars%20Letter%20of%20Recommendation Click on 'view' the response of Daniel Lyons. This will open his proposal document request form where you will see the document he uploaded. However, if you try to click on this document, nothing happens.

**Comment by ecsion** [comment]
fixed.
