### ISSUE TITLE
CASG: Deleting Co-PIs

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#611]
Hi, 

Is it possible to delete a Co-PI?
I've switched a few Co-PIs to PIs for reporting purposes but now they show up as the PI and co-PI. 
So they have two of the same projects showing up. 

This is for the Delta Science Fellowship program.
Here is an example: http://eseagrant2.ucsd.edu/index.php?module=People&view=Detail&record=3026&mode=eSeaGrantHistory&tab_label=eSeaGrant%20Transaction%20History 

![screen shot 2017-03-01 at 9 32 04 am](https://cloud.githubusercontent.com/assets/17860279/23472567/1f144336-fe62-11e6-8ffc-64c94237df8f.png)

Thank you, 

Miho

**Comment by ecsion** [comment]
Mini, we need some time to analyze this. We will get back to you on this early next week.

**Comment by mumezawa** [comment]
Hello,

Just following up regarding this matter.
I want to solicit these reports but don't want to confuse them. 

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.
