### ISSUE TITLE
RISG -- custom reporting form numeric data not correct

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#613]
At this URL

http://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=5203&mode=showMultiQuestionStem&QuestionId=4827&tab_label=Level%20of%20Effort%20in%20Man%20Months&tab_label=Level%20of%20Effort%20in%20Man%20Months

the user doing the reporting is able to insert and save non-numeric data (see screen shot)

![screen shot 2017-03-02 at 10 48 47 am](https://cloud.githubusercontent.com/assets/18398763/23514786/5799afdc-ff36-11e6-806a-b30d7736eb48.png)

into a field in the custom form field that is designated as numeric (see URL and screen shot)

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=4827&showList=true

![screen shot 2017-03-02 at 10 53 58 am](https://cloud.githubusercontent.com/assets/18398763/23514847/9166975c-ff36-11e6-9933-47dcf7c22003.png)

This must be corrected. Users should not be able to enter non-numeric data into numeric fields in a report form. Thank you.

**Comment by ecsion** [comment]
fixed.
