### ISSUE TITLE
NCSG - SG Classification and Focus  Area

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#616]
When completing the full proposal application and the form entitled, "SG Classification and Focus Area" there is a submit button.  The rest of the forms have a save button and the submit can be a bit confusing.

**Comment by ecsion** [comment]
Mary, Instead of SG & Classification, which is on old hard coded form and is deprecated. Could you please create a custom form.

**Comment by ecsion** [comment]
We have created custom form for Focus Area & Classifications. Use these instead of hard coded form which is now deprecated. We are closing this issue. Email me if you have any questions.
