### ISSUE TITLE
NCSG - Roll for Additional Personal 

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#617]
When you add additional personal to a full proposal, the role only gives one option as a faculty member.  Could a picklist be created so we can add additional roles?  Example of additional roles would be:  SG Staff Member, Collaborator, Local Fisherman, Citizen.

**Comment by ecsion** [comment]
Mary, We will get this done for you. Give us a couple of days.

**Comment by ecsion** [comment]
done.
