### ISSUE TITLE
NCSG - Budget Instructions

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#618]
Where do you upload budget form instructions?  When you are a PI, the first tab for the budget from is instructions.   I do not see on the RC side where it is possible to upload instructions to complete the budget form.

**Comment by ecsion** [comment]
When you open the RFP, Left Hand B=Navigation panel has a tab "RFP Instructions for PI". You can enter the budget instructions there.
