### ISSUE TITLE
NCSG - Instructions Saved between Pre-Proposals and Full Proposals

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#619]
When we move from pre-proposals to full proposals there is not the ability to upload both sets of instructions.  We will need to delete the PDF upload of the pre-proposal instructions to replace with full proposal instructions.  We would like a way to save or archive the previous instructions in the call.

**Comment by ecsion** [comment]
Yes, We will add this but we will need at least 1 week to make these change.

**Comment by ecsion** [comment]
done. Closing this issue. If you still find something wrong, please reopen or add another bug.
