### ISSUE TITLE
OSG - Custom Form Report only pulling partial data

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#621]
Our Customs Form Responses is only producing data from our Supported Student custom form. Needs to include/produce the data from all of our current custom forms.

![custom_forms_responses_2017-03-06_1602](https://cloud.githubusercontent.com/assets/17169131/23635852/ed5c238a-0286-11e7-8bd1-b574233068ef.png)

**Comment by mcbridec** [comment]
I had tried that, also tried closing out my browser. Mysteriously, about 3 hours after submitting, I had stayed logged in and suddenly the report worked. So it is working now. This had happened before, I just didn't report it because I didn't have time to spend on it. IF it happens again I will let you know. Thanks

**Comment by ecsion** [comment]
ok, I will close this issue for now. Let me know if this happens again and we will get on the phone and do some diagnostic testing.

**Comment by mcbridec** [comment]
This has occurred once again. Acts like something is caught in a loop. I was editing our custom form report called Custom Form Report - Students. When I saved, the Custom Form Report - Students page normally would close and the Custom Form Responses opens. This time it did not , it only went back to the same Custom Form Report - Students. This is exactly the same situation as I reported last time.

**Comment by mcbridec** [comment]
Update - this occurs also when switching from all other Custom Form Reports back to Custom Form Responses. Not just the one for students.
Also note that when I log out of eSeaGrant, everything goes back to normal and operations are fine again. But it repeats as soon as I open up any Custom Form Report.

**Comment by ecsion** [comment]
Cathy, these will take some time to debug and fix.
