### ISSUE TITLE
OSG -reopen #621

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#623]
#621 issue has re-occurred, please see new comments. Thanks

**Comment by ecsion** [comment]
Cathy, please provide link & screenshot  each page that you are clicking in the order you are clicking so we can reproduce this on our side.

**Comment by ecsion** [comment]
Cathy, Is this still an issue. If so can you please provide link & screenshots.

**Comment by mcbridec** [comment]
It's hard to explain. There is still a freeze when switching between the custom forms reports, but now I can easily close the browser and wait, or I can click on something else and it starts behaving properly. Let's close and if it start getting worse I will put in a new ticket with the clicking order.
