### ISSUE TITLE
RISG -- Rebuttal Text box seems to have a word limit and should not -- CRITICAL ISSUE

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#624]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=6214&mode=showRebuttalForm&tab_label=Rebuttal&tab_label=Rebuttal

when typing and/or cutting and pasting text into the rebuttal text box, then clicking save, a message is returned saying Rebuttal Saved but when you leave the rebuttal tab, then return, everything beyond what is shown in the screen shot below is missing/has not been saved.

![screen shot 2017-03-10 at 4 57 32 pm](https://cloud.githubusercontent.com/assets/18398763/23814810/052986f4-05b3-11e7-85b2-e1bfc3caac49.png)

I cannot edit the rebuttal custom form (does not show up in my choices). Is there a word limit associated with the text boxes? If so, can I modify them or turn them off? 

PIs are unable to save all of their rebuttal text; the rebuttal period closed today and we need access to all rebuttal comments from PIs for our panel to review. This needs to be fixed quickly. Thank you.

**Comment by ecsion** [comment]
Alan, We will make the rebuttal text unlimited. Give us till tomorrow.

**Comment by alandesbonnet** [comment]
Thank You.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
We have made the rebuttal text unlimited. The PI would have to redo the rebuttals. Let me know if you face any issues.
