### ISSUE TITLE
RISG -- Inconsistent Custom Form Development

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#626]
At this URL

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=7646&showList=RFP

I see this text (see screenshot below)

![screen shot 2017-03-13 at 8 45 33 am](https://cloud.githubusercontent.com/assets/18398763/23854832/963f85b8-07c9-11e7-8be9-f2015befab0d.png)

which is NOT what I input or saved, and NOT what is seen by the user at this URL

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=7628&mode=showMultiQuestionStem&QuestionId=7646&tab_label=IMPORTANT%20INFORMATION%20---%20National%20Strategic%20Initiative&tab_label=IMPORTANT%20INFORMATION%20---%20National%20Strategic%20Initiative

as shown in this screenshot below.

![screen shot 2017-03-13 at 8 47 32 am](https://cloud.githubusercontent.com/assets/18398763/23854866/c1643860-07c9-11e7-88d0-6975cdf1475c.png)

Given this, I don't know how to edit or amend the custom form since what I saved and what the user sees are not what is in the custom form opened as SG ADMIN. Please correct this so there is consistency across users and uses. Thank You.

**Comment by ecsion** [comment]
This can happen if you copy/paste html directly to the editor box. Instead, you should use the paste as text button. This option removes all html and then you can style as you want. We have deleted your instructions and added as text.
