### ISSUE TITLE
MIT - Picklist Edits are not happening

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#627]
In PEOPLE I edited my eSeaGrant Role History Values picklist (deleted "Reviewers" and added "Advisory Committee, changed the order). The changes show in the picklist  but when I go to use it in the PEOPLE record, I don't see the changes.

**Comment by ecsion** [comment]
fixed. There is a role tab, where you had to enable the pick list entry for SGAdmin. We have done that and everything should be fine now.
