### ISSUE TITLE
CASG: Cumulative Budget Worksheet 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#628]
Hi,

I'm setting up a RFP and would like to know what is the best way for an applicant to fill out a budget worksheet and justifications for their cumulative budget is.
![screen shot 2017-03-13 at 1 46 47 pm](https://cloud.githubusercontent.com/assets/17860279/23874610/8e5ccd40-07f3-11e7-8e18-3fe1d4c06126.png)
 There isn't an option to select that, so it makes it difficult to differentiate between yearly and cumulative. 

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, Currently we don;t have a provision for Cumulative budget sheet. Other SeaGrant programs basically rely on 90-4 to get a cumulative view. If that does not work for you, then please start a thread in BaseCamp and we can have a discussion on how to handle this.
