### ISSUE TITLE
Previous Next Buttons RFP Custom Form

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#629]
For some reason, there are not "previous" or "next" button options on this "Aquaculture Title Page" RFP custom form. All other custom forms in this RFP have this option.

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=14306&mode=showMultiQuestionStem&QuestionId=14205&tab_label=Aquaculture%20Title%20Page%20&tab_label=Aquaculture%20Title%20Page
![capture](https://cloud.githubusercontent.com/assets/17168500/23914470/4684b25c-08a3-11e7-8264-4f181b717d82.JPG)

http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=14306&mode=showMultiQuestionStem&QuestionId=14336&tab_label=Aquaculture%20Additional%20Personnel%20Vitae&tab_label=Aquaculture%20Additional%20Personnel%20Vitae
![capture1](https://cloud.githubusercontent.com/assets/17168500/23914481/4da6d8b2-08a3-11e7-8af4-3884e801abf9.JPG)

**Comment by ecsion** [comment]
fixed.
