### ISSUE TITLE
Reporting: Email "From" and "To" fields reversed when sending "A new task has been started"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#63]
Kate set up a new report call, added a staff member's (Jeffrey Adams) project and published it. She then got an email addressed TO her FROM Jeff. We're pretty sure this is backwards: The email should've gone to Jeff; but we're not sure who it should be from—that is, should it be from Kate, or should it be from our system eddress, wsgres@uw.edu (aka "WSG Research").

**Comment by mgduke** [comment]
Meant to provide example:

From: Jeffrey Adams <jaws@u.washington.edu>
Subject: Washington Sea Grant Task Started - 2014 annual report - staff - new: A-Adams
Date: February 29, 2016 at 1:03:58 PM PST
To: kalitle@uw.edu

Hello Jeffrey Adams,

A new Task has been started.
 
Task Type	Project Report Due
Task Title	2014 annual report - staff - new
Projects	Project : A-Adams
Assigned By :	Kate Litle
Assigned To :	Jeffrey Adams
Due Date :	2016-03-31 00:00:00
Expiry Date :	
Task Status :	Started
 
Thank you,
WSG Research
Washington Sea Grant
College of the Environment
University of Washington

**Comment by ecsion** [comment]
done.
