### ISSUE TITLE
Save button on custom form

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#630]
The save button on a RFP custom form does not appear until you start typing. This happens even when you have entered text, saved, navigated away from the form, and then returned to the form. In the instructions, we tell them they need to save before navigating away from the page (because the text does not auto save). If they are reading the instructions and do not see a save option, it is somewhat confusing. The save button should be visible regardless of whether or not they have entered text.  
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=14306&mode=showMultiQuestionStem&QuestionId=14207&tab_label=Aquaculture%20Project%20Summary%20Form%2090-2%20and%20NEPA&tab_label=Aquaculture%20Project%20Summary%20Form%2090-2%20and%20NEPA
![capture](https://cloud.githubusercontent.com/assets/17168500/23914940/bc1e1bb0-08a4-11e7-9ffa-458f2b8e2b51.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17168500/23914945/bea86cdc-08a4-11e7-8910-8bf80b693aed.JPG)

**Comment by ecsion** [comment]
Hi Mary, On R2, we are working on auto save. So Save button will be eliminated for custom form answers. Instead, it will have a fleeting alert that will tell them that the entered answer has been saved.
