### ISSUE TITLE
RISG -- Custom Rating form NOT saving rating

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#631]
at this URL

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=NzVBMTJDRjktNUI5QS00MzRDLUE3RjYtNEVCRjQ1Q0RERTJE&exuti=NzY2MQ==

the custom form has 2 rating options, which after being selected, then saved, do not show on screen after that and indeed are not saved (see screenshot).

![screen shot 2017-03-14 at 4 52 26 pm](https://cloud.githubusercontent.com/assets/18398763/23921937/d545a900-08d6-11e7-9e24-519c0f903b20.png)

This must be corrected so that panels can have rating saved. Thank you.

**Comment by ecsion** [comment]
The issue her was that you added the same value (0) for both encourage & discourage and eSeagrant would;t allow that. We have now taken that check off. But you really should always assigns  different value. For instance, you can assign a 1 to encourage and a 0 to discourage.
