### ISSUE TITLE
RISG --- Panel Comments doesn't print all panel comments

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#632]
At this URL

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=NzVBMTJDRjktNUI5QS00MzRDLUE3RjYtNEVCRjQ1Q0RERTJE&exuti=NzY2MQ==

clicking on the PRINT icon returns a PDF of panel comments for only 1 proposal (see attached). This needs to be fixed so that all comments print.

[3821PeerPanelComments.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/845312/3821PeerPanelComments.pdf)

**Comment by ecsion** [comment]
Alan, this was due to a css issue in the html that was added. There was a display:none attribute and also divs were mismatched. Too avoid this issue, use add as plain text.
