### ISSUE TITLE
RISG -- Reviewer # should associate with Review Name

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#633]
Investigators write rebuttals according to Reviewer #1 , #2, etc. 

Reviewer comments are output on to a PDF with their name on them, but do not have their corresponding Reviewer # (e.g., 1, 2, etc.)

It would be very helpful to have both Name and Reviewer # appear on the PDF output so that panelists and others can be sure that rebuttal comments are correctly aligned with reviewer comments.

**Comment by ecsion** [comment]
Alan, Could you help us with which PDF output you re referring to and also mark it up so we understand exactly what you want.

**Comment by alandesbonnet** [comment]
This was corrected when the issue with reviewer anonymity was corrected. Thank you.
