### ISSUE TITLE
RISG -- Project Start & Stop Dates Not Calculating Correctly in Output Forms

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#635]
at this URL

http://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&record=5848&mode=showDetailViewByMode&requestMode=summary&tab_label=LBL_GENERAL_INFO

I have provided the start and end dates of funding for an RFP (see screenshot)

![screen shot 2017-03-16 at 11 20 07 am](https://cloud.githubusercontent.com/assets/18398763/24003776/c63b47a2-0a3a-11e7-8f62-1581cfd7cd03.png)

However, in output PDF files, all dates come out as 11/30/-0001 (see screenshots)

![screen shot 2017-03-16 at 11 22 51 am](https://cloud.githubusercontent.com/assets/18398763/24003834/ee292e3c-0a3a-11e7-8fd4-e8e4c6484680.png)
![screen shot 2017-03-16 at 11 23 13 am](https://cloud.githubusercontent.com/assets/18398763/24003851/fb79b64c-0a3a-11e7-8c69-cef0b4defe88.png)

This must be fixed immediately so that proposals submitted for institutional review will not be denied due to incorrect project start and stop dates.

**Comment by ecsion** [comment]
The initiation and  completion dates are missing from the proposal. Once you add the dates in proposal, the form will show correct dates.
