### ISSUE TITLE
OSG - Peer Review comments not printing

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#636]
![image](https://cloud.githubusercontent.com/assets/18152637/24065718/7679b1f4-0b2a-11e7-8d08-a4a3ecdd025f.png)

Using the RFP Reports function for Preproposals, Peer Comments do not print (PDF Export). Luckily these can be accessed in a different way, but wondering if this can be fixed?

**Comment by ecsion** [comment]
done.
