### ISSUE TITLE
MIT - Search not working in eSeaGrant Role History field

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#637]
I added an item to the picklist for  "eSeaGrant Role History" (ie., Advisory Committee) and assigned that label to all my Committee members. However, searching for that term in that field returns zero records.  

Thus the "Custom View" I set up in PEOPLE, titled "SG Committee," does not work.

**Comment by ecsion** [comment]
Kathy, You were using User role which is very different than eSeaGrant Role History. User Role is used for permissions assignment: SG Admin, PI, Staff roles.

What you were looking for was "eSeaGrant Role History". I switched the condition and now it works.

**Comment by kdez** [comment]
Thanks!  I thought I had the right field, but I guess not….

**Comment by kdez** [comment]
Actually there is still a problem - "Role History" is supposed to be a field that lists all the past roles that person has played. However, if there is more than one role listed, the search function will not work. Which kind of defeats the purpose of the field....
