### ISSUE TITLE
Unable to Access Uploaded Fellowship Documents

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#638]
Good morning,

We are currently trying to access files that were uploaded as part of a Fellowship/Internship RFP (deadline was last night). However, the links to access the PDFs are not hyperlinked to the corresponding documents - the pathway is visible but we can't follow the link to the files. Note the pathway in the bottom right corner of the screen shot. Please let us know when this is fixed so we can download their applications. Thanks for your help!

Best,
Sam

http://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=6015&mode=showMultiQuestionStem&QuestionId=3400&tab_label=VASG%20Sci%20Comm%20Intern%20-%201%20Internship%20Application&tab_label=VASG%20Sci%20Comm%20Intern%20-%201%20Internship%20Application

![screen shot 2017-03-21 at 10 00 04 am](https://cloud.githubusercontent.com/assets/17860369/24150787/2b959e82-0e1d-11e7-90f5-1a691fcc0f8d.png)

**Comment by ecsion** [comment]
The question was not configured correctly. You have to use file upload  instead of text input.
