### ISSUE TITLE
MIT - Change of address for $%EmailSignature%$

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#640]
I think I cannot edit this field myself:  $%EmailSignature%$

PLEASE CHANGE:
MIT Sea Grant College Program, E38-300
77 Massachusetts Avenue
Cambridge, MA 02139
(617) 253-7042

TO NEW ADDRESS:
MIT Sea Grant College Program, NW98
12 Emily Street
Cambridge MA 02139
 (617) 253-7042

**Comment by ecsion** [comment]
done.
