### ISSUE TITLE
RISG -- Reviewer Comments DO NOT print anonymously

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#643]
at this URL

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=RTBDOUMyMkYtOTFGQS00NUZGLThEODMtRDNENTA1NTNBM0FB&exuti=NzYxNw==#

when I click "View Panel Comments" it takes me to this URL:

http://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer&guid=RTBDOUMyMkYtOTFGQS00NUZGLThEODMtRDNENTA1NTNBM0FB&exuti=NzYxNw==#

and this screen view:

![screen shot 2017-03-22 at 1 15 55 pm](https://cloud.githubusercontent.com/assets/18398763/24211205/b5d10f48-0f01-11e7-8337-f070a9be7cd8.png)

Note that reviewers are only identified as Reviewer #1, as they should be so that they remain anonymous to all.

When I click the PRINT icon on the screen view above,  I get a PDF as shown in the screenshot below:

![screen shot 2017-03-22 at 1 17 27 pm](https://cloud.githubusercontent.com/assets/18398763/24211297/fb7f395c-0f01-11e7-827d-2699a007ef84.png)

Note that Reviewer #1 is now identified by name. This should not be so; the reviewer should remain anonymous and referred to ONLY as Reviewer #1 throughout all output. The ONLY person who should be able to see who a reviewer is, is the eSG ADMIN.  Please correct this so that we can retain reviewer anonymity throughout our review and decision-making processes. This is a critical element of the review process.

**Comment by ecsion** [comment]
We will fix this.

**Comment by ecsion** [comment]
fixed.
