### ISSUE TITLE
CASG: Adding More Budget Years Under Projects 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#644]
Hi, 

Is there a way to add more than two years under "funding" in Projects?
Some projects are longer than two years so it would be great if we could capture this information. 

Example link: http://eseagrant2.ucsd.edu/index.php?module=Projects&view=Detail&record=36711&mode=showDetailViewByMode&requestMode=summary&tab_label=Project%20Information 

![screen shot 2017-03-23 at 11 42 46 am](https://cloud.githubusercontent.com/assets/17860279/24264559/0dcd1586-0fbe-11e7-8f59-14385e2da5ff.png)

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, This requires schema changes and so we will add this as part of R2 change.
