### ISSUE TITLE
Instructions PDF link broken under current tasks

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#646]
Logging in as a PI, under current tasks, the link to Instructions PDF yields a file download error when clicked., even though a PDF has been uploaded in the RFP set up and that file is available for download under the Start here tab of the proposal.

http://eseagrant.oregonstate.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask
![capture](https://cloud.githubusercontent.com/assets/17168500/24426707/516f92ac-13bd-11e7-9d6d-b4b4c86a99fb.JPG)

![capture1](https://cloud.githubusercontent.com/assets/17168500/24426715/54b24bda-13bd-11e7-8e5e-69200fd24063.JPG)

**Comment by ecsion** [comment]
fixed. However, we noticed that you have entered 01-31-2018 as the close date. So this phase will remain open till Jan 2018, right?

**Comment by marypleasant** [comment]
Yes, thank you for checking. We accept conference support requests on a rolling basis throughout the year.
