### ISSUE TITLE
MIT - Awards Picklist should feed Grant Number field in 90-2

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#647]
In filling out the 90-2 form (Admin view) online:  the "Grant Number" field should be fed by the "Awards" Picklist. 

If you want to rename the "Awards" picklist as "Grant Number" that would be fine. We use 'grant number', 'award', and 'award number' interchangeably.

**Comment by ecsion** [comment]
Kathy, currently the forms cannot be fed from the predefined pick list. We will look at adding this feature in R2.
