### ISSUE TITLE
OSG - Forgot password instruction wrong

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#648]
When we try to log in and click on Forgot our password?, the instructions say that "...your password will be sent to your email address", but that is not what actually occurs when you request it.

What it actually should say: "Please provide the following information - you will be sent a link to reset your password."
Please make this change. 

![2017-03-31_0909](https://cloud.githubusercontent.com/assets/17169131/24559092/4723bc9c-15f2-11e7-8704-373de12404f3.png)
http://eseagrant.oregonstate.edu/index.php?modules=Users&view=Login&status=1

**Comment by ecsion** [comment]
Thanks for pointing this out. we will update the text.

**Comment by ecsion** [comment]
fixed.
