### ISSUE TITLE
PI Budget amounts and justification not showing up in 90-4 form feed

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#649]
PI Budget amounts and justification line items not showing up in 90-4 form feed. 

These proposals are due this Monday April 3rd. Thank you, Mia

**Comment by ecsion** [comment]
Please provide screenshot that explains the issue and the url

**Comment by mzwolinski** [comment]
http://eseagrant.texasseagrant.org/operations.php?action=budget&proposal_id=MzQ3Ng==&id=21

Clint Dawson is the Lead PI. Amounts  and justification text is there (below), but does not feed to 90-4 (below)


[cid:image008.jpg@01D2AA21.5893CE50] [cid:image009.jpg@01D2AA21.5893CE50]

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

**Comment by ecsion** [comment]
Looking into this.

**Comment by ecsion** [comment]
fixed the 90-4, Now PI info and justification is showing.

**Comment by mzwolinski** [comment]
Thank you!!

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]
