### ISSUE TITLE
MIT - Layout of Objectives, Methodology, Rationale on Project Summary page(s) 

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#650]
Whenever the three Project Summary paragraphs -- **Objectives, Methodology, Rationale** -- appear, they should be in that order.
On this page, for example, in Applications RFP, they are arranged Objectives, Rationale, Methodology (which made me fill it out wrong) so please reorder the fields:
![image](https://cloud.githubusercontent.com/assets/17729848/24565564/b3e58e2e-1623-11e7-80d8-bf8e4403e045.png)
ALSO make sure it says OBJECTIVES, plural, not the singular as it is now.

**Comment by ecsion** [comment]
fixed.
