### ISSUE TITLE
MIT - Project Summary Form changes

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#651]
The Project Summary needs to display funding for each year of the grant request (1st Year, 2nd Year, 3rd Year, etc.) like this

1st Year     SG Funds Requested:  _________            Matching Funds: ________
2nd Year   SG Funds Requested:  _________            Matching Funds: ________
[etc.]

**Remove** 'Total Months Effort' from the Project Summary Form.

(I hope we have this in time for Full Proposals deadline, June 12)

**Comment by ecsion** [comment]
Kathy, We have added Total Months effort for Washington. The funds requested is there but is in a little different format:

<img width="875" alt="screen shot 2017-04-03 at 10 05 16 am" src="https://cloud.githubusercontent.com/assets/1612666/24613055/1cf46a92-1855-11e7-99c0-f6e9615b2cdb.png">

Could you review and see if this is ok?

**Comment by kdez** [comment]
Hi—

I was actually putting together the Knauss Fellowship packets and, in those, the Summary Form does not show the $$ (see attached.)  The Summary Form for a regular proposal does show the $$.

The Preprop Summary Form has an error in the $$ line. It should give the initiation date under “Fiscal Year Beginning.”   Alternatively, you can have it just say Year 1, Year 2, Year 3, etc. and change the label to read “Funding Year”- that’s fine.  I prefer the first option as it gives more exact information.

You don’t need to do anything about the Fellowship Summary Forms because I’m done with those for this year and what we have is fine. However, in the future, any changes to proposal Summary Forms also apply to fellowship Summary Forms, they are identical.

K.
