### ISSUE TITLE
PI cannot get totals to calculate after entering $ into budget category; Full proposals due today.

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#653]
PI cannot get totals to calculate after entering $ into budget category. These proposals are due today. He was using IE and has now tried both Chrome and Firefox to no avail. He said that both browsers were updated to most recent versions.

http://eseagrant.texasseagrant.org/operations.php?action=budget&proposal_id=MzQ5OA==&id=50

[Budget Issue.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/891037/Budget.Issue.pdf)

**Comment by ecsion** [comment]
Mia, It is very likely the issue is due to use of IE. To fix this, please have the PI delete the all budget sheets and then create them using chrome.

**Comment by mzwolinski** [comment]
Thank you, that makes sense...I will have him completely delete the sheet.

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

**Comment by mzwolinski** [comment]
This worked, thank you.
