### ISSUE TITLE
Full Proposal Report List (not urgent)

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#654]
The Full Proposal Report listed all Full proposals whether submitted or not.

Ideally it would list for just those that were submitted.

There were only 2 that were started and not submitted, my test proposal and one other proposal that a PI did not make the deadline, so not too much I need to edit...

Again, not urgent. Thank you for your support,
Mia

**Comment by ecsion** [comment]
we will add.

**Comment by ecsion** [comment]
done.
