### ISSUE TITLE
Focus Area does not feed the new Project Summary Form

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#655]
Focus Area does not feed the new Project Summary Form.

Not sure what I need to do when I am compiling the proposal documents for upload for the reviewers, as that information is missing. Will this feed be able to work this week? I am scheduled to provide access to the reviewers on Monday, April 10th. Please let me know so that I will know when to download the zip files.

Thank you for your help,
Mia

**Comment by ecsion** [comment]
We have added he proper key to the form & now the focus area is pulling properly.
