### ISSUE TITLE
Special Approval for late submission for a Full Proposal: How to Turn RFP Back On Without Letting Other PIs Re-submit?

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#656]
Special Approval for late submission for a Full Proposal: How to Turn RFP Back On Without Letting Other PIs Re-submit?

Is there a way to do this? 
Or do I turn the RFP back on and hope the other PIs do not re-submit?

Would it work if I simply delete accessibility to the other PIs who already submitted and turn the RFP back on? If I do this method, would I still have access to those proposals that were submitted to be able to download those?

Please confirm and thank you,
Mia

**Comment by ecsion** [comment]
Mia, we currently don;t have a way to do this. One thing you can do is to have the PI send you the info and you can enter the information for her/him. If there is sufficient interest, we can add this feature in R2.

**Comment by mzwolinski** [comment]
Thank you. My other question was as a method, what would the effect be if I removed the access to those PIs who had submitted proposals, and then re-opened for just those two late PI submissions and extended the due date? If I remove the access to those who have already submitted, I can still see their submitted proposals for download? Perhaps silly question, but just need sanity confirmation, thank you!

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

**Comment by ecsion** [comment]
Mia, Don;t think this will work. Any PI that clicks on the completed proposal will be able to make changes since the submission date  has been extended.

**Comment by mzwolinski** [comment]
Hi, thank you. However, will it work if I delete the access to those PIs who have already submitted?

Also, when I do that, I will still have access to those previously submitted proposals?

Thank you and regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

**Comment by mzwolinski** [comment]
Hi, please respond:

Will this method work:
If I delete the access to those PIs who have already submitted:
1. Then when I extend the date, they would not have access to be able to change their proposal, correct?
2. Will I still have access to those previously submitted proposals?
3. Or, is their proposal record tied to that RFP title and if I delete their access to that title, I cannot access their proposal record?

Thank you,
Mia

From: Zwolinski, Mia
Sent: Tuesday, April 04, 2017 4:45 PM
To: 'ecsion/eSeaGrant-Client-Bug-Tracker' <reply@reply.github.com>
Subject: RE: [ecsion/eSeaGrant-Client-Bug-Tracker] Special Approval for late submission for a Full Proposal: How to Turn RFP Back On Without Letting Other PIs Re-submit? (#656)

Hi, thank you. However, will it work if I delete the access to those PIs who have already submitted?

Also, when I do that, I will still have access to those previously submitted proposals?

Thank you and regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

**Comment by ecsion** [comment]
Mia, If you extend the date all PI would be able to modify the proposal. If you remove some PI or even all PI  from invite list, the removed PI will not be able to initiate a new proposal, however, they will still be able to update an existing proposal till the due date is reached.

**Comment by mzwolinski** [comment]
Hi, thank you.

I think I understand. The proposals submitted and the PIs who submitted the proposals, all of those records are tied to the RFP name and dates, correct?

Thank you!
Mia

**Comment by ecsion** [comment]
Yes they are tied to RFP name & dates. The permission to the proposal is purely to the investigator. Ability to create new proposal is tied to access mode, but not editing of the proposal. Editing is only restricted by the close date.

**Comment by mzwolinski** [comment]
Good morning, thank you, please respond to my question sent last night.

I apologize for the multiple questions. I’m the daughter of a scientist, analytical, and would like to understand the system software engineering, because it helps me better understand the basis for your answers.

What are the previously submitted proposal records tied to?

Is it the RFP title?

Is this why I cannot simply remove access to the other 33 PIs who have previously submitted proposals?


Mia, If you extend the date all PI would be able to modify the proposal. If you remove some PI or even all PI from invite list, the removed PI will not be able to initiate a new proposal, however, they will still be able to update an existing proposal till the due date is reached.

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]

From: Zwolinski, Mia
Sent: Wednesday, April 05, 2017 6:27 PM
To: 'ecsion/eSeaGrant-Client-Bug-Tracker' <reply@reply.github.com>; ecsion/eSeaGrant-Client-Bug-Tracker <eSeaGrant-Client-Bug-Tracker@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ecsion/eSeaGrant-Client-Bug-Tracker] Special Approval for late submission for a Full Proposal: How to Turn RFP Back On Without Letting Other PIs Re-submit? (#656)

Hi, thank you.

I think I understand. The proposals submitted and the PIs who submitted the proposals, all of those records are tied to the RFP name and dates, correct?

Thank you!
Mia

**Comment by ecsion** [comment]
We checked with a test RFP and it appears that you right. If you delete access, then the PI will not be able to access the proposal.
