### ISSUE TITLE
Peer Comments Download Incorrect Affiliation Displaying

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#657]
As an admin, when I go to a request for proposals under RFP --> RFP Reports and click "Peer Comments PDF Export," the institution affiliation that displays with the Peer Reviewer Name is the affiliation of the PI, not the Peer Reviewer. 

http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=4176&tab_label=RFP%20Reports

![capture1](https://cloud.githubusercontent.com/assets/17168500/24672577/20cfa9a8-192a-11e7-881f-c69fdc909384.JPG)
![capture](https://cloud.githubusercontent.com/assets/17168500/24672581/23e9ad8c-192a-11e7-8f22-b15429bb3718.JPG)

**Comment by ecsion** [comment]
Thanks Mary for pointing this out. We will fix.

**Comment by ecsion** [comment]
fixed.

**Comment by marypleasant** [comment]
Thank you! Looks good.
