### ISSUE TITLE
Proposal Submit Status Not Obvious

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#658]
For report submissions, a "Report Submitted" pop up appears. It would be useful if a "Proposal Submitted" pop up box appeared when proposals are submitted. Several PI's submitting proposals were confused as to whether their proposal submission went through as the confirmation email can have some lag time.

**Comment by ecsion** [comment]
done, please check.

**Comment by marypleasant** [comment]
It worked! Thanks for the quick fix.
