### ISSUE TITLE
URGENT: MASGC- error message when PI submits report

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#659]
I have a PI trying to submit a report and she is getting a strange error on her submission preview page.  I tried submitting it for her as an admin, but it says the same thing. However when I logon to a trial account, or check other unsubmitted reports, this doesn't appear.  Reports ae due today.

![error on submission screen](https://cloud.githubusercontent.com/assets/22300443/24725392/64c95a56-1a14-11e7-9fe9-fdef9dad018a.jpg)

**Comment by ecsion** [comment]
http://eseagrant.masgc.org/index.php?module=Reporting&view=Detail&record=3782&mode=showMultiQuestionStem&QuestionId=1857&tab_label=A.%20Progress%20Summary%20and%20General%20Comments&tab_label=A.%20Progress%20Summary%20and%20General%20Comments

**Comment by ecsion** [comment]
http://eseagrant.masgc.org/index.php?module=Reporting&view=Detail&record=3782&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

**Comment by ecsion** [comment]
This was a packet size issue on mysql. max_allowed_packet size changed to 128MB in mysql config file.

**Comment by MASGCleist** [comment]
Thank you for fixing this so quickly!
