### ISSUE TITLE
Proposal Sub-Award budgets and Scope of Work (Budget Justifications) do not download with the main Proposal Summary zipfile documentsfile download

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#660]
http://eseagrant.texasseagrant.org/index.php?module=RFPProposal&view=Detail&record=3517&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets

[screenprt_lack of sub docs.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/903415/screenprt_lack.of.sub.docs.pdf)

Thank you!
Mia

**Comment by ecsion** [comment]
done.
