### ISSUE TITLE
 is there a way to change the criteria from 3 boxes to only 2 criteria boxes? Peer reviews are due to be released Monday

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#662]
is there a way to change the criteria from 3 boxes to only 2 criteria boxes?

**Comment by ecsion** [comment]
Yes sure create a **new** rating and add 2 criteria to it. http://eseagrant.texasseagrant.org/index.php?module=ReviewRating&view=List&showList=RFP&tab_label=Manage%20Rating%20Forms

**Comment by mzwolinski** [comment]
Thank you! I will try it out and let you know if I need assistance.

Regards,
Mia

Mia Zwolinski, Research Coordinator
Texas Sea Grant College Program | Texas A&M University | 979-458-0449
http://texasseagrant.org/
[cid:501AB10A-6550-423C-967F-9827F6D0E23F]
