### ISSUE TITLE
WSG: Submission Preview Budget Justification Missing Senior Personnel Info

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#663]
Using this page as an example:
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=39163&mode=showSubmissionPreview&tab_label=Submission%20Preview&tab_label=Proposal%20Summary

We note that there's no information for Senior Personnel when clicking the "View" button (see attached example). The information does appear elsewhere (e.g., clicking the green dots on the budget worksheets), so we know the data exist.
[Preview Budget Justification-Missing Senior Personnel.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/911099/Preview.Budget.Justification-Missing.Senior.Personnel.pdf)

**Comment by ecsion** [comment]
fixed, please check

**Comment by ecsion** [comment]
Closing this issue. Please reopen if not fixed.

**Comment by mgduke** [comment]
I checked this and it all looks good to me now. Will let Kate know.
