### ISSUE TITLE
CASG: RFP Budget Download Issues 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#664]
Hello,

When we download the budget with the information pulling from the budget worksheets, not all the information is coming through. 

For example, for Pomeroy's application (http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=35969&mode=showProposalTitle&tab_label=Start%20Here), if you download the zip folder and view budget_839 there are salaries for Pomeroy/Culver that don’t show up on the 90-4. The 90-4 total is correct ($71,211) but the salary numbers and other info is missing.

In addition, there is budget justification text for Pomeroy that doesn’t show up in either pdf but was entered in the system in the same manner as all the other text that does show up.

Can you get us a copy of the 90-4 form that has the complete information or look into fixing this problem? Thank you. 

Kind regards,

Miho

[budget_839.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/917153/budget_839.pdf)
[budget90-4_2017.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/917154/budget90-4_2017.pdf)

**Comment by ecsion** [comment]
Miho, We have fixed this issue. Please check and let us know.

**Comment by ecsion** [comment]
Closing this issue, please reopen if not fixed.
