### ISSUE TITLE
NHSG Preprosal Reports

### ISSUE THREAD

**Issue by nelsonsj** [ecsion/eSeaGrant-Client-Bug-Tracker#667]
We are unable to download or view the panel review comments. The steps I have taken are:
Click on RFP Report
Click on Panel Comments and Score
The next screen is black with exception of the "<Back" report

The panel members have submitted their comments as I can view if I log in as a panelist.

Thank you.

**Comment by ecsion** [comment]
In your case, there were no ratings selected and the application was not coded for no ratings. We have now added this. Try again, the exports should work now.

**Comment by nelsonsj** [comment]
Thank you! I can now see the comments.


Sally J. Nelson
Sally.nelson@unh.edu<mailto:Sally.nelson@unh.edu>
603.862.2987

[SMSOE_Horiz_RGB small]
