### ISSUE TITLE
RISG -- ADMIN ONLY entries visible to users

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#669]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=5269&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

at the Submission Preview screen, users are able to see custom forms options checked at "admin only" visible.  See screen shot below:

![screen shot 2017-04-17 at 8 18 19 am](https://cloud.githubusercontent.com/assets/18398763/25088759/af9b02ec-2346-11e7-9a37-0f5f7c9a8065.png)

Users/PIs cannot see this when entering data, so it is confusing to see this later in the process. Furthermore, if the ADMIN is entering critical notes about a project, it is not desirable to have the User/PI see these notes. 

This should be fixed immediately. It makes no sense to ADMIN ONLY entries that are then visible to all. Thank you.

**Comment by alandesbonnet** [comment]
The fields under "Impacts and Accomplishments" in the screen shot labeled TITLE, RELEVANCE RESPONSE RESULTS, RECAP, NOTES, and FUTURE IMPACT FOLLOW UP? are all checked as ADMIN ONLY visible in the custom form.

**Comment by ecsion** [comment]
Notes, we will fix.

**Comment by ecsion** [comment]
fixed. Please check.

**Comment by alandesbonnet** [comment]
Yes, thank you. 

Alan Desbonnet
Assistant Director
