### ISSUE TITLE
WSG: Replacing Sample Budget Justifications (pdf) 

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#673]
http://esg.wsg.washington.edu/Sample_Budget_Justification.pdf

See screenshot, where can we upload OUR pdf Sample Budget Justification file?
![screen shot 2017-04-19 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/26942420/25199757/c497f9f0-2500-11e7-9abc-a3548eec21ec.png)

**Comment by ecsion** [comment]
We have a static file that is used for all RFP. Please add the file that you would like and we will replace.

**Comment by alandesbonnet** [comment]
Please be advised that Washington Sea Grant’s budget justification needs may not necessarily be identical to those of other Sea Grant institutions. IF individual program cannot attach their own specific budget justifications, then those that ARE use for ALL program must be rather generic. I am guessing our needs are similar, but may not be identical.

Just a warning shot across the bow that this may open a list of issues.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Good point. If each SeaGrant wants a different file, we will have to make an enhancement so the file path can be configurable.

**Comment by chelkahn** [comment]
Where did the static file come from? Our preference would be that each program could have their own doc if they chose. 

Attached is our document for ref. 
[BudgetJustificationInstructions.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/945499/BudgetJustificationInstructions.pdf)

**Comment by chelkahn** [comment]
We are still waiting on how to proceed with this issue. We will be opening our call on Monday

**Comment by ecsion** [comment]
We will try to get a solution for you by Monday.

**Comment by ecsion** [comment]
done. Please check. We are closing this issue. Please reopen if not fixed.

**Comment by chelkahn** [comment]
Is fixed, thank you
