### ISSUE TITLE
RISG--Source code in Custom Form won't allow "open in new tab" command

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#674]
In developing a Custom RFP Form, at this URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=8110&showList=

when inserting a hyperlink to a PDF document in the SOURCE CODE, upon saving, eSeaGrant inserts QUOTE marks into the <target=_blank> command, rendering the link invalid. Because of this, users cannot access required RFP documents. See screenshot below.

![screen shot 2017-04-20 at 7 15 47 am](https://cloud.githubusercontent.com/assets/18398763/25228239/b2b2258c-2599-11e7-8d57-90e486daef5e.png)

eSeaGrant MUST be corrected so that it DOES NOT insert the quotes upon saving the form, that renders the link invalid. Thank you. This is a critical fix.

**Comment by alandesbonnet** [comment]
Addendum to #674---the quotes are inserted even when toggling the SOURCE button on/off. The hyperlinks inserted last week when the Custom RFP Form was created worked fine. Now this week they all of a sudden do not, so something has occurred now to then.

**Comment by ecsion** [comment]
Alan, we have added a control to add links. Use the control instead of editing the source. That should work. Let us know if it does;t.

**Comment by alandesbonnet** [comment]
It works great. Thank you. Simplifies things significantly. Nicely done.
AD

Alan Desbonnet
Assistant Director
