### ISSUE TITLE
OSG: Copying people on eSG emails

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#675]
I can cc and bcc one address using eSG's email feature - is there a way to also include more than one person in these fields? I tried both comma and semicolon to separate the addresses and received an error each time:
![image](https://cloud.githubusercontent.com/assets/18152637/25246616/1202ded2-25bd-11e7-8b40-d08bb780cc7c.png)

**Comment by ecsion** [comment]
Sarah, use commas **without spaces:**  one.email.com,two.email.com

**Comment by ecsion** [comment]
We now allow space (s) after the comma: one@email.com, two@email.com

Please check.
