### ISSUE TITLE
WSG: On campus/Off campus budget names

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#677]
We had issues at the preprop stage with the budget types. In the old system the codes were "UW On-campus" "UW off-campus" and other. Without the "UW" many of our PIs selected incorrectly, which caused issues with IDC calculations. If possible, we would like to include the UW here; however, we realize this may be an issue if this is the same for all SG programs. Is this name customizable or do we need to agree on a single name for the whole network?  

See screenshot: 
![screen shot 2017-04-20 at 2 19 01 pm](https://cloud.githubusercontent.com/assets/26942420/25253102/5f39ecba-25d4-11e7-82f6-fa54d496c708.png)

http://esg.wsg.washington.edu/operations.php?action=budget&guid=A2237020-C7F8-4927-AE4C-36FA9B51B420&proposal_id=Mzk1Mzc=

**Comment by ecsion** [comment]
We will get this done in the next few days.

**Comment by ecsion** [comment]
done, please check

**Comment by chelkahn** [comment]
Currently this say "WA" it NEEDS to say "UW On-Campus" and "UW Off-Campus".

WA has no significance and will likely cause more confusion. Please fix ASAP!
