### ISSUE TITLE
RISG --- IMPORT from other RFP not on Co-PI form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#679]
I notice that the IMPORT from past RFPs is present and active on forms for the Principal Investigator, and for Other Personnel, but NOT for Co-Principal Investigators.

You should make the IMPORT function available for the Co-PI form as well.

**Comment by ecsion** [comment]
Alan, currently the import button shows for the PI but not for SGAdmin. However, we will be making an enhancement so the Import button will also show for SGAdmin.

**Comment by alandesbonnet** [comment]
at this URL:

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=8021&mode=showMultiQuestionStem&QuestionId=6732&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators <http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=8021&mode=showMultiQuestionStem&QuestionId=6732&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators>

when logging in as a PI/Investigator, there is NO option for IMPORT DATA (see screen shot). Import Data is present for Investigator and Other Personnel, but NOT for Co-PI.





Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Alan, the import button only shows up if you have data in the copi form in other proposals. We added some data and it then showed the import button.
