### ISSUE TITLE
RISG -- Add Multi-form Zip to Custom Form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#681]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartAnswers&parent=&page=1&view=List&viewname=169&orderby=&sortorder=&showList=true&tab_label=Custom+Form+Responses&search_params=%5B%5B%5B%22answer%22%2C%22c%22%2C%22publications%22%5D%5D%5D

please add to the ACTIONS dropdown, the ability to create a MULTI-FILE ZIP download attached PDF documents from any and all selected reports. The MULTI-FILE option should be added to the Custom Form titled "Publications."  This is a custom form NOT the standard form.

URL to the Custom Form "Publications" is:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Detail&record=5114&viewname=214&showList=true&show_retire=

OR

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=5114&showList=true

Thank you.

**Comment by ecsion** [comment]
Working on this.

**Comment by ecsion** [comment]
done, please check.

**Comment by alandesbonnet** [comment]
appears to work wonderfully!! Thank you.
Alan

Alan Desbonnet
Assistant Director
