### ISSUE TITLE
NCSG - Add titles to custom forms

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#682]
This might be in the 2.0 version....we created a custom form for impacts and accomplishments.  When you add a row, you can see 1, 2, 3, etc.  (see image)

![image](https://cloud.githubusercontent.com/assets/21174930/25285864/bd1c1d70-2689-11e7-877b-4e83df965d45.png)

Could we have the title line show up next to the number?

**Comment by mebarrow** [comment]
![image](https://cloud.githubusercontent.com/assets/21174930/25285889/dd2a2620-2689-11e7-9fba-962c25cc44f2.png)

**Comment by ecsion** [comment]
Done, please check

**Comment by mebarrow** [comment]
Yes. This one is done. 

Mary Beth Barrow
Finance Officer
NC Sea Grant and WRRI
