### ISSUE TITLE
WSG: "Next" button missing on custom forms in RFP

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#685]
The "<Previous" and "Next>" buttons are missing from the two following custom forms in RFP Title: Testing for RFP full proposal
-  Full Proposal Current and Pending Support 
-  Full Proposal Project Narrative 

Call opens on Monday, need fix ASAP! 

![screen shot 2017-04-25 at 9 26 37 am](https://cloud.githubusercontent.com/assets/26942420/25396467/7e6e0940-2999-11e7-915a-ff6789233a5d.png)
![screen shot 2017-04-25 at 9 26 49 am](https://cloud.githubusercontent.com/assets/26942420/25396470/7fc15f40-2999-11e7-84a7-76420fe39748.png)
![screen shot 2017-04-25 at 9 27 02 am](https://cloud.githubusercontent.com/assets/26942420/25396473/81b17952-2999-11e7-9d7c-fa4d7834f1bf.png)
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=39851&mode=showMultiQuestionStem&QuestionId=39247&tab_label=Full%20Proposal%20Current%20and%20Pending%20Support%20&tab_label=Full%20Proposal%20Current%20and%20Pending%20Support

**Comment by ecsion** [comment]
This is due to spaces being added after the custom form name. We are working to trim the space programmatically, but in the meantime, you can edit the form and remove the space manually.

**Comment by ecsion** [comment]
This has been fixed.
