### ISSUE TITLE
WSG: incomplete budget justifications

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#687]
View mode: http://esg.wsg.washington.edu/operations.php?action=justification&id=888 
PI entry mode: http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=Mzk4NTE=&id=888#

**Entry for International travel not showing up on "view" - see screenshots.
Also, justification for indirect cost does not appear in the "view" mode**

![screen shot 2017-04-25 at 10 36 27 am](https://cloud.githubusercontent.com/assets/26942420/25399086/1d08ca32-29a3-11e7-9245-9fe42f4ff0e8.png)
![screen shot 2017-04-25 at 10 36 18 am](https://cloud.githubusercontent.com/assets/26942420/25399090/1e5c4cce-29a3-11e7-81b0-1744460b48f4.png)

![screen shot 2017-04-25 at 10 36 12 am](https://cloud.githubusercontent.com/assets/26942420/25399093/21a88faa-29a3-11e7-82f0-76efb725d8bb.png)
![screen shot 2017-04-25 at 10 35 58 am](https://cloud.githubusercontent.com/assets/26942420/25399099/24063f18-29a3-11e7-84ae-3079bcfcd85f.png)

**Comment by chelkahn** [comment]
note: both appear on budget worksheets through download here: http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=34570&phaseid=34572&tab_label=Full-Proposals

[budget_888.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/955982/budget_888.pdf)

**Comment by ecsion** [comment]
noted, we will fix.

**Comment by ecsion** [comment]
Chelsea, Can you provide a document on how yo would like the Justification to look. We will then code it.

**Comment by chelkahn** [comment]
I noticed the justification for indirect cost appears at the top of the "view" option, which is 100% fine. 

So the only issue is with International Travel justification. As far as layout and look, identical to the way domestic travel is coded should be sufficient. I just need what is typed in the justification box to appear below the budget worksheet entry in the "view" option (both in the budget worksheets when editing and on the budget worksheets tab in the budget page). if you need more information, please let me know.

**Comment by ecsion** [comment]
done,
