### ISSUE TITLE
Tab Sequence Not Working for Additional Personnel

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#690]
In the RFP "Oregon Sea Grant Biennial Research Competition 2018-2020," the tab sequence lists Investigators as "1" and Additional Personnel as "2," but when I log in as a PI, the order is out of sequence.
![capture](https://cloud.githubusercontent.com/assets/17168500/25411762/65e1aaf0-29d3-11e7-95da-847db0fcabfb.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17168500/25411764/6962ee5a-29d3-11e7-8ba8-3efcedde231a.JPG)

**Comment by ecsion** [comment]
fixed, please check.
