### ISSUE TITLE
MIT - Project end date display (r2.0)

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#691]
On any page that shows the end date of a project, what the user really wants to see is the current, actual end date of the project -- In some cases this is the original "end date", but often it is the EXTENDED end date (because the PI got a n no-cost extension to finish work.)

I'm referring to display pages such as Linked Projects for a Report Call. Right now we see a column 'End Date w. Ext.'  that only displays a date if the project has been extended; the others are blank so we have to remember how long that project runs. Which we can mostly do BUT, if possible....

Program that field so that IF the 'End Date w. Ext' field is blank THEN display the contents of 'Original End Date' field.  The column header would be 'End Date' with a hover bubble stating "Current project end date, with or without extension"

Except for my own Custom View "Start & End Dates", I only ever want to see the actual, assigned, current end date, whichever it is.  It's not a deal-breaker but it would be great.

**Comment by ecsion** [comment]
Looking into this.

**Comment by ecsion** [comment]
done.
