### ISSUE TITLE
WSG: Adding new proposal at FullProp stage - change pop up box text?

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#693]
Thinking about the PI's immediate response to starting a new full proposal based on their submitted pre proposal - currently this page make no indication that it recognizes the PI or know's about the submitted preprop. Is there a way to change the language in the pop up box that communicated that there is the functionality to import data on specific customs forms within the full prop process? 

See screen shot. I will write up the text we wish to appear - just hoping this is possible. Do not want PIs to immediately panic. 

http://esg.wsg.washington.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask#

**Comment by chelkahn** [comment]
apologies, the other two attachments were an accident. please ignore.

**Comment by ecsion** [comment]
Chelsea, please provide the text you would like to see.

**Comment by chelkahn** [comment]
text: "Please enter the original or updated title of your submitted preliminary proposal. Once you complete the information on the Start Here (title page), you will be able to import data from your preliminary proposal on other relevant pages.  "

**Comment by chelkahn** [comment]
Sorry, an updated version - "Please enter the original or updated title of your submitted preliminary proposal. Once you complete the information on the Start Here (title page), you will be able to import data from your preliminary proposal on other relevant pages (not including budgets)."

**Comment by ecsion** [comment]
fixed, please check.
