### ISSUE TITLE
WSG - bullet issues with budget instructions 

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#694]
When entering bullets into the budget instructions, once saved they break. 

In Budget Setup - Full Proposal Instructions they appear fine.  

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&record=34267&mode=showDurations&tab_label=Budget%20Setup

![screen shot 2017-04-26 at 11 35 31 am](https://cloud.githubusercontent.com/assets/26942420/25450723/a9dbb3c6-2a74-11e7-9aaf-2ac6c3e80dab.png)

But when viewing, they appear broken . 
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=40330&mode=showBudgetListingData&tab_label=Budgets&tab_label=Budgets

![screen shot 2017-04-26 at 11 36 58 am](https://cloud.githubusercontent.com/assets/26942420/25450749/ca232b3c-2a74-11e7-9a57-f8e311718dca.png)

**Comment by ecsion** [comment]
fixed.
