### ISSUE TITLE
MASGC Error message when dowloading report responses

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#695]
We are getting an error message on some of our Custom Form Responses when we are looking at our annual report data.

If I go here:
http://eseagrant.masgc.org/index.php?module=MultipartAnswers&parent=&page=1&view=List&viewname=169&orderby=&sortorder=&showList=true&tab_label=Custom+Form+Responses&search_params=%5B%5B%5B%22answer%22%2C%22c%22%2C%22M.%22%5D%5D%5D

![image](https://cloud.githubusercontent.com/assets/22300443/25451814/fdedbacc-2a88-11e7-879b-7a8f1a86a050.png)

and I select all then go to Actions>Export

I see this:
http://eseagrant.masgc.org/index.php?module=MultipartAnswers&action=ExportCSV&mode=ExportSelectedRecords&selected_ids=[%224828%22,%224507%22,%224389%22,%224165%22,%224115%22,%224002%22,%223814%22,%223188%22,%222300%22]&excluded_ids=[]&viewname=169&page=9&search_params=[[[%22answer%22,%22c%22,%22M.%22]]]

![image](https://cloud.githubusercontent.com/assets/22300443/25451860/376cbb22-2a89-11e7-9167-2b41b4615499.png)

**Comment by ecsion** [comment]
Export was designed for  max 22 fields. We have now increased it to 100 and so the output should work now. Closing this issue. Please reopen if you face any issues.
