### ISSUE TITLE
Document request sends instructions for PIs to the document provider

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#697]
Using the document request custom form, the instructions to the PIs/applicants now show up for the document provider. The document providers do not need to see the instructions to the PI's/applicants; they only need to see the instructions for the document providers.
![capture](https://cloud.githubusercontent.com/assets/17168500/25495834/95052b98-2b33-11e7-893c-b5444dcb4b0a.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17168500/25495840/9b24ef36-2b33-11e7-8bfa-a5d752f752d0.JPG)

roviders.

**Comment by ecsion** [comment]
Noted, we will fix.

**Comment by ecsion** [comment]
fixed, please check. reopen if you still have an issue.

**Comment by marypleasant** [comment]
Looks good. Thanks!
