### ISSUE TITLE
WSG: students supported - default for new or continuing should be blank

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#698]
Please change the default entry for "new" or "continuing" to blank in the students supported form.  

I think the current default is "continuing," so many PIs are submitting that way without review, often resulting in incorrect entries.

Example:
http://esg.wsg.washington.edu/index.php?module=StudentsSupported&view=Edit&record=40184&parent_id=37237&parent_module=Reporting&tab_label=Students%20Supported

**Comment by ecsion** [comment]
The default initial value already is "Select an option" . See attached screenshot. 
<img width="857" alt="screen shot 2017-04-28 at 8 32 20 am" src="https://cloud.githubusercontent.com/assets/1612666/25528825/87ec1178-2bed-11e7-9738-be7a1c232cbc.png">
