### ISSUE TITLE
ORSG: Reporting- Export spreadsheets, formatting request

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#699]
In Reports, the exported spreadsheet reports always need the same bit of formatting before using. Can we remove the blank column on the left side and the blank row at the top? <add screenshots>
![2017-04-28_1531](https://cloud.githubusercontent.com/assets/17169131/25549668/258a1bde-2c28-11e7-8aef-3a92b98018fd.png)

**Comment by ecsion** [comment]
Yes we can do this. Ok if we include the the R2 release at end of May? or do you need it sooner?

**Comment by mcbridec** [comment]
It is okay to include it in R2 - thank you!

**Comment by kdez** [comment]
Yes, please do get rid of these blank/extra rows and columns, thanks.
