### ISSUE TITLE
OSG- Reports> Custom Forms output for Zip files not working

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#703]
When I try to run a report for SOME Custom Forms responses, the output is okay for the Excel Export, but for the Multifile Zip output (for the same exact filter) I get the popup, "No Files present for multi file download".

When filtering, these searches/filters produce the error in the filter Zip output:
Tools
New
Prizes
Economic
Updates
Progress
Extramural
Practices

These filters do not produce the Zip output error:
Publications
Supplemental
Supported
Outreach

http://eseagrant.oregonstate.edu/index.php?module=MultipartAnswers&view=List&showList=true&tab_label=Custom%20Form%20Responses&viewname=169

The step-by-step to re-create my results when searching for custom reports with 'Prizes' in their title:
In Reports > Custom Form Report

1- Search/filter for Prizes 
2- Select all reports
3- Choose Actions > Download Multi File Zip

Popup: No Files present for multi file download
Note that the filtered results revert back to a non-filtered full list of all reports

4- Choose "OK"
___________________________

1- Search/filter for Prizes 
2- Select all reports
3- Choose Actions > Export

Popup: Opening CustomFormsResponsesExport-05012017.xls
Choose "Open with Excel" and "OK"
Excel report opens correctly, with 27 reports
![2017-05-01_1124](https://cloud.githubusercontent.com/assets/17169131/25590550/de3ba384-2e65-11e7-9445-22503cf9f07f.png)
![2017-05-01_1120](https://cloud.githubusercontent.com/assets/17169131/25590598/0a9045c0-2e66-11e7-8a16-c64dfb2ede36.png)

**Comment by ecsion** [comment]
Cathy, The "Download multi-file zip "  zips the uploaded files in the selected responses and downloads the zip file. If the selected  custom forms do not have any uploaded files, you will get the message you stated.  

Do you have custom forms that have files uploaded  that is giving you the error?

**Comment by mcbridec** [comment]
Okay, I did not know that "If the selected custom forms do not have any uploaded files, you will get the message you stated." You can close this.
