### ISSUE TITLE
OSG- Reports: change the attachment download name 

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#705]
In Reports > Custom Forms Responses
When I go to download one of the choices is "Download Multi File Zip". 
That sounds a lot like I am downloading custom form reports, but it actually refers to the files that are attached to the selected reports. 

Can we please change that to " Download Report Attachments Zip" in order to clarify that type of export?

Thanks!

**Comment by ecsion** [comment]
The action is now named "Download Custom Form Attachments", & the download file is named CustomFormAttachments.zip
please check

**Comment by mcbridec** [comment]
Works, looks great - thank you!
