### ISSUE TITLE
WSG: URGENT - 90-4 calc. incorrect

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#706]
The Total Direct Costs A-G does not appear to be calculating properly on the 90-4 - at least not in this case (see attachment).

Link to budget worksheet - which looks fine - http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=Mzk5MzQ=&id=894

NOTE: OUR FULL PROPOSAL IS CURRENTLY OPEN FOR PIS (CLOSED JUNE 1)- WE NEED TO BE SURE BUDGET WORKSHEETS ARE WORKING PROPERLY!

[budget90-4_2017.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/969020/budget90-4_2017.pdf)

**Comment by ecsion** [comment]
Noted, we will prioritize this issue.

**Comment by ecsion** [comment]
There was some issue when multiple budget sheet were present but not all were included in 90-4. This has now been fixed. Please check and confirm. Let us know if you see any other issues.

**Comment by ecsion** [comment]
Kate -- Would you please check and let us know if you still have any problems with computations. Thanks

**Comment by chelkahn** [comment]
this is fixed, thank you!
