### ISSUE TITLE
WSG: Issue with labels of subawards on 90-4s

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#707]
Two layer issue -

1. Names of most subawards are not carrying over to the 90-4s. See budget sheet here: http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=Mzk1MTY=&id=884

And 90-4 here:
[budget90-4_2017.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/977493/budget90-4_2017.pdf)

2. Or the wrong name appears with the subaward - i.e. See budget sheet here: http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=Mzk1MTY=&id=886

And 90-4 here:
[budget90-4_2018.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/977497/budget90-4_2018.pdf)

Thoughts?

**Comment by ecsion** [comment]
fixed, please check.

**Comment by ecsion** [comment]
Should we close this issue?
