### ISSUE TITLE
NCSG - Person Not Receiving Emails

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#708]
I have a PI, Robert Young that I have deleted his account and readded him and he is still not receiving emails from the system.  For account set up or resetting his password.  So, I decided to set his password and log in to see if the report was there.  When I logged in, there are reports listed but, not for him.  What is going on?  

User Name:  ryoung@coastal.edu
Password:  

He should have project 2014-DMM-02 tied to his name and there are 5 that are listed that are not his projects.

**Comment by mebarrow** [comment]
http://eseagrant.ncseagrant.ncsu.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask

It is showing up projects that do not have listed as PI.  Here is the link that shows the projects that are not his.

**Comment by ecsion** [comment]
Looking into this.

**Comment by ecsion** [comment]
Appears like Migration issue. It has been fixed. Note, Robert will see 2014-DMM-02 on the closed project list since the project w extension has a 2016 date.  

Emails are going properly. Ask Robert to check on his spam/ bulk email.

**Comment by mebarrow** [comment]
He said that the email was not in either one....he seems to be the only person who is having issues with this.

**Comment by ecsion** [comment]
We are pretty certain that he should have received the following emails: Please have him look thru his spam folder.

**8:54 am today -- Test Email** - Are you receiving this email? Mary Beth

**Apr 24 - North Carolina Sea Grant Annual Report - Past Due Report** - Dear North Carolina Sea Grant funding recipient Robert Young, Your report for NC Sea Grant project, ..

**April 20 - North Carolina Sea Grant Annual Report - Completion Report** - Dear North Carolina Sea Grant funding recipient Robert Young, This is a friendly reminder that you 

**Mar 31 - Annual Report - Completion Report** - Dear North Carolina Sea Grant funding recipient Robert Young, The North Carolina Sea Grant funding

**Mar 03 - North Carolina Sea Grant Annual Reporting Heads Up** - I am sending this on behalf of Susan White and John Fear. Good day! Thank you for your work as a PI

**Comment by ecsion** [comment]
Closing this. If it happens again, please reopen.
