### ISSUE TITLE
MIT - Preproposal popup question not needed for RFP that has only Full Proposal selected

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#711]
When only the Full Proposal phase is selected in the RFP Call Builder, do not display the popup window that asks the PI to enter the name of their preproposal (to import data)

![image](https://cloud.githubusercontent.com/assets/17729848/25822637/3902d73c-3407-11e7-9237-2d614f4dbbf1.png)

**Comment by ecsion** [comment]
fixed.
