### ISSUE TITLE
RISG -- CRITICAL Budget Calculations Errors

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#712]
At this budget worksheet URL:

http://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTAwMDA=&id=212

No. of People, Pos. Effort Sea Grant are not calculating correctly. see screen shot below

![screen shot 2017-05-09 at 7 32 06 am](https://cloud.githubusercontent.com/assets/18398763/25848784/dd8850c0-3489-11e7-9c16-1d3c4273162d.png)

In the budget worksheet, all personnel are listed as Senior Personnel; the values in the 904 PDF generate correctly for that line item. The 90-4 PDF then shows 4 people with 16 months of effort for Associates, but looking at the worksheet you will see there are no personnel listed in Other Personnel lines. 

Furthermore, a dollar value of 30689 is entered into Sea Grant Funds in error, making the entire value for Personnel and Fringe incorrect. 

This error must be corrected.  Quickly. Thank you.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
Yes, that is fixed. Thank you.

Alan Desbonnet
Assistant Director
