### ISSUE TITLE
RISG -- Presentation data Exporting Incorrectly to Excel

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#714]
![screen shot 2017-05-11 at 9 21 18 am](https://cloud.githubusercontent.com/assets/18398763/25951302/3868ab00-362b-11e7-8329-e7c3c4983d07.png)
In the user interface screen shot below you can see that there is a Yes/No check box for "Informal Education".

![screen shot 2017-05-11 at 9 16 49 am](https://cloud.githubusercontent.com/assets/18398763/25951212/04424ffc-362b-11e7-91ad-7579e43eef25.png)
 
This must be fixed; the data are needed for annual reporting purposes. Thank you.
Regardless whether or not the user clicks the box or does not, the exported Excel file shows / inserts the PI name into the Informal Education column of the Excel worksheet (see screen shot below).

**Comment by ecsion** [comment]
Not applicable to R2. We are closing this item, please reopen if you still have an issue.
