### ISSUE TITLE
NCSG - Access to report

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#715]
I have a staff member that his role is defined as staff access and he cannot read a report that was submitted.  The log in is chuck_weirich@ncsu.edu and when he goes to the reports tab, he searched for the 2016 report for Robert Roer.  When he clicks on the report to view it, he gets the following shot:

![image](https://cloud.githubusercontent.com/assets/21174930/25954060/26394662-3633-11e7-96ed-f5aa5832e53a.png)

He can view other reports, so that is weird that it is just that single report.

**Comment by ecsion** [comment]
fixed, please check.
