### ISSUE TITLE
Security Warnings with log in

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#716]
Hi there,

We are getting a security warning with logging into eSeaGrant that our logins entered could be compromised. This is happening for multiple users of eSeaGrant. See link below for more details.

https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct

**Comment by mcbridec** [comment]
Our certificate expired but has since been updated. We can close this.
