### ISSUE TITLE
WSG: error when downloading word file narratives in reporting

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#718]
When you download and try to open a word file that has been attached as a narrative in reporting, you get the following error messages (see screen shots)
<img width="541" alt="screen shot 2017-05-15 at 10 17 47 am" src="https://cloud.githubusercontent.com/assets/28117296/26080536/e2a5b2cc-397b-11e7-98b9-2d9987b6b4d1.png">
<img width="501" alt="screen shot 2017-05-15 at 10 17 54 am" src="https://cloud.githubusercontent.com/assets/28117296/26080541/e6de8468-397b-11e7-8398-67e5257ac62b.png">

If you just say okay to all, the files actually seem to open just fine and contents do not appear corrupted...

But can you please fix so we don't get the error messages? 

Thanks.

**Comment by ecsion** [comment]
Kate, please provide url link.

**Comment by kalitle** [comment]
http://esg.wsg.washington.edu/index.php?module=Reporting&relatedModule=Narratives&view=Detail&record=40436&mode=showRelatedList&tab_label=Narratives

Here is a link.  However, please note that you don't get the error messages until you actually try to open the document.

**Comment by ecsion** [comment]
fixed, please check

**Comment by kalitle** [comment]
confirmed - fixed.  thank you
