### ISSUE TITLE
WSG: URGENT - Reports - Customs Forms not showing in Admin view

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#723]
Help!  I can't access the majority of my reporting info to make edits, etc.  Custom forms pages are not showing properly in the Admin view (have not tested for PIs).  Please fix asap.

for example:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=40355&mode=showMultiQuestionStem&QuestionId=15959&tab_label=Economic%20Impacts&tab_label=Economic%20Impacts

![screen shot 2017-05-23 at 4 28 47 pm](https://cloud.githubusercontent.com/assets/28117296/26380828/b4b2372c-3fd5-11e7-995b-67a13a7d586c.png)

another example:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=38331&mode=showMultiQuestionStem&QuestionId=15948&tab_label=Meetings,%20Workshops,%20Presentations&tab_label=Meetings,%20Workshops,%20Presentations

![screen shot 2017-05-23 at 4 34 43 pm](https://cloud.githubusercontent.com/assets/28117296/26380844/c83788f6-3fd5-11e7-89be-fcebd96f25b6.png)

**Comment by ecsion** [comment]
fixed.
