### ISSUE TITLE
RISG --- "Green Dots" for Proposals?

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#724]
It would be very nice to have the "green dots" that show the user they have completed a custom form show up in the RFP/Proposals Module as they do in Reporting Module. A check box the PI could click to signify they have completed something, would make it easier for them to see quickly what is left to complete in a proposal they are working on. This will be even more helpful in R2 when multiple people might be working on the same proposal. 
Thank you for considering this functionality.

**Comment by ecsion** [comment]
Yes, added this to R2
