### ISSUE TITLE
RISG --- Functionality of "Mandatory" option in Custom RFP Forms

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#725]
As presently designed, when the "Is Mandatory" check box is selected in designing a Custom RFP Form, the user cannot SAVE their data input to the form until ALL mandatory fields are completed. There are times when a PI may have to leave a form uncompleted due to time constraints, for instance. At present, the PI cannot save the data and return to complete it later. 

Is there some way to make the functionality of the "Is Mandatory" check box be that the PI cannot submit the proposal until all mandatory fields are completed? This would allow the PI to save input data along the way, but be forced to complete Is Mandatory form fields before they could submit the proposal. This is a more functional and elegant way of handling Mandatory data fields.

**Comment by ecsion** [comment]
This is a good suggestion. We will consider making this enhancement soon.

**Comment by Dipali-Ecsion** [comment]
Done. Please check.
