### ISSUE TITLE
Promoting a proposal for funding without a 90-2

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#728]
When I try to promote a proposal to project and the RFP did not include a 90-2 form (which makes sense to not include it for fellowships), the system will not allow me to promote the proposal to project,.

http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=updateProposaltoPromote&record=2999&phaseid=3001&proposalid=3403&tab_label=Fellowship%20Applications
![capture](https://cloud.githubusercontent.com/assets/17168500/26427066/0cbc7fe4-4090-11e7-9120-ec24dc427953.JPG)

**Comment by ecsion** [comment]
Mary, The workaround for this is to add the 90-2 form and make it available to Sg Admin only. This way you can promote the proposal. In the future we will make changes to the flow so 90-2 is not required.
