### ISSUE TITLE
RISG -- Picklist Order Not Working Correctly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#729]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=10583&mode=showMultiQuestionStem&QuestionId=10629&tab_label=Omnibus%20SG%20Classification%20&%20Focus%20Area%20Effort&tab_label=Omnibus%20SG%20Classification%20&%20Focus%20Area%20Effort

the PI sees the following order:

![screen shot 2017-05-25 at 7 31 10 am](https://cloud.githubusercontent.com/assets/18398763/26448769/d3e34936-411c-11e7-8c82-77556ab7f1e7.png)

However, in the Picklist Editor, at this URL:

https://eseagrant.gso.uri.edu/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9

ADMIN sees this ordering:

![screen shot 2017-05-25 at 7 37 17 am](https://cloud.githubusercontent.com/assets/18398763/26448788/01568c84-411d-11e7-9f6c-f9cd5fdb00ed.png)

Note that item 177 is ordered correctly in the ADMIN Picklist Editor, but does not show up in the correct order for the PI. I would like the corrected. Please DO NOT refill the pick list editor with a different list as then I have to remove half the items, which is time consuming. Please find the issue so that the PI sees the correct ordering as per the PickList Editor. Thank You.

**Comment by ecsion** [comment]
Ok Noted.
