### ISSUE TITLE
RISG --- Budget Worksheet "Waived IDC as Match" check box

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#730]
At this URL:

https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTA1ODM=&id=228

when the "Waived IDC as Match" checkbox is selected, a value is entered (and this is working correctly; thank you).

There are times when only a portion of the "Waived IDC as Match" is used in a proposal. Is it possible that the budget worksheets could be coded so that:

IF the "Waived IDC as Match" checkbox is selected, a value is generated by eSeaGrant and entered into the budget exactly as it is now done --- no change in this is requested.

IF the "Waived IDC as Match" checkbox is NOT selected, can the worksheet be coded so that a value can be added into the waived idc value box by the user? The values entered by the user MUST be added into the total just as it currently is when the box is checked. The difference is that the value is input by the user when the box in NOT selected, and calculated by eSeaGrant when it is.

Thank you.

**Comment by ecsion** [comment]
Alan, We will put this in the queue and get this done in the next few weeks.
