### ISSUE TITLE
MASGC: Urgent - Users cannot login/change password

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#731]
We are having a big problem right now. Users that haven't accessed the system in a couple of months and a few new users are receiving errors when they try to login. It seems to have something to do with the reset password that they are required to do since the security update a while back.

I am able to troubleshoot the problem by sending them a "reset password" on my admin account from inside the system but I am expecting 14 full proposals plus all the Co-PIs to login for my full proposal deadline next week and I can't spend the time to send all of them reset password links.   I've had to stop what I'm doing and send 4 already today.'

Unfortunately I don't have a screenshot since I am not the one trying to access the system. I will ask the next one to send me a screenshot.
In the meantime, they say it says "Not Found":

"Not Found
The requested URL /modules/Users/actions/&invalid_request=1 was not found on this server."

**Comment by ecsion** [comment]
fixed.
