### ISSUE TITLE
LASG - New Account Verification Problem

### ISSUE THREAD

**Issue by LSUSG** [ecsion/eSeaGrant-Client-Bug-Tracker#732]
We are also having problems with access to Ecsion at Louisiana Sea Grant, however, ours has to do with new users. 

As they attempt to complete the verification steps, they hit a snag with the phone verification. When they enter their number, they receive a call, but the call indicates that there is a system error. 

Any assistance is appreciated. Thanks.

**Comment by ecsion** [comment]
fixed.
