### ISSUE TITLE
OSG Send Email is not working

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#734]
When I go to the Actions button --> drop down list "Send Email," this function is not working both in the People tab and also the RFP --> Enable Access for PI tab, and possibly elsewhere.
![capture](https://cloud.githubusercontent.com/assets/17168500/26687697/45f94da8-46a5-11e7-8d97-7ac9609759ca.JPG)

**Comment by ecsion** [comment]
Mary, We logged into your account and sent an email and it was delivered fine. Did you get this popup:
<img width="1099" alt="screen shot 2017-06-01 at 12 09 58 pm" src="https://cloud.githubusercontent.com/assets/1612666/26689350/5f22c322-46c3-11e7-8cb9-5c1ee5bbcb64.png">

**Comment by marypleasant** [comment]
It is working now... likely user error. Apologies!
