### ISSUE TITLE
User Password Issue

### ISSUE THREAD

**Issue by nelsonsj** [ecsion/eSeaGrant-Client-Bug-Tracker#735]
Proposals are due tomorrow, June 2. PI's now just entering back into system and many are resetting their passwords. When they reset they are receiving the following error messages. 

Not Found
The requested URL /modules/Users/actions/&invalid_request=1 was not found on this server.

I am getting around this issue by triggering the reset as an administrator but wonder what is causing this issue? Thank you.

**Comment by nelsonsj** [comment]
Another could not get the log in fields to appear on their screen.

![image](https://cloud.githubusercontent.com/assets/25692455/26698815/6b47a33a-46e5-11e7-9627-b5900a99df3f.png)

**Comment by ecsion** [comment]
fixed.

**Comment by nelsonsj** [comment]
Thank you!

Sally J. Nelson
Sally.nelson@unh.edu<mailto:Sally.nelson@unh.edu>
603.862.2987

[SMSOE_Horiz_RGB small]
