### ISSUE TITLE
RISG -- RFP Module Invite Peer Reviewers Not Working -- CRITICAL

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#736]
at this url:

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=3821&phaseid=3823&tab_label=Full-Proposals

when I set a due date and time, then click SAVE, nothing is saved and I am not allowed to invite reviewers. This must be corrected so I can begin the review process for research proposals. Thank you.

**Comment by ecsion** [comment]
Alan, we are in middle of launching new peer review module with Conflict of interest form. If you could launch next Tuesday/Wednesday, we will have the new peer reviews pushed for RI.

**Comment by chelkahn** [comment]
I need to send my reviews out today and Monday, as promised to the reviewers. If it is not working for WSG this will be a HUGE issue for us.

**Comment by ecsion** [comment]
fixed.
