### ISSUE TITLE
WSG - URGENT Issues with Co-PIs on Summary form

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#737]
Our full proposals were submitted yesterday and dowloaded by WSG today. There are issues with the summary form where Co-PIs are either not showing up or some are showing up. Here are the two that I found so far: 

FRIEDMAN
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41300&mode=showProposalTitle&tab_label=Start%20Here

Download only shows Chadsey and Harvell and online version shows Burge and Blake. See attachment. 
[Project_Summary_Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1048623/Project_Summary_Form.pdf)

CHRISTIE 
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41294&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

Same issue only NO Co-PIs are showing on summary. See attached:
[1. Project_Summary_Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1048626/1.Project_Summary_Form.pdf)

We NEED to send out reviewers today OR monday. This is a major issue and needs to be fixed ASAP. I have only reviewed 8 of the 31 proposals we received. Will send others as I find them!

**Comment by chelkahn** [comment]
Same with 

GALLAGHER: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41284&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

HAUSER: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=40966&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

**Comment by chelkahn** [comment]
HELFIELD: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41433&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

**Comment by chelkahn** [comment]
HOLTGRIEVE: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=40629&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

**Comment by chelkahn** [comment]
KELLY: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41232&mode=showMultiQuestionStem&QuestionId=34082&tab_label=Co-Principal%20Investigators&tab_label=Co-Principal%20Investigators

**Comment by chelkahn** [comment]
And many more.

**Comment by ecsion** [comment]
fixed. The issue was that we were displaying investigators that had hours associated with them in the budget sheet. However, now we are displaying all. We are closing this issue if you still have a problem, please reopen.

**Comment by chelkahn** [comment]
Many thanks, all! It is fixed and working well!
