### ISSUE TITLE
WSG - Project summary form - budget years show as 0

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#738]
See example for Gough:

http://esg.wsg.washington.edu/operations.php?action=budget&proposal_id=NDA3NDI=&id=899

[1. Project_Summary_Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1048731/1.Project_Summary_Form.pdf)

Should be pulling data from budget sheets.

**Comment by ecsion** [comment]
fixed. Please check. Re-Open if not fixed.
