### ISSUE TITLE
OSG - trouble setting up a custom view with PI Name condition

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#739]
Within Reports, Add Custom View I am having a little bit of trouble setting up a custom view that will include responses from 4 Custom Forms AND that also excludes all Custom Forms responses with PIs with TEST in the name. I have one PI with the first name TEST and it will not filter out.
First I created a view without excluding the PI name with TEST in it, saved it. That worked just fine. Then I added a condition to exclude the PI name TEST, but the result did not change – it still included the PI name, TEST.
I deleted the custom view and started over, and got the same result. 

What am I doing wrong? It cannot be an "Any condition" - that did Not work at all. 
Is the condition “PI Name” only good for the PI last name? That is not a choice in the condition picklist.

Here are my steps:
1) Reports > Add custom view > 
2) View Name: Custom Form Report - Influenced Funding
3) Set as Public
4) Choose columns and order (Max 12): Custom Form Title, PI Name, Project Number, Reporting Call
5) All Conditions >
Add Condition >	PI Name	not equal to	TEST
6) Any Condition > 
Add Condition >	Custom Form Title 	equals 	E. New Extramural Funding in Addition to Matching Funds
Add Condition >	Custom Form Title 	equals 	New Extramural Funding in Addition to Matching Funds
Add Condition >	Custom Form Title 	equals 	D. Prizes and Honors Awarded to Project Personnel
Add Condition >	Custom Form Title 	equals 	Prizes and Honors Awarded to Project Personnel 
7) SAVE
Attached are the custom view setup and then the resulting view. 
![2017-06-02_1712a](https://cloud.githubusercontent.com/assets/17169131/26748947/ec68b940-47b7-11e7-8970-606f5ea9a424.png)
![2017-06-02_1715](https://cloud.githubusercontent.com/assets/17169131/26748959/125bc4c6-47b8-11e7-874b-b33a13678d2a.png)

Thanks!

**Comment by ecsion** [comment]
The issue is with the following condition you added:
	PI Name	**not equal to**	TEST  (Test is not equal to Kolesar, Test) and so it is not caught

Instead you should us the clause **"Does not contain"** This will work perfectly for you.
