### ISSUE TITLE
RISG -- PI Name not showing in Conflict of Interest form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#740]
At this URL:

https://eseagrant.gso.uri.edu/operations.php?action=peerresponseform&guid=F7EE39A5-9235-4B6E-9BCC-FFF78D6A34DF

The PI Name is not showing in the upper right portion of form. Either remove the PI name or have the correct PI name for the proposal interred.

![screen shot 2017-06-05 at 8 49 16 am](https://cloud.githubusercontent.com/assets/18398763/26784540/32078d26-49cc-11e7-9c67-e9761aeeb37c.png)

thank you.

**Comment by ecsion** [comment]
fixed.
