### ISSUE TITLE
RISG -- Comment on New/R2 Peer Review Screen

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#741]
In the screen taken below, it would make the presentation of the various options that the user can select clearer, and cleaner, if there were a SPACE inserted between the radio button and the text.

This is not a critical fix, and is more a suggestion that would make the overall presentation to the user slightly more professional and polished looking.

**Comment by alandesbonnet** [comment]
![screen shot 2017-06-05 at 8 48 59 am](https://cloud.githubusercontent.com/assets/18398763/26785734/eef26cb2-49d1-11e7-9ba9-913208ac96df.png)

**Comment by alandesbonnet** [comment]
My apologies ---- I forget the screenshot, then hit the wrong button here in GitHub. It's Monday morning......Please see the suggestion contained above.

**Comment by ecsion** [comment]
fixed.
