### ISSUE TITLE
RISG --- Correction in Peer Review Comments Screen

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#744]
See the PDF below to correct nearly invisible logo and to make link to Reviewer Instructions more visible. Thank you.

[PeerReviewScreenCorrection.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1052645/PeerReviewScreenCorrection.pdf)

**Comment by ecsion** [comment]
fixed.
