### ISSUE TITLE
WSG - PI missing on summary form (URGENT)

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#745]
#737 

I think there is a similar issue with PIs on the summary form. See here: 
http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=41029&mode=showProposalTitle&tab_label=Start%20Here

Cattolico is not showing up on form.

**Comment by ecsion** [comment]
fixed.
