### ISSUE TITLE
MIT - Correction to "Link Projects" view in Report Calls

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#747]
In the view that allows you to select projects to link to when building a Report Call -- http://eseagrant.mit.edu/index.php?module=CallReporting&relatedModule=Projects&view=Detail&record=34360&mode=showRelatedList&tab_label=Link%20Projects  --  please include the project title.

![image](https://user-images.githubusercontent.com/17729848/26882881-a243671a-4b69-11e7-8600-1b0fe15dacc2.png)

**Comment by ecsion** [comment]
Kathy, We will do this.

**Comment by Dipali-Ecsion** [comment]
Done. Added 'Project title' column in Link Projects.
Please check.
![image](https://user-images.githubusercontent.com/17423049/50092130-407c8200-0233-11e9-81b2-70148fdcee82.png)

**Comment by kdez** [comment]
Thx!
