### ISSUE TITLE
RISG -- Custom Form Export Fields Are Garbled

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#750]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=MultipartAnswers&parent=&page=1&view=List&viewname=169&orderby=&sortorder=&showList=true&tab_label=Custom+Form+Responses&search_params=%5B%5B%5B%22answer%22%2C%22c%22%2C%22impacts%22%5D%2C%5B%22pi_name%22%2C%22c%22%2C%22nixon%22%5D%5D%5D

the Excel file exported has several fields mixed/transposed. For instance, the Title field has data that should be in the Type field; Relevance, Response, Results field data should be in the Title field; Recap field data should be in Relevance, Response, Results field etc.  This needs to one corrected. Thank You.

[CustomFormResponsesExport-06082017-2.xlsx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1061743/CustomFormResponsesExport-06082017-2.xlsx)

**Comment by alandesbonnet** [comment]
It appears that Column J or K data was moved into Column D (Type) during the export process. I tried several times but all with the same result that the data are not in the correct columns beginning with Column D.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
This appears to be exporting data correctly now. Thank you.
