### ISSUE TITLE
NHSG - CP Support

### ISSUE THREAD

**Issue by nelsonsj** [ecsion/eSeaGrant-Client-Bug-Tracker#753]
Good morning, I am in the process of downloading final proposal to prepare for peer review. I find that the CP support data is not downloading with the other proposal components. Have I done something wrong or is this a bug in the system?

Thank you.

**Comment by ecsion** [comment]
Sally, We can't reproduce this issue. Please provide the name of the proposal that has the CP Support form missing.

**Comment by nelsonsj** [comment]
I have just received advise from RISG and it appears I simply neglected to click the download in PDF button contained within the custom form. Sorry for any alarm and please excuse my ignorance on the system! Have a great day and thank you for your help.
