### ISSUE TITLE
WSG - IMPORTANT !! Peer reviewer form changes impact current review process

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#755]
Deepak - I was a little startled to notice that the change to the peer reviewer form would impact my current, on-going review process. I know we made comments on this layout, but given that there was no time to test it or use it prior to it rolling out is very concerning to me. 

Here are most immediate concerns, but I have other questions I'd like to discuss later.

1. Reviewers are able to select "None" -  meaning a reviewer can not rate an criteria, which was not formerly an option and most certainly not an option for WSG. This could be very bad for us if people arent paying attention or get confused with instructions. 

2. Reviewers are able to comment for each criteria AND leave an overall comment. I see this being useful for Panels but WSG has never used this for external reviewers. I do not know how this interacts with the rebuttal stage and was not able to test this before release. This is not how we wanted to do it nor was it how we have done it in the past OR at the proposals stage. 

AND we have reviewers who have already submitted reviews for this call and only submitted one section of comments. This is concerning to know there will be varying formats moving forward. 

3. The link for the instructions is hidden. I also do not like how it needs to be in a pop up window and is not easy for reviewers to reference the rating instructions while reviewing the proposal. It is important they know what the criteria are and what we would like them to be scoring for. 

Please help me address these concerns ASAP.

**Comment by ecsion** [comment]
We have rolled back the code branch to have old panel reviews.
