### ISSUE TITLE
URGENT FIX - Document Request Submissions viewable to Applicant

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#756]
Issue #1. eSeaGrant now copies the applicant/PI on the submission confirmation of documents (letters of recommendation) to the document providers. The Email 1 below was sent both to Elise Granek (the document provider) and Sabra Comet (the applicant), and the "clicking here" link was live and linked to the document provided, which is a breech of confidentiality, (a big problem!).

The "Form response viewable by PI" box was NOT checked for this form, see image below. 

Issue #2. In addition, when I set the panel review due date, it changed the submission deadline provided in the email to the panel review due date (and it supposed to be the application deadline). See email 2 below. The deadline is supposed to be June 12th.

**Email 1**
Dear Elise Granek,

You have successfully submitted the following documents for Sabra Comet for: 2017 Natural Resource Policy Fellowship - Sabra Comet for the 2017 Natural Resource Policy Fellowship .

S Comet- OR NatResPolicy Fellow Recommendation_Granek.pdf

You may access your personalized document submission page by **clicking  here** at any time up until the deadline (**12 Jun 2017, 05:00 PM**) to update your submission. You will receive a confirmation email each time you click the submit button with your latest updates.

Submission Date and time: 12 Jun 2017, 04:19 PM

**Email 2**
Dear Daniel Cox,

You have successfully submitted the following documents for Todd Lemein for: 2017 Natural Resource Policy Fellowship - Todd Lemein for the 2017 Natural Resource Policy Fellowship .

2017 Natural Resource Policy Fellowship_ToddLemein_from_DanCox.pdf

You may access your personalized document submission page by clicking  here at any time up until the deadline (**30 Jun 2017, 04:00 PM)** to update your submission. You will receive a confirmation email each time you click the submit button with your latest updates.

Submission Date and time: 13 Jun 2017, 01:19 PM

Sincerely,

Oregon Sea Grant
eSeaGrant Coordinator
Corvallis OR 97333
541-737-2714

![capture](https://user-images.githubusercontent.com/17168500/27103501-b20ce486-503d-11e7-8293-cf03a8bb707b.JPG)

**Comment by ecsion** [comment]
fixed, please check.
