### ISSUE TITLE
MIT - edit for project initiation popup window

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#757]
In the popup window that the PI sees when s/he starts a new proposal change...

If you wish to start a new proposal, fill the title and click continue.

   ...to ...

To start a new proposal, enter project title here and click continue.

**Comment by Dipali-Ecsion** [comment]
Done. Please check.
![image](https://user-images.githubusercontent.com/17423049/49801272-bedaaf00-fd6f-11e8-8f37-dfa830ff89e6.png)

**Comment by kdez** [comment]
Thanks!
