### ISSUE TITLE
RISG--Reviewers Can't Easily Find Download Proposal Link in new (R2) reviewer panel

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#758]
I have had many queries by reviewers going to the new (R2) reviewer page, saying they can't see where to access the actual proposal. A few have also asked about finding instructions. See the screen shot below, which has the DOWNLOAD PROPOSAL and INSTRUCTIONS links portrayed in a light blue color, rendering it difficult to see----it does not jump right out.

![screen shot 2017-06-21 at 9 33 50 am](https://user-images.githubusercontent.com/18398763/27386918-40e27284-5665-11e7-9f97-51356ca2e44f.png)

I request that the text for those two important links be given a color that stands out starkly --- bolded white would probably be best, though bold red or bold yellow or bold orange or bold pink would likely jump off the page as well. I would also suggest that the text "Scoring Rubrics" and "Reviewer Comments" be made white or other color that stands out a bit more easily. We won't want reviewers putting text in the wrong places, or having to search for things.  Thank You for considering this change.

**Comment by ecsion** [comment]
change the download link to a button that is much more obvious. Please check. We are closing this issue. Please reopen if not resolved.
