### ISSUE TITLE
MIT -- "Password not secure" at login reported by user

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#759]
One of my PIs is using the latest Firefox on a Mac - he says that when he goes to login to eSG he gets a popup warning him that his login info may not be secure.  He says it's because eseagrant.mit.edu is not encrypted (http not https)  

He may be wrong, but FYI - screenshot below

![password_unprotected](https://user-images.githubusercontent.com/17729848/27401529-8558db70-5691-11e7-9822-49a1d8dab88c.png)

**Comment by alandesbonnet** [comment]
Tell it the first time to accept the certificate or something like that and all is good. I use it all the time without issue.

**Comment by ecsion** [comment]
SSL certificate has been installed for MIT eSeaGrant.
