### ISSUE TITLE
MIT - "Search All Records" results - show PI for "User Task Information" results

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#762]
Example: If you search for "Nitrogen" in the "Search All Records" bar and click on "External User Tasks" and select one of the items -- the PI is not displayed - please show PI.  (A good general rule: "always show the PI")

**Comment by ecsion** [comment]
Currently we can only show the title ins search results. We will look into showing additional fields.
