### ISSUE TITLE
CASG: Downloading Panel Review Comments 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#763]
Hello, 

I've tried downloading several times the "multiple pdf files zipped" files and some of them are not coming through. It shows the file size as zero bytes and I get an error message. Can you please look into this?

Link: https://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=32486&tab_label=RFP%20Reports

Screen capture of zip folder:
![screen shot 2017-07-07 at 9 32 06 am](https://user-images.githubusercontent.com/17860279/27967407-cbd8b12a-62f7-11e7-8e92-966d039f7d27.png)

Screen capture of error message: 
![screen shot 2017-07-07 at 9 32 19 am](https://user-images.githubusercontent.com/17860279/27967425-dc00f242-62f7-11e7-9d8c-9d9386ceadd9.png)

Thanks,

Miho

**Comment by ecsion** [comment]
fixed. We are closing this issue. If not fixed, please open or re-create anew one.
