### ISSUE TITLE
RISG -- user email template does not autofill the To: field

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#764]
At the following URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=3821&phaseid=3823&tab_label=Full-Proposals

The selected reviewer email addresses are not populated into the To: field of the user email template (see screenshot below)

![screen shot 2017-07-10 at 9 05 15 am](https://user-images.githubusercontent.com/18398763/28019529-424bdf04-654f-11e7-8d3a-98c4992ce652.png)
Please correct this so that I can email reviewers reminders of an oncoming deadline date. Thank you.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
fixed thank you

Alan Desbonnet
Assistant Director
