### ISSUE TITLE
Some emails going to spam, others not

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#766]
I sent an email via eSeaGrant to applicants to a fellowship and copied my eSeaGrant email. Of the 12 intended recipients of this email, 4 were copied to my inbox and the other 8 ended up in my spam folder. This keeps happening causing me to not want to send emails from eSeaGrant since I am never sure if the recipient actually receives the information. I can pass along which email addresses ended up in spam versus the inbox, if that is helpful.

**Comment by ecsion** [comment]
Send us the actual emails that went into spam and that went into inbox from the same set. You can send it to eSeaGrant@ecsion.com

**Comment by ecsion** [comment]
Is this considered resolved? Should we close this?

**Comment by marypleasant** [comment]
I think so, you can close.
