### ISSUE TITLE
OSG Urgent - Peer reviews not visible to PI

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#767]
I have shared the peer reviews with PI's so that they can provide a rebuttal, but the PI cannot see the peer review. We plan on sharing reviews with PIs by early August for our Biennial competition, so this is an urgent fix. Please see links and images below for more detail.

ADMIN VIEW
http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=17610&phaseid=17612&tab_label=Full-Proposals
![capture1](https://user-images.githubusercontent.com/17168500/28189098-6eaf8fa0-67d9-11e7-9faa-8498c031ae6c.JPG)

http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=17610&phaseid=17612&tab_label=Full-Proposals
![capture2](https://user-images.githubusercontent.com/17168500/28189141-9e000b54-67d9-11e7-8e49-aa6d5724ceea.JPG)

PI VIEW
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=17623&mode=showRebuttalForm&tab_label=Rebuttal
![capture4](https://user-images.githubusercontent.com/17168500/28189189-d18b3818-67d9-11e7-9c8a-41260b0dc0e6.JPG)

**Comment by marypleasant** [comment]
It looks like panelists also cannot see the peer review:
http://eseagrant.oregonstate.edu/operations.php?action=panel_reviewer_detail&guid=OUM0NEJBNTctMDFFMC00MTU1LUExQTgtRDE4MTM2MDlFMjQ4&exuti=MTc2OTY=&propid=MTc3MDQ=&reviewer=MTc3MTE=&rid=SDE2LTIxMQ==#
![capture](https://user-images.githubusercontent.com/17168500/28189438-c6a98cfa-67da-11e7-9974-f88a96e0fe70.JPG)

**Comment by ecsion** [comment]
Mary, for a peer review to be available to Panel  Reviewer, you have to mark the review as "Accepted"
This is done from Step 7, "Invite Peer Reviewers for Proposals" Tab. Click on "Change" hyperlink from Accepted Peer reviews column. 

For a Peer review to be viewable by the PI, both the following conditions have to be true:
1. The review is marked accepted (as explained above)
2. The review is shared with the PI (this is done from the completed tab)

**Comment by marypleasant** [comment]
Thanks for the instructions. Works perfectly!

Mary
