### ISSUE TITLE
OSG Urgent Rebuttal Feature not working

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#768]
I am testing out the rebuttal feature which we plan on delivering to PI's shortly for a current research competition, and I cannot see where to upload or submit my rebuttal as a PI. How do PI's submit anything?

PI view:
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=17623&mode=showRebuttalForm&tab_label=Rebuttal
http://eseagrant.oregonstate.edu/index.php?module=People&view=List&tab_label=All%20People#
![capture](https://user-images.githubusercontent.com/17168500/28189848-c527fe46-67dc-11e7-86cb-6bf4d1f2ef0f.JPG)

**Comment by ecsion** [comment]
Mary, for a peer review to be available to Panel  Reviewer, you have to mark the review as "Accepted"
This is done from Step 7, "Invite Peer Reviewers for Proposals" Tab. Click on "Change" hyperlink from Accepted Peer reviews column. 

For a Peer review to be viewable by the PI, both the following conditions have to be true:
1. The review is marked accepted (as explained above)
2. The review is shared with the PI (this is done from the completed tab)

**Comment by marypleasant** [comment]
Thanks so much for the instructions! Works perfectly.

**Comment by marypleasant** [comment]
One more question - the PI uploaded a file with her submitted rebuttal, but I cannot seem to find it anywhere from the admin side? Where do attached rebuttal files go?

PI VIEW
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=17635&mode=showRebuttalForm&tab_label=Rebuttal
![capture](https://user-images.githubusercontent.com/17168500/28222688-729421ea-687d-11e7-929a-c0a441eb11cb.JPG)

ADMIN VIEW
http://eseagrant.oregonstate.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=17610&phaseid=17612&tab_label=Full-Proposals
![capture1](https://user-images.githubusercontent.com/17168500/28222747-a80edd1a-687d-11e7-9832-945be2e4bbc0.JPG)

**Comment by ecsion** [comment]
The issue was that download link was showing even when there were no rebuttal files there to download. Now we have changed the logic to show download link only when rebuttal files are present.

**Comment by ecsion** [comment]
Please check and let us know if you need anything else or we can close this issue.

**Comment by marypleasant** [comment]
Looks good. Thanks!
