### ISSUE TITLE
!!! WSG - Edits needed to hard coded instructions in rebuttal stage

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#770]
Deepak promised these changes last week. Must be done ASAP, opening rebuttals tomorrow!

PI view: http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=44220&mode=showRebuttalForm&tab_label=Rebuttal

Instructions for **REBUTTAL SUPPORTING DOCUMENTS** should read::: 

REBUTTAL SUPPORTING DOCUMENTS
- An optional function to include supplemental files with your rebuttals. Use the "choose file" button below to upload a document.
- You may upload one file per review/rebuttal.
- Only PDF Documents are accepted.

**Comment by ecsion** [comment]
Chelsea, we have fixed the instructions. Please check and let us know if you find any issues. We have deployed to both Beta and all servers including Washington server.

**Comment by chelkahn** [comment]
Thank you!
