### ISSUE TITLE
WSG - supporting doc upload function not working

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#771]
Deepak added a file upload option for EACH review/rebuttal. BUT when a file is added it:

1. Gets uploaded, but still says "no file selected" next to the button, while the title of the doc is floating off to the side. 

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=44220&mode=showRebuttalForm&tab_label=Rebuttal

![screen shot 2017-07-18 at 1 29 39 pm](https://user-images.githubusercontent.com/26942420/28338322-6d9e2ddc-6bbd-11e7-9504-8d7e3a31d971.png)

2. When in the system as an Admin, trying to download the doc, there is only ONE download option, with no discernible way to tell which review the file is in relation to. 

3. When trying to download the file, the system says there is no file. 
http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=34570&phaseid=34572&tab_label=Full-Proposals

![screen shot 2017-07-18 at 1 29 17 pm](https://user-images.githubusercontent.com/26942420/28338442-d6dd9558-6bbd-11e7-9706-98e11aab3950.png)

(all of which needs to be fixed by tomorrow)

**Comment by ecsion** [comment]
1. Now shows the file name of the file uploaded. 
2. Now on admin screen download link will show only if rebuttals are present to be downloaded. 
3. This is same resolution as 2.

please check and report any issues.

**Comment by chelkahn** [comment]
Looks great, thanks!
