### ISSUE TITLE
WSG - rebuttal stage, identification of submitted rebuttals

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#772]
On the main screen of full proposals: 
![screen shot 2017-07-18 at 1 35 52 pm](https://user-images.githubusercontent.com/26942420/28338592-49fda5a0-6bbe-11e7-8072-b60f270866e7.png)

You can see how many rebuttals have been submitted and how many are missing. Great tool, very useful.

However, when you dive into "Manage Rebuttals" there is no indication of this data. You have to individually download each "PDF export" to see if the rebuttal exists. There should be some indicator of who submitted and who hasn't on this screen. 

Furthermore, you do not know who attached a file - (in the rebuttal interface called "REBUTTAL SUPPORTING DOCUMENTS" and in the admin interface called "Rebuttal File"). For this you need to download each file to see if it exists. Please see issue #771 for other issues related to this.

**Comment by ecsion** [comment]
done, now download link shows only if a rebuttal file is present.

**Comment by chelkahn** [comment]
Is there any possibility for an indicator as to which review the file is related to? 

Please note in the WSG version, you can upload one file for each review during the rebuttal process.

**Comment by ecsion** [comment]
Chelsea, We will look into this but can't promise this can be done quickly.

**Comment by ecsion** [comment]
fixed.
