### ISSUE TITLE
RISG--Reviewer allowed access as PI CRITICAL -- ISSUE

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#773]
see screen shot below, which was sent to a reviewer, and which provided access to eSeaGrant as if they were the PI --- this SHOULD NOT happen. I do not have any further detail than this, nor has any other reviewer reported a similar experience. This reviewer has User History = Reviewer and so should not have any direct access to the proposal other than as a reviewer. Please look into this so that such does not/cannot occur again in the future. Thank you.

![screen shot 2017-07-19 at 11 22 08 am](https://user-images.githubusercontent.com/18398763/28375322-2c6f23e4-6c75-11e7-9d2e-e968372ec873.png)

**Comment by ecsion** [comment]
Alan, anyone, even reviewers can self register for a PI account in eSeaGrant. The email that you have attached is simply email verification step during self registration process.

**Comment by alandesbonnet** [comment]
I thought I had set eSeaGrant so that it is INVITE ONLY, meaning stray persons cannot simply register for an account. I do not want anyone to be able to self-register, so if I have somehow NOT set eSeaGrant up correctly, some instruction as how to do so would be welcomed as I thought I had indeed set it up to exclude the option to self register.

Thank you for providing guidance so that I can be sure no one can self-register.
Alan

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Alan, we currently have MIT setup to not allow public registrations. In case of MIT, Kathy has to add every PI to eSeaGrant. It is a simple process, You will first create a people record and then select a people record (or records) and send a welcome email to create a user account for them. Let us know if you want to change RI eSeaGrant to not allow public registrations.

**Comment by alandesbonnet** [comment]
Yes, please change the RISG process to mimic that of MIT to not allow public registrations. Thank you very much.
Alan

**Comment by ecsion** [comment]
Done, please check.
