### ISSUE TITLE
CASG: State Fellows RFA Tab Sequence Issue

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#774]
Hi,

I'm creating a RFA for the 2018 State Fellows, but the tab sequence that I want won't save. 
I would like the following sequence:

1. CV
2. Personal education and career goal statement
3. Identify Letter Writers
4. Invite Letter Writers
5. Transcripts 

But it keep changing it to the below: 
![screen shot 2017-07-21 at 9 37 51 am](https://user-images.githubusercontent.com/17860279/28473289-d0dcb8c2-6df8-11e7-80f7-8fdb189ddead.png)

And here's the link to the RFA: https://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&record=40477&mode=changeLHSTabSequence&tab_label=Tab%20Sequence&tab_label=Tab%20Sequence 

Thanks for your help.

Kind regards,

Miho

**Comment by ecsion** [comment]
& in form name (Personal **&** Career) was causing the issue. We have made  a change so we no special characters will not be an issue when saving sort order. We are closing this issue. Please reopen if you still face an issue while saving.
