### ISSUE TITLE
RISG -- Error in Peer Review Comment PDF output for PI

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#776]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=3821&phaseid=3823&tab_label=Full-Proposals

When I click PDF EXPORT for the first PI in the list (BIDWELL -- see screenshot below):

![screen shot 2017-07-25 at 2 38 58 pm](https://user-images.githubusercontent.com/18398763/28588078-48adae96-7147-11e7-8b5a-13764e5ed20e.png)

I am returned the PDF which is attached. In the PDF there are a number of "comments" boxes that are blank, and are from "RISG TestMonkey" which is a fake account I use for testing new forms and functions. I did use TestMonkey on the Bidwell proposal to test review comment entry, etc., but subsequently removed all trace (so I thought) before entering the true peer review process.

[PeerComments_RISG.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1174408/PeerComments_RISG.pdf)

I would like to have ALL comments by TestMonkey removed so that a clean set of review comments go to the PI. I also do not want those comments to go to the Panel part of the process. Thank you for removing them. If possible, there should be fix created so that these kinds of "ghosts" don't linger in the system once they are removed by ADMIN (or at least thought they are being removed).

**Comment by ecsion** [comment]
fixed. Closing this issue, please reopen if not fixed.
