### ISSUE TITLE
Error in RFP Reports  - Full Props

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#777]
When downloading Proposal List (Excel Export) file, I see a glitch in data. 

http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=DownloadPreProposalsList&record=34267&phaseval=34270

See Kerry Naish row - shows $0 for all budget information, which I know to be incorrect. She is requesting Y1 $124,960.00 SG  / $70,568.00 CS for example.

I checked others to see if there were issues but Cordell, Keister, McDonald and Williams all appear correct. Would love to know whats causing this and if it is impacting any others.

Thanks

**Comment by ecsion** [comment]
We had an issue where some calculations were not triggered in some rare situations. This has been fixed, please check. we are closing this issue. Please reopen if it is not fixed.
