### ISSUE TITLE
WSG = Panel review - review/rebuttal download option

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#778]
http://esg.wsg.washington.edu/operations.php?action=panel_reviewer_detail&guid=MEJDNTFDNjAtREJBOC00MEIyLUJBQjUtNTRCRDg4NzM0QTg1&exuti=NDQzMjE=&propid=NDA0MDY=&reviewer=NDQzMjI=&rid=SDE2LTIxOQ==#

In the current Full Proposal panel, you can download a pdf of the proposal but only view a pop up window for the review/rebuttal. This is an issue for users as you cannot reference the content while typing in the comment boxes. 

Please make these both downloads. Can look exactly like the blinded version of the "Peer Review PDF Downloads" in RFP reports with the rebuttals attached.

**Comment by ecsion** [comment]
The view for review/rebuttal has a print button that downloads a pdf.

**Comment by chelkahn** [comment]
I still have issue with this - from a usability standpoint, it does not make sense that these two files get downloaded differently. Please keep in mind that many of our panelists are not the most computer savvy people. If not a huge issues, I would like to continue requesting this.
