### ISSUE TITLE
RISG --- Reviewer Numbering in Rebuttal / Panel modes

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#780]
As ADMIN, when I access peer review comments in PDF it provides reviewer identity. 
As PI reviewer identity is hidden, and reviewer is references as Reviewer #1 (#2, so forth).

PLEASE add Reviewer # to the PDF version for ADMIN. When PIs respond in a rebuttal, they reference reviewers as #1, #2, etc. If ADMIN and Panelists do not have the correct Reviewer # associated with Reviewer identify, chaos will ensue. 

Please ADD reviewer # to the PDF (and screen views) for ADMIN and Panelists. Thank you.

**Comment by ecsion** [comment]
This is on our list to do and will be done early next week.

**Comment by ecsion** [comment]
fixed.
