### ISSUE TITLE
RISG --- "View" option of Share not working for ADMIN in Rebuttal

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#781]
at this URL

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&record=3821&phaseid=3823&mode=rebuttalsSetup&tab_label=Full-Proposals

clicking the "View" option after Sharing a rebuttal , does not open a view to the rebuttal as expected. Instead, ADMIN has to login as the PI, which is cumbersome. Please correct this. Thanks.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
Fixed indeed. Thank You.

Alan Desbonnet
Assistant Director
