### ISSUE TITLE
Reviews...they WERE here

### ISSUE THREAD

**Issue by JenMerrill** [ecsion/eSeaGrant-Client-Bug-Tracker#782]
I'm prepping for our technical panel and went into our system to verify reviews submitted and accepted were still there and they are not. I received the cc of notification to a reviewer this morning that his review was successfully submitted but it is not in the system; still as "started" not submitted. Others that had submitted comments with scores are not visible.

**Comment by ecsion** [comment]
Jen, The reviews are there. The SG Admin Panel review screen was developed for the old Panel reviews and so was not displaying the correct status. This has been fixed. Please check.

**Comment by ecsion** [comment]
We are closing this issue. If it is not resolved, please open it back.
