### ISSUE TITLE
NCSG - Export Peer Review Avg Rating

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#783]
Is there a way we can export this page so we can have all the average scores in one excel spreadsheet?  We would like this entire page exported:  http://eseagrant.ncseagrant.ncsu.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=13146&phaseid=13148&tab_label=Full-Proposals

**Comment by ecsion** [comment]
Hi Mary, You can individual and average scores from the Reports Tab (Left hand side navigation)

http://eseagrant.ncseagrant.ncsu.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=13146&tab_label=RFP%20Reports

**Comment by ecsion** [comment]
We are closing this issue. If it is not resolved, please open it back.
