### ISSUE TITLE
WSG: Scribe cannot see any proposals

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#784]
We have assigned Kate Litle (me) as scribe for all proposals.  However, when I use my panel view link, I get a blank page - last thing I can see is the link for instructions and the whole section where proposals are supposed to appear is blank.

When we remove me as scribe for a proposal, it then appears in my list...

**Comment by ecsion** [comment]
Kate, we are yet to complete the Scribe functionality and so it not available for use.  We are looking into a work around for you. Give us a few days to consider options.

**Comment by kalitle** [comment]
It's fine - we don't have to use the scribe function for our upcoming panel... were just going to try it since it appeared to be there.  Thanks.

**Comment by ecsion** [comment]
fixed, please check

**Comment by ecsion** [comment]
closing, please reopen if not fixed.
