### ISSUE TITLE
Proposed Update to eSG Annual Reporting Publication Form

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#785]
After completing the annual reporting cycle, we would like to propose matching the "publication types" included on eSG's Publication form (under Repors / Report Calls) so that it includes all of the publication types that are listed on the National Sea Grant Library's publication submission portal. Please see comparative screen shots below. 

The current list of publication types in eSG does not include some of the most commonly used options (e.g. reprints (peer-reviewed), theses/dissertations, etc.), which was very confusing for all of our PIs this year. 

Thanks in advance for your help, and please reach out to us with any questions. 

All the best,
Virginia Sea Grant
![screen shot 2017-08-01 at 2 31 51 pm](https://user-images.githubusercontent.com/17860369/28841112-22738306-76c7-11e7-8591-787faf94565d.png)

![screen shot 2017-08-01 at 2 30 32 pm](https://user-images.githubusercontent.com/17860369/28841109-1f9d0f44-76c7-11e7-8149-b0e6c087062a.png)

**Comment by ecsion** [comment]
Sam, We will add Publication Types for all VA SG & all other SeaGrants. Please post the hyperlink where we can get the list of Publication Types.

**Comment by ecsion** [comment]
If you like, you can easily add / edit publication list yourself. Go to Settings (Top Left) --> Picklist editor. Then Select **Publication** as the module and **Publication Type** as the Picklist. Then you can delete/add or update the Publication Types.

**Comment by SamuelJLake** [comment]
Thanks Deepak!

I had a great discussion with [Cynthia Murray, Director of the National Sea Grant Library](http://nsgl.gso.uri.edu/about/staff.html) this morning, and she would be happy to work with you and Kathy to help streamline any processes you might want to put in place in the future. For now, I have taken the approach that you included in the second comment and manually added the "publication types" they list on their database entry form to our Picklist. FYI without granting you access to the system there is not a good way to access the "publication types" they list (that are included in the screen shot), but Cynthia would be happy to confirm those for Ecsion if you would like to update all of the other programs Picklists. 

I am guessing that other programs did this earlier and maybe I just missed it, but that will definitely streamline the process for us next year. 

You can mark this thread as resolved, thanks!

Best,
Sam
