### ISSUE TITLE
CASG: Proposal Download - Project Summary Form 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#786]
Hi, 

In the past, the project summary form (90-2) used to include the objectives, methodology, and rationale, but it's not pulling it anymore. Can you please look into this?
Currently, a 90-2 form isn't downloading but I get a project summary. 

I've attached last year's and my current one as examples. 

Also, is there a way to download the additional personnel information as a separate file rather than just the proposal summary PDF? 

Thanks,

Miho 
[2018_Project_Summary_Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1195370/2018_Project_Summary_Form.pdf)
[2017_90-2Form.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1195371/2017_90-2Form.pdf)

**Comment by mumezawa** [comment]
I realized this is the same as the Current and Pending, so it's working.

However, the additional personnel is not downloading with all the information.
I've attached an example and the link is https://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=40279&mode=showMultiQuestionStem&QuestionId=14066&tab_label=Additional%20Personnel&tab_label=Additional%20Personnel

[Additional-Personnel.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1198065/Additional-Personnel.pdf)

**Comment by ecsion** [comment]
When you created a new firm, there were keys missing. We have added them now.Please check.

**Comment by ecsion** [comment]
We have also fixed the additional personnel issue. Please check.
