### ISSUE TITLE
CASG: Current and Pending Support Download 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#787]
Hi, 

The current and pending support files are not included in the downloadable zip folder for the 2018 Standard Core Awards - Full Proposal RFP. Can you please look into this? 

Here's what I could download last year. 
[2017_cpsupport.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1195408/2017_cpsupport.pdf)

Thanks,

Miho

**Comment by ecsion** [comment]
Hi Miho, There is a flag in the custom form that determines if a particular form should be downloaded or not. That was not checked. See Screenshot: 
<img width="804" alt="screen shot 2017-08-03 at 8 00 16 am" src="https://user-images.githubusercontent.com/1612666/28903398-43ad5388-7822-11e7-8ca7-f82b974afcc2.png">

We have now checked it and so C&P should now be included. Please check.

**Comment by mumezawa** [comment]
It’s working, thank you! 

Sorry about my elementary question. 

And thanks for the quick response. 

 

Regards,

 

Miho
