### ISSUE TITLE
RISG -- Peer Review Scores not Showing on Panel or PI outputs

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#788]
As shown in the 2 screen shots at bottom, and as shown at the following URL:  

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=3821&phaseid=3823&tab_label=Full-Proposals

Peer review scores for each category are not being either on screen or in output PDFs. Please correct this so that all peer scoring is properly showing. Thank you.

![screen shot 2017-08-03 at 6 50 10 am](https://user-images.githubusercontent.com/18398763/28918785-be20f4bc-7818-11e7-9cfe-2747ccf82304.png)

![screen shot 2017-08-03 at 6 53 36 am](https://user-images.githubusercontent.com/18398763/28918790-c20516f8-7818-11e7-91e1-13e67a4e6fad.png)

**Comment by ecsion** [comment]
Restored labels. Scores are now showing.

**Comment by alandesbonnet** [comment]
Thank you. Please close this issue in Github if not done already.

Alan Desbonnet
Assistant Director
