### ISSUE TITLE
RISG - Peer Score not showing for Scientific Merit

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#789]
As shown in the screen shot following, peer score for the first criteria :: Scientific Merit & Rationale, is not being shown. This is happening in both the PDF output and in the screen view generated for both Panel and PI (rebuttal phase) views. Please correct this error/omission.  Thank you.

![screen shot 2017-08-03 at 10 07 45 am](https://user-images.githubusercontent.com/18398763/28925826-fe8fe98e-7833-11e7-8aca-080b55ef00e7.png)

**Comment by ecsion** [comment]
ok we will fix.

**Comment by ecsion** [comment]
fixed.
