### ISSUE TITLE
MIT - Peer review tracking, a discrepancy

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#790]
For MIT's RFP FY2018: in the Full Proposals view (screenshot below, see panel 7, 'Manage Peer Reviews') it shows seven missing; however there is only one missing (see second screenshot of the 'Pending' view.)

![image](https://user-images.githubusercontent.com/17729848/29029141-a1008264-7b54-11e7-9240-910e810dca63.png)

![image](https://user-images.githubusercontent.com/17729848/29029263-16ca1366-7b55-11e7-8386-011963115848.png)

**Comment by ecsion** [comment]
fixed.
