### ISSUE TITLE
MIT - Peer review download changes in Excel - fields and layout

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#791]
Layout on the Excel download is too "fancy". Please

1. Remove blank columns and rows in all worksheets
2. Do not use fill color (so we can rearrange the list)
3. PI lname and PI fname should be separate fields/columns (so we can alphabetize the list)
4. Include the Reviewers affiliation, it's important
5. Include these fields, in this order on the Comments & Scores worksheet:

-  PI lname, PI fname, PI affiliation, PI Email, proposal title, Rev lname, Rev fname, Rev affiliation, Comments, Score, [Rating Comment]

The other worksheets are fine, just take out the blank rows/columns

**Comment by ecsion** [comment]
fixed. please check.
