### ISSUE TITLE
Rebuttal Save vs Submit

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#792]
When logged in as a PI in the rebuttal section of an RFP, when I click **save** it says "rebuttal **submitted** successfully" when it should just save it. 
http://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=17623&mode=showRebuttalForm&tab_label=Rebuttal
![capture](https://user-images.githubusercontent.com/17168500/29180393-8fa88d40-7dac-11e7-863f-1e8d3cfcbaf4.JPG)

**Comment by ecsion** [comment]
fixed.
