### ISSUE TITLE
RISG --- Rebuttal PDF not saving; Rebuttal comments not saving

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#793]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=10541&mode=showRebuttalForm&tab_label=Rebuttal&tab_label=Rebuttal

rebuttal document upload does not save, yet when I try to save it says it is saved and must be deleted, but there is nothing to delete. This must be corrected.

Secondly, the PI entered rebuttal comments and uploaded a PDF document, saved and submitted. No comments were saved and no attachment was saved. As ADMIN I cut-and-paste from Word and comments now saved, but all formatting is a mess. Since there is no panel to assist with cut-and-paste from Word (as there is for ADMIN), this is a mess and the rebuttal comments are nearly incomprehensible. 

At a minimum, please correct this so that the rebuttal PDF may be saved. Thank you. 

Rebuttal closes today, the 11th of August at 4:00 PM so this is critical/time sensitive.

**Comment by ecsion** [comment]
fixed, please check.
