### ISSUE TITLE
RISG -- Report Call Information Screen Scroll Bar Issue

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#795]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=CallReporting&view=Edit&record=11902

when the (Preview) link is accessed, the scroll bars disappear from the browser once the preview is closed. ADMIN then has to return back a screen and start over, losing any changes made because scrolling UP to SAVE is not allowed. This needs to be corrected. Thank you.

**Comment by ecsion** [comment]
fixed.
