### ISSUE TITLE
RISG --- Panelist Paste from Word not working

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#796]
At this URL:

https://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer_detail&guid=NzRBRTg1OEYtOEZDNi00MDExLTlBMkMtRjkyQ0Q3MjEyMjcw&exuti=MTE5MzI=&propid=MTA1NDE=&reviewer=MTE5NDA=&rid=SDE2LTIwOQ==

paste from Word is not working. It pastes into the popup window, but is not then inserted into the Reviewer Comment window. Please correct this so Panelist can cut-and-paste text. Thank you.

**Comment by ecsion** [comment]
fixed.
