### ISSUE TITLE
CASG: Peer Review 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#798]
Hi,

Can you please delete the score for reviewer #0 for Adina Paytan's proposal?
This was a test that I entered and later deleted. Even though it's not showing up in the peer reviewer list, the score and comments are still showing up. And it's impacting the average score. 
Reviewer #1 (June Oferdorfer) is a legitimate reviewer, so please keep her score and comments. 

Peer reviewer list: https://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=showPeer&record=40056&phaseid=40057&tab_label=Full-Proposals 

Peer review comments: https://eseagrant2.ucsd.edu/operations.php?action=printpanelpdf&rfpproposalid=40165&rfpid=40056&type=peerreview 

Thanks,

Miho

**Comment by ecsion** [comment]
Miho, We will have it fixed early next week.

**Comment by ecsion** [comment]
fixed.
