### ISSUE TITLE
OSG: remove peer test reviewers

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#802]
I managed to test my peer review invitations within an actual peer review. To clean things up, I'd like the four review invitations I have marked removed from the list, if possible. 
![2017-09-01_1454](https://user-images.githubusercontent.com/17169131/29989101-d9bfedf8-8f25-11e7-816a-ce895bc00879.png)

**Comment by ecsion** [comment]
Go to invite peer reviewers for proposal tab. Click on the proposal and you can delete test reviewers from the popup screen.
