### ISSUE TITLE
CASG: Downloading State Fellows Proposal List 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#803]
Hi, 

I can't seem to download a compiled excel of all the 2018 state fellow applications that we received.
Can you please help? I was able to do it for the core proposals...

Link to state fellows RFA: https://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=40477&tab_label=RFP%20Reports

This is what I get when I try to click on the "Proposal List":
![screen shot 2017-09-05 at 9 53 45 am](https://user-images.githubusercontent.com/17860279/30072774-3ad0c548-9220-11e7-8268-a713c41e9f1a.png)

I'd like this document ASAP. Thank you. 

Kind regards,

Miho

**Comment by ecsion** [comment]
fixed. Please check.
