### ISSUE TITLE
More than 2 year project - budget

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#805]
We will be setting up four year projects in the next few months. Currently, when you set up a project in eSG, you only have the option for two years in the when entering the funding (see screen capture). Can we add up to four years?
![capture](https://user-images.githubusercontent.com/17168500/30188772-22c380d2-93e5-11e7-869e-77650ecce697.JPG)

**Comment by ecsion** [comment]
Mary -- We have this on our to do list and expect to have this change completed in the next few weeks.

**Comment by ecsion** [comment]
done.
