### ISSUE TITLE
OSG- Accepted Peer Reviews not showing up for the PI!

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#808]
The PI is not seeing peer reviews, therefore they cannot move forward with rebuttals. The PI cannot see the Peer Review that I know is now in the system and is accepted. As the PI, for Peer Reviews it shows me “No records found”. 
As an admin I have no "Share with PI" option to allow me to share the accepted Peer Review with the PI. 
For the peer review form we used a custom form, if that helps. This is NOT a test RFP.

**As an ADMIN:**
![peer_review_mgt_form_osg_2018-21_omnibus_2017-09-18_1547](https://user-images.githubusercontent.com/17169131/30568364-9c64f392-9c89-11e7-89f9-0313c28a40a4.png)
**As the PI:**
![pi_peer_review_osg_2018-21_omnibus_2017-09-18](https://user-images.githubusercontent.com/17169131/30568405-e81a7082-9c89-11e7-8322-25e4c538d738.png)

Thanks!

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mcbridec** [comment]
Update: The PI can see that there is a review, but both of the hyperlinks to **View Reviewer Comments** and to **Download Reviewer Comments as PDF file** do not work.
![mcbride_rebuttal_issue_update](https://user-images.githubusercontent.com/17169131/30758360-f24e8728-9f86-11e7-82ca-666489858cbb.png)
A popup appears after clicking on the **View Reviewer Comments** hyperlink.
![arebuttal_2017-09-19_1757](https://user-images.githubusercontent.com/17169131/30758405-1cfcfaea-9f87-11e7-87d9-a5d3a542c75a.png)
Nothing changes if the PI clicks on the **Download Reviewer Comments as PDF file** hyperlink.

**Comment by mcbridec** [comment]
Update: The PI Can now see that there is an accepted peer review, but the hyperlink to see the review comments is broken.
![osgmcbride_rebuttal_issue_for_pi_update](https://user-images.githubusercontent.com/17169131/30758677-388bf0bc-9f88-11e7-8331-38657e120223.png)
Choosing this hyperlink creates a popup. 
![arebuttal_2017-09-19_1757](https://user-images.githubusercontent.com/17169131/30758700-44e2fcfc-9f88-11e7-92ee-dbe5a94ba1e8.png)

**Comment by ecsion** [comment]
we are looking into this issue.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mcbridec** [comment]
Yes! Works just fine now. Thank you so much!
