### ISSUE TITLE
Picklist Editor for People -- eSG Role History not working?

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#809]
Hi there,

I tried to add options to the eSG Role History Picklist (including the options of Intend to submit application, application submitted, research students, indent to submit proposal, and proposal submitted), but these don't show up as options when I add or edit a person to the People list.

http://eseagrant.oregonstate.edu/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9
![capture1](https://user-images.githubusercontent.com/17168500/30568659-441057fc-9c8b-11e7-8770-e7419971a3bd.JPG)
![capture2](https://user-images.githubusercontent.com/17168500/30568662-484980b4-9c8b-11e7-889b-62a2c41a5d03.JPG)
![capture](https://user-images.githubusercontent.com/17168500/30568663-4a85dbca-9c8b-11e7-8ea3-dfd59afec015.JPG)

**Comment by mra142** [comment]
You need to click the blue tab 'values assigned to a role" in image 2 and
add the role there too... Found that out recently.

-- Sent from mobile

**Comment by marypleasant** [comment]
Thanks, Mike. I believe I already did that, and it still isn’t working? See image #2 in the Github issue.

Respectfully,

Mary Pleasant
Research and Scholars Coordinator
Email: mary.pleasant@oregonstate.edu<mailto:mary.pleasant@oregonstate.edu>|Phone: 541.737.0661

**Comment by ecsion** [comment]
Hi Mary, We will look into this and get back to you.

**Comment by marypleasant** [comment]
Hi there,

I am just checking in on the status of this issue. Thanks.

**Comment by mcbridec** [comment]
I do not think this has been resolved, but I'm not sure because it's tricky to figure out how to work with the User Roles and eSeaGrant Role History in eSeaGrant. Instead, can ORSG have a short tutorial on how the Picklist editor works for the PEOPLE section of eSeaGrant, including how the User Roles and eSeaGrant Role History work when setting up people accounts. I don't want to take up much of your time, though.

**Comment by mcbridec** [comment]
This seems to be working fine now - thank you so much!

**Comment by mcbridec** [comment]
Can you close this for us? Mary Pleasant is no longer on this project.
