### ISSUE TITLE
custom phase - import proposals

### ISSUE THREAD

**Issue by kalitle** [ecsion/eSeaGrant-Client-Bug-Tracker#810]
When you import proposals in a custom phase - you currently get a strange warning message that asks if you really want to "merge" this proposal.  Not sure what "merge" is supposed to mean in this context, but it makes me nervous.  I thought this function was supposed to be "copying" proposals?

Cannot include screenshot as it would include confidential information, but will email to Deepak.

Thanks
Kate

**Comment by ecsion** [comment]
done.
