### ISSUE TITLE
RISG -- PI cannot see reviewer comments

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#812]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=rebuttalsSetup&record=10577&phaseid=10578&tab_label=Full-Proposal

The VIEW to review comments does not show comments. Furthermore, when user = PI, reviewer comments are not visible in the Rebuttal tab output. This must be corrected so that PIs can respond to reviewer comments in a rebuttal. Thank you.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
It is working fine. Thank you.

Alan Desbonnet
Assistant Director
