### ISSUE TITLE
MIT - Clean up Panel Review download in RFP Reports

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#813]
In RFP Reports > Panel Review downloads:  Remove empty entries (no comments, no scores) and include the Proposal Title and PI in each entry, like this, changes in red:

PI:
Proposal Title : 
Reviewer: 
Panelist Role: 
Overall Weighted Rating:
Comments :

Also in RFP > Full-Proposal > Select Panel Reviewers & Start Panel Review change the header of the seventh column to “Downloaded”. (“In Progess” is okay if the panelist is actually commenting on that proposal -- mostly they aren’t.)
![image](https://user-images.githubusercontent.com/17729848/30760433-271cedc0-9fa8-11e7-8a3a-976833f4a4e2.png)

**Comment by ecsion** [comment]
done, please check.

**Comment by kdez** [comment]
I checked and it looks very nice. 

I would prefer that the "Rating Comments:" section header not appear if the Admin has not selected that feature in Setup. (Few programs use rating comments, in any case.)
