### ISSUE TITLE
RISG -- Error in 90-4 Budget form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#815]
At this URL

https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=OTcyMg==&id=229

You see that the PI is listed on 2 budget lines, each with different values. On the screen shot below, you see that on the 90-4 output PDF that the PI budget lines are printed twice, in error. **All calculations ARE CORRECT, so it is not a math problem**, but rather that the PI budget values are printing in the Associate/co-PI line, and should not be. Please correct this as it is very confusing. Thank you.

![0-4](https://user-images.githubusercontent.com/18398763/31029810-15e185c4-a521-11e7-92f4-8dc9465c7785.png)

**Comment by alandesbonnet** [comment]
SEE Image contained here for better definition of the problem that needs to be corrected

![90-4form_error](https://user-images.githubusercontent.com/18398763/31082315-97dc4ff4-a75c-11e7-9517-ebb2b86ad175.jpg)

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
Thank you. It appears to now be calculating correctly.
Alan

Alan Desbonnet
Assistant Director
