### ISSUE TITLE
CASG: Unable to Create New Projects 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#816]
Hi,

I get the below error message every time I try to create a new project:

![screen shot 2017-10-04 at 12 36 49 pm](https://user-images.githubusercontent.com/17860279/31196034-1df6f60c-a901-11e7-8ee3-eed183e24825.png)

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.
