### ISSUE TITLE
RISG -- "copy" budget worksheet error

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#817]
At this URL:
https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTIzMTQ=&id=257
when I "copy" a budget worksheet, 3 lines of budget values (for Vancouver, BC) show up under Travel (see screenshot), 
 
![screen shot 2017-10-05 at 6 28 04 pm](https://user-images.githubusercontent.com/18398763/31255579-92b51fc8-a9fb-11e7-80ab-5d9f17a47324.png)

that were not in the worksheet copied. This happens every time I use the "copy" budget worksheet command. While not a critical issue, it would be nice if this could be corrected. Thank you.

**Comment by ecsion** [comment]
Alan, this was because the template we were using for making a new copy had some extraneous rows in it. I believe this is fixed. Please check.
