### ISSUE TITLE
RISG -- 90-4 forms coming up blank  CRITICAL

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#819]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13099&mode=showBudget_90_4&tab_label=Budget%2090-4&duration=384

90-4 forms for individual years are coming up BLANK......do values are moved from the worksheets onto the PDF output. This must be corrected. Thank you.

**Comment by ecsion** [comment]
Hi Alan, The reason the 90-4 is coming blank is that when you import sheets from a mother RFP, they no longer have proper selection on the budget periods that were defined on this RFP. This makes them not be included. If you go into the budget sheets and reselect budget periods on proposals imported from another RFP, it will work just fine. Please check.
