### ISSUE TITLE
Automated Email Confusion

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#82]
We are trying to understand what emails the system sends, as well as when, to whom and from whom. Initially, a list from you might help explain this if you can answer all these questions. But meanwhile, some elaboration:

To illustrate, Kate got an email from a Investigator email (Christine Stawitz) for a report she just submitted. The "From" email was Christine's eddress, but the message was also addressed **to** her, and logic of this is confusing to us. Further, we assume she did get a copy of the same message, but we don't know for certain.

Another area of confusion regards the issue we had with the situation where "looking" at an old project (migrated record) turned the investigator into a user, which caused us concern because we thought those users were then getting new "Welcome" emails. (Further, we don't even know what the "make user" trigger is: Is it looking at their profile? One of their projects?)

Regardless, you said the investigators **weren't** getting welcome messages when activated as users—great! But then we don't understand how to initiate a welcome email to an investigator if making them a "user" doesn't do this. 

BTW, just to be sure (since there's not another ticket on this), we do NOT want investigators to become users just by our looking at their records.

**Comment by mcbridec** [comment]
Oregon also has the same issue as in the second paragraph above. 
As the RC originator of the Reporting Call below, my RC email address received an email from an investigator's email when the PI submitted a report:
From: pleasanm@oregonstate.edu (the PI)

To: cathy.mcbride@oregonstate.edu (the RC)

"Hello Mary Pleasant,
A task has been completed.

Task Type            Project Report Due
Task Title             Test: 2016-18 Omnibus Research Annual Report Call
Projects                Project : 123456
Assigned By         Catherine McBride
Assigned To        Mary Pleasant
Due Date             2016-04-30 00:00:00
Expiry Date         
Task Status          Submitted

Thank you,
Oregon Sea Grant
eSeaGrant Coordinator
Corvallis OR 97333
541-737-2714"

Mary (the PI) did not receive this email.
Looks like the email template is using the incorrect email targets. 
For Oregon Sea Grant, we wish it to be changed this way:

The To: should go to the PI email and also to eSeaGrant@oregonstate.edu
The From: should be eSeaGrant@oregonstate.edu
No salutation, replace “Hello Mary Pleasant,
A task has been completed” with “Your Report has been submitted:” 

The rest of the email remains the same.
