### ISSUE TITLE
VASG - Document Request Submission Deadline Issue

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#822]
We currently have a Fellowship RFP open, and heard from a referee this morning that they were unable to submit their letter because the student selected a "due date" before the actual RFP deadline. Per earlier requests (earlier this spring), we were under the impression that no one would be locked out of the system and unable to submit letters before the deadline - but it appears that this is no longer the case. We request that no referees be locked out before the actual RFP deadline. Can this be changed and saved ASAP? The deadline is later this week, Nov 16 at 5:00pm.  

Please see the first two request on this page:

https://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=12210&mode=showMultiQuestionStem&QuestionId=531&tab_label=GRF%20-%20Invite%20Letter%20Writers

**Comment by ecsion** [comment]
Sam, We will take care of this in tomorrows release.

**Comment by SamuelJLake** [comment]
Thank you!

Samuel J. Lake, Ph.D.
Fellowship & Research Program Coordinator
Virginia Sea Grant
Work: (804) 684-7436
Email: sjlake@vims.edu<mailto:sjlake@vims.edu>



On Nov 13, 2017, at 12:01 PM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:


Sam, We will take care of this in tomorrows release.

-

**Comment by ecsion** [comment]
fixed, please check.
