### ISSUE TITLE
Issue Uploading Multiple PDFs to Single RFP Form

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#823]
Hello,

Last night a student informed me that they were having issues submitting multiple PDFs onto a single eSeaGrant online [RFP form](https://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=12405&mode=showMultiQuestionStem&QuestionId=535&tab_label=GRF%20-%20Resumes/CVs&tab_label=GRF%20-%20Resumes/CVs). 

After working with them last night and this morning we determined that once she clicked the "Select File" button, selected the PDF file on her Desktop, and hit "Open" and then "Save" the system would artificially add non-existent files to the subsequent sections (i.e., 
Upload Advisor's Resume/CV, Upload Co-Advisor's Resume/CV (if applicable), and Upload Professional Outreach Mentor's Resume/CV). We were able to fix the problem by clicking the "x" next to those subtitles to delete the non-existent PDF files (in fact, eSG told us there were no associate file). We could also reset the form by clicking the trash can icon to clear it. 

I'm not sure how big of a problem this is - she tried it on her computer using Safari and Chrome and ran into the same problem. I was able to replicate it on my test proposal using Firefox ([link](https://vaseagrant.ecsion.com/index.php?module=RFPProposal&view=Detail&record=12161&mode=showMultiQuestionStem&QuestionId=535&tab_label=GRF%20-%20Resumes/CVs&tab_label=GRF%20-%20Resumes/CVs))  after uploading a single PDF, then leaving the page and  going back shortly afterwards. If you stay on the page and immediately upload the remaining CVs it does not appear to happen. Is there a quick/easy fix for this problem?

Thanks in advance for your help!

Best,
Sam

**Comment by ecsion** [comment]
fixed, please check.
