### ISSUE TITLE
NCSG - Change in year date not allowing us to email people

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#824]
It seems when we have a due date for a proposal that is in 2018, if we try to email someone for letters of recommendation for a due date that is in 2017, we receive this error.  

![image](https://user-images.githubusercontent.com/21174930/32801366-d5e0d616-c94a-11e7-821a-3980895861e1.png)
Here is the link:  http://eseagrant.ncseagrant.ncsu.edu/index.php?module=RFPProposal&view=Detail&record=26425&mode=showTasksData&&tab_label=NMFS%20Fellowship%20-%20NMFS%20Mentor%20-%20Signed%20Letter%20of%20Commitment&questionid=13096

**Comment by mebarrow** [comment]
The due date of the submission is 1/26/2018 and he was trying to make the due date for the letter 12/31/2017.  If we make the due date in 2018, it is fine.

**Comment by ecsion** [comment]
fixed, please check
