### ISSUE TITLE
RISG -- Create New Rating Form ERROR

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#825]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=ReviewRating&view=Edit

the following message appears (see screen shot below)

![screen shot 2017-11-21 at 10 03 50 am](https://user-images.githubusercontent.com/18398763/33079329-56abe9cc-cea3-11e7-9be3-52d5e2e79b38.png)

Even as a NEW rating form is created, eSeaGrant says there is already 1 person having used the form (which is impossible since it has not yet been created and saved) and so no changes can be made to the form. This needs to be corrected so that new ratings forms can be created. Thank you.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
Thank You!! It is indeed fixed

Alan Desbonnet
Assistant Director
