### ISSUE TITLE
RISG -- No option to Delete instructions attachment file

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#827]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=uploadPhaseInstruction&record=13528&phaseid=13529&tab_label=Fellowship%20Application

There is no option to be able to delete an instructions file once uploaded. There should be the option to delete the file if it is decided that no instruction PDF is needed. Please add the option to delete instructions PDF uploads. Thank you.

**Comment by ecsion** [comment]
done.
