### ISSUE TITLE
RISG -- Error in Budget Worksheet/Budget Justification

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#829]
at this URL:

https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTA1ODY=&id=233#

You will see under the budget worksheet line for E. Travel, that there is no travel costs listed, and there is no budget justification as shown by the lack of the "green dot" in the Justifications column.

However, if you click "view" under Justifications you will see there is text, which then prints in the Budget Justification pages of the 90-4 PDF output, creating an error in the budgets (the justification  describes travel that is not budgeted for).

This must be corrected. Thank you.

**Comment by alandesbonnet** [comment]
The same occurs at this URL:

https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTIzMTQ=&id=257

suggesting this is a system-wide error with eSeaGrant NOT permanently removing budget justification text when deleted/removed. This needs to be corrected. Thanks.

**Comment by ecsion** [comment]
fixed, please check

**Comment by alandesbonnet** [comment]
It appears to be working as expected. I have Closed the Issue in GitHub
Thank you.

Alan Desbonnet
Assistant Director
