### ISSUE TITLE
Issue with time stamp on Document Request Form

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#832]
Good evening,

A reference letter writer noted this evening that when they submitted their recommendation letter that the timestamp on the eSG document request form was incorrect - exactly 12 hours early. Please see the attached screenshot where I was able to reproduce the error - submitted a document at 11:16 PM, but the highlighted area on the form list 11:16 AM. If you have any questions please feel free to contact me. 

Best,
Sam

<img width="1060" alt="screen shot 2017-12-04 at 11 19 04 pm" src="https://user-images.githubusercontent.com/17860369/33589934-e1398c06-d949-11e7-90fe-91928a609239.png">

https://vaseagrant.ecsion.com/operations.php?action=responseform&guid=5F8AEAD1-46E7-4D64-933E-B037EF8A74CA

**Comment by ecsion** [comment]
fixed.
