### ISSUE TITLE
Emails not getting to recipients 

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#833]
Hi there,

I am having more problems with emails from eSeaGrant. I sent an email to a group of recipients on November 21st using a custom email template. Some of the intended recipients received the email and some did not (I had them check their junk mail). These recipients were at the same institution. I also tried to cc: eseagrant@oregonstate.edu, but never received the email copy in my inbox or junk mail (perhaps I entered in the email address incorrectly?) I can forward you one of the emails that actually went through to a recipient if that helps to solve the issue.

Thanks for your help.

**Comment by ecsion** [comment]
Hi Mary, Could you please provide us the the project title & PI name of the intended recipient.
As an fyi, we log sent emails and we have record of 9 emails sent successfully.  

Thanks

**Comment by ecsion** [comment]
Issue fixed by switching to Oregon State SMTP server.
