### ISSUE TITLE
RISG -- Import Data link should not be visible

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#835]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13786&mode=showMultiQuestionStem&QuestionId=6317&tab_label=Tk1GUy9TRyBGZWxsb3dzaGlwIDEuIFRpdGxlIFBhZ2U=&tab_label=Tk1GUy9TRyBGZWxsb3dzaGlwIDEuIFRpdGxlIFBhZ2U=

and in other customs forms as well, the IMPORT DATA option shows in the form, but should not be visible since the option to import data from previous RFPs is set to OFF. Please have this so that then the option is set to OFF, the Import Data text/link, is NOT visible as it is confusing to the user. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
