### ISSUE TITLE
History User does not go to current user

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#837]
When I try to assign someone as a user "Principle Investigator" it puts it under historical data and will not allow me to put a current use role in.  This has been happening, but it has become worse today because since I cannot make someone a PI, they cannot see what I want them to see as an invite only.  Please see links below.

https://www.laseagrantdb.org/index.php?module=People&view=Edit&record=9721

https://www.laseagrantdb.org/index.php?module=People&view=Detail&record=9721

**Comment by ecsion** [comment]
Here's how you can change the role of a person.

Step 1: Go to People List.
Step 2: Select the person who you want to change the role and go to the detail screen of that person.
Step 3: Click the Actions Menu
Step 4a: If the selected person has been given login access, the actions menu will show a option to "Change Role"
Step 4b: If the selected person does not have login access, the actions menu will show a option to make the selected person a login user "Make User" In the "Make User" flow, you will be able to select a role for that person. Later if you wish to change the role, you may use 4a.
