### ISSUE TITLE
Report Call Template Tab Order

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#839]
When you save a report call as a template, the tab sequence order does not save. Screen shots below show the tab order from the original report call "2016-18 Progress Report Call (NCE)" and the Template of this report call. 
![original](https://user-images.githubusercontent.com/17168500/34220368-42f7d828-e569-11e7-9677-f3cba35b2c80.JPG)
![template](https://user-images.githubusercontent.com/17168500/34220369-44371b36-e569-11e7-9b12-d4af4537c3f8.JPG)

**Comment by ecsion** [comment]
fixed
