### ISSUE TITLE
RISG -- Custom Form Not Working Correctly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#840]
At this URL:  
https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=5972&showList=

the custom form shows that the PI/USER should have access to input information to Question #1, while Question #2 (upload PDF) is available ONLY to ADMIN. Yet when the PI/USER logs in to their account, the Question/Custom Form does not show in their left hand list of options when creating their application/proposal. A similar Custom Form, at this URL:
https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Detail&record=5973&viewname=&showList=&show_retire=

is designed the same way, and again is not visible to the PI/USER, and should be. Please correct this, or inform me how to properly configure the Custom Form, so that the PI and see and input their data, and ADMIN can upload the file, with the PI/USER not having access to upload. Thank you.

**Comment by ecsion** [comment]
the show to pi flag was not set. once set, it works.

**Comment by alandesbonnet** [comment]
My apologies, I should have looked there. I will close this issue.

Alan Desbonnet
Assistant Director
