### ISSUE TITLE
RISG -- ADMIN uploaded files not showing to USER

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#841]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=6320&showList=

you can see a file uploaded by ADMIN which should then be available to the USER when logged in and accessing that Custom Form.

However, at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13786&mode=showMultiQuestionStem&QuestionId=6320&tab_label=Tk1GUy9TRyBGZWxsb3dzaGlwIDIuIFByb2plY3QgU3VtbWFyeQ==&tab_label=Tk1GUy9TRyBGZWxsb3dzaGlwIDIuIFByb2plY3QgU3VtbWFyeQ==

you will see that the file uploaded by ADMIN is not available to the USER.

This needs to be corrected because PIs developing proposals are not able to access files that are required for their application/proposal. This needs immediate resolution. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Added files uploaded to custom form in proposal. 
Please check.

![image](https://user-images.githubusercontent.com/17423049/50091491-8df7ef80-0231-11e9-8b2c-b640046b7bf9.png)
