### ISSUE TITLE
OSG: Custom Form Answer Summary Report columns are offset by one column

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#848]
When I exported a Custom Form Answer Summary Report, I discovered that some of the columns are offset by one column. The answers for either column "L" or column "M" are missing. I cannot determine which one because the answers to both questions (the column headings) are yes/no answers.  These happen to be critical columns for reporting.
Anyway, because of the missing column/answers, the remaining columns are now all shifted to the left to fill the missing column. 
Can you fix?

![2018-01-19_1045](https://user-images.githubusercontent.com/17169131/35166591-3d0084d2-fd07-11e7-9454-490acf2b4940.png)

**Comment by mcbridec** [comment]
With further study, I believe the answers to column "M" are what is missing. Therefore every answer in columns N-T are shifted to the left.

**Comment by ecsion** [comment]
Looking into this.

**Comment by mcbridec** [comment]
Both issues are fixed for those custom forms. Thank you very much!
