### ISSUE TITLE
Annual Reporting Instructions Not Transfering to Individual Reports

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#849]
Good morning,

We had a PI reach out to us this weekend to ask why the instructions for the "Narrative" was not included in the Instructions section of their annual report. When I logged on this morning I could see the text we included under the Report Call Instructions section (https://vaseagrant.ecsion.com/index.php?module=Instructions&view=List&tab_label=Instructions). However, when I went into the report that they had started for their project the text was not listed (see screen shot; https://vaseagrant.ecsion.com/index.php?module=Reporting&view=Detail&record=14845&mode=showInstructions&tab_label=SW5zdHJ1Y3Rpb25z&tab_label=SW5zdHJ1Y3Rpb25z)

Please let us know why this text is not transferring over to the individual reports. 

<img width="918" alt="screen shot 2018-01-29 at 8 49 15 am" src="https://user-images.githubusercontent.com/17860369/35513821-49875640-04d2-11e8-8e4e-b0576ec91004.png">

All the best,
Sam

**Comment by ecsion** [comment]
Looking into this issue.

**Comment by ecsion** [comment]
This is fixed in V2.0. We will coordinate with you to update your instance to V2.0
