### ISSUE TITLE
VASG - Issues Trying to Use RFP Custom Phase

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#854]
Hi Deepak et al.,

I am trying to use the custom phase option in the RFP section of eSG but seem to be running into a few issues. While I was able to create another review phase, I wanted to be able to paste in PDFs for the reviewers without needing to have additional proposals submitted for this phase (essentially jumping straight to step 7 - is that possible? It would likely be easier to explain what I am trying to do over the phone, but I have included the link below. 

https://vaseagrant.ecsion.com/index.php?module=RFP&view=Detail&mode=showPhase&record=12094&phaseid=15244&tab_label=Final%20Panel%20Summaries

I look forward to chatting with you soon. 

Best,
Sam

**Comment by ecsion** [comment]
fixed in V2.0
