### ISSUE TITLE
RISG: Change PI action not working

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#857]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13802&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

When I select the "Change PI" option in the ACTIONS tab, (e.g., select Dennis Nixon as PI) the PI is NOT changed upon clicking the Update button on either the action or on the Start Here screen. This must be corrected as the PI must be changed for this fellowship application.

I tried the above Change PI action with the RFP both in the Closed and Open phases, and it did not work in either. thank you for fixing this.

**Comment by ecsion** [comment]
fixed, closing. Please reopen if you encounter this issue again.
