### ISSUE TITLE
RISG -- Change PI still not working

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#858]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13802&mode=showProposalTitle&tab_label=Start%20Here&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

change PI function is still not working. I need to get these applications processed for submittal, and I need to change the PI to do so. Thank you for addressing this issue.

**Comment by ecsion** [comment]
This was fixed a while ago. Closing. If this is still an issue, please reopen.
