### ISSUE TITLE
MDSG: Custom form export

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#861]
We are trying to export our custom form responses for partners this period by project (Custom form responses>Filter by project>Select "Partners this period">Export). What I am getting is missing key partner information. All that's being exported is an ID number of some sort. This ID number I'm presuming is a database locator, but what we really need is the export of the partner information (probably a connection to the look up table).  The same thing happens for the "Students Supported" export function. 

We need both of these export functions to do our reporting quickly and efficiently.

Thanks,

Mike

Custom Form Answer Summary Report |   |  

Partners   this period |   |  

Reporting Call | PI Name | Project Number | Partners This Period

2018 Annual Extension | Robert Tjaden | A/AQ-4 | 3561
2018 Annual Extension | Robert Tjaden | A/AQ-4 | 3574
2018 Annual Extension | Robert Tjaden | A/AQ-4 | 3273
2018 Annual Extension | Robert Tjaden | A/AQ-4 | 3584

**Comment by ecsion** [comment]
This is another artifact of the standard form to custom form refactoring. Working to fix this issue. We will try to have this working for you this week.

**Comment by ecsion** [comment]
This has been fixed, please check.

**Comment by mra142** [comment]
This export functionality is fixed in the two 'by project' xls export tables.
Thanks
