### ISSUE TITLE
MDSG: Partners not populating report list

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#862]
We've had a new report submitted and cannot figure out why the partners associated with this project are not showing up in the "Partners this Period" list (what are the date parameters that determine "this period") AND if I create a custom responses form report for all partners with no conditions on it, the project's partners do not show up in this list.

Custom form response: https://eseagrant.mdsg.umd.edu/index.php?module=PartnerReport&view=List&viewname=262&tab_label=Partners%20for%20a%20project
![image](https://user-images.githubusercontent.com/31412413/37972424-530daa74-31a6-11e8-9394-ee59e82685a6.png)

Project report A/AQ-4: https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=3069&mode=showInstructions&tab_label=SW5zdHJ1Y3Rpb25z

**Comment by ecsion** [comment]
We have switched Partners This period stand form to custom form and this has caused the issue you are experiencing. We are working to fix this.

**Comment by ecsion** [comment]
Mike, We are closing this issue. If this is still happening, then please reopen.
