### ISSUE TITLE
RISG--Uploaded Documents Won't Save

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#865]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=14838&mode=showMultiQuestionStem&QuestionId=7893&tab_label=UmVxdWlyZWQgTk9BQS9TZWEgR3JhbnQgRm9ybXM=&tab_label=UmVxdWlyZWQgTk9BQS9TZWEgR3JhbnQgRm9ybXM=

Select File and/or Save commands do not work; a PDF document can be selected and then uploaded, but will not Save and/or does not properly upload so it can be saved. This must be corrected so that file proposal files can be uploaded. Thank you.

**Comment by ecsion** [comment]
@alandesbonnet We are able to save. I will call you later in the day to figure out how to reproduce this issue.

**Comment by ecsion** [comment]
@alandesbonnet Are you still having this issue, if not, let's close it for now and we can reopen if you encounter the same issue again.
