### ISSUE TITLE
Criteria peer review comments not downloading

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#867]
As a panelist, after peer reviews have been accepted and shared, when you click "Download Peer Reviews & PI Rebuttals," the comments under each criteria (AKA the rating comment box) are not available in the download. Only the overall reviewer comments are downloaded. See screen capture below for a visual explanation. The panelists comments under each criteria and overall comments do download correctly. 

![capture](https://user-images.githubusercontent.com/17168500/38509765-b43c7056-3bd7-11e8-8c4f-d04241d706b9.JPG)

**Comment by ecsion** [comment]
Mary, Can you please add a link where you are downloading the comments. Thanks.

**Comment by marypleasant** [comment]
As a panelist, when peer reviews are shared, you can download them on the link below under "Download Peer Reviews and PI Rebuttals." Note that for this particular RFP and review, I did a workaround (copied and pasted comments from the criteria box to the overall comment box).

http://eseagrant.oregonstate.edu/operations.php?action=panel_reviewer_detail&guid=NEQyOTE1NTItREI5My00RjEyLUE1QkQtMzk2Q0REQzEwRUJG&exuti=Mjc1Mzc=&propid=MjExNDg=&reviewer=Mjc1Mzg=&rid=SDE2LTIxMQ==

Respectfully,

Mary Pleasant
Research and Scholars Coordinator
Email: mary.pleasant@oregonstate.edu<mailto:mary.pleasant@oregonstate.edu>|Phone: 541.737.0661

**Comment by marypleasant** [comment]
Yes, I sent it by email, since the link provides access to a live competition.

**Comment by ecsion** [comment]
Mary, Closing this issue. If this is still happening, then please reopen this issue.

**Comment by marypleasant** [comment]
Please reopen this issue. The issue has not been resolved. Thanks.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
