### ISSUE TITLE
eSeaGrant Role History

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#868]
When I add a person to eSG (http://eseagrant.oregonstate.edu/index.php?module=People&view=Edit), my only option under eSeaGrant Role History is "SG Administrators."

However, under the picklist editor, I have added more options than this: http://eseagrant.oregonstate.edu/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9

![capture1](https://user-images.githubusercontent.com/17168500/38509945-450ec5ca-3bd8-11e8-988d-b548985fea05.JPG)
![capture](https://user-images.githubusercontent.com/17168500/38509950-499d3acc-3bd8-11e8-8da6-6a93cce6b957.JPG)

**Comment by ecsion** [comment]
fixed.
