### ISSUE TITLE
ORSG- sort and search functionality lost for another column 

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#869]
In People> All people the column named "eSeaGrant Role History" will sort, but the search feature is not working. Apologies for the spelling errors.
![2018-04-09_1332](https://user-images.githubusercontent.com/17169131/38522987-1400bf52-3bff-11e8-803f-46035ba35440.png)

**Comment by ecsion** [comment]
fixed.
