### ISSUE TITLE
RISG:  Document title mismatch

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#870]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=14295&mode=showMultiQuestionStem&QuestionId=16079&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBDdXJyaWN1bHVtIFZpdGFlIC8gUmVzdW1l&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBDdXJyaWN1bHVtIFZpdGFlIC8gUmVzdW1l

the file name for the CV of the applicant does not match the PDF title when downloaded and opened (see screen shot below).

![screen shot 2018-04-17 at 10 40 35 am](https://user-images.githubusercontent.com/18398763/38877150-0d1b5700-422c-11e8-9568-9a74fc7fcd8f.png)

The correct document opens, but the file name is incorrect, which is very confusing and needs to be fixed. Thank you.

**Comment by ecsion** [comment]
Hi Alan, This is happening because the author has put "Adam Lee Erickson" as the title & adobe automatically display the title. Not a eSeaGrant issue and so closing it.
