### ISSUE TITLE
MDSG: Criteria based rating form not adding correctly

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#872]
We've created a criteria-based rating form for a fellowship we are reviewing. Criteria #2 is not adding in to the total sum for the overall rating. As a result, the highest score one can receive is 4.25/5.

Rating form:
https://eseagrant.mdsg.umd.edu/index.php?module=ReviewRating&view=Detail&record=5492

Peer review example: https://eseagrant.mdsg.umd.edu/operations.php?action=peerresponseform&guid=DBAC3D35-F642-44EE-B996-B0FBB3345DC7

**Comment by Dipali-Ecsion** [comment]
Done. Please check.
