### ISSUE TITLE
ORSG: PDF report files cuts off text, output could be improved

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#875]
![screen shot 2018-05-14 at 11 02 58 am](https://user-images.githubusercontent.com/18152637/40014933-c3030d98-5766-11e8-80f7-dd07a3ef7393.png)
![screen shot 2018-05-14 at 11 03 34 am](https://user-images.githubusercontent.com/18152637/40014939-c5f9ddf6-5766-11e8-8960-9a3ef639c541.png)

Two screen shots from a report - one is the report in eSG where you push a button to download as PDF, and the other file is the downloaded PDF. Text is cut off on the right hand side of the downloaded PDF. The first issue is to fix downloads so text is not cut off. The next issue (which might address the problem) is to change the output of these reports so that text boxes are the full page and not just half a page. Presently, the report prompt is on the left hand side and takes up a lot of room (see screen shot of downloaded PDF), so the text box responses are squished into the right hand side of the page.

**Comment by mra142** [comment]
MDSG has a similar issue with text being cut off at the bottom of pages
when boxes span multiple pages. Would LOVE to see these text boxes span the
page horizontally!

-- Sent from mobile

**Comment by ecsion** [comment]
@SEK-OSG We are working on this.

**Comment by SEK-OSG** [comment]
Great! Thank you!!
