### ISSUE TITLE
ORSG: feedback on forms management beta

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#876]
We are right in the middle of reporting so this is a good exercise for me. I wish I could use Forms Managment now. Unfortunately, in my testing of the new custom view feature for Forms Management in eSeaGrant, I find that all of my exported files are garbled with html, and have no spreadsheet format. Attached is an export for one of my two test reports.

[CustomFormExport_E7561A47-B683-428D-97C1-030F2762517D.txt](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2040865/CustomFormExport_E7561A47-B683-428D-97C1-030F2762517D.txt)

**Comment by ecsion** [comment]
Hi Cathy, Could you please provide the url link of the page you exported this report, We will troubleshoot and fix this issue.

**Comment by mcbridec** [comment]
http://eseagrant.oregonstate.edu/index.php?module=MultipartQuestionStem&view=List&showList=ReportUsed&viewname=214&tab_label=Reporting%20In%20Used%20Forms
I am not sure I am using the Forms feature correctly. I attempted to get a report of economic benefits from completed or used forms.

![2018-05-25_1726](https://user-images.githubusercontent.com/17169131/40570549-dbc0a902-6040-11e8-9a37-323595e4726e.png)

**Comment by ecsion** [comment]
The sport you re doing is for Forms metadata (as opposed to form data that user is entering). We have provided this feature so you can share the forms from 1 institution to another institution. This form export is not for the data.
