### ISSUE TITLE
RISG -- Data in Proposal NOT Saving

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#877]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=100185&mode=showMultiQuestionStem&QuestionId=16073&tab_label=UkVRVUlSRUQgMTgtMjAgUkZQIEZPUk1T&tab_label=UkVRVUlSRUQgMTgtMjAgUkZQIEZPUk1T

documents uploaded into the Required Forms tab are not being saved. They show as being attached (see screenshot)

![1](https://user-images.githubusercontent.com/18398763/41116293-e3adeb0e-6a57-11e8-950d-b11aacdee079.png)

but upon minimizing the the question/form, an error is returned. See screen shot.

![2](https://user-images.githubusercontent.com/18398763/41116331-00443a2a-6a58-11e8-98d7-89ce278f02c1.png)

At the same URL, data entered into the Data Management Plan tab doesn't save.

Please problem solve these various issues. Thank you.

**Comment by ecsion** [comment]
Alan, We will research and get this issue resolved asap and let you know once done.

**Comment by alandesbonnet** [comment]
Thank you. It is not critical as a worked around it, but the issue should be resolved.

**Comment by ecsion** [comment]
Currently there are 2 steps to upload a file. 
Step1: Select the file
Step2: Click on save button, this uploads the file to server.

We will change instructions to avoid confusion.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
We have added a warning message on file upload to let user know how to save file data.
![Uploading image.png…]()
