### ISSUE TITLE
MDSG: Duplication of forms within Report

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#879]
We've observed a strange duplication for the forms in a report output. The student only has the one set of forms, but two sets appear on the report output (and in the instructions). Can this duplication be rectified?

https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=4776&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by alandesbonnet** [comment]
Yes, please correct this.  I have noted this as well previously and the issues has not yet been rectified.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=4776&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=UmVwb3J0IFN1bW1hcnk=

Also resolved this issue on Instructions page.
https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=4776&mode=showInstructions&tab_label=SW5zdHJ1Y3Rpb25z&tab_label=SW5zdHJ1Y3Rpb25z

**Comment by mra142** [comment]
Looks good.
