### ISSUE TITLE
Microsoft edge not supported?

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#881]
Hi,

I have a user getting this error this morning. He has no other access right now. Is this an ongoing issue?

![image](https://user-images.githubusercontent.com/31412413/43782847-435e9ec6-9a2e-11e8-8eea-052902eba531.png)

**Comment by ecsion** [comment]
Hi Mike, currently eSeaGrant support is limited to chrome, firefox & safari. 

Could you please ask this user to use one of the supported browsers.
