### ISSUE TITLE
VASG- Promote to Project

### ISSUE THREAD

**Issue by abigailhils** [ecsion/eSeaGrant-Client-Bug-Tracker#882]
I cannot select proposals for funding nor promote to projects in eSeaGrant. 

First, whenever I select for funding, I receive this "Alert! Super 90-4 PI name / Duration added." Where exactly might I find this 90-4? Also, when I go to the RFP Reports to download the Cumulative 90-4, nothing is filled in. 

Second, when trying to promote to projects, I get "Cannot promote this proposal. 90-2 form is missing." Can you please walk me through this process? We were able to do this last year, however now I am at a standstill.

**Comment by ecsion** [comment]
Fixed, please check.
