### ISSUE TITLE
OSG- forms data

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#886]
Can you provide written instructions on how to access and use the submitted Forms data? I'm not sure what my problem is, but I cannot figure out how to retrieve data from all forms. I know the data is there but there are no written instructions for retrieving data from our PI-submitted forms. Some examples:  I need a report of all of the economics data reported on all projects completed between February 2, 2017 and January 31, 2018. I also need all of the publications and communications products reported on all projects completed between February 2, 2018 and today. I am probably missing something simple and right in front of me.

**Comment by ecsion** [comment]
Hi Cathy, OSG has been moved to R2 ver 0.7 . In this release, the report download has been moved to the Report Call Detail page. On the left hand navigation, you will see: "Download Excel Custom Form Reports"

<img width="989" alt="screen shot 2018-09-28 at 6 36 17 pm" src="https://user-images.githubusercontent.com/1612666/46236574-80774b80-c34d-11e8-9ed0-e9cd2cc05614.png">
When you click this, you will get a page similar to:

**Comment by ecsion** [comment]
We are working on adding on demand Guide that will be released soon.

**Comment by ecsion** [comment]
Closed this issue, but please reopen if you are still having difficulty.

**Comment by mcbridec** [comment]
Hi- I realize that, but that is not an option in my account. Attached is what I see when I log in using cathy.mcbride@oregonstate.edu<mailto:cathy.mcbride@oregonstate.edu>.

-Cathy

Catherine McBride
Oregon Sea Grant
1600 SW Western Blvd Ste 350
Corvallis OR  97333
541-737-8692
cathy.mcbride@oregonstate.edu<mailto:cathy.mcbride@oregonstate.edu>
