### ISSUE TITLE
Question: Where do we  add Co-investigators?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#89]
Deepak, we discussed this possibly before the bug-tracker was available, but we don't see any way to add co-principal investigators or any other research project staff (e.g., research associate, graduate student) to a project.

For migrated projects, the data are associated with the field "type" which points to the table "project_users."

**Comment by mgduke** [comment]
Deepak, we just realized that we should've included in the following request:
How do we reinstate the co-investigator info and linkages from the migrated data?

**Comment by ecsion** [comment]
done.
