### ISSUE TITLE
Menu items cannot be seen.

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#891]
Menu items on hover or active items cannot be seen.
See below:
![screen shot 2018-10-23 at 2 19 34 pm](https://user-images.githubusercontent.com/36545478/47385147-d8943a00-d6ce-11e8-9297-53a0f2bbf578.png)
![screen shot 2018-10-23 at 2 19 15 pm](https://user-images.githubusercontent.com/36545478/47385149-dcc05780-d6ce-11e8-982c-19d0d5bbb37c.png)

**Comment by Dipali-Ecsion** [comment]
![image](https://user-images.githubusercontent.com/17423049/47572345-5b7bf580-d958-11e8-9a3d-185055097fb2.png)

**Comment by tomxiong-aqua** [comment]
Thanks
