### ISSUE TITLE
Remove hidden fields from PI view

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#893]
Can you remove the hidden/admin only fields from the PI view?
Question 1 & 2 are Admin fields.
See example below:
![screen shot 2018-10-25 at 2 26 57 pm](https://user-images.githubusercontent.com/36545478/47525220-4de44400-d862-11e8-91dd-4a3ef300567c.png)

They also show up in the pdf when the PI hits the "PDF this page" button

**Comment by ecsion** [comment]
Done, please check.

**Comment by Dipali-Ecsion** [comment]
![image](https://user-images.githubusercontent.com/17423049/47572022-992c4e80-d957-11e8-987e-b6c9e28691e4.png)

**Comment by tomxiong-aqua** [comment]
It is fixed in the proposal summary, but it still shows up on the other forms.

![screen shot 2018-10-29 at 1 38 34 pm](https://user-images.githubusercontent.com/36545478/47672579-644f1000-db80-11e8-889b-7435daa4b559.png)

**Comment by tomxiong-aqua** [comment]
Still there:

![screen shot 2018-11-14 at 3 29 14 pm](https://user-images.githubusercontent.com/36545478/48513732-2ad60000-e822-11e8-9f34-b05c93b29a3a.png)

**Comment by ecsion** [comment]
previously we fixed it for SGAdmin view and did not realize that the same issue was affecting the PI view. Now we have fixed the PI view as well.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/49426301-2f109000-f7c6-11e8-88c7-c0e81b82f426.png)

**Comment by mra142** [comment]
Works on MDSG's site.
