### ISSUE TITLE
WISG - Add alert when system fails to save

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#894]
Just wondering if we could add an alert or some message to the user notifying them that the data could not be saved.

Thanks

**Comment by ecsion** [comment]
Tom, We are confused on this request. Could you please provide url &  screenshot of the screen where you would like us to add the alert. Also provide other scenarios where the same alert should be added.

**Comment by tomxiong-aqua** [comment]
This may have been fixed in one of the updates, or just a glitch.
