### ISSUE TITLE
MDSG - Publication module

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#898]
There appears to be a character limit in the "Publication Title" field in the pubs module, which is cutting off data entered by PIs.

Is this intentional, or can it be removed? It does not appear to cause an issue in the PDF output (there is plenty of space).

![image](https://user-images.githubusercontent.com/31412413/47795133-515f4b80-dcf8-11e8-9885-8854f2eb4fd0.png)

**Comment by ecsion** [comment]
The text size limit was 128 characters. We have now increased it to unlimited characters. Please check.

**Comment by mra142** [comment]
Fixed and closed. Thank you.
