### ISSUE TITLE
ORSG: Staff cannot see PI reports

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#900]
My Oregon Sea Grant coworker, Tiffany Woods is set up as with staff permissions. She cannot access any PI reports at all. Are we doing something wrong with our permissions setup?

**Comment by ecsion** [comment]
Cathy, We could not reproduce the issue. Please provide the email of the staff account that is now working. And the url link  of the report that is not showing to them.

**Comment by mcbridec** [comment]
I logged in as Staff user, tiffany.woods@oregonstate.edu. I chose to look at SG Investigator, Robert Wheatcroft's projects. I could see that he had two projects, but Tiffany was not allowed to see them. When I clicked on the title of each project, this is what Tiffany sees:
![denied_woods](https://user-images.githubusercontent.com/17169131/48294742-11f0d780-e43b-11e8-9446-22af9e295534.PNG)
However, when Tiffany chooses to look at projects by SG Investigator, Sally Hacker, Tiffany can see all of that Hacker's project documents.  I do not understand why Tiffany can access Hacker's project documentation, but cannot access those by Wheatcroft. Tiffany needs to access all PI project reports. Can you help? Let me know if you need other information.

**Comment by ecsion** [comment]
Noted. We were not able to reproduce the issue. We will troubleshoot it and get this fixed asap. We will update you once this is done.
