### ISSUE TITLE
WISG - PDF does not include whole text.

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#901]
Some text is not getting transferred to the PDF. 
In the proposal summary of this submission, some text is cut off in the pdf. I'm not sure if this is the only one, it was just the one that was brought to my attention.

https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101321&mode=showSubmissionPreview&tab_label=UHJvcG9zYWwgU3VtbWFyeQ&tab_label=UHJvcG9zYWwgU3VtbWFyeQ==

If access to a water source with **< 30 mg/L nitrate is not possible, some homeowners may even need to consider both.**
- The bolded portion is left out of the pdf.

Here is the PDF:
[101321proposal.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2548947/101321proposal.pdf)

**Comment by Dipali-Ecsion** [comment]
Resolved, Please check.
[101321proposal.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2552779/101321proposal.pdf)
