### ISSUE TITLE
VASG - New User Registration Issues (phone call)

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#902]
Hello,

We are currently having a large number of new users sign into our eSG portal (Virginia) and over the past two months 2-3 students have run into issues when progressing through the new security steps during registration. The problem appears to be linked to the step where they receive a phone call with an verification code.

Two of the students have noted that they are Verizon Wireless customers, one of which was using an iPhone. They also tried entering their office phone numbers (land lines, Cox Communications) as well, as an alternative to their cell phone numbers, with no success. 

I have  manually entered them into the system, but it would be great to get this issue fixed ASAP. While I don't have a lot of additional information to share, I have included the information I do have at this point below, and welcome you to call me at 804-684-7436 if I can answer any questions. 

Best,
Sam

The first student to have this issue was Taylor Goelz, who tried to register in late-September. Lauren Ferris was the most recent student to run into this issue (yesterday, November 5th) and I have included her email and screenshot below.

Hello Sam,

I am trying to register for eSeaGrant but am stuck on this page. After submitting my phone number, I receive a call; and there is about a minute of silence before a voice states that there is an application error.

Thank you!
Laur

<img width="864" alt="screen shot 2018-11-05 at 11 09 32" src="https://user-images.githubusercontent.com/17860369/48070014-e3f26580-e1a4-11e8-968d-457369ec5f3b.png">

**Comment by ecsion** [comment]
Sam, We are not able to reproduce this issue. It may be that the phone call was missed, in that case, we currently have no way to ask for the call again. We are going to add a button so that the system will attempt another call with the verification code.

**Comment by SamuelJLake** [comment]
Thanks for looking into this, I wasn't sure if you would be able to identify the issue with the limited information I could provide currently. However, I wanted you to be aware.  

I know both students fairly well and can confirm that they did not miss the calls. The two calls played out differently. The first student picked up and the call dropped within a few seconds of her answering. The second student did not hear anything but stayed on the line for about a minute before she heard an error message. 

If another person experiences this issue and reaches out to us, is there something that we could do to help you isolate/identify what might be happening?

Best,
Sam

**Comment by Dipali-Ecsion** [comment]
We have added Retry button so that the system will attempt another call with the verification code. Please check.

![image](https://user-images.githubusercontent.com/17423049/49291128-2cb0ec00-f4cf-11e8-85b1-c899f1138dd5.png)

**Comment by mzwolinski** [comment]
TXSG: Researcher is not receiving the code to his cell phone and the retry button has not worked. He uses a Mac, Firefox yesterday and used Google Chrome this morning. Name is Peter Santschi at Texas A&M at Galveston, santchhi@tamug.edu and ph # 409-539-1007. Please review and advise. Thank you, Mia Zwolinski, Asst Director, Texas Sea Grant.

**Comment by mzwolinski** [comment]
Santchi@tamug.edu

**Comment by mzwolinski** [comment]
My apologies, santschi@tamug.edu
