### ISSUE TITLE
WISG - please change alert message on peer review screen

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#904]
Can we change this alert to: "Proposal pdf not uploaded.  Please contact your University of Wisconsin Aquatic Sciences Center Administrator"

![screen shot 2018-11-06 at 11 07 08 am](https://user-images.githubusercontent.com/36545478/48080854-47d05a80-e1b4-11e8-8f47-9b025cdb3819.png)

Thanks.

**Comment by ecsion** [comment]
Fixed, please check.
