### ISSUE TITLE
MDSG -- 90-4 PDF Export malfunctioning

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#906]
The 90-4 form for collating data from the budget module is no longer exporting correctly into a 1-page PDF document. The file extension ".pdf" was also not attached to the file and had to be added manually.

Also on this form, there are extra categories/rows for fringe benefits (on-campus, off-campus, other) which should not be there. There is only one fringe benefit calculation -- note how this looks on the official Sea Grant form here: https://seagrant.noaa.gov/Portals/1/Forms/90-4-Budget-form-PDF.pdf

This form: 
![image](https://user-images.githubusercontent.com/31412413/48096056-3e5ee680-e1e4-11e8-9be8-4c3668d7520c.png)

Link to location: https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=104405&mode=showBudget_90_4&tab_label=OTAtNA&tab_label=OTAtNA==

What I was able to download: [104405budget90-4.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2555140/104405budget90-4.pdf)

**Comment by mra142** [comment]
I sent the following to Deepak, so I'm including it here for comprehensiveness.
*****
I've inquired with Dorn at the national office whether this 90-4 form will be acceptable. He thinks it will be, but he has to inquire with others since he is retiring. We came up with a couple issues:
1. Everything should be in whole dollars, not decimals. 
2. The expiration date has just been updated by the national office to 2/28/2021.
3. Also Fringe benefits still don't show up in line B. Total Personnel (A and B) does (and should since it's a subtotal). What this should be is the total fringe benefits for all in section A. 
4. New 90-4 document changes the terms "Grantee Funds" with "Matching Funds".
5. Dorn did not know what the "Waived IDC" column of boxes was. This total should be part of the Grantee Funds/Matching Funds column (like it is on your worksheet form). (Otherwise -- in my attached example -- 1788 plus 894 do not add up to 6257). Two ways I think this can be done: 1) as an extra row, or 2) include the waived/forgone IDC as part of the on-campus, off-campus, or other totals (i.e. a formula that adds waived to the number already in the box). 
What is easier for you?

Here's a direct link to the current form
https://seagrant.noaa.gov/Portals/1/90-4-Budget-form-PDF-11272018.pdf

[106041budget90-4.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2629489/106041budget90-4.pdf)

**Comment by ecsion** [comment]
@mra142 Mike, 

Your 5th point,  -- Since the bottom block is not present in official 90-4 pdf template, should we simply remove it.  See attached.
<img width="938" alt="screen shot 2018-12-03 at 9 05 03 am" src="https://user-images.githubusercontent.com/1612666/49378429-951fe900-f6da-11e8-9ffc-2faffa71d40e.png">

**Comment by mra142** [comment]
Well I'm hesitant to get rid of it completely, because that block varies a bit between their three versions and some of the data you provide in your block are included in their form.  

Their PDF looks like this: 
![image](https://user-images.githubusercontent.com/31412413/49379571-635c5180-f6dd-11e8-875c-d8d8666fdca5.png)
So they have the percent charged and the "subtotal" in that blank. So those data must remain (at a minimum).

Their XLSM version looks like this:

![image](https://user-images.githubusercontent.com/31412413/49379210-9520e880-f6dc-11e8-9d87-f24ea4d823d0.png)

So it's very similar to your version (but without an extra column for waived IDC and missing the percentage). Their first yellow column is just blanks without formulas so that you can write in informative text or numbers. 

Perhaps the best solution is still three columns. 1st column is indirect %. 2nd column is Sea Grant Subtotal. 3rd column is Match subtotal.

Then if one waives indirect on a portion of their funds, those waived values are added to the match subtotal in the correct row. Then the match subtotal times the indirect rate would be what goes in the column all the way to the left. Does this make sense?

If you'd like to talk about this on the phone, I'm happy to do so.

![image](https://user-images.githubusercontent.com/31412413/49380307-648e7e00-f6df-11e8-8da6-0e170364511b.png)

**Comment by mra142** [comment]
Checking it no see whether any of these changes are going to be incorporated soon? Many RFPs are coming out in the near future that require 90-4 PDFs.

**Comment by mra142** [comment]
There was further discussion on this issue on Basecamp. Please see the discussion string there to incorporate changes on the 90-4 output/PDF download. Folks there generally agreed with my suggested changes with the exception of changing the word "waived" to "foregone". Please see images.

https://basecamp.com/2782140/projects/13305906/messages/83550014
