### ISSUE TITLE
MDSG - Budget justification view

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#907]
On the budget justification view, indirect costs, which are letter H in the worksheets, appear first at the top of the justification printout. They should be last.

![image](https://user-images.githubusercontent.com/31412413/48096916-867f0880-e1e6-11e8-8b7b-242fdb68e8d6.png)https://eseagrant.mdsg.umd.edu/operations.php?action=justification&id=36
https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=104405&mode=showBudgetListingData&tab_label=QnVkZ2V0cw&tab_label=QnVkZ2V0cw==

Can these justifications be exported as a PDF that does not say "Close Window" on it?

**Comment by ecsion** [comment]
Looking into these issues ..

**Comment by ecsion** [comment]
Corrected Justification H position. 

The enhancement request to export in pdf (without close window) is in progress.

**Comment by mra142** [comment]
Corrected. Closed.
