### ISSUE TITLE
WISG - user uploaded files not found

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#908]
We are getting some errors when we try to retrieve user uploaded files.
Here is an example:
- no CV can be found on these
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101202&mode=showMultiQuestionStem&QuestionId=100620&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101132&mode=showMultiQuestionStem&QuestionId=100620&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101416&mode=showMultiQuestionStem&QuestionId=100620&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101260&mode=showMultiQuestionStem&QuestionId=100620&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=&tab_label=V1JJIFByaW5jaXBhbCBJbnZlc3RpZ2F0b3I=

Missing narrative file upload here:
https://edrop.aqua.wisc.edu/index.php?module=RFPProposal&view=Detail&record=101416&mode=showMultiQuestionStem&QuestionId=100622&tab_label=V1JJIFByb3Bvc2FsIE5hcnJhdGl2ZSBGaWxlIFVwbG9hZA==&tab_label=V1JJIFByb3Bvc2FsIE5hcnJhdGl2ZSBGaWxlIFVwbG9hZA==

**Comment by ecsion** [comment]
fixed, please check
