### ISSUE TITLE
MDSG - Duplication of focus areas on preview

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#909]
We are seeing a duplication of the focus areas on the Submission Preview page for our proposal, even though there is only one option on our 90-2:
https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=104405&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

![image](https://user-images.githubusercontent.com/31412413/48154464-b2f25d80-e296-11e8-9345-d5c07e70e60d.png)

![image](https://user-images.githubusercontent.com/31412413/48154528-d4534980-e296-11e8-8349-9e13e18fb193.png)

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mra142** [comment]
This appears correct.
