### ISSUE TITLE
MDSG - HTML Tags in text boxes causing text loss

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#910]
I posted the following in Basecamp earlier, and I've now found that the html tags are causing a print problem with the PDF function.

> I see that in reporting text boxes, some html tags are now working in the PDF output (e.g. < SUP>, < i>, < b>). I learned this by accident as one of my PIs entered these tags in his writing.
> 
> Can we be provided with a list of tags that are now acceptable? 
> 
> M

When people type in only a "less than" sign -- as in "p < 0.05", the rest of the paragraph is cut out of the PDF document. An example is this record --> PDF this Page --> last paragraphs on page 12/25 of PDF: 
https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=103093&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

Mike

**Comment by ecsion** [comment]
fixed, please check. 

Mike, the HTML tags are allowed only when you see a full text editor with the input text area. Otherwise, tags will print as data.

**Comment by mra142** [comment]
This appears to be fixed.
