### ISSUE TITLE
MDSG - Mismatched field printing in PDF for Student supported

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#911]
I only have seen this glitch in one place so far ... not in every PDF translation.

At the link below, the student supported fields. Student 1 Teodoro is in degree type "PhD" and Degree Year "3rd". On the submission preview page (and in the student module), these fields show correctly. However, when you create the PDF of the submission preview, they flip (degree year = PhD, degree type = 3rd).

I have not seen this error recreated in other PDFs generated, so it's somewhat a mystery to me.

https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=102520&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

![image](https://user-images.githubusercontent.com/31412413/48280498-c4b43c00-e421-11e8-8ad5-0f1118de3ffc.png)

**Comment by mra142** [comment]
Here is another example where I found this mismatched error. 

https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=103073&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mra142** [comment]
These appear correct.
