### ISSUE TITLE
Report Call - Submission Preview Issues

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#913]
Hello,

We currently have a PI who is trying finish and submit their report, but they are running into a few different issues. The one that I have been able to replicate is an error when they reach the Submission Preview page - they receive this error message (screenshot below)...

"Record you are trying to access is not found
Please contact the Sea Grant Administrator for further assistance."

We are working with the PI to find a different way for them to submit their report, but would like to determine what is causing this issue before we release our annual reporting calls next month.

Best,
Sam

**Link to webpage**
https://vaseagrant.ecsion.com/index.php?module=Reporting&view=Detail&record=102044&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**eSeaGrant Details**
Call: 2018 NOAA NMFS Sea Grant Fellowship - Final Reports 
Call Type: NMFS Final Report 
Project: R/719911 

<img width="1196" alt="screen shot 2018-11-18 at 9 19 08 am" src="https://user-images.githubusercontent.com/17860369/48673780-0ffdd700-eb13-11e8-9ff1-de6ca0851b36.png">

**Comment by ecsion** [comment]
fixed & verified.
