### ISSUE TITLE
MDSG: PRIORITY Data not saving in forms when all fields are not completed

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#914]
In the reporting module, you used to be able to press the save button to record in-progress data on forms that have multiple required elements. Now if I enter data in one * box, click save, and go to another module in the report, the data do NOT save but rather seem to get lost. It appears as if you must enter data in each box with a required* marker before you can save your data.

I believe we fixed this in eSG v1 so that data could be saved even if only some required boxes were filled in. Please fix the 'save button' function right away!

Example form: https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=104761&mode=showMultiQuestionStem&QuestionId=101445&tab_label=UmVzZWFyY2ggTmFycmF0aXZl&tab_label=UmVzZWFyY2ggTmFycmF0aXZl

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by mra142** [comment]
Tried on a new report. Works correctly. Thank you!
