### ISSUE TITLE
MDSG: Partners missing in custom forms output and summary pages

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#915]
This is a 2 issue post. We were reviewing partners for this year and noticed:

1. Partners from report calls before 2018 are not showing up in custom report calls output, and the partner output from reports does not appear to be searchable/queryable:
**Custom Report calls list:** https://eseagrant.mdsg.umd.edu/index.php?module=MultipartAnswers&view=List&showList=true&tab_label=Custom%20Form%20Responses&viewname=169
**Custom query for partners from 2017** https://eseagrant.mdsg.umd.edu/index.php?module=MultipartAnswers&view=List&viewname=275&tab_label=Partners%202

2. Partners that are listed in projects from those early years are not showing up on the summary page for the report (but they are being exported to PDF).
Example: **Summary page** https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=1541&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=UmVwb3J0IFN1bW1hcnk=
**Partner report page** https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&relatedModule=PartnerReport&view=Detail&record=1541&mode=showRelatedList&tab_label=UGFydG5lcnMgdGhpcyBwZXJpb2Q=

Example: **Summary Page** https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=1394&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=UmVwb3J0IFN1bW1hcnk=
**Partner report page** https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&relatedModule=PartnerReport&view=Detail&record=1394&mode=showRelatedList&tab_label=UGFydG5lcnMgdGhpcyBwZXJpb2Q=

**Comment by ecsion** [comment]
Mike, for 2017, Partners this period was a hard coded form and so you have to create a view in Partners this period. We have created a view for you: 
https://eseagrant.mdsg.umd.edu/index.php?module=PartnerReport&view=List&viewname=277

#2 was a coding error and is fixed. Please check.

**Comment by mra142** [comment]
These issues are fixed.
