### ISSUE TITLE
Dates wont save when creating report calls

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#917]
The dates revert to 0000-00-00 when you press the save button on a Report Call setup. I have to go back and edit it again to get the dates to save.

**Comment by ecsion** [comment]
We are unable to reproduce this issue. Please provide a url link and a screenshot.

**Comment by Drew-Casey** [comment]
As you can see in these screen captures, I created a new report using your test report as a template. I saved the dates and it reverted. I went back in and changed the dates again.

**Comment by ecsion** [comment]
Drew, we are unable to see the screenshot or the url. Can you please repost.

**Comment by Drew-Casey** [comment]
![capture 1](https://user-images.githubusercontent.com/44243756/49380151-89cabe80-f6d6-11e8-8775-f0184248a5c2.JPG)
![capture 2](https://user-images.githubusercontent.com/44243756/49380164-93542680-f6d6-11e8-8b5b-21c3c6e56154.JPG)
![capture 3](https://user-images.githubusercontent.com/44243756/49380177-994a0780-f6d6-11e8-8fdf-1a7dd6ed0676.JPG)
![capture 4](https://user-images.githubusercontent.com/44243756/49380178-9b13cb00-f6d6-11e8-8510-63e0257029da.JPG)

**Comment by ecsion** [comment]
Drew, We still can not reproduce this issue. Please provide your browser name and version. Thanks

**Comment by Drew-Casey** [comment]
Google Chrome
Google Chrome is up to date
Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by ecsion** [comment]
Drew, Are you still experiencing this issue? If so can you provide a screenshot an a link,

**Comment by Drew-Casey** [comment]
When I create a “+ New From Template or Call” and change the dates. After saving, the dates revert to 0000-00-00. It also doesn’t keep any of the associated projects. Below is a step by step I did to show you what happens. I have just stopped using the “+ New From Template or Call” button because it is more work than simply creating a brand new one.

Step 1
[cid:image005.jpg@01D5388A.AE647880]
Step 2: I change the text and dates
[cid:image006.jpg@01D5388A.AE647880]
[cid:image007.jpg@01D5388A.AE647880]
Step 3: I click save
[cid:image008.jpg@01D5388A.AE647880]

**Comment by Dipali-Ecsion** [comment]
Hi,
We can't see images uploaded by you, can you please upload it again..
Also can you tell us which report call you are using to create template from that button.
Thanks

**Comment by Drew-Casey** [comment]
I have attached a word doc with the pictures. It does not matter what report call is the template.

**Comment by Drew-Casey** [comment]
Any update on this yet?
