### ISSUE TITLE
MDSG: Budget Justification coding error

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#918]
Running a practice RFP with the budget module. There is a brief coding error that is leading to a file name not associated with the proposal and extra line of text being added to the justification. 
"[MBrooks_Grad Transcript.pdf], Mos. Effort: 1 SG 0.25 Grantee, Benefits Rt.:0.43 , Mo. Salary: $5000"

https://eseagrant.mdsg.umd.edu/operations.php?action=budget&proposal_id=MTA2MDQx&id=43

Justification view: https://eseagrant.mdsg.umd.edu/operations.php?action=justification&id=42

![image](https://user-images.githubusercontent.com/31412413/49173392-95eb0080-f311-11e8-99c6-b17fd506d113.png)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/49798449-47ede800-fd68-11e8-9d2a-c54b77045bcd.png)

**Comment by mra142** [comment]
Fixed in this one location. But your fix may have led to problems elsewhere in budget justifications. I checked another proposal in development and the justification has text and $ for the PI, but the information is not showing up in the justification document:

https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=105586&mode=showBudgetListingData&tab_label=QnVkZ2V0cw==&tab_label=QnVkZ2V0cw==

It's very strange that it's pulling data differently on different worksheets. This one appears to work correctly: 
https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=104405&mode=showBudgetListingData&tab_label=QnVkZ2V0cw&tab_label=QnVkZ2V0cw==
https://eseagrant.mdsg.umd.edu/operations.php?action=justification&id=36

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
This is moot after 7 months.
