### ISSUE TITLE
Minor coding issue: Wisywig conversion ' --> &'

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#919]
Ampersands are showing up in the RTF translation of instructions for our RFPs. Specifically, in the instructions for a form we have written:
MDSG's 
and it shows up as 
MDSG&'s

This & doesn't show up on the custom form view (preview), but it does show up when creating a proposal.

Examples include: 

https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=106210&mode=showMultiQuestionStem&QuestionId=106079&tab_label=MSBTaWduZWQgVGl0bGUgUGFnZQ==&tab_label=MSBTaWduZWQgVGl0bGUgUGFnZQ==

https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=106210&mode=showMultiQuestionStem&QuestionId=106081&tab_label=MiBQcm9qZWN0IFN1bW1hcnk=&tab_label=MiBQcm9qZWN0IFN1bW1hcnk=

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
Closed
