### ISSUE TITLE
Partners dropdown default still not quite right

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#92]
CORRECTION FROM INITIAL POST: 
For migrated Partners that already had "Scale" and "Types" values associated with them, the values are inconsistently displayed; also, on initially adding a new partner, we still see inconsistent values: 
1. When we click "Add Partners," the default Scale menu shows "FEDERAL or NATIONAL" and the Types field shows "Select an Option." Both should be "Select an Option."

2. When we select an existing partner from the "Partner Name" field," sometimes nothing appears in Scale and Types, and other times we do see the values we expect (e.g., the Camp Berachah partner record correctly shows Local and NGO for Scale and Type).

See (1) a URL for the page displayed in the (2) following screenshots, and (3) an Excel file listing all partners and, when data are available, values for Scale and Types. We're hoping that, all else fails, the Excel table may help you resolve the inconsistencies in populating this form's Scale and Types fields.

http://esg.wsg.washington.edu/index.php?module=PartnerReport&view=Edit&sourceModule=Reporting&sourceRecord=15965&relationOperation=true

![screen shot 2016-03-11 at 10 10 25 am](https://cloud.githubusercontent.com/assets/17168836/13711126/c567c356-e771-11e5-8e26-70f5ba29c8d0.png)
![screen shot 2016-03-11 at 9 39 28 am](https://cloud.githubusercontent.com/assets/17168836/13711129/c9cf806e-e771-11e5-854e-cb965d5d35d0.png)
![screen shot 2016-03-11 at 9 40 55 am](https://cloud.githubusercontent.com/assets/17168836/13711134/cf60e018-e771-11e5-8736-fc9b7a4fc570.png)

[Partners_3_11_2016.xlsx](https://github.com/ecsion/eSeaGrant-Bug-Tracker/files/169709/Partners_3_11_2016.xlsx)

**Comment by ecsion** [comment]
done, please check. I there are still issues, please provide details & reopen.

**Comment by mgduke** [comment]
OK, I checked some 6-7 records and it appears things have improved, but when initiating a new Partner record in a report, "FEDERAL or NATIONAL" is still the default for "Scale." Please set the "Scale" default to "Select an option".

**Comment by ecsion** [comment]
fixed
