### ISSUE TITLE
MDSG: Site Use instructions now have a character limit?

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#920]
I edited site use instructions for a report call I'm about to issue and once I saved it, only a certain number of characters were saved. Save works for less characters, but not for longer paragraphs.

https://eseagrant.mdsg.umd.edu/index.php?module=CallReporting&view=Detail&record=106363

**Comment by ecsion** [comment]
fixed, please check

**Comment by mra142** [comment]
Fixed and closed. Thank you.
