### ISSUE TITLE
MDSG: Promote to Project Issue

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#921]
Copied over from previous thread you just closed. Posted yesterday.
***
I'm having this same problem today. See below:

I'm trying to promote this proposal to a project, and eSG is stuck in a cycling time out mode and will not transfer the project over. I've previously promoted another project within this RFP call as a test case (but subsequently deleted it).

https://eseagrant.mdsg.umd.edu/index.php?module=RFP&view=Detail&mode=updateProposaltoPromote&record=105562&phaseid=105563&proposalid=106346&tab_label=Program%20Development

![image](https://user-images.githubusercontent.com/31412413/49466928-3ab48480-f7cf-11e8-8860-aeb37f6475c4.png)

_Originally posted by @mra142 in https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/882#issuecomment-444226173_

**Comment by ecsion** [comment]
fixed, please check

**Comment by mra142** [comment]
I was able to pull in the project. However, it pulled in the year 1 funds information into the 'subprogram' field. And it did not pull in the primary award number.

**Comment by mra142** [comment]
This pulled correctly on the next PD award I promoted to a project.
Closed.
