### ISSUE TITLE
problems with date started and email

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#922]
When I start a RFP and put in a date 12-6-2018 - R2 reads it as 6-12-2018 (it switches the first and second numbers).  

This also happens on the email that the PI gets when they submit.  It either show Dear , or Dear <Last Name>, <First Name>.

**Comment by Dipali-Ecsion** [comment]
As you mentioned about, I found date format issue on RFP listing page, I resolved that issue there. If you find date format issue at any other place, please provide links. 

![image](https://user-images.githubusercontent.com/17423049/49805741-e46db580-fd7b-11e8-9bf3-99d87de39516.png)

Also issue regarding salutation in email is resolved. Please check.
