### ISSUE TITLE
Can't find email templates

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#923]
When I click on a person's name and select email templet a blank page shows up.  See below attachment and link.

https://www.laseagrantdb.org/index.php?__vtrftk=sid%3A7d97cd8d52efda90d95178774e6b5306078436bd%2C1544455804&selected_ids=%5B%229721%22%5D&excluded_ids=&viewname=&module=Emails&view=ComposeEmail&callreportingid=&rfpphaseid=&search_key=&operator=&search_value=&search_params=null&fieldModule=People&to=%5B%5D&selectedFields=%5B%22email%22%5D&relatedLoad=1&triggerEventName=postSelection982
[User email.docx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2663718/User.email.docx)

**Comment by Dipali-Ecsion** [comment]
To get email templates under 'Select Template' section, you need to add template for people module.
To add template:
1. Please go to this link : https://www.laseagrantdb.org/index.php?module=EmailTemplates&view=List&type=Normal
2. Add Email template and while creating template, select 'People' as module.

So you will be able to get templates there.

**Comment by katielea** [comment]
This still isn’t working.
