### ISSUE TITLE
MDSG - Budget data entry error messages and other problems entering data

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#926]
I'm trying to create a budget worksheet for a PI in his view.  I entered the information to create a new worksheet (https://eseagrant.mdsg.umd.edu/operations.php?action=budget&guid=E5C71F4E-04A5-4467-BE27-4C3F626B8783&proposal_id=MTA2NTM2) and I was given back this error message: 

{"url":"operations.php?action=budget&proposal_id=MTA2NTM2&id=47"}

I hit the back button to the budgets page (https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=106536&mode=showBudgetListingData&tab_label=QnVkZ2V0cw==&tab_label=QnVkZ2V0cw==), Tab 4 and the budget worksheet appeared to be added (I tried this a couple times). Within the budget worksheet (title: UMCES-Lyubchich) I was able to enter data, but when I clicked the save button in a row, I was taken to a blank screen (though it appeared to save the data once I went back and clicked "update budget" at the top). 

Once I'm back on this worksheet though and trying to enter budget justifications, no window is popping up when I click on the pink dot to edit. I'm completely stuck.

This is the first time I've had this serious of an issue with this acting as a PI. I've entered another proposal/budget (PI Preheim) without similar problems within the same RFP.

At the moment I am stuck.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
Fixed. Thank you.
