### ISSUE TITLE
RISG: Recommendation Letter Request will not allow upload of requested document

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#927]
In our 2020 Knauss RFP, when a letter of recommendation writer is sent an invitation email, then opens it, clicks the link to submit the letter, the screen does not allow for a document to be uploaded. The SUBMIT button appears functional, but no document can be attached. This needs to be corrected for this function to work. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
Fixed, thank you.

Alan Desbonnet
Assistant Director
