### ISSUE TITLE
RISG: Custom Form Check Box option

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#928]
See the screen shot below. You will note that the list ends with a checkbox with no associated text. This makes it look as if there is a missing final choice, but there is not. It would be less confusing if when created Check Box lists in custom forms that the list end with the final entry in the list rather than a blank box at list end. 

This is not critical, but can lead to confusion. If this can be corrected so that no empty check box ends the list, that would be great.

<img width="300" alt="screen shot 2018-12-14 at 10 40 51 am" src="https://user-images.githubusercontent.com/18398763/50012676-47826680-ff8d-11e8-811e-6cf4d58df55b.png">

**Comment by ecsion** [comment]
Alan, we will fix this bug next week and update you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/50088501-3b1a3a00-0229-11e9-812c-f22efa5dea9c.png)

**Comment by alandesbonnet** [comment]
Perfect. Thank you.

Alan Desbonnet
Assistant Director
