### ISSUE TITLE
MDSG: Priority -- Fellowship request for proposal selection just hangs

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#929]
We have an open Knauss RFP and when a new PI tries to start an application, the system just hangs like this:
![image](https://user-images.githubusercontent.com/31412413/50012628-228df380-ff8d-11e8-9afb-eb014f040166.png)

I've tried this logged in as two different PIs with the same result.

Here is a link to one of the PI log in pages: https://eseagrant.mdsg.umd.edu/index.php?module=RFPPhase&view=List&tab_label=Current%20Tasks&type=currenttask

This only happens for the "2020 Knauss Marine Policy Fellowship" RFP. All of the other RFPs and fellowship applications in the Current Task menu function correctly to create a proposal.

Mike

**Comment by ecsion** [comment]
We will get this issue fixed in Monday's build.

**Comment by mra142** [comment]
Thanks.

-- Sent from mobile

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
Corrected. Thanks.
