### ISSUE TITLE
RISG: Deleted form shows up in new proposals

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#930]
See screen shot below showing custom forms selected for Knauss 2020 RFP.

<img width="1795" alt="screen shot 2018-12-17 at 1 15 30 pm" src="https://user-images.githubusercontent.com/18398763/50106554-296f6d00-01fe-11e9-8a5f-f4ef79df54db.png">

See screen shot below and notice red form in left column "Knauss --- Application Checklist" from a view taken within a newly created proposal. That form DOES NOT appear in the list of selected forms above, yet shows up here in the list of forms being used. This should not be.

Further more, if you go to Forms Library and search for Knauss --- Application Checklist no form is found, because the form was deleted. 

Unused and/or deleted forms should not show up in proposals. I noticed WASG has a similar issue which was fixed; why wasn't this fix applied to all eSeaGrant users? 

Please correct this so that forms not being used do not show up as is happening. Thank you.

**Comment by alandesbonnet** [comment]
<img width="1784" alt="screen shot 2018-12-17 at 1 15 08 pm" src="https://user-images.githubusercontent.com/18398763/50106854-ff6a7a80-01fe-11e9-9e2b-474fd629d48c.png">
 Apologies, here is the missing screen shot.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/50154933-b4c92b00-02f0-11e9-80fc-9d3fc1d34112.png)

![image](https://user-images.githubusercontent.com/17423049/50155096-30c37300-02f1-11e9-836c-17f3b0865b66.png)

**Comment by alandesbonnet** [comment]
Thank you. I closed the issue

Alan Desbonnet
Assistant Director
