### ISSUE TITLE
WASG: Can submission preview order be made to match tab order?

### ISSUE THREAD

**Issue by deborahpurce** [ecsion/eSeaGrant-Client-Bug-Tracker#932]
Just wondering if the order of RFP submission preview standard questions can be made to match tab order?

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by deborahpurce** [comment]
Looks good! Thank you!

[Washington Sea Grant]<https://wsg.washington.edu/>

Deborah Purce
Program Specialist   Washington Sea Grant<https://wsg.washington.edu>
College of the Environment  |  University of Washington
T 206.616.5718<tel:206-616-5718> M-Th
