### ISSUE TITLE
ORSG - Menu item to remove

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#933]
![2018-12-17_1408](https://user-images.githubusercontent.com/17169131/50119325-53795d00-0207-11e9-93ef-3e6fbc37120a.png)

**Comment by ecsion** [comment]
We will look into this issue and fix.

**Comment by mcbridec** [comment]
I may be wrong about this one - this seems to be a custom report created by one of my colleagues. So lets close this issue. We can just delete it if it is a problem.
