### ISSUE TITLE
ORSG - Menu items to remove

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#934]
https://eseagrant.oregonstate.edu/index.php?module=People&view=List&tab_label=All%20People (this link likely will not help since it is a menu item that is an issue)

![2018-12-17_1357](https://user-images.githubusercontent.com/17169131/50119399-8885af80-0207-11e9-9d77-c8f551d4c465.png)

**Comment by ecsion** [comment]
We will look at this and fix.

**Comment by ecsion** [comment]
fixed, please check

**Comment by mcbridec** [comment]
It looks fine now - thanks!
