### ISSUE TITLE
LASG - Request for Affiliation

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#936]
I just spoke with Deepak today and LASG is requesting that the "Affiliation" field when a PI first fills out their information be mandatory.  We understand that those that are already in the system cannot be change to be mandatory, but from now on, we would like that first field called  "Affiliation" to be mandatory.  Please let me know if you have any questions.

**Comment by mcbridec** [comment]
Can you help me understand why you would like this to be mandatory?

**Comment by katielea** [comment]
Because when I run the report of who has submitted a specific proposal, I can see quickly which university they are from. This helps me in quickly telling my Director how many different universities in LA submitted a specific proposal.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
