### ISSUE TITLE
ORSG: eSG v2 popup box text is too faint

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#937]
https://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=104353&mode=showTasksData&&tab_label=Ri4gTk1GUyBGZWxsb3dzaGlwIExldHRlciBvZiBDb21taXRtZW50&questionid=104002

https://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=104353&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

The question is very faint at the top of the screen (right side pane) – can this be fixed to be more noticeable? Note this same thing happens with J. Letter of Recc request and with the submission preview (screen shot below)
 
 
![image](https://user-images.githubusercontent.com/18152637/50250905-0b894000-0397-11e9-8737-12defa27230b.png)

![image](https://user-images.githubusercontent.com/18152637/50250923-147a1180-0397-11e9-956f-469b48ad2e12.png)

https://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=104353&mode=showMultiQuestionStem&QuestionId=104006&tab_label=Si4gTk1GUyBGZWxsb3dzaGlwIExldHRlcnMgb2YgUmVjb21tZW5kYXRpb24

right side screen the box cuts off the text – this is a minor issue

![image](https://user-images.githubusercontent.com/18152637/50250937-1e037980-0397-11e9-8e78-970f5741af0a.png)

**Comment by ecsion** [comment]
We are not able to understand the issue you have stated. Could you please upload higher resolution images and highlight the issue in red outline.

**Comment by SEK-OSG** [comment]
OK, here are a few examples of the text, circled in red (left hand photo) and from eSG (right hand pane).
Any time the system prompts a yes/no response, the text is not readable - it's very faint gray writing on a gray background, way up at the top left of the screen.
Can this prompt text be more noticeable?

![image](https://user-images.githubusercontent.com/18152637/50523959-d7dda280-0a87-11e9-9059-29ecf78770b1.png)

**Comment by SEK-OSG** [comment]
This is as zoomed in as I can make it - left hand pane. The prompt text is practically un-readable.
![image](https://user-images.githubusercontent.com/18152637/50524003-212df200-0a88-11e9-97a4-eef2f25c6f67.png)
