### ISSUE TITLE
ORSG: eSG v2 no document uploaded notification could be bigger / more prominent

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#938]
https://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=104353&mode=showMultiQuestionStem&QuestionId=104008&tab_label=TC4gTk1GUyBGZWxsb3dzaGlwIERhdGEgU2hhcmluZyBQbGFu&tab_label=TC4gTk1GUyBGZWxsb3dzaGlwIERhdGEgU2hhcmluZyBQbGFu
The red circle is soo easy to miss – can this be bigger? Right hand pane below

![image](https://user-images.githubusercontent.com/18152637/50250994-47240a00-0397-11e9-9bc5-b80cfacae99e.png)

**Comment by ecsion** [comment]
We are not able to understand the issue you have stated. Could you please upload higher resolution images and highlight the issue in red outline.

**Comment by SEK-OSG** [comment]
OK, here's a screenshot of the red circle that indicates no file uploaded (left side pane, inside the larger red circle), versus a screenshot of the "regular" circle indicating that a file is uploaded (right side pane from eSG). The red circle indication is not very noticeable - can the whole circle be filled in red, instead?

![image](https://user-images.githubusercontent.com/18152637/50524166-1cb60900-0a89-11e9-8af8-0b726c7545fc.png)
