### ISSUE TITLE
ORSG: PDF file upload not recognized in open call  - VERY BIG DEAL

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#940]
PIs trying to complete Program Development proposal submissions are unable to upload files as PDFs, and receive the following error:
![image](https://user-images.githubusercontent.com/18152637/50460227-098c2780-0929-11e9-913f-7242cf051ea0.png)

This is a big deal because our Program Development Call closes on December 31. This error occurs for both Proposal Narrative and Data Management Plan (anywhere there is a PDF upload)

**Comment by ecsion** [comment]
Fixed. This issue was happening because no file type was chosen on the form. We have now added some coding to select any file when no file type is selected.

**Comment by SEK-OSG** [comment]
Many thanks!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by SEK-OSG** [comment]
It works now
