### ISSUE TITLE
ORSG: Reports date filter fixes

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#942]
When I open a custom Report I find that I am able to filter any Modified Time column by year alone. Or I can filter by just entering any number or date or partial date and I get the expected results. Very simple. I can use this to find all reports modified within any month or year. It is good. I have no issues with this, just using it for a comparison here. 
https://eseagrant.oregonstate.edu/index.php?module=Reporting&view=List&viewname=259&tab_label=Reports%20by%20Date
Okay, when I want to filter and sort any of the columns named Created Time, Reporting Start Date, or Reporting End Date, a calendar pops up. I cannot easily filter for all 2018 records, for example. I am  required to choose one date. This is only useful for finding reports starting or ending on a certain date. But we have a widening range of starting and ending dates in our database. So this is actually not as useful as first hoped. In addition, the method of choosing a year (especially), month and date is clumsy and takes too many keystrokes.
Here's another issue - the filter just does not work for these columns! 
The best way I can explain this is by video (link provided). The example in the video is typical for all of ORSG custom reports: 
https://www.screencast.com/t/KFsZiIBK8kaq  (I did not record audio or sound)
Can we change the Report columns named Created Time, Reporting Start Date, or Reporting End Date columns to filter in the same manner that the Modified Time column does?

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![image](https://user-images.githubusercontent.com/17423049/51679742-bc71a300-2005-11e9-97bd-811c182638f7.png)


![image](https://user-images.githubusercontent.com/17423049/51679810-f17df580-2005-11e9-8023-fba5186446df.png)
