### ISSUE TITLE
RISG:: Odd Behavior at Step 1: Select Forms in RFP module

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#943]
In the RFP module (this URL  https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=101278&phaseid=101279&tab_label=Pre-Proposal)

when I select by tags I am returned a list of the forms containing that tag. All forms with that tag are shown. However, as you can see in this screen shot:

<img width="1017" alt="screen shot 2018-12-28 at 12 27 03 pm" src="https://user-images.githubusercontent.com/18398763/50523139-678d4c00-0a9c-11e9-9eda-c6f3624e5495.png">

the list ends at the 16th form, which is correct, but then follows with form 11 through 16, and then continues to repeat in this way. While not critical given that the search works correctly, it is confusing to then have a continuing partial list of forms cycle through. It would be nice to see ONLY the one set of correct forms show, and the list end at the last form found.

**Comment by ecsion** [comment]
Alan, We are working to fix this issue but may take another day or 2 to resolve.
What browser are you using? Please try Chrome and check if this issue is present on Chrome for you as  well. Thanks

**Comment by alandesbonnet** [comment]
I use either Safari or Firefox, as do most of our users. This is not a critical issue as everything works, if is just confusing first time seeing it. The issue should be corrected, but since it is an ADMIN only issue (as far as I know) it should not impact users at large.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
fixed. Thank You
