### ISSUE TITLE
RISG:: Bad Screen Display at Step 1: Select Forms

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#944]
At the Step 1: Select Forms portion of the RFP module, when adding the "Proposal PDF" from the Hardcoded Forms and adding it to an RFP, the result is 2 check boxes, both showing "Show Propos..." next to the box. See screen shot below.

<img width="1112" alt="screen shot 2018-12-28 at 1 06 47 pm" src="https://user-images.githubusercontent.com/18398763/50524129-f8b2f180-0aa1-11e9-9612-3f5b83b7a8e8.png">

Since there are 2 check boxes, both with the same label, neither of which can be read to the end, it is not clear what the end result will be. This is somewhat critical because it is unclear which box to select  as appropriate. If there were a "hover" function such that when moused over all the text showed up, that would resolve the problem. But the moment, there is no way to see which check box leads to what result. Please fix or provide guidance because I need to use that form next week. Thank you.

**Comment by ecsion** [comment]
@alandesbonnet Hi Alan, could you please provide the url of this page.

**Comment by alandesbonnet** [comment]
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=101278&phaseid=101279&tab_label=Pre-Proposal <https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=101278&phaseid=101279&tab_label=Pre-Proposal>


Alan Desbonnet
Assistant Director

**Comment by alandesbonnet** [comment]
fixed. thank you

**Comment by alandesbonnet** [comment]
I logged in and all seemed fine and that the issue was corrected. I could see the full text, and selected the appropriate check box. After leaving that screen and returning the the Select Forms function, the text is no longer fully visible AND the check box was not saved. 

it appears that whatever fix was applied does not remain in place. Please check this. thank you.

**Comment by alandesbonnet** [comment]
Behavior is erratic. If I leave the Forms module and then return, all the text accompanying the check boxes for Proposal PDF option. It gets contracted / not visible if I add a new form, but returns to full visibility if I leave forms module than return. Regardless, clicking/selecting a check box is NEVER saved.

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
fixed. Thank You
