### ISSUE TITLE
RISG:: 90-4 form not showing Budget Worksheet data  CRITICAL ISSUE

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#945]
At this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=101416&mode=showBudget_90_4&tab_label=OTAtNA==&duration=403

data from the budget years do not display correctly when using the dropdown (next to the PDF Export button). The only budget data displayed consistently is the "Show Full Data" result. Other selections either return $0 in a categories, or show the combined (Show Full Data) budget years data.

This is an important issue that must be resolved soon as we will have people developing budgets very soon. Thank you.

**Comment by ecsion** [comment]
Alan, The issue was happening because both worksheets had the same budget period selected. We edited your worksheets and fixed the budget period. The numbers should be showing correctly now. Please check.

**Comment by alandesbonnet** [comment]
Oops. Sorry about that being MY error. Will look more closely in the future, and thank you for pointing that out.

Alan Desbonnet
Assistant Director
