### ISSUE TITLE
RISG:: Confusing popup on Budget Worksheets

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#946]
at this URL

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=101416&mode=showBudget_90_4&tab_label=OTAtNA==&duration=403

when entering values in budget worksheets section "G. Other Costs" a popup comes on screen noting "IDC amount 0" (see screen shot below) even though there would be IDC applied to that budget item. The popup disappears one the budget line is "saved". 

<img width="943" alt="screen shot 2019-01-02 at 12 16 35 pm" src="https://user-images.githubusercontent.com/18398763/50603357-4657a180-0e88-11e9-895a-e42f9296880f.png">

This really should be removed as it is distracting and incorrect. It then leads to wondering if the budget worksheet is calculating values correctly because of this (the worksheet IS calculating things correctly).

Please correct this so that either the correct IDC applied to a value entered in the budget is displayed, or better yet, remove the popup. Since things are calculating correctly, there is no need for the popup.

**Comment by ecsion** [comment]
Alan, On Subawards, the  IDC is taken on the first 25000. We added the IDC Amount to give the user the information on how much of the 25000 is already taken. However, we understand that this is confusing and so over the next few days, we will remove this info and instead add a icon on the bottom right of the cell, which when clicked will provide the sub award IDC computation info.

**Comment by alandesbonnet** [comment]
OK, that makes sense and is a nice feature now that it is explained. Your solution as proposed sounds less confusing. 

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Don on R2.5
