### ISSUE TITLE
LASG - Lists do not work

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#948]
I cannot add a drop down list.  It doesn't show up correctly.  I create one and then try to save it and it goes away (this is under RFP forms) See:

![image](https://user-images.githubusercontent.com/25613788/50659133-3eb7fb80-0f61-11e9-98b3-5f2d1956b5ed.png)

***Need this to be done right away since our RFP needs to be out by tomorrow.

**Comment by ecsion** [comment]
Fixed, please check
