### ISSUE TITLE
LASG: problem with \'s

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#950]
Every time I add an 's it puts a \ in front of it.  

https://www.laseagrantdb.org/index.php?module=RFP&view=Detail&mode=createPhase&record=102393&phaseid=102394&tab_label=Pre-Proposal

**Comment by STI-ORSG** [comment]
ORSG is also having this issue. In many of our custom forms, the there are now several backslashes that have been inserted before each  's.
![backslashes](https://user-images.githubusercontent.com/46287278/50986921-f34fa100-14bc-11e9-98e9-5dada96de3bc.png)

**Comment by ecsion** [comment]
fixed, please check

**Comment by ecsion** [comment]
If you see the problem,  edit the text, remove the slash and save again.
