### ISSUE TITLE
RISG:: Duplicate information after Import from Phase action

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#951]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=101599&mode=showMultiQuestionStem&QuestionId=101596&tab_label=UHJpbmNpcGFsIEludmVzdGlnYXRvciAoUHJlLVByb3Bvc2FsKQ==&tab_label=UHJpbmNpcGFsIEludmVzdGlnYXRvciAoUHJlLVByb3Bvc2FsKQ==

and as shown in the screen shot below:

<img width="1368" alt="screen shot 2019-01-10 at 11 46 07 am" src="https://user-images.githubusercontent.com/18398763/50983531-a2947400-14cd-11e9-96da-2b778605dd90.png">

Principal Investigator (Pre-Proposal), Co-Principal (Pre-Proposal), and Additional Project Personnel (Pre-Proposal) show up as 2 separate forms after doing a Step 4: Copy Proposals from Another Phase action (at this URL: https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=copyProposalFromOtherPhase&record=101278&phaseid=101280&tab_label=Full-Proposal)

Information from the Pre-proposal is transferred to one of the forms, but not the other, which is blank.  This must be corrected so that only 1 form -- the one with the information transferred from the pre-proposal phase -- is available for viewing/access. Thank you.

**Comment by ecsion** [comment]
Alan, We have reproduced this bug and are working on it. We will let you know.

**Comment by alandesbonnet** [comment]
Thank you

Alan Desbonnet
Assistant Director

**Comment by alandesbonnet** [comment]
while you work on resolving this issue, should I not change anything in the RFP, or am I free to continue tinkering with forms and set up of the RFP? Thank you. I don’t want to be changing things if you need me not to. It sounds like you replicated the problem, suggesting I can continue to alter the RFP, but I want to be sure before doing so. 
Thank you.
Alan

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
Alan, We will have to delete the import as it had some issues with it. Other than that, anything you do won't affect anything that we re doing.

**Comment by ecsion** [comment]
Fixed.
