### ISSUE TITLE
RISG:: Custom Forms save but cannot be found --  CRITICAL ISSUE --

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#953]
At this URL
https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&parent=&page=1&view=List&viewname=213&orderby=&sortorder=&showList=RFP&search_params=%5B%5B%5B%22tags%22%2C%22c%22%2C%2220-22%22%5D%5D%5D

I have created a custom form, in the RFP forms section, titled Sea Grant Data Management Plan. The form with that title was created, saved, and had a tag "20-22 RFP". I created the form at least twice, and possibly a third time. Each time it appeared to save, then when I went open/edit the custom form, it cannot be found. It does not turn up in a search by title, or by tag. This issue must be resolved as there is the need to create custom forms for an open RFP. Thank you.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check. 
Forms are also visible now.
![image](https://user-images.githubusercontent.com/17423049/51254194-83627e80-19c6-11e9-95c6-2e96ae9bb3ad.png)

**Comment by alandesbonnet** [comment]
fixed, thank you.
