### ISSUE TITLE
MDSG: Download Proposal Zip does not include all letters 

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#956]
Multiple letters are requested as part of our Knauss application. It appears that not all letters are being included in the download proposal zip file button/function.
Example:
https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=106637&mode=showSubmissionPreview&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
Fixed. Closed.
