### ISSUE TITLE
ORSG: Phase PDF Instructions confusing

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#959]
Is it possible to make the secondary set of instructions optional or have the ability to modify the link text? These appear in the “Current Tasks” box as well as on the “Start Here” page of an RFP (labeled differently in each). We have typically made all the instruction files the same for a given RFP/application so when they are both available together it is a confusing. In the event that a file is not loaded for one of the 2 instructions, the link is still available and prompts a pop-up that says “Instructions file does not exist!”. It would be better if that link was not there at all if there is no file loaded or to be able to change the link text.
![image](https://user-images.githubusercontent.com/46287278/52493381-2babd300-2b80-11e9-92d7-3abee004183e.png)
![image](https://user-images.githubusercontent.com/46287278/52493392-30708700-2b80-11e9-89dc-ad5546cd8d67.png)

**Comment by ecsion** [comment]
Done. Please check.

**Comment by STI-ORSG** [comment]
This is fixed, thank you.
