### ISSUE TITLE
LASG - Marcus Coleman taken off

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#961]
When the PI receives an email in the Reporting phase the email copies Marcus Coleman and signs it "Best Regards, Marcus Coleman"  Marcus no longer works for us, it needs to be changed to just sent the email to me and at the end of the submission email it needs to say: "Best Regards, Katie Lea"

**Comment by mra142** [comment]
Katie,

You should be able to change this in the system emails tab from the gear at
the top right of the page. Lots of customizable emails there.

Mike

-- Sent from mobile

**Comment by katielea** [comment]
I still can't change that he gets an email.  How do I do that?

**Comment by mra142** [comment]
That I don't know. We have a group email that we get stuff sent to... Then
we can change who's in the group (a Google group).

Mike

-- Sent from mobile
