### ISSUE TITLE
ORSG: Problem downloading application file

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#962]
In a recent application, one of the applicant PDFs cannot to downloaded. The page linked [here](https://eseagrant.oregonstate.edu/index.php?module=RFPProposal&view=Detail&record=106040&mode=showMultiQuestionStem&QuestionId=104214&tab_label=S25hdXNzIEZlbGxvd3NoaXAgQXBwbGljYXRpb24gVXBsb2Fk&tab_label=S25hdXNzIEZlbGxvd3NoaXAgQXBwbGljYXRpb24gVXBsb2Fk) shows an error message saying "File Download Error: No File Exists". Is there anyway this file can be accessed and/or any insight into why this may have occurred?
![image](https://user-images.githubusercontent.com/46287278/53438271-64d3a800-39b4-11e9-83ed-f4e3074378b5.png)

**Comment by ecsion** [comment]
We could not reproduce this issue. However, we have added some safeguards to avoid this issue in the future.
