### ISSUE TITLE
NCSG:  Budget Worksheet Personnel

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#963]
We have an open RFP, 2019 NMFS-Sea Grant Fellowships in Population and Ecosystems Dynamics.  One of the applications from Rebecca Van Hoeck is trying to add her adviser in the budget worksheet.  We have a custom form for adding investigators - why are these values not showing up as an option under the Salaries and Wages on the budget worksheet?  Just the "PI" Rebecca Van Hoeck is showing up and the drop down list does not contain anyone else.  I tried to look in the custom form but, didn't see anything that related to the budget worksheet.

The custom form we are using is - Investigators NMFS Fellowship

**Comment by ecsion** [comment]
The key was missing from the custom form and now we have added it.  Fixed, please check.
