### ISSUE TITLE
LASG - Need help NOW

### ISSUE THREAD

**Issue by katielea** [ecsion/eSeaGrant-Client-Bug-Tracker#964]
I am in need of help ASAP regarding custom forms and downloading them into PDF's (it will not allow me to open it) in the .zip file.  I can't get a hold of Deepak and need to get this done today.  If someone can help me with this, PLEASE call me at 225-578-6445.

**Comment by mra142** [comment]
I have one thought. In your custom form setup (RFP>choose forms), on each
form (edit form) there is an option to include it in the download PDF zip.
Is this box checked for each form separately?



-- Sent from mobile
