### ISSUE TITLE
NCSG: Peer Reviewers Page

### ISSUE THREAD

**Issue by mebarrow** [ecsion/eSeaGrant-Client-Bug-Tracker#965]
We have had at least 4-5 reviewers this year get confused (and lose their review) over thinking they had submitted their review when the hit the "submit" button associated with the COI as opposed to the "submit" button on the review itself.  I suspect they entered their review, hit the submit button which brings up the COI, and then hit "submit" associated with the COI.  They then close out before hitting submit on the review itself (after signing the COI).  This causes them to lose their review.  Perhaps they could rename the COI "submit" button to "adopt and sign."  Such that the only submit button is on the review itself?  Just a thought.  Or perhaps they could change the system such that it captures what they have entered when the COI window is brought up?  Just seems a way to make the system more user friendly.

This is from our Research Coordinator.  Maybe there is a better way to do it.

**Comment by ecsion** [comment]
Done.
