### ISSUE TITLE
One delegate cannot access report

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#967]
One delegate (Kim Hawkenson) to project 2018SP-R-Pollack-H9 cannot see report calls. I confirmed that the project is on the report call, the PI and the other Delegate can see the report call. I reinstituted Kim Hawkenson as a delegate for the project and still no report call. 

Also, can delegates see projects in Open Project tab? Because she cannot see that either.

**Comment by Dipali-Ecsion** [comment]
Fixed Please check.
