### ISSUE TITLE
Reporting: Validation alert balloons usability issue (investigator view)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#97]
This issue relates only to investigators:
At least on some pages (see example URL and screenshot for Community Hazard Resilience form), the red validation alert popup balloons cover the field to which they refer, causing some confusion for users. We determined that, while you can (a) still type in the field covered by the alert and (b) click the red balloons to make them go away, this may not be obvious to our often-impatient investigators, so we're wondering if you can either:
(1) move them so they don't cover the associated field
(2) eliminate them entirely and only give the alert(s) when attempting to save the form data. However, one of our staff said they actually like the alerts to appear **while** the investigator is filling out the form, if possible (i.e., option (1) above is preferred).

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17852&mode=showMultiQuestionStem&QuestionId=15958&tab_label=Community%20Hazard%20Resilience

![screen shot 2016-03-11 at 9 12 38 am](https://cloud.githubusercontent.com/assets/17168836/13709662/01a54ee0-e76a-11e5-900d-442c47aa59e8.png)

**Comment by ecsion** [comment]
fixed. The balloons now fade away after 2 or 3 seconds.
