### ISSUE TITLE
MDSG: Peer reviews submitted, but the form is not changing to submitted status

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#970]
We've had many peer reviews submitted to our current omnibus RFP (40 as of this writing). However, on the peer review forms themselves, the status of the form is remaining "Not submitted". This is causing major confusion (and multiple submissions) for numerous peer reviewers. Even reviews we've checked as "accepted" have the  not submitted label.
Please correct ASAP.
Mike

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by mra142** [comment]
Closed. Thanks for the promptness!
