### ISSUE TITLE
Annual Reporting - Issue with Submission Preview Page

### ISSUE THREAD

**Issue by SamuelJLake** [ecsion/eSeaGrant-Client-Bug-Tracker#971]
Hello,

One of our PIs is currently receiving an error message when they try to access the Submission Preview Page for their annual report (webpage address below). Because of the error they cannot submit their report. I have attached a screenshot for reference. Please contact me at 804-684-7436 with any questions. 

All the best,
Sam

![Unknown](https://user-images.githubusercontent.com/17860369/55101627-f2c9ae00-509a-11e9-9e58-0cdb61576be3.png)

https://vaseagrant.ecsion.com/index.php?module=Reporting&view=Detail&record=107603&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
