### ISSUE TITLE
ORSG- Panel Review Deadline mismatch

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#973]
In setting up a panel review for a current fellowship application, the deadline on the Panel Review Form for the reviewer does not match with the deadline set in the Form set-up. The screen shot below shows the Form set-up window and then the Panelist form. Seems like there is a glitch in the deadline, or is there another place where the deadline needs to be established?

![image](https://user-images.githubusercontent.com/46287278/56232377-7725a600-6035-11e9-9b4b-9c11016526d8.png)

**Comment by pankaj-ecsion** [comment]
Fixed.Please check.

**Comment by STI-ORSG** [comment]
Looks good, thanks.
