### ISSUE TITLE
RISG: Add option to REMOVE Rating Criteria from form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#980]
At this URL, 

https://eseagrant.gso.uri.edu/index.php?module=ReviewRating&view=Edit&record=107260&showList=RFPStandard&tab_label=Rating%20Forms

Please add the option to REMOVE Criteria from rating forms. At present, forms cannot be modified by removing criteria (note that the option the REMOVE Ratings does exist) forcing the user to create a new rating form even if they simply want to remove a criteria. 

Please add functionality to REMOVE Criteria from rating forms. Thank you.

**Comment by pankaj-ecsion** [comment]
Fixed. Please check.
