### ISSUE TITLE
RISG: Review Due Date (Hrs. Min. counter) not displaying

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#981]
at this URL:

https://eseagrant.gso.uri.edu/operations.php?action=peerresponseform&guid=1A35D37C-E023-46C0-B6D9-B276C287FF64

please note that the "Hrs Mins" counter is not displaying correctly. It should display time, but is displaying "NaN" instead. This needs to be corrected. Thank you. 

This not a critical issue, but is annoying and confusing since the correct date/time is displayed in other areas of the screen.

**Comment by Dipali-Ecsion** [comment]
It was a Safari issue and we have fixed it. Please Check.

**Comment by alandesbonnet** [comment]
this has been corrected and the issue may be closed. Thank you.

Alan Desbonnet
Assistant Director
