### ISSUE TITLE
Projects wont close

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#987]
The following projects won't close:
2018SP-E-Cummins
2018SP-E-Balboa
I edit the project, change the Project Status to closed, then save. The status reverts to open.

**Comment by ecsion** [comment]
Looking into this issue.

**Comment by ecsion** [comment]
Hi Drew, MIT had requested a workflow associated with close project that looked at the close date and or extension date and automatically open the project of these dates were not past. iN your case original close date was in the future and so project automatically opened. We have now removed the workflow so it won't open up automatically even if the close date is in future. Please check.

**Comment by Drew-Casey** [comment]
Ah, so if the “Original End Date” field has a listed end date that is in the future, the “Project Status” field will not override it. But now the “Project Status” field does override the date?

When I “choose projects” for a report call, it is still bringing up “closed projects” in the search. Is this by design? If it is, can a checkbox be added to exclude closed projects? I have added a snapshot. The Reporting Call Title: EMM-2019-MONTH. But it occurs on all report call setup.

Thanks,

Drew
