### ISSUE TITLE
RISG: Panelist Comments Screen -- Confusing Wording to Change

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#991]
At this URL:

https://eseagrant.gso.uri.edu/operations.php?action=panel_reviewer_detail&guid=MjJGN0QwMDgtQzg0OC00MjE0LTk1QjYtQjkzRUZFOTc5RTRD&exuti=MTA4MjE0&propid=MTAzMzY0&reviewer=MTA4MjE1&rid=SDE2LTIwOQ==

Please change the wording in the right side input screen to be "Panelist Comments"

Currently it says Reviewer Comments, which panelists interpret to mean that reviewer comments will display in that box, which is not the case. Please change as requested above to remove that confusion. Thank You.

**Comment by Dipali-Ecsion** [comment]
Done. Please check.
