### ISSUE TITLE
RISG: Cannot Promote Proposal to Project

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#993]
at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=selectProjectForFunding&record=101780&phaseid=101782&tab_label=Full-Proposal
I have completed and saved what is needed to select a project for funding. 

However, at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=promoteProposal&record=101780&phaseid=101782&tab_label=Full-Proposal
the project selected for funding does not appear in the list so that it can be promoted to a project.

Please correct this so that this (and other) proposals that are funded can be promoted to project level for annual reporting and other activities. Thank you.

**Comment by Dipali-Ecsion** [comment]
This is as designed. We only allow submitted proposals to be promoted. None of the proposals are in submitted status and so the list is not showing any proposals.

The select for funding also should have shown submitted proposals only. This has now been corrected.

**Comment by alandesbonnet** [comment]
I did not realize that. My apologies for entering this to Github.

Alan Desbonnet
Assistant Director
