### ISSUE TITLE
ORSG: Panel scoring is incorrect

### ISSUE THREAD

**Issue by SEK-OSG** [ecsion/eSeaGrant-Client-Bug-Tracker#994]
I found an issue with panel scoring. We have 7 weighted panel review categories that total to "5 points". When I select "5 points - excellent" in all 7 categories, the cumulative score is "4 points of 5 possible points". This is incorrect - the score should be "5 points of 5 possible points". Screen shot below: 
![ORSG Wrong scoring eSG Panel](https://user-images.githubusercontent.com/18152637/62726966-40e9a900-b9cd-11e9-8c11-cbdf64d6006f.png)

When I hit the "save" button, the scoring changes to the correct total value, "5 points of 5 possible points". Screen shot below - the only difference is hitting "save": 
![ORSG Correct score afer save eSG panel](https://user-images.githubusercontent.com/18152637/62727069-7d1d0980-b9cd-11e9-85cb-d03529454cc9.png)

Can the glitch be corrected so that panel scoring is accurately reflected throughout the process?
Thank you,
Sarah

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check .

**Comment by ecsion** [comment]
Sarah, We are closing this. Please reopen if not fixed.
