### ISSUE TITLE
RISG: PDF Print of Scribe Notes to Performing Properly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#995]
at this url:

https://eseagrant.gso.uri.edu/operations.php?action=panel_scribe_detail&guid=MDQ4N0I5QUItQ0I4Qy00OUQ5LThERUMtQkE2RkE4Nzc3OEQ0&exuti=MTA4MzYz&propid=MTAzNzMz&reviewer=MTA4Mzc1&rid=LQ==&scribe=1#

clicking the PRINT icon, then opening in PDF format, returns the correct cover page but page 2 shows Scribe Notes from a different full proposal of the same PI. It would be nice if this could be corrected.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

![Screenshot from 2019-08-23 16-43-32](https://user-images.githubusercontent.com/17423049/63588876-2f0b2700-c5c5-11e9-8fc5-7099e8d96f52.png)

**Comment by alandesbonnet** [comment]
fixed. Thank you.
