### ISSUE TITLE
TXSG Peer Reviewer List with Rating - 3 Peer Reviews But Score & PDF Duplicates to 4

### ISSUE THREAD

**Issue by mzwolinski** [ecsion/eSeaGrant-Client-Bug-Tracker#996]
Peer Reviewer List with Rating

Proposal Guneralp, Burak has 3 reviews that have been accepted. However, when downloading the Peer Review excel file, the reviewer count had 4. The Jose Jimenez review was duplicated. The score in the excel file,on the Peer Reviewer List with Rating and in the PDF, all had the incorrect score due to the Jimenez review being duplicated. Below is link to the TXSG page, screen print image and an upload pdf screen print.

Thank you for your assistance,
Mia Zwolinski

http://eseagrant.texasseagrant.org/index.php?module=RFP&view=Detail&mode=showPeer&record=103956&phaseid=103958&tab_label=Full-Proposal&source=Peer#

![image](https://user-images.githubusercontent.com/23663698/63610402-07a16380-c59f-11e9-8237-cf16ac6ac734.png)

[TXSG PeerReviewerListWithRating-3 PeerReviewsButScore&PDF Duplicates to 4.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/3535510/TXSG.PeerReviewerListWithRating-3.PeerReviewsButScore.PDF.Duplicates.to.4.pdf)

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
[113285_PeerComments.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/3545848/113285_PeerComments.pdf)

**Comment by mzwolinski** [comment]
Fixed all, thank you!
