### ISSUE TITLE
RISG: Co-PI not showing in budget worksheet

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#999]
at this URL:
https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTAzNjg3&id=388

when accessing Select Personnel dropdown in the budget worksheet one co-PI is listed twice (screen shot)
<img width="986" alt="Screen Shot 2019-09-16 at 10 56 45 AM" src="https://user-images.githubusercontent.com/18398763/64969494-0566b800-d872-11e9-9c7c-22072486e41e.png">

however, at this URL
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=103687&mode=showMultiQuestionStem&QuestionId=101594&tab_label=Q28tUHJpbmNpcGFsIEludmVzdGlnYXRvcnM=&tab_label=Q28tUHJpbmNpcGFsIEludmVzdGlnYXRvcnM=
 
you see that another co-PI exists (screen shot)
<img width="777" alt="Screen Shot 2019-09-16 at 10 59 08 AM" src="https://user-images.githubusercontent.com/18398763/64969606-3a730a80-d872-11e9-8d57-1d7911b1a199.png">

but that name is not available to select in the budget worksheet. This needs to be corrected so that each co-PI is listed and can be selected from the dropdown. Thank you.

**Comment by pankaj-ecsion** [comment]
Fixed. Please check.

**Comment by alandesbonnet** [comment]
Fixed. Thank you.
